"""Tail-order gate (V3.0 rider; Docs/forward_roadmap_v3.md item 6).

The full-line certificate's limiting-order clause (book ch. 2,
eq. tailscalecalendar: lambda_{+-,far} >= lambda_{+-,near} in the endpoint
chart) is promoted from advisory to an OPT-IN gate
(OptionsSettings.ledgerTailOrderGate). Locks:

1. RAW ``tail_order_ok`` is unchanged on the certificate fixtures; the new
   signed per-side gaps carry the sign of each decision.
2. The tolerance-aware clause ``tail_certified`` (TAIL_ORDER_TOL = 1e-6)
   accepts a 1e-8 reversal (the soft lambda rows' residual scale) and
   rejects 1e-5; the raw clause still cries wolf on the 1e-8 one.
3. A theta-realizable TAIL-ONLY failure at common alpha (ledger clause
   passes on the whole line, right endpoint scales reversed by 1e-4 in log
   scale) is left alone by the exchange with the gate off (round 0,
   byte-identical) and repaired with it on — the lambda_+- seam rows
   tighten under the per-pair interface escalation; no rank row enters.
4. Unequal exponents (lighter far tail) are irreducible AT ONCE under the
   gate: no round is burned, the thetas are untouched.
5. ``tail_gate=False`` is byte-identical to the default call on the
   test_symmetric_exchange rig (driver and ladder entry points).
6. API: with the gate on, a quality row whose tail clause fails is not
   ready and names "tail order" (side included); the export raises
   PublishBlockedError naming it; gate off -> ready, exports as before.
"""

from __future__ import annotations

import dataclasses
import math
from datetime import date

import numpy as np
import pytest

from volfit.api import export, quality, service
from volfit.api.state import AppState
from volfit.calib.calendar_certificate import (
    SLOPE_TIE,
    TAIL_ORDER_TOL,
    ledger_certificate,
)
from volfit.calib.symmetric import (
    IFACE_BASE_WEIGHT,
    SliceSpec,
    _spec_params,
    build_interface,
    repair_surface,
)
from volfit.calib.symmetric_exchange import (
    _CAL_TOL,
    MAX_EXCHANGE_ROUNDS,
    exchange_ladder,
    exchange_refit,
    pair_ok,
)
from volfit.models.lqd.basis import LQDParams, endpoint_scales
from volfit.models.lqd.calibrate import calibrate_slice
from volfit.models.lqd.quadrature import build_slice

REF_DATE = date(2026, 6, 10)
TICKER = "ALPHA"

# The certificate fixture pair (test_calendar_certificate): far has strictly
# larger endpoint scales on both sides -> ordered, tail orders hold.
NEAR = LQDParams(L=np.log(0.12), R=np.log(0.10), a=np.array([0.020, -0.010]))
FAR = LQDParams(L=np.log(0.20), R=np.log(0.17), a=np.array([0.015, -0.008]))

# Tail-only rig: a much heavier LEFT tail (the martingale normalization then
# lifts the whole far quantile, so the pair stays ledger-ordered on the grid
# and the right continuations cross only where the ledger is ~1e-12) with
# the RIGHT endpoint log-scale 1e-4 BELOW the near one: the tail clause
# fails on the right by ~1e-5 in A units (10x TAIL_ORDER_TOL), the ledger
# clause passes. Same Legendre coefficients so log A_R differs by exactly
# R_DEFICIT (endpoint_rows: log A_R = R + sum (-1)^n a_n).
R_DEFICIT = 1e-4
FAR_TAIL = LQDParams(L=np.log(0.20), R=NEAR.R - R_DEFICIT, a=NEAR.a.copy())

K_Q = np.linspace(-0.4, 0.4, 33)
T_NEAR, T_FAR = 0.5, 1.0


def _pair_specs(p_near: LQDParams, p_far: LQDParams):
    """Quotes GENERATED by the two laws (so the independent optimum of each
    slice is its own params — exactly representable) + the joint specs."""
    s_near, s_far = build_slice(p_near), build_slice(p_far)
    specs = [
        SliceSpec(
            t=t, k=K_Q, w=np.asarray(s.implied_w(K_Q), dtype=float),
            fit_kwargs=dict(
                n_order=p.order, alpha_left=p.alpha_left, alpha_right=p.alpha_right,
            ),
        )
        for t, s, p in ((T_NEAR, s_near, p_near), (T_FAR, s_far, p_far))
    ]
    thetas = [p_near.to_vector(), p_far.to_vector()]
    return specs, thetas, s_near, s_far


def _isos(state: AppState) -> list[str]:
    return [e.isoformat() for e in sorted(state.forwards(TICKER))]


# ------------------------------------------------ 1. raw clause + signed gaps
def test_raw_tail_order_unchanged_and_gaps_carry_the_sign():
    near, far = build_slice(NEAR), build_slice(FAR)
    cert = ledger_certificate(near, far)
    assert cert.tail_order_ok and cert.tail_certified()
    assert cert.tail_gap_left > 0.0 and cert.tail_gap_right > 0.0
    assert not cert.tail_irreducible
    # Decay-rate branch: the gap IS the endpoint-scale difference far - near.
    a_l_n, a_r_n = endpoint_scales(NEAR)
    a_l_f, a_r_f = endpoint_scales(FAR)
    assert cert.tail_gap_left == pytest.approx(a_l_f - a_l_n, rel=1e-9)
    assert cert.tail_gap_right == pytest.approx(a_r_f - a_r_n, rel=1e-9)
    assert cert.tail_gap_min == min(cert.tail_gap_left, cert.tail_gap_right)

    rev = ledger_certificate(far, near)
    assert not rev.tail_order_left and not rev.tail_order_right
    assert rev.tail_gap_left < 0.0 and rev.tail_gap_right < 0.0
    assert not rev.tail_certified()
    # Identical slices: exact tie on both sides -> ordered, zero gaps.
    same = ledger_certificate(near, near)
    assert same.tail_order_ok and same.tail_certified()
    assert same.tail_gap_left == 0.0 and same.tail_gap_right == 0.0


# --------------------------------------------------------- 2. tolerance band
def test_tail_certified_tolerance_accepts_1e8_rejects_1e5():
    near = build_slice(NEAR)
    # Grid-identical slices whose right endpoint scale is reversed by eps:
    # the ledger gap is identically zero (no tail candidate: the quantile
    # continuations meet AT the boundary), only the tail clause moves.
    soft = dataclasses.replace(near, a_right=near.a_right - 1e-8)
    cert = ledger_certificate(near, soft)
    assert cert.certified(_CAL_TOL) and cert.min_gap == 0.0
    assert not cert.tail_order_right  # raw clause: 1e-8 > SLOPE_TIE cries wolf
    assert 1e-8 > SLOPE_TIE
    assert cert.tail_gap_right == pytest.approx(-1e-8, rel=1e-6)
    assert cert.tail_certified()  # tolerance-aware clause accepts it

    hard = dataclasses.replace(near, a_right=near.a_right - 1e-5)
    cert2 = ledger_certificate(near, hard)
    assert cert2.certified(_CAL_TOL)
    assert not cert2.tail_certified()  # a genuine reversal
    assert cert2.tail_certified(tol=1e-4)  # the tolerance knob is honored
    assert not cert2.tail_irreducible
    assert pair_ok(cert2) and not pair_ok(cert2, tail_gate=True)


# --------------------------------- 3. tail-only failure: gate off vs gate on
def test_tail_only_failure_repaired_under_gate_left_alone_without_it():
    specs, thetas, s_near, s_far = _pair_specs(NEAR, FAR_TAIL)
    cert = ledger_certificate(s_near, s_far)
    # Precondition: ledger clause passes on the WHOLE line, tail clause
    # fails on the right only (a tail-only failure at common alpha).
    assert cert.certified(_CAL_TOL)
    assert cert.tail_order_left and not cert.tail_order_right
    assert cert.tail_gap_left > 0.0
    assert cert.tail_gap_right < -TAIL_ORDER_TOL
    assert not cert.tail_certified() and not cert.tail_irreducible
    # The quotes themselves are calendar-ordered (no in-support violation).
    assert np.all(specs[1].w >= specs[0].w)

    iface = build_interface(specs[0], specs[1], tail_contract=True)
    off = exchange_refit(specs, thetas, [iface], IFACE_BASE_WEIGHT)
    assert off.converged and off.rounds == 0 and off.irreducible == ()
    for out, orig in zip(off.thetas, thetas):
        assert out.tobytes() == orig.tobytes()

    on = exchange_refit(specs, thetas, [iface], IFACE_BASE_WEIGHT, tail_gate=True)
    assert on.converged
    assert 1 <= on.rounds <= MAX_EXCHANGE_ROUNDS
    assert on.irreducible == ()
    assert all(r.size == 0 for r in on.active_ranks)  # a slope repair, no rank rows
    fresh = on.certificates[0]
    assert fresh.certified(_CAL_TOL) and fresh.tail_certified()
    # The repair is a wing-slope nudge: both slices still price their own
    # quotes to a hair (nothing in the belly moved).
    for theta, s in zip(on.thetas, specs):
        slc = build_slice(_spec_params(theta, s.fit_kwargs))
        iv_err = np.max(np.abs(np.sqrt(slc.implied_w(s.k) / s.t) - np.sqrt(s.w / s.t)))
        assert iv_err < 1e-3

    # Ladder entry point: gate off passes the ladder through untouched,
    # gate on touches both slices and certifies the tail clause.
    l_off, t_off, c_off = exchange_ladder(specs, thetas)
    assert t_off == [False, False] and pair_ok(c_off[0])
    l_on, t_on, c_on = exchange_ladder(specs, thetas, tail_gate=True)
    assert t_on == [True, True] and pair_ok(c_on[0], tail_gate=True)


# --------------------------------------------- 4. unequal exponents: irreducible
def test_unequal_exponents_are_irreducible_at_once():
    near = LQDParams(
        L=np.log(0.12), R=np.log(0.10), a=np.array([0.020, -0.010]),
        alpha_left=0.25, alpha_right=0.25,
    )
    lighter = LQDParams(  # larger scales, but a LIGHTER right tail exponent
        L=np.log(0.20), R=np.log(0.17), a=np.array([0.015, -0.008]),
        alpha_left=0.25, alpha_right=0.40,
    )
    specs, thetas, s_near, s_far = _pair_specs(near, lighter)
    cert = ledger_certificate(s_near, s_far)
    assert not cert.tail_order_right and cert.tail_irreducible
    assert cert.tail_gap_right == -math.inf
    assert cert.tail_order_left and cert.tail_gap_left > 0.0  # common alpha side
    assert not cert.tail_certified() and not cert.tail_certified(tol=1.0)
    # Reversed roles: the far tail is HEAVIER -> ordered by the exponents.
    back = ledger_certificate(s_far, s_near)
    assert back.tail_order_right and back.tail_gap_right == math.inf
    assert not back.tail_irreducible

    iface = build_interface(specs[0], specs[1], tail_contract=True)
    res = exchange_refit(specs, thetas, [iface], IFACE_BASE_WEIGHT, tail_gate=True)
    assert res.rounds == 0  # no round burned on an exponent
    assert res.irreducible == (0,)
    assert not res.converged
    for out, orig in zip(res.thetas, thetas):
        assert out.tobytes() == orig.tobytes()


# ------------------------------------------------ 5. gate off = byte-identical
def test_tail_gate_off_is_byte_identical():
    """The test_symmetric_exchange rig (sampled screens blind, one exchanged
    rank certifies): the explicit tail_gate=False call reproduces the default
    call bit for bit, driver and ladder alike."""
    k_wide = np.linspace(-0.40, 0.40, 33)
    w_wide = 0.020 + 0.50 * k_wide**2
    k_narrow = np.linspace(-0.15, 0.15, 13)
    w_narrow = 0.0245 + 0.55 * k_narrow**2
    near = calibrate_slice(k_wide, w_wide, t=0.5, n_order=6)
    far = calibrate_slice(k_narrow, w_narrow, t=0.75, n_order=6)
    specs = [
        SliceSpec(t=0.5, k=k_wide, w=w_wide, fit_kwargs=dict(n_order=6)),
        SliceSpec(t=0.75, k=k_narrow, w=w_narrow, fit_kwargs=dict(n_order=6)),
    ]
    repair = repair_surface(specs, [near.params.to_vector(), far.params.to_vector()])
    iface = build_interface(specs[0], specs[1], tail_contract=True)
    default = exchange_refit(specs, repair.thetas, [iface], IFACE_BASE_WEIGHT)
    explicit = exchange_refit(
        specs, repair.thetas, [iface], IFACE_BASE_WEIGHT, tail_gate=False
    )
    assert default.converged and default.rounds >= 1
    assert explicit.rounds == default.rounds
    assert explicit.irreducible == default.irreducible
    for a, b in zip(default.thetas, explicit.thetas):
        assert a.tobytes() == b.tobytes()
    for a, b in zip(default.active_ranks, explicit.active_ranks):
        assert a.tobytes() == b.tobytes()
    l_default = exchange_ladder(specs, repair.thetas)
    l_explicit = exchange_ladder(specs, repair.thetas, tail_gate=False)
    assert l_default[1] == l_explicit[1]
    for a, b in zip(l_default[0], l_explicit[0]):
        assert a.tobytes() == b.tobytes()


# ------------------------------------------------------------- 6. API gating
def _tail_only_prev(record):
    """A 'previous' slice = this record's own slice with a HEAVIER right
    endpoint scale: identical ledger on the grid (gap 0, certified), tail
    clause reversed on the right by 1e-3 relative (~1e-4 in A units)."""
    sl = record.result.slice
    return dataclasses.replace(sl, a_right=sl.a_right * (1.0 + 1e-3))


def test_gate_on_row_not_ready_and_export_blocks_on_tail_order(monkeypatch):
    state = AppState(REF_DATE)
    state.set_options(
        state.options().model_copy(update={"ledgerTailOrderGate": True})
    )
    isos = _isos(state)
    near = service.calibrate_node(state, TICKER, isos[0], "mid")
    far = service.calibrate_node(state, TICKER, isos[1], "mid")

    # The natural pair certifies, tail clause included: ready under the gate.
    clean, _ = quality._node_row(
        state, TICKER, isos[1], "mid", far, near.result.slice, None,
        near.prepared.k, None, 50.0, False,
    )
    assert clean.ledgerTailGated and clean.ledgerTailCertified and clean.ready
    assert clean.ledgerTailGapMin is not None and clean.ledgerTailGapMin > -TAIL_ORDER_TOL

    node, _ = quality._node_row(
        state, TICKER, isos[1], "mid", far, _tail_only_prev(far), None,
        far.prepared.k, None, 50.0, False,
    )
    assert node.calendarOk and node.ledgerCertified  # ledger clause passes
    assert node.ledgerTailGated and not node.ledgerTailCertified
    assert not node.ledgerTailOrderOk and not node.ledgerTailIrreducible
    assert node.ledgerTailGapRight is not None and node.ledgerTailGapRight < -TAIL_ORDER_TOL
    assert node.ledgerTailGapMin == node.ledgerTailGapRight
    assert not node.ready
    assert any("tail order" in s and "right" in s for s in node.issues)

    # Export: a gated row failing the tail clause blocks the publish naming it.
    real = export.build_quality_report

    def poisoned(state_, mode):
        report = real(state_, mode)
        for row in report.nodes:
            if row.hasFit and row.expiry == isos[1]:
                row.ledgerTailGated = True
                row.ledgerTailCertified = False
                row.ledgerTailGapRight = -2e-5
                row.ledgerTailGapMin = -2e-5
        return report

    monkeypatch.setattr(export, "build_quality_report", poisoned)
    with pytest.raises(export.PublishBlockedError, match="tail order"):
        export.build_surface_export(state, tickers=[TICKER])
    draft = export.build_surface_export(state, tickers=[TICKER], require_clean=False)
    assert len(draft.tickers[0].nodes) == 2


def test_gate_off_keeps_tail_clause_advisory(monkeypatch):
    state = AppState(REF_DATE)
    assert not state.options().ledgerTailOrderGate  # the default
    isos = _isos(state)
    far = service.calibrate_node(state, TICKER, isos[1], "mid")
    node, _ = quality._node_row(
        state, TICKER, isos[1], "mid", far, _tail_only_prev(far), None,
        far.prepared.k, None, 50.0, False,
    )
    assert not node.ledgerTailGated and not node.ledgerTailCertified
    assert not node.ledgerTailOrderOk  # reported (advisory) ...
    assert node.ready and not any("tail order" in s for s in node.issues)  # ... never gates

    real = export.build_quality_report

    def poisoned(state_, mode):
        report = real(state_, mode)
        for row in report.nodes:
            if row.hasFit and row.expiry == isos[1]:
                row.ledgerTailCertified = False  # advisory failure, gate off
                row.ledgerTailGapRight = -2e-5
        return report

    monkeypatch.setattr(export, "build_quality_report", poisoned)
    out = export.build_surface_export(state, tickers=[TICKER])  # no raise
    assert len(out.tickers[0].nodes) == 1
