"""Help Center settings-schema locks (HELP CENTER ARC, H1).

The in-app Settings reference takes every machine fact (type, default, range,
enum) from frontend/src/lib/help/settingsSchema.json, GENERATED by
backend/gen_help_schema.py from the pydantic settings models. These locks make
a forgotten regeneration a test failure instead of a stale reference:

* the committed JSON matches the live models field for field;
* the generator's simplification is faithful on known fields (enum choices,
  bounds, optional/nullable, defaults);
* every field of the three models is present exactly once.
"""

from __future__ import annotations

import json

import gen_help_schema as gen
from volfit.api.help_schema import build_schema, drift
from volfit.api.schemas import FitSettings, OptionsSettings
from volfit.api.schemas_market import MarketSettings


def test_committed_schema_matches_live_models():
    problems = drift(gen.OUT)
    assert problems == [], "settingsSchema.json drifted — run `python gen_help_schema.py`:\n" + "\n".join(problems)


def test_every_field_present_once():
    doc = build_schema()
    for key, model in (("fit", FitSettings), ("options", OptionsSettings), ("market", MarketSettings)):
        names = [f["name"] for f in doc["models"][key]["fields"]]
        assert names == list(model.model_fields), key
        assert len(set(names)) == len(names), key


def test_simplification_is_faithful():
    doc = build_schema()
    fit = {f["name"]: f for f in doc["models"]["fit"]["fields"]}
    opt = {f["name"]: f for f in doc["models"]["options"]["fields"]}
    mkt = {f["name"]: f for f in doc["models"]["market"]["fields"]}
    # Enum with choices + default.
    assert fit["model"]["type"] == "enum" and fit["model"]["enum"] == ["lqd", "svi", "sigmoid"]
    assert fit["model"]["default"] == "lqd"
    # Bounded int.
    assert fit["nOrder"] == {"name": "nOrder", "type": "int", "default": 16, "min": 4, "max": 24}
    # Nullable float.
    assert fit["midAnchorTauRef"]["type"] == "float" and fit["midAnchorTauRef"].get("optional") is True
    # Bool, list, dict.
    assert opt["enforceCalendar"]["type"] == "bool" and opt["enforceCalendar"]["default"] is True
    assert opt["priorAnchorDeltas"]["type"] == "list"
    assert fit["tailAlphaByTicker"]["type"] == "dict"
    # Exclusive bounds survive.
    ssr = opt["autoUpdateSeconds"]
    assert ssr["max"] == 86400 and ssr.get("exclusiveMin") is True
    # Market model.
    assert mkt["dividendMode"]["type"] == "enum" and "continuous" in mkt["dividendMode"]["enum"]
    # The document round-trips through JSON unchanged.
    assert json.loads(json.dumps(doc)) == doc
