"""The paper's generated-numbers macro store.

Every number a caption or the running text quotes is registered here and
emitted as ``\\newcommand{\\Mac<CamelCaseSlug>}{...}`` into
``figures/paper_macros.tex`` plus a human inventory ``figures/MACROS.md``.

The store persists between runs in ``figures/_macros_store.json`` so that
``gen_figures.py --only fig_x`` can refresh one figure's macros while the
rest of the file keeps its previous values.  A full run overwrites every
entry, so the JSON never goes stale silently: the tex header records which
run wrote it.
"""

from __future__ import annotations

import json
import re
from datetime import date

import numpy as np

from figstyle import FIG_DIR

_STORE_PATH = FIG_DIR / "_macros_store.json"
_NAME_RE = re.compile(r"^[A-Za-z]+$")

# Emission order of the sections inside paper_macros.tex.
SECTION_ORDER = [
    "snapshot", "toy", "exact", "spy", "nvda", "chart", "tails", "lee",
    "doublehump", "jacobian", "butterfly", "calendar", "ticket",
    "certification", "timing", "guard", "cliff", "incidents", "multistart",
    "aliases",
]


def num(x: float, nd: int = 2) -> str:
    """Fixed-point decimal string (the default macro body)."""
    return f"{float(x):.{nd}f}"


def sci(x: float, nd: int = 1) -> str:
    """m x 10^e in ensuremath form for tiny audit-scale numbers."""
    x = float(x)
    if x == 0.0:
        return r"\ensuremath{0}"
    e = int(np.floor(np.log10(abs(x))))
    return rf"\ensuremath{{{x / 10.0 ** e:.{nd}f}\times10^{{{e}}}}}"


class MacroStore:
    """Ordered, persistent name -> (value, meaning, section) registry."""

    def __init__(self) -> None:
        self._entries: dict[str, dict[str, str]] = {}
        if _STORE_PATH.exists():
            self._entries = json.loads(_STORE_PATH.read_text(encoding="utf-8"))

    def add(self, section: str, name: str, value, meaning: str) -> None:
        """Register one macro; ``value`` is the final LaTeX macro body."""
        if not _NAME_RE.match(name):
            raise ValueError(f"macro name {name!r} must be letters only")
        if section not in SECTION_ORDER:
            raise ValueError(f"unknown macro section {section!r}")
        self._entries[name] = {
            "value": str(value), "meaning": meaning, "section": section,
        }

    def value(self, name: str) -> str:
        """Stored macro body (used by the alias layer so names can't drift)."""
        return self._entries[name]["value"]

    def _sorted(self) -> list[tuple[str, dict[str, str]]]:
        return sorted(
            self._entries.items(),
            key=lambda kv: (SECTION_ORDER.index(kv[1]["section"]), kv[0]),
        )

    def write(self) -> tuple[int, str]:
        """Emit paper_macros.tex + MACROS.md + the JSON store; return count."""
        FIG_DIR.mkdir(parents=True, exist_ok=True)
        _STORE_PATH.write_text(
            json.dumps(self._entries, indent=1), encoding="utf-8"
        )
        stamp = date.today().isoformat()
        tex = [
            "% Auto-generated by Papers/lqd_paper/scripts/gen_figures.py"
            " -- do not edit.",
            f"% Written {stamp}; every value derives from the frozen snapshot",
            "% lqd_paper_snapshot_20260804_0208.json or a fixed-seed synthetic"
            " construction.",
        ]
        md = [
            "# Macro inventory (auto-generated -- do not edit)",
            "",
            "Emitted by `scripts/gen_figures.py` into `paper_macros.tex`."
            f" Last write {stamp}.",
            "",
            "| Macro | Value | Meaning |",
            "|---|---|---|",
        ]
        section = None
        for name, entry in self._sorted():
            if entry["section"] != section:
                section = entry["section"]
                tex.append(f"% --- {section}")
            tex.append(rf"\newcommand{{\Mac{name}}}{{{entry['value']}}}")
            value_md = entry["value"].replace("|", r"\|")
            meaning_md = entry["meaning"].replace("|", r"\|")
            md.append(rf"| `\Mac{name}` | `{value_md}` | {meaning_md} |")
        (FIG_DIR / "paper_macros.tex").write_text(
            "\n".join(tex) + "\n", encoding="utf-8"
        )
        (FIG_DIR / "MACROS.md").write_text(
            "\n".join(md) + "\n", encoding="utf-8"
        )
        return len(self._entries), str(FIG_DIR / "paper_macros.tex")


STORE = MacroStore()
