// Guide — the MCP connector (HELP CENTER follow-on, 2026-09-09): driving the
// desk from a Claude chat. Grounded in backend/volfit_mcp (server.py,
// tools_*.py, ops.py, jobs.py, ui/) and Docs/mcp_connector.md. Tool names are
// what the chat shows, so they stay verbatim; everything else is desk voice.
import type { GuidePage } from "../types";

export const CONNECTOR: GuidePage = {
  id: "connector",
  title: "Drive the desk from a Claude chat",
  summary: "Set up the MCP connector, run the whole routine in one message, compare two settings, and read the charts that render inside the conversation.",
  related: ["help:guides:workflow", "help:glossary:mcp-connector", "help:glossary:mcp-app", "docs_mcp_connector", "docs_bloomberg_setup"],
  body: [
    "## What it is",
    "",
    "The **connector** lets a Claude chat operate this app. It is a Model Context Protocol (MCP) server that talks to the running backend over the same HTTP API the workbench uses, so a message such as *fetch quotes on EuroStoxx and SPX, calibrate in LQD-24 and Local Vol, and chart the comparative LV surfaces* becomes one tool call, the numbers come back as tables, and the charts render inside the conversation.",
    "",
    "Three facts shape everything below:",
    "",
    "- **Same desk.** The chat and the workbench share one universe, one Options dialog and one set of fits. Add a ticker from the chat and the Nodes pane shows it; calibrate from the chat and every lens updates. Nothing numerical lives in the connector.",
    "- **Curated verbs, not the whole API.** About twenty tools with compact outputs — rms in vol basis points, arbitrage flags, readiness — instead of the app's routes. Charts are [MCP Apps](help:glossary:mcp-app): interactive Plotly views the chat host renders inline; a host that cannot render them gets the structured data and, on request, a PNG.",
    "- **One calibration at a time.** A settings change from the chat marks fits stale exactly as the dialog does, and a second calibration waits for the first.",
    "",
    "## Setting it up in Claude Desktop",
    "",
    "1. Start the app (`.\\restart.ps1` from the repo root, any data source). The connector is a client of the backend on :8000 and does nothing without it.",
    "2. Register the server in `%APPDATA%\\Claude\\claude_desktop_config.json`: the command is the repo's venv Python with `-m volfit_mcp`, the environment carries `VOLFIT_API_URL` (default `http://127.0.0.1:8000`). The operator note carries the exact block — [The vol-fitter MCP connector](help:docs:docs_mcp_connector).",
    "3. Restart Claude Desktop. **vol-fitter** appears under Settings ▸ Developer and its tools sit behind the chat's **+** menu.",
    "4. The first chart asks *Allow this app to render?* — choose **Always allow**.",
    "",
    "After a connector code change, quit Claude Desktop from the **system-tray icon**: closing the window leaves the app and the old server process alive, and it keeps answering with the old tool list.",
    "",
    "Local stdio is the right transport on a desk with a Bloomberg Terminal: the Terminal lives on this machine, and a cloud-hosted connector could not reach it.",
    "",
    "## The remote path",
    "",
    "`python -m volfit_mcp --transport streamable-http --port 8765` serves the same server at `/mcp` for claude.ai and mobile. Claude reaches custom connectors from Anthropic's cloud, so the endpoint needs HTTPS (a tunnel, or the hosted container) and an authentication choice — none, an API-key header, or OAuth. One app instance per tenant; Bloomberg stays local. Inline charts from a *custom remote* connector are not yet verified in claude.ai — check before relying on them.",
    "",
    "## The tools, by step",
    "",
    "| Step | Tools | What they do |",
    "|---|---|---|",
    "| Routine | `run_desk_workflow` · `wait_for_workflow` · `workflow_status` | The whole desk routine in one call: universe → fetch → settings → calibrate → report, plus the Local Vol compare chart. |",
    "| A vs B | `compare_settings` | Two calibrations under two partial settings; the differences per ticker and per expiry in vol bp. |",
    "| Sources | `list_data_sources` | A status light per feed and the data age. |",
    "| Universe | `set_universe` · `get_universe` · `list_expiries` | Spoken names (*EuroStoxx*, *the S&P*) become app tickers pinned to a source that lists them. |",
    "| Data | `fetch_preview` · `fetch_quotes` | A coverage dry run; chains and spots. |",
    "| Settings | `get_fit_settings` · `configure_fit` | Model, LQD order, fit target, Local Vol on / off, grid. |",
    "| Run | `calibrate` · `wait_for_calibration` · `calibration_status` · `cancel_calibration` | The background calibration with streamed progress. |",
    "| Numbers | `calibration_report` · `get_smile` · `get_vol_surface` · `get_lv_surface` · `get_lv_compare` | Rms in vol bp, arbitrage flags, readiness, the grids. |",
    "| Charts | `chart_lv_compare` · `chart_smile` · `chart_vol_surface` · `chart_term_structure` | The four inline charts (below). |",
    "",
    "Resources the chat can read: the app status, the live settings and their schema, the documentation catalog and the ticker aliases. Two prompts, *desk_calibration* and *morning_check*, pre-fill the routine.",
    "",
    "## The routine in one message",
    "",
    "`run_desk_workflow` runs the desk routine end to end and records every step; a failing step stops the chain and says why. It runs as a **background job**: the call waits up to `wait_seconds` (60 s by default) with progress streamed, returns the full result if the run is done, and otherwise hands back a handle that `wait_for_workflow` resumes — so no chat host's tool-call budget truncates a live Bloomberg run. A ticker just added is not quoted twice: chains younger than `refetch_if_older_than` (120 s) are left alone.",
    "",
    "**Example.** *Run the desk routine on EuroStoxx and SPX in LQD-24 with Local Vol, and show the LV comparison.* The connector resolves EuroStoxx to SX5E on a source that lists it (Bloomberg or Eurex) and SPX to Cboe, fetches both chains, sets the model and Local Vol, calibrates with progress, and returns the report: per-ticker surface rms, per-expiry rms with the worst slice named, arbitrage flags, readiness. The Local Vol compare card renders in the same reply. On the Terminal this took 102 s for 14 expiries, most of it the first quote request of each new ticker.",
    "",
    "Read the report the way you read the Quality lens: a surface rms driven by one slice is that slice's story, not the fitter's — a 2-day index expiry with an ATM put / call discontinuity in its delayed marks reads 125 bp while its neighbours read 1–4 bp.",
    "",
    "## A vs B settings",
    "",
    "`compare_settings` calibrates twice under two partial settings — LQD-24 against LQD-16, mid against haircut, calendar enforcement on against off — and tabulates the differences per ticker and per expiry in vol bp. The run named `keep` goes last, so the app ends calibrated under the settings you want to work with.",
    "",
    "## The charts",
    "",
    "Every chart is an [MCP App](help:glossary:mcp-app): a Plotly view inside the chat with its own controls.",
    "",
    "- **LV compare** — the fitted affine local-vol sheet, the parametric surface's Dupire twin and their difference, as 3D or heatmap, with a per-expiry rms strip whose bars send a message back to the chat.",
    "- **Smile** — the fitted smile against the bid / ask bands, with prev / next expiry buttons.",
    "- **Vol surface** — σ(k, T) as 3D or heatmap on a k, K/F or strike axis, cropped to the quoted range, with the ATM ridge; a click opens that smile.",
    "- **Term structure** — ATM and var-swap vol and total variance on the calendar or the event-dilated clock, with events, dividends and calendar violations; a click opens that smile.",
    "",
    "Every card carries a **Workbench** button that opens the same node in this app (`/?node=TICKER|YYYY-MM-DD&activity=…`), so a chat finding lands on the lens in one click.",
    "",
    "## The fit target rule",
    "",
    "A tool called without a fit target uses the Options dialog's target — [fitMode](help:settings:fitMode) — never the target the UI last viewed, which a chat cannot see. A run, its report and its charts therefore always name one target; ask for another explicitly.",
    "",
    "Units everywhere: rms in vol basis points (1 bp = 0.01 vol point), vols as decimals, `k = ln(K/F)`, `x = K/F`, `t` in years.",
    "",
    "## When a card does not appear",
    "",
    "- Set `VOLFIT_MCP_TRACE` to a file (or pass `--trace`): one JSON line per inbound MCP message — the host's advertised capabilities, every resource read, every tool call and its outcome. Chat hosts log message names only, so this is how a silent *no card* is diagnosed.",
    "- The chart pages show a status line for every failure state — *Connecting to the host*, *Loading the chart library*, *the host blocked the chart library*, *no chart data* — instead of a blank card.",
    "- The pages embed their own Plotly bundle (`VOLFIT_MCP_PLOTLY=inline`, the default), so a sandbox that blocks the CDN still renders; `cdn` serves the small page instead.",
    "- `VOLFIT_WORKBENCH_URL` sets where the Workbench buttons point (default the Vite dev server); empty hides them.",
    "",
    "## Limits",
    "",
    "- One desk per app instance: two chats against the same backend share the universe and the settings.",
    "- Tool-call time budgets in chat hosts are undocumented: `calibrate` waits at most `wait_seconds` and hands back a resumable status; the macros hand back a `wait_for_workflow` handle.",
    "- Live Bloomberg timing is the Terminal's reference-data throughput: the first quote request of a new ticker costs tens of seconds per few thousand contracts; the calibration itself is ~15 s.",
    "",
    "Verification: `pytest tests/test_mcp_connector.py tests/test_mcp_stdio.py` runs the whole pipeline against the synthetic app plus a real stdio launch; `node scripts/mcp_app_check.mjs` plays the chart host headlessly.",
  ].join("\n"),
};
