// Guides — lenses, first half (HELP CENTER ARC, H1): graph, forwards.
// Grounded in views/GraphViewer.tsx + components/graphshell/*, and
// views/ForwardsViewer.tsx + components/ForwardPanel.tsx + DividendEditor.
import type { GuidePage } from "../types";

export const GRAPH: GuidePage = {
  id: "graph",
  title: "Graph lens — extrapolating the dark universe",
  lens: "graph",
  summary: "Draw the relations between markets as arrows on a canvas, preview, run the propagation, explain every reconstructed node, and validate the skill.",
  related: ["help:glossary:graph-extrapolation", "help:glossary:precision-messages", "help:glossary:relation", "help:glossary:relation-confidence", "14_graph_extrapolation", "14_graph_messages", "14_graph_three_priors"],
  body: [
    "## What it is for",
    "",
    "The Graph lens fills the **dark** nodes of the universe from the **lit** ones. Each node carries three ATM handles (level, skew, curvature); the lit nodes' innovations propagate along calendar edges (one ticker's expiries) and cross-asset edges (index or ETF → names), and every dark node's transported prior smile is [retargeted](help:glossary:retargeting) to the posterior handles, wings intact. The spine is **Configure → Preview → Run → Explain → Validate**; configuring is now a canvas of arrows, not a form. It needs the live backend.",
    "",
    "## Layout",
    "",
    "- **Top bar** — observation source (`From calibrations` | `Manual what-if`), the operator (`Layered` | `Precision`, with `Smooth field` appearing as a third segment only while it is the selected legacy operator), the **config pill** (`config <name> vN` or `config auto`, with an amber *N edits* tag while the draft differs from the active config — **Apply** / **Discard**), the **preflight chip** (rose blocker · amber warnings · emerald clean · slate no report), the **Live** toggle, the post-run summary (tagged *preview* when it came from Live rather than a Run), the last error, `Clear field` (resets the posterior, keeps observations) and **Run** — the single primary action, and the only one that records.",
    "- **Coupling** (left; follows Layout ▸ Diagnostics aside) — three disclosure levels, nothing from a deeper one shown at a shallower one:",
    "  - **Level 0** (what you touch every day): the **Desk | Learned** amplitude preset, the **Calendar relations** switch with its **Calendar @ ref distance** confidence slider, the **Cross-asset** confidence slider — both σ in vol points, right = more confident — a live +1 pt example on the canonical 3M/6M pair, and the **Relations · n** button into the drawer.",
    "  - **Fine-tune** (shape, family, overrides): the calendar shape exponent αT, the amplitude levels ρ calendar / ρ cross-asset, the calendar decay family and ε, cross-expiry tolerance, per-ticker **Calendar overrides** with the ladder view, the **Cross-asset matrix** (receiver × informer, β/σ per cell), and — Layered only — **Dynamics** (clamp max age, residual half-life, per-class semantics).",
    "  - **Advanced**: the units toggle (σ vol points / raw precision p) and **Smooth field (legacy)**, which swaps the whole pane for the legacy weights, the η κ λ ν dials and the per-edge weight matrix, with **← Back to Layered** to leave it.",
    "- **Smile universe** (centre) — the canvas: ticker pods on calendar spines, every relation an **arrow** from informer to receiver. After a run the reveal stages nodes by their BFS distance from the observations — an attribution picture, never solver chronology (the posterior is solved jointly).",
    "- **Inspector** (right) — a selected **arrow** shows the relation card (sliders); otherwise the selected node's facts and its prior → posterior move: ATM vol · Skew · Curvature · Shift, **Posterior confidence (1σ)**, **Incoming confidence q = Σp**, Innovation, Prior source, Prior as-of, Transport distance; *Open this node's reconstructed smile*. Under Layered or Precision the **Message inspector** lists incoming messages (informer, its innovation z, β, the vote β·z, σ_edge), the exact local consensus and the global posterior with a divergence explainer.",
    "- **Drawer** (bottom) — `Relations` | `Preview` | `Diagnostics` | `Validation` | `Observation plan`.",
    "",
    "## First run",
    "",
    "1. Mark what is dark ([Managing the universe](help:guides:universe)). At least one lit node must connect to each dark component; a component with no lit path stays at its transported prior with a broad band (the inspector says so).",
    "2. Make sure the lit nodes are calibrated — the graph reads committed fits.",
    "3. Leave the operator on **Layered** (the default) and the source on **From calibrations**.",
    "4. Read the **preflight chip**. Amber warnings are worth a click; rose blocks Run.",
    "5. **Run**. The canvas reveals hop by hop; the drawer opens **Diagnostics** (cycle warnings + the per-node prior → posterior table). Turning **Live** on first lets a dial or an arrow edit re-solve as you go — nothing is recorded until you press Run.",
    "6. Click a dark node. The inspector shows how far it moved and how confident the posterior is; the message inspector shows *who* moved it.",
    "7. Double-click it: its reconstructed smile opens as a pinned tab under the Parametric lens with a **GRAPH** badge (model · prior source · posterior var-swap ± 1σ; `✕` clears the overlay).",
    "",
    "## The canvas is the editor",
    "",
    "Every relation draws as an **arrow**, informer → receiver: thickness reads relationship confidence on fixed σ anchors (10 pt thin … ¼ pt thick, the same anchors the Confidence sliders use, so a slider move and the arrow it draws always agree), colour reads β (cool below 1, slate at 1, warm above 1, rose when negative). Cross-ticker relations bundle into one curve per ticker pair — width = the pair's total incoming confidence Σp, colour = its confidence-weighted mean β — and a click expands the bundle into its individual arrows.",
    "",
    "- Click an arrow (or a calendar hop) to open its **relation card** in the Inspector.",
    "- The **Connect** tool (canvas toolbar), or Shift-drag from any node, draws informer → receiver as a new relation and selects it.",
    "- Click a ticker's pod label to collapse it to one node; the toolbar's collapse-all / expand-all button does every pod at once.",
    "- **Focus** (canvas toolbar) hides the Coupling pane and the Inspector so the canvas gets the whole lens; **Esc** restores them (or, with a relation selected, clears the selection first).",
    "",
    "## The relation card",
    "",
    "Selecting an arrow opens its card in the Inspector: informer → receiver, a class select, **⇄** to flip the direction and **×** to close the card without deleting anything.",
    "",
    "- **Confidence** — the σ slider (σ = 1/√p vol points, or raw p behind the units lens). A calendar row still following the maturity-distance rule shows an **auto** badge and today's derived value; moving the slider locks it explicit, and **↺** returns it to the rule (a cross row's ↺ returns to the pane's cross-asset confidence).",
    "- **β** — one slider, mark at 1, with an exact-entry box; **link handles** (on by default) drives β ATM, β skew and β curvature together, unlink to set **β skew** / **β curvature** on their own.",
    "- **Semantics** (Layered only) — reciprocal ⇄ or directed →, or **auto** (the class default).",
    "- The footer reads the **implied reverse** (1/β, σ/|β| — the one-factor identities), carries **+ reverse** and **Delete**. An arrow is ONE factor, drawn informer → receiver; under reciprocal semantics information already flows back at the implied values, so you rarely need a second arrow. **+ reverse** adds the explicit opposite arrow as its own factor (flipped identities) — the tool for a directed relation you want in both directions, with the caveat that two directed arcs facing each other form a directed cycle the Layered solve rejects (preflight blocks it). Once the opposite arrow exists the button reads **⇐ reverse** and selects it.",
    "",
    "## The Relations tab",
    "",
    "The drawer's **Relations** tab lists every arrow of the canvas as a row: a search box, class chips (calendar, index, etf, peer, custom — each with its count), a sort selector (informer, receiver, confidence, |β|), and a click on a row selects it on the canvas and opens its relation card; **×** removes it. The toolbar carries **Undo** / **Redo** (Ctrl+Z / Ctrl+Y), **Seed auto** (load the auto relations as editable rows), **Reset to auto** (stage an empty draft — the solve falls back to the auto relations), **Templates ▾** — **Hub → names** (a chosen ticker informs every other ticker's matching expiry), **Peers ⇄** (one reciprocal factor per ticker pair and shared expiry) and **Calendar only** (drop every cross relation) — and **Full editor** for the per-handle grid with the golden-scenario preview.",
    "",
    "## Operators",
    "",
    "- **Layered** — the default. The dynamic-harmonic pipeline: directed parents (systematic β·m) + the node's own remembered dislocation u decaying by a half-life + harmonic completion. The **Decomposition** card in the inspector shows mark = baseline + systematic + residual + harmonic with the residual-surprise χ, and the drawer's **Timeline preview** scrubs the A/B fixture through time.",
    "- **Precision** — every edge is a contract z_i ≈ β z_j at a stated relation variance. Full configured amplitude regardless of confidence; competing messages precision-averaged, never added (equal opposing signals cancel to 0.00); distance costs confidence, not amplitude; a silent neighbour costs nothing. Policy lives in the Coupling pane's Level 0 and Fine-tune sections.",
    "- **Smooth field (legacy)** — reached from the pane's Advanced section only: a screened directed-Laplacian smoothness prior with the dials [κ](help:settings:graphKappaScale) · [η](help:settings:graphEtaScale) · [λ](help:settings:graphLambdaScale) · [ν](help:settings:graphNu) in its **Solver** section, plus a **Weights** section (calendar / cross-ticker weight, cross-ticker β) and an **Edges** button into the per-edge matrix; the autotune scores η by leave-one-out. It stays the *wire* default and the explicit rollback, so replay and the byte-identity locks are untouched even though the dialog leads with Layered.",
    "",
    "## Config lifecycle: Apply / Discard",
    "",
    "What you see is what runs. Every relation edit — a slider move, a Connect gesture, a template, an undo — stages a **draft** at once; while the draft differs from the active config, **Run** solves the draft, not the active config (there is no separate run-draft toggle). The config pill's popover shows both slots, the diff (`+added −removed ~changed`), an optional note, **Apply** (promotes the draft to active, event-logged) and **Discard** (reverts to a clean copy of active). Saving a Dynamics policy stages it on the draft the same way.",
    "",
    "## Live preview",
    "",
    "The **Live** toggle re-solves the current body — dials, arrows, pulses, whichever operator is selected — a few hundred milliseconds after each change, and tags the summary strip **preview**. A live preview never records: no innovation history, no residual-store write, nothing for `graph_inferred` to remember. Switching it off leaves the last preview on screen until the next **Run**, which always commits.",
    "",
    "## What-if pulses",
    "",
    "Switch the source to **Manual what-if**: click a node to pulse / unpulse it, drop a node from the Nodes pane for +1 vol pt, or pick a canonical scenario in **Preview** (`Calendar pulse` · `Competing signals` · `Cross basket`). Run solves the active operator on the production machinery with those synthetic observations; nothing persists.",
    "",
    "## Validation and the observation plan",
    "",
    "**Validation** runs the current-day leave-one-node-out side by side — transported prior (no propagation) vs smooth field vs messages — and links the offline multi-regime benchmark artifact (404 until a pack has run). Read [skill](help:glossary:skill) in ATM vol bp and [ζ](help:glossary:zeta) (std 1 = bands the right width). **Observation plan** ranks *where to quote next* on the solved posterior, with a why-annotation per candidate.",
    "",
    "## Numbers and badges",
    "",
    "- **β** — the edge's amplitude; |β| beyond the cap renders amber. **σ** — the relationship uncertainty in vol points (or **p** = 1/σ²), on the same fixed anchors (10 pt … ¼ pt) as the arrow width and the Confidence sliders. **q = Σp** — incoming confidence; the solved marginal sd is authoritative.",
    "- **Innovation** — the lit node's fitted-minus-prior handle move, the thing that propagates.",
    "- **χ** — residual surprise (Layered): |χ| > 2 is a loud dislocation.",
    "- **Cycle warnings** — cycles whose β product ≠ 1, an internally inconsistent edge configuration.",
    "",
    "## Chords",
    "",
    "Click a node or an arrow inspects it · double-click a node opens its smile · Delete removes the selected relation · Esc clears the selection (or leaves Focus) · drag node → node adds a relation (a plain drag, the Connect tool, or Shift) · Ctrl+Z / Ctrl+Y undo / redo the draft · drag node → node (plain, Connect tool or Shift) adds a relation · drag the background / wheel pan and zoom · drop a Nodes-pane row to light it (calibrations) or pulse it (what-if); dropped on the tab strip it opens pinned.",
    "",
    "## Pitfalls",
    "",
    "- An exact skill of `0.000` bp is a **disconnection**, not damping — check the topology (the transient-name case file).",
    "- The reveal animation is attribution, not chronology; do not read hop order as solve order.",
    "- Bands are guarded by the [idiosyncratic floor](help:glossary:idio-floor); in calm tape dark-name skill ≈ 0 is expected — the graph carries shared repricing, not earnings news.",
    "- Smooth-field's dials and its per-edge weight matrix do nothing under Layered or Precision; conversely, the relation card, the Relations tab and the Layered Dynamics card are all inert under Smooth field — there is no relation editor to open.",
    "- A relation card's **auto** badge means the confidence slider is still following the maturity-distance rule — moving it locks in an explicit value, and only **↺** returns it to the rule.",
    "- The Local Vol lens can calibrate to the graph-extrapolated smiles (its `Graph-extrapolated` toggle) — a projection, labelled as such.",
    "",
    "## Related settings",
    "",
    "[graphPropagationMode](help:settings:graphPropagationMode) · [graphKappaScale](help:settings:graphKappaScale) · [graphEtaScale](help:settings:graphEtaScale) · [graphLambdaScale](help:settings:graphLambdaScale) · [graphNu](help:settings:graphNu) · [priorPersistenceMode](help:settings:priorPersistenceMode)",
    "",
    "## Read more",
    "",
    "[Graph smile-extrapolation (Note 14)](help:docs:14_graph_extrapolation) · [Every edge is a contract](help:docs:14_graph_messages) · [Three priors for a dark universe](help:docs:14_graph_three_priors) · [Precision-message framework](help:docs:docs_graph_precision_messages) · [Dynamic directed-harmonic framework](help:docs:docs_graph_dynamic_harmonic)",
  ].join("\n"),
};

export const FORWARDS: GuidePage = {
  id: "forwards",
  title: "Forwards lens — forwards, dividends and borrow",
  lens: "forwards",
  summary: "Read the parity, theoretical and active forward per expiry, fix a bad read, set carry and dividends — every other lens refits from here.",
  related: ["help:glossary:forward", "help:glossary:carry-borrow-dividends", "06_forwards_dividends", "06_forwards_dividends_inference"],
  body: [
    "## What it is for",
    "",
    "Every smile is drawn in log-moneyness k = log(K/F), so a wrong forward shifts the whole smile and gaps it at the money. The Forwards lens is where the forward of each expiry is read, judged and, when needed, overridden — for the active tab's **ticker**, across its whole expiry ladder. Parametric and Local Vol both read the active forward through the ticker's forwards version, so an edit here refits every lens. Live backend only.",
    "",
    "## Layout",
    "",
    "- **Top** — the forward-curve chart with dividend ex-date markers.",
    "- **Left — the ladder**: `Expiry` · `T` · `Parity` · `Theo` · `Manual` · `Active` · `Borrow` (implied borrow in bp, with its 1σ noise floor in the tooltip) · optional `Joint` · `±σ` · `Source`. Clicking a row opens that node's tab (preview) and moves the editor to it.",
    "- **Joint carry** checkbox — the joint borrow / de-Am fixed point per expiry: de-Americanize at the split carry, iterate to the parity / theoretical fixed point; adds the Joint and ±σ columns.",
    "- **Right — the Forward panel** for the tab's expiry:",
    "  - the three candidates side by side — **Parity** (with its regression diagnostics), **Theo** (from the carry model), **Active** (the one the fit uses);",
    "  - the **mode** switch (parity · theoretical · manual) and a **Manual forward** box;",
    "  - the carry inputs `r` (continuous rate) and `q` (dividend yield) that feed the theoretical forward;",
    "  - the **dividend editor** — *Dividend model*: continuous · discrete absolute · discrete proportional · mixed (cash before the switch horizon, proportional after); a schedule of ex-dates and amounts with `Remove dividend` per row;",
    "  - **Apply**, which posts the change and triggers the session reload so the smile refits.",
    "",
    "## Dividend models",
    "",
    "- **Continuous** — a yield `q`; the forward is F = S e^{(r−q)T}. Right for indices and most ETFs.",
    "- **Discrete absolute** — cash amounts on ex-dates; the forward drops by the compounded cash. Right for single names inside the announced horizon.",
    "- **Discrete proportional** — a fraction of spot on each ex-date; scales with the spot move.",
    "- **Mixed** — discrete before [switchYears](help:settings:switchYears), continuous after: the announced dividends, then a yield for the long end.",
    "",
    "## First use",
    "",
    "1. Open any node of the ticker and press Alt+2.",
    "2. Read the ladder. `Parity` and `Theo` should agree to a few bp of borrow on a liquid name. A `Parity` far from `Theo` on one expiry, with a large `±σ`, is a noisy or gated chain, not a market read.",
    "3. Look at the smile of that expiry under Parametric: a wrong forward shows as a kink or gap at the money.",
    "4. Switch the mode to **Theo** for that expiry (or type a **Manual** level), set `r` and `q` if the carry model needs them, and **Apply**. The ticker's version bumps; its nodes refit (or go stale, under the gate).",
    "5. For a dividend-paying name, set the dividend model and enter the schedule; the chart's markers should land on the ex-dates.",
    "",
    "## How the parity forward is read",
    "",
    "Put-call parity makes C − P = D (F − K) a straight line in K. Least squares pins the line's **level** (the forward) to a fraction of a bp and its **slope** (the discount, hence the rate) poorly — tens of bp on a realistic chain. Production therefore keeps the price level, trims incoherent stale quotes, clamps the rate into a physical band, and runs a near-ATM American de-bias loop so the regressed forward is consistent with American quotes. Trust the well-identified parameter.",
    "",
    "## Numbers and badges",
    "",
    "- **Borrow (bp)** — the implied borrow from parity vs the theoretical carry; its tooltip carries the 1σ noise floor (parity residuals / (t √n)) — a read is only as good as this.",
    "- **Joint · ±σ** — the fixed-point borrow and its sd, engaged per expiry only above [jointCarryEngageBp](help:settings:jointCarryEngageBp); below it the parity forward is kept exactly.",
    "- **Source** — where the active forward came from: parity, theoretical, manual, or the zero-carry pin.",
    "- **T** — the year fraction to expiry on the calendar clock (the event clock never touches carry).",
    "- The gap between **Parity** and **Theo**, read as a rate over `T`, is the implied **Borrow**; a borrow that jumps between adjacent expiries is a data problem before it is a market fact.",
    "- The **synthesized zero-carry** pill: the feed gated NBBO and emitted Black prices from its own IV marks at F = spot, D = 1, zero spread; parity carries no information, so the forward is pinned to that convention.",
    "",
    "## Chords",
    "",
    "Click a ladder row to move the editor (preview tab) · the chart pans and zooms like every other (wheel, drag, double-click resets).",
    "",
    "## Pitfalls",
    "",
    "- **The ATM kink.** A slope contaminated by the early-exercise premium of deep ITM puts shows up as a kink at the money; read the gap locally at F rather than trusting the regressed slope.",
    "- **The delayed feed that gapped the ATM smile** — a failed rate anchor; the discount clamp is the fix, and the pill above explains when parity is inert.",
    "- Editing carry or dividends bumps that ticker's version only; with [autoCalibrate](help:settings:autoCalibrate) off the nodes wait, stale, for Calibrate.",
    "- The Market settings (`rate`, `dividendMode`, `dividendYield`, `dividends`, `switchYears`) are per ticker: what you set here does not touch the next name.",
    "- De-Americanization and carry always run on the calendar clock, even with the event clock on.",
    "",
    "## Related settings",
    "",
    "[jointCarry](help:settings:jointCarry) · [jointCarryEngageBp](help:settings:jointCarryEngageBp) · [rate](help:settings:rate) · [dividendMode](help:settings:dividendMode) · [dividendYield](help:settings:dividendYield) · [dividends](help:settings:dividends) · [switchYears](help:settings:switchYears)",
    "",
    "## Read more",
    "",
    "[Forwards, discounting and dividends (Note 06)](help:docs:06_forwards_dividends) · [One straight line](help:docs:06_forwards_dividends_inference) · [De-Americanization (Note 05)](help:docs:05_deamericanization)",
  ].join("\n"),
};
