// Guides — lenses, second half (HELP CENTER ARC, H1): parametric, localvol,
// quality. Grounded in views/SmileViewer.tsx + components/parametric/*,
// views/LocalVolViewer.tsx + components/localvol/*, views/QualityViewer.tsx
// + components/quality/*, and lib/shortcuts.ts.
import type { GuidePage } from "../types";

export const PARAMETRIC: GuidePage = {
  id: "parametric",
  title: "Parametric lens — smiles, densities, term structure",
  lens: "parametric",
  summary: "Read and edit one node's smile, compare model families, and check butterfly and calendar cleanliness across the ticker's ladder.",
  related: ["help:glossary:smile", "help:glossary:fit-target", "help:glossary:lqd", "01_lqd_model", "07_calibration_objective"],
  body: [
    "## What it is for",
    "",
    "The Parametric lens is the per-expiry fitting and editing view: the active tab's smile against its quotes, the risk-neutral density behind it, the other model families on the same quotes, and the ticker-level views that test arbitrage across expiries. Quote edits post to the backend fit session and the returned refit replaces the curve.",
    "",
    "## Layout of the chart card",
    "",
    "- **Toolbar** — NODE views `Smile · Density · Compare · Table` (about the tab's expiry) and TICKER views `Term · Densities · Stacked IV · Surface` (the whole ladder).",
    "  - On Density, the sub-toggle `Density · Log Q-density · CDF`.",
    "  - Right-aligned badges: `LIVE` / `MOCK`, `STALE`, `UPDATED`.",
    "- **Header** — the node title, the **GRAPH** and **FILTER** provenance badges when an overlay is active, and the quote toolbar: `Undo` · `Redo` · `Reset edits`.",
    "- **Chart** — with the **layer rail** at its right (`Target` · `Calib. quotes` · `Calib. fit` · `Weights`) and `Y-center` / `Y-fit` as overlay buttons on the chart itself.",
    "- **Footer** — the interaction hint, and the x-axis unit next to the axis: `k = ln(K/F)` · `Strike K` · `% ATM` · `Delta` · `(K−F)/σF√T` · `k/σ√T`. A range brush under the smile sets the strike window.",
    "- **Aside** (Layout ▸ Diagnostics aside), three cards:",
    "  - `Spot move` — a **Market spot / Scenario** selector (the followed level is lit, the other dimmed): the market spot streams off the live book when one is up (else the last probe / fetched chain) and keeps the surface synced to it; the scenario is the SSR dial — ±0.1 % fine-tune buttons (Shift: 1 %), **Reset to 0.0%**, **Sync to market** — that transports every lens live. **Recalibrate _ticker_ (_scope_)** is the top-bar Calibrate for this ticker only: the same scope (Param + LV / Param only / LV only, read from the top bar) and the same snapshot rule (streamed quotes + spot when a book streams, else the last fetched chain), as the background job; the previous fit stays on screen until the new one lands.",
    "  - `Variance swap` — one quote per node, seeded at the model's fair level; slider or exact entry, exclude, remove, undo; the penalty weight readout.",
    "  - `Fit diagnostics` — ATM · skew · curvature · RMS; wings, Lee slopes and var-swap vol at the expanded size; the model + hyperparameters chip (full values in the tooltip).",
    "  - **Three sizes, one expanded at a time.** Every card is compact (one row: title + a live readout), standard (the default) or expanded. The ⇕ toggle in a header — or a click on a compact row — expands that card and compresses the other two, so the column never scrolls; the toggle on the expanded card folds all three back to standard. Shared with the Local Vol aside, kept across reloads.",
    "",
    "## The four layers",
    "",
    "- **Target** — the shaded fit target: the mid, the bid-ask band, or the haircut band.",
    "- **Calib. quotes** — the quotes the last calibration saw, with your exclusions and amendments.",
    "- **Calib. fit** — the fitted curve on its calibration spot (vs the market frame's rolled fit).",
    "- **Weights** — the effective per-quote weight strip under the smile.",
    "",
    "## Two frames on one chart",
    "",
    "**Market** = the prevailing bid/ask quotes with their target, and the fit *rolled* to the prevailing spot. **Calib.** = the quotes and target the last calibration used (with your exclusions and amendments), and the fit on its calibration spot. Each frame sits at its own forward, so both are internally comparable. On a streaming source the market frame updates at ~1 Hz.",
    "",
    "## First use",
    "",
    "1. Open a node (Nodes pane click). The Smile view shows bid/ask bands, the shaded target and the fitted curve; a dashed prior when one is loaded.",
    "2. Click a quote to select it. `Del` excludes it (again restores); `↑ / ↓` amend its mid by 0.1 vol pt (`Shift` = 0.5); `Ctrl+Z / Ctrl+Y` undo / redo; `Esc` deselects. The refit lands with an `UPDATED` flash.",
    "3. Switch to **Density**: the pdf must be ≥ 0 everywhere (structural for LQD). **Log Q-density** shows ℓ(u) = log q(u), the LQD backbone; **CDF** the distribution function.",
    "4. **Compare** shows the prevailing family; click another family's chip to fit it lazily on the same quotes. Read `RMS bp` · `Max bp` · `Tails L/R` (each side's tail contract: exp, or int / gauss for generalized LQD tails) and the validity chip (certified / breach / no signal).",
    "5. **Table** lists the market frame (quotes, target, fit at market spot); `Calib. quotes` toggles the calibration columns; Copy / CSV in the footer.",
    "6. **Term** — the ATM term structure across the ladder, real or event-dilated clock; the lower panel is the forward-variance ladder per interval. While an event calendar is active the calendar-day reading (√(w/t) above, the invariant Δw/Δt below) is drawn dashed beside the working clock's, so an event's effect — the hot interval pulled down, the vol crush — shows on either axis. **Auto-calibrate events** reads every interval hotter than both its neighbours as one exactly sized event (ramps, backwardation and dips yield none); its result line and the ladder spread before → after sit under the button. **Densities** overlays every expiry's density (SVI/MCS dips draw signed in red). **Stacked IV** overlays total variance w = σ²T — non-crossing means no calendar arbitrage. **Surface** — σ(k, T) in 3D; hover for the linked crosshair.",
    "",
    "## Numbers and badges",
    "",
    "- **RMS · max** in vol bp, against the active [fit target](help:glossary:fit-target) — zero inside a band.",
    "- **ATM · skew · curvature** — the three [handles](help:glossary:handle); **Lee L/R** the wing slopes (cap 1.95); **var-swap vol** the model's fair level and, when quoted, the basis.",
    "- `STALE` — inputs moved since the fit; `MOCK` — no backend, a built-in fixture; `UPDATED` — a refit just landed.",
    "- **GRAPH** — this smile is a graph reconstruction (model · prior source · quote metrics · posterior var-swap ± 1σ; `✕` clears). **FILTER** — the observation filter's gains per handle and ρ; amber when the measurement was flagged contaminated.",
    "- The **Weights** layer draws the effective per-quote weights so you see what the optimizer sees.",
    "",
    "## Chords",
    "",
    "Click a quote · `Del` exclude / restore · `↑ ↓` amend (Shift ×5) · `Ctrl+Z / Ctrl+Y` · `Esc` · wheel zoom (`Shift` x, `Alt` y) · drag pan · double-click reset · brush the strike window.",
    "",
    "## Pitfalls",
    "",
    "- In `MOCK` mode there is no fit session: quote edits do nothing until the backend is up.",
    "- Stacked **vol** smiles carry no calendar content; only **Stacked IV** (total variance) tests it. ATM-only monotonicity is necessary, not sufficient.",
    "- A band-fit RMS is legitimately smaller than a mid-fit RMS; compare like with like.",
    "- `Y-fit` rescales to the curves, `Y-center` recentres on ATM; `Alt+wheel` bypasses the auto-scale.",
    "- Save prior lives in the top bar's `Priors ▾`, not here.",
    "",
    "## Related settings",
    "",
    "[model](help:settings:model) · [nOrder](help:settings:nOrder) · [fitMode](help:settings:fitMode) · [haircut](help:settings:haircut) · [weightScheme](help:settings:weightScheme) · [leeSlopeMax](help:settings:leeSlopeMax) · [sviChart](help:settings:sviChart) · [bellyRepair](help:settings:bellyRepair) · [varSwapEnabled](help:settings:varSwapEnabled) · [enforceCalendar](help:settings:enforceCalendar) · [tailAlphaLeft](help:settings:tailAlphaLeft)",
    "",
    "## Read more",
    "",
    "[The LQD model (Note 01)](help:docs:01_lqd_model) · [SVI and SVI-JW (Note 02)](help:docs:02_svi_jw) · [The calibration objective (Note 07)](help:docs:07_calibration_objective) · [Calendar arbitrage (Note 10)](help:docs:10_calendar_arbitrage)",
  ].join("\n"),
};

export const LOCALVOL: GuidePage = {
  id: "localvol",
  title: "Local Vol lens — the jointly fitted surface",
  lens: "localvol",
  summary: "The piecewise-affine local-variance surface calibrated to the whole ticker at once, its reconstructed smiles, densities, term structure and 3D meshes.",
  related: ["help:glossary:local-volatility", "help:glossary:dupire-pde", "help:glossary:dupire-twin", "04_local_volatility", "docs_localvol_methodology"],
  body: [
    "## What it is for",
    "",
    "The Local Vol lens shows the fourth model: one continuous piecewise-affine local-**variance** sheet on a strike × maturity grid, calibrated jointly to every lit expiry of the ticker through the Dupire PDE as a pricing map. Every view here is derived from that calibrated surface (`POST /fit/affine/{ticker}`). Live backend only; the activity-bar icon is inert while [localVolEnabled](help:settings:localVolEnabled) is off.",
    "",
    "## Layout",
    "",
    "- **Toolbar** — NODE views `Smile · Table` (the tab's expiry) and TICKER views `Term · Densities · Stacked IV · LV surface · IV surface · Compare`.",
    "  - On **LV surface**, the render toggle `3D σ²_loc` / `Heat map`.",
    "  - On **Term**, the clock toggle `Real time` / `Event-dilated`.",
    "  - The **Graph-extrapolated** button: calibrate the surface to the graph's reconstructed smiles instead of the live quotes.",
    "  - Right-aligned badges: `STALE`, `arb-free` or `n cal. viol.`, and `rms · conv · max bp`.",
    "- **Footer** — the strike-axis unit: the Parametric selector on the smile, densities, IV surface and stacked-variance views; on the 3D LV mesh `x = K/F` · `k = ln(K/F)` · `Strike K` (the nodal grid lives in x, so only coordinates derivable from it are offered).",
    "- **Aside**, three cards like the Parametric lens:",
    "  - `Spot move` — the same card, wired to the shared session.",
    "  - `Variance swap` — on the affine payload's own var-swap information.",
    "  - `Fit diagnostics` — smile and surface RMS, the **per-expiry fit table** (a row click opens that expiry's tab; it scrolls inside a capped height at the standard size and runs free when expanded) and the **calibration trace player** (replays the accepted solver steps; scrub or play).",
    "  - The same three sizes and the same ⇕ toggles as the Parametric aside — one card expanded, the other two compact.",
    "",
    "## The views, one line each",
    "",
    "- **Smile** — the reconstructed arbitrage-free smile of the tab's expiry vs its quotes.",
    "- **Table** — per-strike reconstructed IVs and prices for that expiry.",
    "- **Term** — ATM and var-swap term structure across the ladder, on either clock.",
    "- **Densities** — every expiry's Breeden-Litzenberger density overlaid (≥ 0 ⇔ no butterfly).",
    "- **Stacked IV** — total variance w = σ²τ per expiry (non-crossing ⇔ no calendar).",
    "- **LV surface** — the nodal local-variance grid, as a 3D mesh or a heatmap.",
    "- **IV surface** — the implied-vol mesh reconstructed from the surface over t × strike.",
    "- **Compare** — the parametric surface's **Dupire twin** beside the fitted sheet: two local-variance sheets, their difference, and the smiles and scores of both (see below).",
    "",
    "## The Compare tab — the Dupire twin",
    "",
    "There are two ways to get a local-volatility surface out of a market, and they read the Dupire equation in opposite directions. The LV fit reads it as a **pricing map**: it looks for the positive piecewise-affine sheet whose forward-PDE prices meet the quotes. The **Dupire twin** reads it as a **formula**: it takes the calibrated parametric surface (the displayed model — LQD, or the SVI-JW / MCS overlay), carries its total variance between expiries, differentiates it twice in strike and once in maturity, and divides. The tab puts the two side by side on the same vertex lattice, so the difference between fitting a surface and differentiating one is something you can look at.",
    "",
    "- **Time chips** — how the parametric total variance is carried between listed expiries before it is differentiated: **Smooth** (default) is a monotone C¹ interpolation in variance time, so the twin is continuous in both directions; **Buckets** is the market staircase, constant forward variance per listed expiry.",
    "- **Tails chip** — what the surface is beyond the quoted range: **Model wings**, the displayed model's own analytic wings (the only target in v1; *Match LQD*, *Quoted range* and *Affine wings* are listed as coming). An exponential-class wing gives a local variance growing without bound in log-moneyness while the fitted sheet is Gaussian-class there — the wings are where the two structurally differ, and the twin shows that as it is.",
    "- **Sheets** — the twin on the left (drawn *smooth*: the surface sampled between the vertices, the vertices themselves exact), the fitted sheet on the right (its own triangles). One camera, one crop: rotate, zoom or brush either and both follow.",
    "- **Difference** — twin minus fitted sheet in vol, on a diverging ramp symmetric about zero, with a signed readout per vertex.",
    "- **Smiles** — the tab's expiry with the fitted reconstruction (sky), the parametric source (lime) and the twin (orange, dashed) on the quotes, and a per-expiry score table below it (click a row to move to that expiry).",
    "- **The strip** — RMS vs the fit target for the twin, the fitted sheet (on its converged operator) and the parametric source; the **round trip**: the twin repriced back against its own parametric source at the quoted strikes, with two companions — the **floor** (a flat surface's error on the same operator: no round trip reads below it) and the **sheet** figure (the vertex sample's own round trip: what a coarse lattice loses); then the repairs the extraction needed (butterfly cells where the implied surface itself carries strike arbitrage, calendar cells where its variance decreases in time, floored and capped cells — counted per row, hover for the detail).",
    "",
    "Two rules keep the comparison meaningful. The twin's smile and scores come from the **smooth** surface on a second-order display operator (never from the coarse sample, and never from the fit's own first-order calibration operator, which misprices a one-month front by over a hundred basis points even for a flat surface — that is why the fitted sheet's *conv* figure can sit far above its *rms*). And the comparison is **anchored**: built at the calibration spot, from the calibrated fits and the calibration cache, so a live spot tick never rebuilds it; a moved spot shows an **ANCHOR** badge with the shift.",
    "",
    "The twin is a reference, not a model: never a fit, never a prior, never the LV calibration's seed.",
    "",
    "## First use",
    "",
    "1. Calibrate with scope *Parametric + LV* or *Local-Vol only*. The status bar narrates the LV job per ticker.",
    "2. Open a node, press Alt+4. **Smile** shows the reconstructed arbitrage-free smile against the quotes.",
    "3. **LV surface** — the nodal grid as a 3D mesh (drag rotates, `Shift+drag` pans, `Ctrl+drag` pitches, the wheel zooms about the sheet's centre, double-click resets; the two sliders beside and below the plot crop a strike × maturity rectangle, and the crop is re-centred so the sheet never leaves the window) or a heatmap. Look for spikes: they mark strikes the grid could not identify.",
    "4. **IV surface** — the reconstructed implied-vol mesh over t × strike; hover for the crosshair linked to the Parametric Surface of the same ticker.",
    "5. **Densities** (≥ 0 ⇔ no butterfly) and **Stacked IV** (non-crossing ⇔ no calendar) — both structural for the LV surface; a `cal. viol.` badge means adjacent-maturity prices decreased on the PDE lattice.",
    "6. Play the trace in the aside to see how the fit converged.",
    "7. **Compare** — with a parametric fit on the ticker, read the fitted sheet against the parametric surface's Dupire twin: the round trip and its floor say how exact the twin is, the difference sheet where the fit and the differentiation part ways.",
    "",
    "## Numbers and badges",
    "",
    "- `rms` — per-quote IV error of the surface vs the fit target; `conv` — the same on the **converged** reprice operator (the figure to trust); `max` — the worst quote. NaN from a diverged fit renders `—`.",
    "- `arb-free` — no butterfly or calendar violation on the PDE lattice; otherwise the count of calendar violations and, in the tooltip, the worst crossing.",
    "- Compare's `round trip · max bp · floor · sheet` — the twin against its own source; the floor is the operator's, the sheet figure the coarse vertex sample's. A twin reading within a couple of floors of its source is exact to the operator.",
    "- Per-expiry diagnostics: vertex coverage in range, vega-floor incidence, PDE steps and timings — the counts that convict a short-dated failure before any model change.",
    "",
    "## The grid",
    "",
    "[gridStrikeMode](help:settings:gridStrikeMode) `delta` places strike vertices by delta ([gridXNodes](help:settings:gridXNodes) is then a floor, exact only in `linear`); [gridXMinPerExpiry](help:settings:gridXMinPerExpiry) is the short-dated coverage floor; [gridTNodes](help:settings:gridTNodes) floors the positive time vertices (0, a pre-front node and every lit expiry are always kept). Roughness: [gridRegLambda](help:settings:gridRegLambda) / [gridRegRho](help:settings:gridRegRho). Grid and solver knobs are **global** (Options ▸ Local Vol) and fold into the affine cache key only — they never invalidate a parametric fit.",
    "",
    "## Pitfalls",
    "",
    "- **The six-day weekly that broke the strike grid** — fit RMS 108 → 23.5 vol bp once per-expiry coverage floors existed. If a short expiry misfits, read its vertex count first.",
    "- **The convex wing that flattened SPY** — [convexWing](help:settings:convexWing) is tail-confined and off by default; a wing constraint sampled on quoted territory costs the belly.",
    "- The **Graph-extrapolated** source is a projection of reconstructed smiles, not quotes; it is labelled violet for that reason.",
    "- The LV var-swap uses [varSwapMethod](help:settings:varSwapMethod): static replication or the source PDE.",
    "- The Numba march ([lvFastKernel](help:settings:lvFastKernel)) falls back to a banded solver if numba is missing — slower, same numbers.",
    "- On the Compare tab a fitted sheet whose `conv` sits far above its `rms` on a short front is compensating its own calibration operator: the one-month front gets few implicit steps. Read the twin's round trip and floor beside it before trusting either number.",
    "",
    "## Related settings",
    "",
    "[localVolEnabled](help:settings:localVolEnabled) · [gridStrikeMode](help:settings:gridStrikeMode) · [gridXNodes](help:settings:gridXNodes) · [gridXMinPerExpiry](help:settings:gridXMinPerExpiry) · [gridTNodes](help:settings:gridTNodes) · [gridRegLambda](help:settings:gridRegLambda) · [gridRegRho](help:settings:gridRegRho) · [densitySmoothWeight](help:settings:densitySmoothWeight) · [convexWing](help:settings:convexWing) · [convexWingWeight](help:settings:convexWingWeight) · [frontTie](help:settings:frontTie) · [lvVolCapMult](help:settings:lvVolCapMult) · [leftWingSlopeMult](help:settings:leftWingSlopeMult) · [lvXMaxMin](help:settings:lvXMaxMin) · [timeScheme](help:settings:timeScheme) · [lvSolver](help:settings:lvSolver) · [lvEarlyStop](help:settings:lvEarlyStop) · [varSwapMethod](help:settings:varSwapMethod)",
    "",
    "## Read more",
    "",
    "[Piecewise-affine local volatility (Note 04)](help:docs:04_local_volatility) · [Local volatility, forward](help:docs:04_local_volatility_forward) · [LV calibration methodology](help:docs:docs_localvol_methodology) · [Spot-vol dynamics (Note 12)](help:docs:12_spot_vol_dynamics)",
  ].join("\n"),
};

export const QUALITY: GuidePage = {
  id: "quality",
  title: "Quality lens — readiness, exceptions and publishing",
  lens: "quality",
  summary: "The universe dashboard: which nodes clear the publish gate, why the others do not, and the export path.",
  related: ["help:glossary:publish-gate", "help:glossary:quality-report", "help:glossary:belly-certificate", "handoff_pitfalls"],
  body: [
    "## What it is for",
    "",
    "Quality aggregates every committed calibration into one page — fit quality, arbitrage diagnostics (including the belly certificate), data age, provenance, LV health — and decides **publish readiness** per node. It never fits: `GET /quality` reads the cache and refreshes on every calibration epoch. It is a universe lens: it renders without a tab and highlights the active node.",
    "",
    "## Layout",
    "",
    "- **Tiles** — the eight universe counters (below).",
    "- **Node card** — the active tab's certificate: Model (· loaded · n quotes · fit mode) · RMS · max IV · ATM · skew · Lee L/R · Cal viol · Tail order · Band relax · Extrap g · cal · Belly g · Flags · Data age · As-of · Status.",
    "- **Tickers** rollup — Ticker · Ready · Stale · nodes · RMS bp, with the LV surface health; the **Export** group: HTML report (new tab) · JSON · CSV.",
    "- **Node table** — Node · Model · quotes · RMS bp · Max IV bp · Lee L/R · Cal viol · Extrap g·cal · Belly g · Status; a `VS` mark when a var-swap quote is active. Sort: `Exceptions first` · `Worst RMS first` · `Ticker · expiry`; a refresh button re-reads the cache. Click a row to preview the node, double-click to pin.",
    "",
    "## The tiles",
    "",
    "- **Publish ready** — nodes with no readiness issue (emerald when all of them).",
    "- **Fitted** — nodes with a committed calibration.",
    "- **Stale** — fitted nodes whose inputs moved since (amber when > 0).",
    "- **No fit** — lit nodes never calibrated, and dark nodes before the graph runs.",
    "- **Arb flags** — nodes with a Lee, calendar or belly flag (rose when > 0).",
    "- **Median RMS** · **Worst RMS** — in vol bp against the fit target; worst turns amber above the budget.",
    "- **LV surfaces** — arb-free surfaces over the tickers with an LV fit.",
    "",
    "## Readiness — what blocks",
    "",
    "A node is ready when none of these holds: `stale` · `RMS > budget` · `Lee wing slope > 2` · calendar arbitrage · an uncertified belly · `stale data (… old)` past the red threshold · and, when gated, an as-of mismatch or a tail-order failure. The export and the publish manifest block on any of them (HTTP 409 with typed reasons).",
    "",
    "## Triage, first pass",
    "",
    "1. Sort **Exceptions first**. Not-ready nodes rise, worst RMS on top.",
    "2. `stale` → Calibrate. `stale data` → Fetch.",
    "3. **Belly g** rose → open the node; if `bellyRepair` did not certify it, exclude the offending quote or switch model (LQD is structural).",
    "4. **Lee L/R** rose → the wing breached 2; on SVI check [leeSlopeMax](help:settings:leeSlopeMax); on LQD the tails are generalized — look at Tail order.",
    "5. **Cal viol** rose → the sampled crossing vs the previous expiry, or the exact full-line ledger gap; recalibrate with [enforceCalendar](help:settings:enforceCalendar) on and the `symmetric` solver.",
    "6. RMS above budget → read the smile: a quarantined or outlying quote, a wrong forward, a band too tight.",
    "7. When the tile reads all ready, export.",
    "",
    "## The columns, precisely",
    "",
    "- **Belly g** — min Durrleman g over the traded range on 801 points; rose = uncertified (blocks); `·R` = a certified repair refit.",
    "- **Extrap g · cal** — worst g and calendar crossing bp over the time-value envelope *beyond* the quotes; advisory; `—` = worthless past the range.",
    "- **Tail order** — the limiting tail order of the adjacent LQD pair; amber advisory, rose when [ledgerTailOrderGate](help:settings:ledgerTailOrderGate) is on; `α` marks unequal exponents (irreducible).",
    "- **Band relax** — with [bandRelaxationDiagnostic](help:settings:bandRelaxationDiagnostic): the smallest symmetric widening of both slices' bands under which the pair certifies.",
    "- **As-of** — the chain's stamp vs the selected as-of; `≠ as-of` amber, rose under [asOfMismatchGate](help:settings:asOfMismatchGate). A data issue, never an arb flag.",
    "- **Data age** — amber past [dataAgeAmberMin](help:settings:dataAgeAmberMin), red past [dataAgeRedMin](help:settings:dataAgeRedMin).",
    "",
    "## Publishing",
    "",
    "[Export surfaces (JSON)](cmd:export.surfacesJson) writes every published surface with its inputs and a reproducibility manifest; [CSV](cmd:export.surfacesCsv) one row per curve point; [the HTML report](cmd:export.report) is the client-facing document. Manifests chain (content-addressed, parent lineage) and a published surface can be **recalled** — a lifecycle transition, not a delete. The same gates feed the certification pack.",
    "",
    "## Pitfalls",
    "",
    "- RMS is measured against the fit target; a band fit's RMS budget means something different from a mid fit's.",
    "- The LV surface RMS shown is the **converged-operator reprice**; a smaller in-solver figure is not the one to publish on.",
    "- Advisory columns (Extrap, Tail order, Band relax, As-of) turn into gates only through their Options switches; the defaults keep them amber.",
    "- A dark node shows *no fit* until the graph runs; graph reconstructions carry their provenance in the report.",
    "",
    "## Related settings",
    "",
    "[dataAgeAmberMin](help:settings:dataAgeAmberMin) · [dataAgeRedMin](help:settings:dataAgeRedMin) · [asOfMismatchGate](help:settings:asOfMismatchGate) · [ledgerTailOrderGate](help:settings:ledgerTailOrderGate) · [bandRelaxationDiagnostic](help:settings:bandRelaxationDiagnostic) · [extrapEnforce](help:settings:extrapEnforce) · [bellyRepair](help:settings:bellyRepair) · [leeSlopeMax](help:settings:leeSlopeMax) · [enforceCalendar](help:settings:enforceCalendar)",
    "",
    "## Read more",
    "",
    "[The wings and the belly](help:docs:02_svi_jw_moments) · [Wings, Lee bounds (Note 09)](help:docs:09_wings_lee_bounds) · [Generalized tails + full-line calendar](help:docs:docs_generalized_tails) · [Pitfalls and adjudications](help:docs:handoff_pitfalls)",
  ].join("\n"),
};
