// Guides — options group (HELP CENTER ARC, H1): options, priors, filter.
// Grounded in views/OptionsViewer.tsx (the section rail), the Fit / Options
// settings schema (lib/help/settingsSchema.json), components/
// PriorPersistencePanel.tsx, components/ObservationFilterPanel.tsx and
// components/topbar/PriorsMenu.tsx.
import type { GuidePage } from "../types";

export const OPTIONS: GuidePage = {
  id: "options",
  title: "Options — the settings dialog",
  summary: "One card per concern, a section rail, one Apply bar for two backend settings models — and which caches each field invalidates.",
  related: ["help:settings", "handoff_settings", "00_system_overview"],
  body: [
    "## What it is",
    "",
    "[Options](cmd:options.open) (Ctrl+,) is the calibration and model settings dialog. Two backend models share one sticky **Apply** bar: **FitSettings** (model, penalties, haircut, weighting — folded into every fit-cache key) and **OptionsSettings** (everything else). Purely cosmetic preferences live in `View ▾`, per-ticker market inputs in the Forwards lens.",
    "",
    "## The section rail",
    "",
    "| Card | What it holds |",
    "|---|---|",
    "| **Parametric** | [model](help:settings:model) (lqd · svi · sigmoid), LQD [nOrder](help:settings:nOrder) · [lqdCoords](help:settings:lqdCoords) · ridge [regLambda](help:settings:regLambda) · barrier; SVI [sviPenaltyWeight](help:settings:sviPenaltyWeight) · [leeSlopeMax](help:settings:leeSlopeMax) · [sviChart](help:settings:sviChart) · [bellyRepair](help:settings:bellyRepair); MCS [nCores](help:settings:nCores) · [sigmoidRidge](help:settings:sigmoidRidge) · [sivWingPenaltyPct](help:settings:sivWingPenaltyPct); tails [tailAlphaLeft](help:settings:tailAlphaLeft) · [tailAlphaRight](help:settings:tailAlphaRight) |",
    "| **Local Vol** | [localVolEnabled](help:settings:localVolEnabled), the grid, regularizers, wing and cap knobs, [timeScheme](help:settings:timeScheme) · [lvSolver](help:settings:lvSolver) · [lvFastKernel](help:settings:lvFastKernel) · [lvEarlyStop](help:settings:lvEarlyStop) |",
    "| **Calibration** | [fitMode](help:settings:fitMode) · [haircut](help:settings:haircut) · [midAnchorWeight](help:settings:midAnchorWeight) · [bandTickFloorTicks](help:settings:bandTickFloorTicks) · [weightScheme](help:settings:weightScheme) · [robustLoss](help:settings:robustLoss); var-swap [varSwapEnabled](help:settings:varSwapEnabled) · [varSwapWeightPct](help:settings:varSwapWeightPct) · [varSwapHardPin](help:settings:varSwapHardPin); calendar [enforceCalendar](help:settings:enforceCalendar) · [surfaceSolver](help:settings:surfaceSolver) · [calendarWeight](help:settings:calendarWeight) · [extrapEnforce](help:settings:extrapEnforce); gates [ledgerTailOrderGate](help:settings:ledgerTailOrderGate) · [asOfMismatchGate](help:settings:asOfMismatchGate); carry [jointCarry](help:settings:jointCarry) |",
    "| **Prior** | the persistence panel — see [Priors](help:guides:priors) |",
    "| **Kalman filter** | the observation-filter panel — see [Observation filter](help:guides:filter) |",
    "| **Events** | [eventsEnabled](help:settings:eventsEnabled) · [normalizeEvents](help:settings:normalizeEvents) · [intradayClock](help:settings:intradayClock) · [sessionVarShare](help:settings:sessionVarShare); the per-ticker event calendar |",
    "| **Graph** | [graphPropagationMode](help:settings:graphPropagationMode) · [graphKappaScale](help:settings:graphKappaScale) · [graphEtaScale](help:settings:graphEtaScale) · [graphLambdaScale](help:settings:graphLambdaScale) · [graphNu](help:settings:graphNu) |",
    "| **Workflow** | [autoCalibrate](help:settings:autoCalibrate) · [autoRollPriorOnFetch](help:settings:autoRollPriorOnFetch) · [spotMode](help:settings:spotMode) · [optionsFetchMode](help:settings:optionsFetchMode) · [schedulerUnifiedFetch](help:settings:schedulerUnifiedFetch) · [autoStream](help:settings:autoStream) · data-age thresholds |",
    "| **Dynamics** | [dynamicsRegime](help:settings:dynamicsRegime) · [ssr](help:settings:ssr) |",
    "",
    "Feature-dependent knobs render only while their feature or model is active (SVI knobs under `model = svi`, LV knobs while LV is enabled).",
    "",
    "## First use",
    "",
    "1. Press Ctrl+,. The rail on the left scrolls to a card and tracks the one in view.",
    "2. Change a value — say `model` to `svi`. Nothing happens yet; the Apply bar becomes active.",
    "3. **Apply**. Every fitted node goes `STALE`; with [autoCalibrate](help:settings:autoCalibrate) on they refit in the background, otherwise press Calibrate.",
    "4. Open the [Settings reference](cmd:help.settings) for any field: type, default, range, cache effect and an example. In the dialog, a field's tooltip carries the same summary.",
    "",
    "## Two models, one Apply",
    "",
    "- **FitSettings** — model family and its penalties, haircut, weighting, robust loss. Folded into every fit-cache key: change one and every node refits.",
    "- **OptionsSettings** — fit mode, calendar coupling, var-swap, priors, filter, events, graph dials, workflow, dynamics, the LV grid. Each field carries its own cache effect (below).",
    "- **MarketSettings** — per ticker (rate, dividends), edited in the Forwards lens, not here.",
    "",
    "## What a change invalidates",
    "",
    "| Cache effect | Fields | What refits |",
    "|---|---|---|",
    "| **fit-version** | every FitSettings field | all views, every node |",
    "| **options-version** | calibration-affecting OptionsSettings (fit mode, calendar, var-swap, prior, events …) | parametric fits |",
    "| **lv-affine-key** | the Local Vol grid and solver knobs | the LV surface only — never a parametric fit |",
    "| **filter-version** | the observation-filter knobs | the filter overlay only |",
    "| **per-ticker-version** | market inputs (rate, dividends, events, forward mode) | that ticker |",
    "| **workflow-gate** / **display-only** | scheduler, data-age thresholds, gates | nothing refits |",
    "",
    "## The additive contract",
    "",
    "Every feature is strictly additive: bands, var-swap targets, calendar coupling, the event clock, priors, the wing penalty, the observation filter — each is byte-identical to its absence when off, and that identity is test-locked. Turning a feature on is therefore a comparison you can make, not a leap.",
    "",
    "## Pitfalls",
    "",
    "- FitSettings bust **every** fit cache; on a large universe change them once, then Apply.",
    "- `leeSlopeMax = 2.0` passes every wing screen with zero penalty and produces a negative tail density — the cap is 1.95 for that reason; 2.0 is explicit-config only.",
    "- `nOrder` above 24 is guarded; the default 16 replaced an earlier 8 after the SPY shoulder-truncation case — a saved workspace may carry the old value.",
    "- [observationFilterMode](help:settings:observationFilterMode) `active` is off by default and has a documented shock-day lag; start with `overlay`.",
    "- [graphLambdaScale](help:settings:graphLambdaScale) > 0 turns on the OT term the held-out benchmarks did not favour; smooth-field only.",
    "- Settings live in the workspace file: opening someone else's workspace installs their settings.",
    "",
    "## Related settings",
    "",
    "Every field: [Settings reference](help:settings). The principal ones: [model](help:settings:model) · [fitMode](help:settings:fitMode) · [enforceCalendar](help:settings:enforceCalendar) · [priorPersistenceMode](help:settings:priorPersistenceMode) · [observationFilterMode](help:settings:observationFilterMode) · [graphPropagationMode](help:settings:graphPropagationMode) · [autoCalibrate](help:settings:autoCalibrate)",
    "",
    "## Read more",
    "",
    "[Settings reference (handoff)](help:docs:handoff_settings) · [System overview, Appendix A — the control atlas](help:docs:00_system_overview) · [The calibration objective (Note 07)](help:docs:07_calibration_objective)",
  ].join("\n"),
};

export const PRIORS: GuidePage = {
  id: "priors",
  title: "Priors — persisting yesterday's surface",
  summary: "Save and fetch priors, choose how they enter today's fit, and read the diagnostics that show where yesterday spoke.",
  related: ["help:glossary:prior", "help:glossary:prior-persistence-modes", "13_bayesian_prior_persistence", "13_prior_flat_directions"],
  body: [
    "## What it is for",
    "",
    "A sparse morning does not determine a smile: on a real expiry with quotes confined to the ATM band, several calibrations agree to 1 vol bp where quoted and disagree by vol *points* in the wing. The [prior](help:glossary:prior) — the saved previous fit, transported to today's market — is admitted into the fit exactly where today's quotes fail to identify a feature, and nowhere else.",
    "",
    "## Saving and fetching",
    "",
    "`Priors ▾` in the top bar: [Save prior — visible tab](cmd:priors.saveVisible) · [Save priors — all open tabs](cmd:priors.saveOpen) · [Save priors — all calibrated](cmd:priors.saveAll) · [Fetch priors](cmd:priors.fetch). [autoLoadPrior](help:settings:autoLoadPrior) fetches on load; [autoRollPriorOnFetch](help:settings:autoRollPriorOnFetch) rolls the prior on every snapshot. Priors persist on the server and are per node.",
    "",
    "## The panel (Options ▸ Prior)",
    "",
    "Two tabs: **Config** and **Evidence** (the prior-persistence evidence charts). Config holds the **mode** selector and the knobs of the active mode:",
    "",
    "- `strike_gap` — *Anchor weight (%)* and the per-side delta locations.",
    "- `quote_operator` — *Operator strength (%)*, the **Operators** set (ATM · RR25 · BF25 · VarSwap · WingL · WingR), *Wing slope scale* (budget share of the wing-slope rows; 0 drops them), *Wings survive an active filter*, *Collar sign* (call − put or put − call).",
    "- `smile_factor` — *Factor strength (%)* and the **Factors** set (ATM · skew · curvature · VarSwap).",
    "- `hybrid` (default) — operators plus a deep-tail anchor: *Tail-anchor weight (%)* and the deltas below the shallowest wing operator.",
    "- Gate knobs for operators and factors: *Required precision*, *Gap exponent γ*, *Support bandwidth / step*, *Two-pass (don't damp signal)*.",
    "- *Var-swap companion*: `Absolute level` or `ATM spread` (the var-swap − ATM spread, so an ATM move carries the tail along).",
    "",
    "Below, the **diagnostics table**: Expiry · Factor · `gap` (1 = fully persisted, 0 = data wins) · `λ` (final weight) · `age` (prior age in days) · `src` (active / nearest / bootstrap / flat) · `h` (transport distance log(F_now / F_prior)). The prior is not a hidden stabilizer — every persisted quantity is listed with its weight.",
    "",
    "## The diagnostics columns",
    "",
    "- `gap` — the activation gap: 1 = fully persisted (today's quotes do not identify this coordinate), 0 = the data wins.",
    "- `λ` — the final calibration weight of the row, after the strength budget and the gap.",
    "- `age` — the prior's age in days; the graph solve prices the same age into its source precision.",
    "- `src` — provenance tier: active (this node's own saved fit) · nearest (a neighbouring expiry's) · bootstrap · flat.",
    "- `h` — the transport distance log(F_now / F_prior); the transport precision decays with it.",
    "",
    "## The modes, in one line each",
    "",
    "`off` nothing · `overlay` draw the prior, do not fit to it · `strike_gap` anchor delta locations where quotes are absent · `quote_operator` persist level-invariant baskets through the activation gate · `smile_factor` persist ATM / skew / curvature / var-swap factors · `hybrid` operators + deep-tail anchor (won the held-out backtest by ~32 vol bp on the wing) · `graph_only` keep the prior for the graph, out of the fit.",
    "",
    "## First use",
    "",
    "1. At the end of a session with fits you trust: `Priors ▾ Save priors — all calibrated`.",
    "2. Next morning: `Fetch priors`, then `Snapshot`, then `Calibrate` with the default `hybrid` mode.",
    "3. Open a sparse node. The dashed prior and the solid fit coincide in the unquoted wing and separate where quotes exist.",
    "4. Read the diagnostics table: a `gap` near 0 on ATM (the data wins) and near 1 on the wing rows (yesterday carries) is the intended picture.",
    "5. Switch to the **Evidence** tab: per node, how much of today's fit the prior carried and where — the same rows as charts through time.",
    "",
    "## Why shape, not level",
    "",
    "Operators and factors are level-invariant baskets (a risk-reversal, a butterfly, a wing slope), so an overnight jump in ATM vol is never damped — the gate persists *shape*. The activation gate has a provable dead zone: a well-observed coordinate receives exactly zero prior weight, not a small one. This is the answer to the case file where a strike anchor damped a genuine jump.",
    "",
    "## Pitfalls",
    "",
    "- A prior with a large `h` (transport distance) has travelled far; the transport precision decays with it and the graph prices the same age in.",
    "- `graph_only` is the mode for a universe you want extrapolated but fitted to the market alone.",
    "- Under an **active** observation filter the ATM / RR / BF rows hand over to the Kalman MAP rows; the wing-slope rows stay only with [wingOperatorsUnderActiveFilter](help:settings:wingOperatorsUnderActiveFilter).",
    "- *Two-pass* measures precision data-only, then refits with the prior — slower, and it never damps a signal the data carries.",
    "- Save priors on a fit you trust, not on a stale or arb-flagged one; the Quality lens is the check.",
    "- A prior saved under one `fitMode` and reused under another still enters as shape rows; only its var-swap companion changes meaning (`Absolute level` vs `ATM spread`).",
    "",
    "## Related settings",
    "",
    "[priorPersistenceMode](help:settings:priorPersistenceMode) · [priorOperatorSet](help:settings:priorOperatorSet) · [priorOperatorStrengthPct](help:settings:priorOperatorStrengthPct) · [priorOperatorRequiredPrecision](help:settings:priorOperatorRequiredPrecision) · [priorOperatorGapExponent](help:settings:priorOperatorGapExponent) · [priorOperatorBandwidth](help:settings:priorOperatorBandwidth) · [priorDataOnlyPrepass](help:settings:priorDataOnlyPrepass) · [priorFactorSet](help:settings:priorFactorSet) · [priorFactorStrengthPct](help:settings:priorFactorStrengthPct) · [priorTailAnchorStrengthPct](help:settings:priorTailAnchorStrengthPct) · [priorAnchorWeightPct](help:settings:priorAnchorWeightPct) · [priorVarSwapMode](help:settings:priorVarSwapMode) · [priorWingSlopeScale](help:settings:priorWingSlopeScale) · [collarSign](help:settings:collarSign) · [autoLoadPrior](help:settings:autoLoadPrior) · [autoRollPriorOnFetch](help:settings:autoRollPriorOnFetch)",
    "",
    "## Read more",
    "",
    "[Bayesian prior persistence (Note 13)](help:docs:13_bayesian_prior_persistence) · [Where the likelihood is flat](help:docs:13_prior_flat_directions) · [Prior persistence roadmap](help:docs:docs_prior_persistence)",
  ].join("\n"),
};

export const FILTER: GuidePage = {
  id: "filter",
  title: "Observation filter — denoising the handles through time",
  summary: "Turn the per-handle Kalman filter on as an overlay, read its gains and innovations, and decide whether it should enter the fit.",
  related: ["help:glossary:observation-filter", "help:glossary:innovation-gate", "15_kalman_filtering", "15_kalman_computed_trust"],
  body: [
    "## What it is for",
    "",
    "Prior persistence fills gaps; the observation filter denoises **through time**. It tracks the three ATM handles (level, skew, curvature) of each node as a state, predicts them forward with a process clock, and updates them with each fit's measurement — treating a genuine data gap as absent evidence, and a close-strike contradiction as noise. The gain is an output, not a dial.",
    "",
    "## The panel (Options ▸ Kalman filter)",
    "",
    "- **Mode** — `off` (byte-identical to the feature never existing) · `overlay` (filtered state and display update *after* the fit commits) · `active` (the prediction enters the calibration objective as a one-stage MAP prior *before* optimization).",
    "- **Covariance route** — `Jacobian` (measurement covariance R propagated from the fit, default) or `Factors` (the cheap precision-factor fallback, an A/B diagnostic).",
    "- Process noise: *ATM noise (bp/√day)* · *Skew noise (/√day)* · *Curvature noise (/√day)* · *Transport noise ×* (per unit of spot-transport distance).",
    "- Safety knobs:",
    "  - *Max gain (1 = free)* — a per-handle cap on the own gain.",
    "  - *Reset after (hours)* — the longest data gap predicted across; beyond it the state resets.",
    "  - *Residual inflation* — a contradiction between quotes reads as measurement noise (capped at ×25).",
    "  - *Data-only prepass* — measure with a strictly persistence-free fit first.",
    "  - The adaptive-σ innovation gate and the filter clock (`calendar` or `session`).",
    "",
    "## Modes, one line each",
    "",
    "- `off` — nothing is computed; byte-identical to the feature never existing.",
    "- `overlay` — the state updates after each fit commits; drawn, badged, never fitted to. Start here.",
    "- `active` — the prediction enters the objective as a one-stage MAP prior before optimization; documented shock-day lag.",
    "- **Diagnostics table** per expiry: `K(ATM)` · `K(skew)` · `K(curv)` (gains, 1 = trust the fit fully) · `innov bp` (measurement − prediction on ATM) · `ρ` (measurement-noise correlation) · `route` · `reset` (reason / provenance) · `⚠` (measurement flagged contaminated).",
    "- **Timeline** toggle — the node's committed filter steps over time: prediction and observation bands, the posterior, the ζ strip, the gain, the Q breakdown and reset markers; a `Live | Replay` source chip.",
    "",
    "## First use",
    "",
    "1. Set the mode to `overlay` and Apply. Nothing in the fit changes; the Parametric chart gains a **FILTER** badge (gains per handle, ρ, provenance).",
    "2. Fit a few sessions (or replay captured ones). Read the table: a gain near 1 on a handle means the prediction is uninformative and the market wins; near 0 means the fit's measurement is noisy relative to the prediction.",
    "3. Open the Timeline. The ζ strip should hover around ±1; a persistent bias means the process noise is mis-set.",
    "4. Only then consider `active` — and keep [filterAdaptiveSigma](help:settings:filterAdaptiveSigma) at its default so a genuine jump inflates Q instead of being damped.",
    "",
    "## How the gain is computed",
    "",
    "The measurement covariance comes from the fit's own information in stated noise units (bid-ask half-spreads: double the noise, quadruple the covariance), inflated by realized inconsistency — a two-strike contradiction drives the inflation to its cap of 25 and turns a curvature gain of 0.73 into 0.20 with nobody touching anything. The prediction covariance grows with the process clock; the [innovation gate](help:glossary:innovation-gate) grows it further when a standardized innovation exceeds 3σ. Updates are **per handle** — cross-handle gains once moved ATM vol by vol points on coarse chains and were removed.",
    "",
    "## Reading the FILTER badge",
    "",
    "On the Parametric chart the badge lists the mode, the gain per handle and ρ; hover for the provenance. Amber means the measurement was flagged contaminated — the filter down-weighted it. The **Fit diagnostics** card still shows the raw fit's handles; the filtered state is the overlay curve.",
    "",
    "## Numbers to watch",
    "",
    "- Measured gains on a real contradiction vs a real gap: level / skew / curvature ≈ 0.80 / 0.72 / 0.03 — high where quotes contradict, near zero where they are simply absent. Noise is not a gap; the filter and the prior split the work.",
    "- [filterResetHours](help:settings:filterResetHours) (96): the longest gap predicted across before the state resets — the `reset` column names the reason.",
    "- Under `session` clock a session carries [filterSessionShare](help:settings:filterSessionShare) = 0.60 of a day's variance and non-trading days [filterNonTradingWeight](help:settings:filterNonTradingWeight) = 0 — on stored intraday data a weekend moves ATM no more than one overnight.",
    "",
    "## Pitfalls",
    "",
    "- `active` carries a documented **shock-day lag**; it is off by default for that reason.",
    "- The filter and prior persistence are easy to confuse in implementation and must not be confused in use: one is temporal, the other fills flat directions of today's likelihood.",
    "- Wing-slope operators drop under an active filter unless [wingOperatorsUnderActiveFilter](help:settings:wingOperatorsUnderActiveFilter) keeps them — they measure a quantity the filtered handles do not.",
    "- A contaminated measurement (`⚠`, amber badge) is down-weighted, not dropped; look at the quote that caused it.",
    "- Filter knobs bump the lightweight filter version only — no fit cache is invalidated by tuning them in `overlay`.",
    "",
    "## Related settings",
    "",
    "[observationFilterMode](help:settings:observationFilterMode) · [filterCovarianceMode](help:settings:filterCovarianceMode) · [filterProcessVolBpSqrtDay](help:settings:filterProcessVolBpSqrtDay) · [filterProcessSkewSqrtDay](help:settings:filterProcessSkewSqrtDay) · [filterProcessCurvSqrtDay](help:settings:filterProcessCurvSqrtDay) · [filterTransportNoiseScale](help:settings:filterTransportNoiseScale) · [filterResidualInflation](help:settings:filterResidualInflation) · [filterAdaptiveSigma](help:settings:filterAdaptiveSigma) · [filterMaxGain](help:settings:filterMaxGain) · [filterResetHours](help:settings:filterResetHours) · [filterClock](help:settings:filterClock) · [filterSessionShare](help:settings:filterSessionShare) · [filterNonTradingWeight](help:settings:filterNonTradingWeight) · [filterDataOnlyPrepass](help:settings:filterDataOnlyPrepass) · [wingOperatorsUnderActiveFilter](help:settings:wingOperatorsUnderActiveFilter)",
    "",
    "## Read more",
    "",
    "[Observation Kalman filtering (Note 15)](help:docs:15_kalman_filtering) · [Trust is computed](help:docs:15_kalman_computed_trust) · [Observation filter roadmap](help:docs:docs_observation_filter)",
  ].join("\n"),
};
