// Guide — the Series lens (SERIES ARC S4): what a series is (frames × lanes),
// the New series… dialog, the transport, the stages and the limits of this
// phase. Grounded in views/SeriesViewer.tsx + components/series/* and
// Docs/series_replay_roadmap.md §3. PURE DATA — locked by content.test.ts.
import type { GuidePage } from "../types";

export const SERIES: GuidePage = {
  id: "series",
  title: "Series lens — replay a time-series of smiles under model lanes",
  lens: "series",
  summary: "Harvest one ticker's chains at a sequence of instants, calibrate them under several model lanes, and replay the smiles frame by frame.",
  related: ["help:glossary:series", "help:glossary:lane", "help:glossary:frame", "help:guides:priors", "help:guides:filter"],
  body: [
    "## What a series is",
    "",
    "A **series** is one ticker's ordered set of instants — its **frames** — each holding the chain as the market quoted it then (spot, the quotes, the expiries alive at that instant) and calibrated under one or more **lanes**. A lane is a settings patch over the live Options frozen at creation — *LQD free*, *LQD + prior*, *LQD + prior + filter*, *SVI-JW free*, *MCS free*, *LV affine free*, *LV affine + prior*, *Current Options* — evaluated **through time**: a lane with a prior reads its own previous frame's surface as the prior, a lane with the observation filter carries its own filter state from frame to frame, a free lane reads nothing from the frame before. The fits run on the server, on a private copy of the app state per lane, through the same calibration path as the live desk; the series, its frames and its fits live in the store.",
    "",
    "One lane is the **production lane** (starred): the one the ghost trail follows and the one differences refer to. Lanes live in the series dialog, never in Options — Options keeps describing the one live configuration.",
    "",
    "## Creating one",
    "",
    "Open a node tab, press Alt+6 and click **New series…**.",
    "",
    "- **Mode** — *Historical*: instants in the past, harvested now through the ticker's source as-of path (Massive serves intraday history; Bloomberg serves previous-close and end-of-day chains; Yahoo and the exchange adapters are forward-only). *Live*: instants from now on, one frame per tick of the step. *Import*: the app's own captures, a backtest store or a fixture directory become the frames.",
    "- **Clock** — a step (1 min … 1 hour, session close, daily at a time of day, weekly), a count, an optional start (blank = now for a live series, the latest instants for a historical one), *session only* (skip non-trading days and out-of-session instants) and **warm-up frames**: extra frames before the start, harvested to seed the prior and filter lanes only.",
    "- **Ladder** — *pinned* (the ticker's universe expiries at creation; a frame drops the ones expired at its instant), *term* or *0dte*, with an optional cap on the number of expiries.",
    "- **Fit target** — mid, bid-ask or haircut, the same meaning as [fitMode](help:settings:fitMode); a lane may override it.",
    "- **Lanes** — tick the presets you want; per lane a colour (blank = the family colour), a name, and the production star.",
    "- **Estimate** — the resolved instants (first, last, how many the source can serve), the harvest time and the calibration time before anything runs. Warnings show in amber: an instant the source cannot serve, a step below the source's floor, a lane that dominates the cost.",
    "- **Start** — the job runs on the server; the dialog closes; the header's status pill narrates harvesting, then calibrating, frame by frame. Pause and Cancel sit beside it; a paused, failed or cancelled series resumes from its first unfinished frame.",
    "",
    "## Replaying",
    "",
    "The **transport bar** at the bottom plays the frames: play / pause, one frame back or forward, ten frames back or forward, first and last, a loop switch, the speed (0.25× … 8×; 1× = two frames a second) and a scrubber over the frame index. The **playhead readout always names the instant and the quote kind** (NBBO quotes or marks) of the frame on screen. Nothing is interpolated between frames: what you see at a frame is that frame's market and that frame's fits.",
    "",
    "Keys, with the lens focused: `Space` play / pause · `←` / `→` one frame · `Shift+←` / `Shift+→` ten frames · `Home` / `End` first / last · `L` loop.",
    "",
    "The **filmstrip** above the transport bar draws sparklines across every frame — spot, the ATM vol of the shown expiry per lane, the fit error per lane — with the playhead crossing them; click or drag on it to scrub. A frame with no fit for a lane leaves a gap.",
    "",
    "## The stages",
    "",
    "- **Smile** (this phase) — the frame's quotes as bands per the series' fit target and every visible lane's smile on top, in the lane's colour; the expiry is the tab's, or the nearest later expiry the frame carries once the tab's has expired (a note above the chart says so). The axis is `k = ln(K/F)` or the fixed strike; the strike window persists across frames; the **ghost trail** draws the production lane's smile from the previous frames, fading, so the motion of the smile reads at a glance.",
    "- **Frames** — the table of instants: spot, quote count, quote kind, harvest status or error, the warm-up flag. Click a row to jump.",
    "- **Surface · Term · Lanes** — the next phase: per-lane surfaces with a shared camera, the term structure per lane on both clocks, and the evidence page (fit error, prior pull, filter gain and handle-path roughness per lane across the frames).",
    "",
    "Lane chips in the header toggle a lane's visibility; the picker lists the ticker's series newest first; **Delete** removes a series with its fits (and the snapshots nothing else references).",
    "",
    "## Limits of this phase",
    "",
    "- Series need the live server started with a store (`VOLFIT_DB`); without one the lens shows an empty state and the routes answer 409.",
    "- A live series takes one frame per tick from the moment it starts; a spot-only tick never makes a frame.",
    "- One ticker per series; a frame's strike window is the source's history window.",
    "- Adopting a lane's frame as the live prior, the file export and the connector tools follow in the next phase.",
    "",
    "## Read more",
    "",
    "[Priors](help:guides:priors) · [The observation filter](help:guides:filter) · [Data sources](help:guides:data-sources) · [Open the Series lens](cmd:lens.series)",
  ].join("\n"),
};
