// Guides — universe group (HELP CENTER ARC, H1): universe, data-sources,
// workflow. Grounded in views/UniverseManager.tsx, components/ExpiryPicker,
// state/useDataSources.ts, components/topbar/AsOfRows.tsx,
// components/WorkflowControls.tsx and the Options ▸ Workflow card.
import type { GuidePage } from "../types";

export const UNIVERSE: GuidePage = {
  id: "universe",
  title: "Managing the universe",
  summary: "Add tickers, choose expiries by rule or by chip, mark nodes lit or dark, and save named universes.",
  related: ["help:guides:data-sources", "help:glossary:universe", "help:glossary:lit-dark"],
  body: [
    "## What it is for",
    "",
    "The **universe** is the set of (ticker, expiry) nodes the app fetches, fits and extrapolates. It lives on the server; every edit flows into the Nodes pane and every lens at once. Open the dialog with [Manage universe…](cmd:universe.manage) (Ctrl+Shift+U), the `⚙` in the Nodes pane, or the bottom icon of the activity bar.",
    "",
    "## Layout of the dialog",
    "",
    "- **Header** — *Add underlying — search symbol or name (e.g. AAPL, Microsoft)…*: the catalogue search; results drop down anchored to the box.",
    "- **Ticker rows** — one card per ticker: its expiry **chips** (click a chip to toggle the node [lit / dark](help:glossary:lit-dark)); `▸` expands the **expiry picker**; **Remove** drops the ticker (its tabs are pruned).",
    "- **Expiry picker** — selection rules as chips: `0DTE` · `Weeklies` · `Monthly` · `Quarterly` · `≤1Y` · `≤2Y` · `All`, a per-expiry checkbox list, and *Re-apply the default selection rule*.",
    "- **Data sources** card (right column) — the active feed selector with a status light per source, and *Open a snapshot file*. A **Per-node sources** policy is rendered but disabled until the multi-source engine lands.",
    "- **Saved universes** aside (when a store is configured) — a name box, the list of saved universes, a delete `×` per row.",
    "",
    "## First use",
    "",
    "1. Search `SPY`, pick it. Repeat for the names you want lit — an index or sector ETF plus its single names is the graph's product case.",
    "2. Expand `▸` and choose a rule. **Monthly** or **≤1Y** is a good first universe; **All** on a weekly-listed name can be dozens of nodes.",
    "3. Decide what is dark. Click the chips of the expiries you want the graph to reconstruct rather than fit — a name with no quotes, a stale book, or a node you are deliberately holding out.",
    "4. Pick the data source (see [Data sources](help:guides:data-sources)).",
    "5. Close the dialog, then `Fetch ▾ Snapshot` and `Calibrate`.",
    "",
    "## The expiry rules",
    "",
    "A rule is a selection you can re-apply as the listing changes; a chip click is a one-off override.",
    "",
    "- **0DTE** — same-day expiries only (research grade).",
    "- **Weeklies** — every weekly listing inside the horizon.",
    "- **Monthly** — the standard third-Friday cycle; the usual first universe.",
    "- **Quarterly** — the quarterly cycle for a sparse long-dated ladder.",
    "- **≤1Y** · **≤2Y** — everything listed up to that tenor.",
    "- **All** — every expiry the source lists; dozens of nodes on a weekly-listed name.",
    "- *Re-apply the default selection rule* resets the chips to the rule's picks.",
    "",
    "## Lit and dark, three surfaces, one map",
    "",
    "The designation is stored per node (`GET/PUT /universe/lit`) and edited from the dialog's chips, the Nodes pane's dots (or `L` on a focused row; a ticker's hover buttons light or darken every expiry), and the Graph canvas (drop a node to light it). Lit nodes are observations of the graph solve; dark nodes receive the propagated innovation and a credible band. Only lit nodes calibrate.",
    "",
    "## Named universes",
    "",
    "[Save universe as…](cmd:universe.saveAs) (the `Universe ▾` menu or the palette prompt) stores the current tickers, expiry picks and lit/dark marks under a name; the menu's **Load saved universe** section lists them (`universe.load:<name>` in the palette). Saved universes persist in the server database (`VOLFIT_DB`). They are cheap to create and slow to rebuild — do not delete them casually.",
    "",
    "## Numbers and badges",
    "",
    "- The Nodes pane header reads `tickers · nodes · lit`.",
    "- A ticker row shows `lit/total`; an amber **≠ as-of** pill means some expiry is served off the selected as-of.",
    "- A chip's fill shows lit (filled) vs dark (outlined).",
    "",
    "## Pitfalls",
    "",
    "- Removing a ticker prunes its tabs and drops its fits; its saved priors on the server survive.",
    "- The dialog needs the live backend (the universe is server state); offline it shows a card.",
    "- 0DTE nodes are research-grade: fine to fetch and fit, but live 0DTE publishing is gated ([intradayClock](help:settings:intradayClock)).",
    "- A very large universe slows the graph: the solver is dense and comfortable to a few thousand nodes.",
    "",
    "## Related settings",
    "",
    "[autoCalibrate](help:settings:autoCalibrate) · [localVolEnabled](help:settings:localVolEnabled) · [intradayClock](help:settings:intradayClock)",
    "",
    "## Read more",
    "",
    "[Data sources](help:guides:data-sources) · [The graph](help:guides:graph) · [System overview](help:docs:00_system_overview)",
  ].join("\n"),
};

export const DATA_SOURCES: GuidePage = {
  id: "data-sources",
  title: "Data sources and as-of",
  summary: "Which feed to pick, what each one carries, how to choose the timestamp you price from, and how the scheduler keeps it fresh.",
  related: ["help:guides:universe", "help:glossary:data-source", "help:glossary:as-of", "docs_exchange_delayed", "docs_bloomberg_setup"],
  body: [
    "## The sources",
    "",
    "The backend registers every configured source and runs **one** active at a time; the Data-sources card of the Universe dialog (and the top-bar selector) switch it, and the whole universe refetches on the new feed.",
    "",
    "| Source | What it carries | Notes |",
    "|---|---|---|",
    "| **Yahoo** | US options, a usable **mid** only | free; band fit modes have little to work with |",
    "| **Bloomberg** (xbbg) | US and non-US indices and equities, full bid/ask | needs a Terminal and an entitlement — a red light is usually account-side, see the setup note |",
    "| **Massive** (Polygon / OPRA) | intraday quotes, a realtime WebSocket book, flat-file history | set `VOLFIT_MASSIVE_KEY`; delayed-tier keys use the delayed WS URL |",
    "| **Cboe · Nasdaq · ASX · HKEX · SGX · Eurex** | the exchange's own delayed book (≈15 min) with full bid/ask, sizes, OI | free, unmetered |",
    "| **Synthetic** | a deterministic test universe | always green; data age is null |",
    "| **File** | a snapshot file's quotes and fits | appears after *Open snapshot…* |",
    "",
    "## Status lights",
    "",
    "- **Green** — reachable and serving; the detail line names the entitlement or lag.",
    "- **Amber** — degraded: a delayed lag past the amber threshold, a partial probe, a book still warming.",
    "- **Red** — unreachable or gated (no Terminal, no key, an account-side block).",
    "- The light re-probes every 30 s, so a Terminal coming up flips it without a reload.",
    "",
    "## Choosing the as-of",
    "",
    "The **As of** rows live in `Fetch ▾`, next to the pull verb:",
    "",
    "- **Live** — the current market.",
    "- **Prev close** — the last stored close.",
    "- **Historical — pick a day**, then a moment: *Close (official)*, *Latest snapshot*, or *n min before close*.",
    "",
    "The market pill and the status-bar **As of** chip repeat the selection. Every day and moment is listed, but only what the active source can actually serve is clickable — the rest is dimmed with the reason (today is always Live; a live-only source has no history; Massive without its flat-file store cannot rebuild a past instant). A day tagged **marks** serves one close per contract (bid = ask, from Massive's aggregate history): the Smile chart then draws hollow diamonds and says *Close marks · no bid/ask* instead of an invisible zero-width band. Bloomberg's history carries real bid/ask. A source that ignores the request stamps the node with a yellow **≠ as-of**.",
    "",
    "## Fetching",
    "",
    "[Snapshot (quotes + spot)](cmd:fetch.snapshot) is the one fetch verb: chains, then spot transport, then an optional prior roll ([autoRollPriorOnFetch](help:settings:autoRollPriorOnFetch)), then a calibration if [autoCalibrate](help:settings:autoCalibrate) is on. The legacy split verbs stay in the palette: [Fetch spots only](cmd:fetch.spots) (transport, no refit) and [Fetch option quotes only](cmd:fetch.options). While a fetch runs the status bar shows a gauge: the chain being downloaded (*chain 2 of 4*) with its bytes against the venue's file size when the venue reports one, the elapsed time of the step, and — when nothing can be measured — elapsed versus the 10-minute client timeout (yellow past half, rose near the end). Each venue download is capped at 120 s.",
    "",
    "## The scheduler",
    "",
    "- [spotMode](help:settings:spotMode) `realtime` polls spot every [spotPollSeconds](help:settings:spotPollSeconds) and transports the surface live; `static` (default) moves spot only on a fetch.",
    "- [optionsFetchMode](help:settings:optionsFetchMode) `auto` refetches chains every [optionsFetchMinutes](help:settings:optionsFetchMinutes); `on_demand` (default) waits for you.",
    "- [schedulerUnifiedFetch](help:settings:schedulerUnifiedFetch) makes the auto timer run the full snapshot sequence instead of the bare refetch.",
    "- On a streaming source [autoStream](help:settings:autoStream) opens the WebSocket book and [streamRefitSeconds](help:settings:streamRefitSeconds) sets the fast refit cadence; the Parametric market frame then updates at ~1 Hz.",
    "",
    "The status bar's **Next fetch** / **Next snapshot** chip counts down the active timer.",
    "",
    "## Data age",
    "",
    "The worst live-chain age across the universe drives the **Quotes** chip and the market pill: amber past [dataAgeAmberMin](help:settings:dataAgeAmberMin) (20 min — a 15-min delayed feed sits under it), red past [dataAgeRedMin](help:settings:dataAgeRedMin) (120 min), at which point the node fails readiness with `stale data (… old)`. Null for historical as-of, synthetic, or nothing fetched.",
    "",
    "## Pitfalls",
    "",
    "- **Synthesized zero-carry chains.** When a feed gates NBBO it emits Black prices from its own IV marks at F = spot, D = 1. The app flags those at capture and pins the forward to that convention instead of regressing it — the Forwards lens shows the pill and its tooltip. Parity carries no information there.",
    "- A Bloomberg red light with the Terminal running is the workflow-review entitlement gate, not a code fault — read [the setup note](help:docs:docs_bloomberg_setup).",
    "- Switching sources refetches the universe; fits are kept and marked stale. Tickers carry over automatically — one portable spelling per name (\"SPY\", \"SPX\"; a Bloomberg \"SPX Index\", Yahoo \"^SPX\" or Massive \"I:SPX\" all store as \"SPX\"); only venue-specific names (a Eurex \"SX5E INDEX\", \"SAP GY Equity\") stay as typed.",
    "- A ticker the active source does not list (that Eurex name on Cboe) shows a yellow **no data** pill on its Nodes-pane row with the venue's reason; the source itself stays usable (its light names the unlisted symbol) instead of going red for everyone.",
    "- A switch never waits on a feed: it answers from the last known status lights, so a hung venue can always be left; a red light warns but never locks the choice. A failed switch lands in the status bar's *Last* chip.",
    "- The as-of mismatch is advisory (amber) until [asOfMismatchGate](help:settings:asOfMismatchGate) promotes it to a publish blocker.",
    "- The per-node source policy in the dialog has no effect yet; every node fetches from the active source.",
    "",
    "## Related settings",
    "",
    "[spotMode](help:settings:spotMode) · [spotPollSeconds](help:settings:spotPollSeconds) · [optionsFetchMode](help:settings:optionsFetchMode) · [optionsFetchMinutes](help:settings:optionsFetchMinutes) · [schedulerUnifiedFetch](help:settings:schedulerUnifiedFetch) · [autoStream](help:settings:autoStream) · [streamRefitSeconds](help:settings:streamRefitSeconds) · [dataAgeAmberMin](help:settings:dataAgeAmberMin) · [dataAgeRedMin](help:settings:dataAgeRedMin) · [asOfMismatchGate](help:settings:asOfMismatchGate)",
    "",
    "## Read more",
    "",
    "[Exchange delayed sources](help:docs:docs_exchange_delayed) · [Bloomberg setup](help:docs:docs_bloomberg_setup) · [Forwards (Note 06)](help:docs:06_forwards_dividends) · [Files](help:guides:files)",
  ].join("\n"),
};

export const WORKFLOW: GuidePage = {
  id: "workflow",
  title: "The daily workflow",
  summary: "Fetch, calibrate, repair, save priors, publish — the cycle a desk runs every session, and the gates that govern it.",
  related: ["help:guides:getting-started", "help:guides:quality", "help:guides:priors", "help:glossary:stale-node"],
  body: [
    "## The cycle",
    "",
    "1. **Fetch priors** — `Priors ▾ Fetch priors` (or [autoLoadPrior](help:settings:autoLoadPrior)) brings yesterday's saved fits back as today's [priors](help:glossary:prior).",
    "2. **Fetch** — `Fetch ▾ Snapshot (quotes + spot)` at the chosen as-of.",
    "3. **Calibrate** — the top-bar button; the scope `▾` chooses Parametric + LV / Parametric only / Local-Vol only. Slice fits and per-ticker LV fits ship to a process pool in the background; the status bar gauge counts nodes.",
    "4. **Read** — Parametric for the smiles, Forwards for anything gapping at the money, Local Vol for the joint surface, Quality for the exceptions.",
    "5. **Repair** — exclude or amend a quote, add a var-swap, switch a forward mode, edit a dividend; the touched ticker goes stale and refits (or waits — see the gate).",
    "6. **Extrapolate** — run the Graph to fill the dark nodes.",
    "7. **Save priors** — `Priors ▾` Save prior (visible tab) / Save priors (all open tabs) / Save priors (all calibrated).",
    "8. **Publish** — `File ▾ Export` surfaces (JSON / CSV) and the HTML quality report.",
    "",
    "## The workflow gate",
    "",
    "[autoCalibrate](help:settings:autoCalibrate) decides what happens when inputs change. On: the affected node refits in the background. Off (the default on the trigger-gated live server): the existing fit is kept, marked **stale**, and waits for an explicit Calibrate. Either way the invalidation is scoped — editing one name's rate, dividends, events or prior bumps that ticker's version only, never the universe.",
    "",
    "## Stale, and stale data",
    "",
    "Two different amber states. A [stale node](help:glossary:stale-node) has a fit whose inputs moved (amber glyph in the Nodes pane and tab strip, `STALE` badge on the chart toolbar, the *Stale* tile in Quality) — Calibrate fixes it. **Stale data** is about the quotes' timestamp ([data age](help:glossary:data-age)) — only a fetch fixes it.",
    "",
    "## Calibrate scope",
    "",
    "- **Parametric + LV** — the slices of every lit node, then the joint LV surface per ticker. The default.",
    "- **Parametric only** — the slices; fast, and enough while you iterate on quotes and forwards.",
    "- **Local-Vol only** — the surfaces; run it once the slices are settled.",
    "",
    "## The Priors ▾ verbs",
    "",
    "- **Save prior — visible tab** · **Save priors — all open tabs** · **Save priors — all calibrated** — which nodes' current fits become the saved prior.",
    "- **Fetch priors** — reload the saved priors for the universe (transported on use).",
    "",
    "## The command center, read left to right",
    "",
    "- `Fetch ▾` — the Snapshot verb and the As-of rows. A subtle indeterminate bar on the button marks a fetch in flight.",
    "- `Calibrate` + scope `▾` — the primary action; disabled while a job runs.",
    "- `Priors ▾` — the four prior verbs.",
    "- **Market pill** — the active source and the quote age; passive readout.",
    "",
    "## Spot moves between calibrations",
    "",
    "The **Spot move** card in the Parametric and Local Vol asides shows three spots — *Calibrated* (the anchor the fits were made at), *Market* (the prevailing provider spot: streamed off the live book at ~1 Hz when one is up, else the last probe or the fetched chain's own) and *Scenario* (anchor × (1 + dial)) — and a **Market spot / Scenario** selector saying which one the surface lives at: following the market keeps the shift synced to it (the scheduler re-syncs at the spot-poll cadence while a book streams, every fetch otherwise); the scenario is the dial (0.1 % steps, ± buttons, Shift for 1 %, **Reset to 0.0%**, **Sync to market**). Either way the calibrated surface is transported live under the active [SSR regime](help:glossary:ssr): every lens follows, the node's live tick stream included, nothing refits. **Recalibrate _ticker_ (_scope_)** is the top-bar Calibrate for that ticker alone — same scope, same snapshot rule (a synchronous quotes + spot snapshot off the streaming book, else the last fetched chain, no request) — run as the background job over ALL its lit nodes (the spot move is per ticker, so a single node cannot be re-anchored alone); the previous fit stays on screen, marked stale, until the new one lands. In `realtime` spot mode the market spot is pinned.",
    "",
    "## Numbers you will read all day",
    "",
    "- Status bar: `n/total` on the gauge; **Nodes** lit / stale; **Last** action and its time.",
    "- Nodes pane: RMS bp per node and the quality dot.",
    "- Quality tiles: Publish ready · Fitted · Stale · No fit · Arb flags · Median RMS · Worst RMS · LV surfaces.",
    "",
    "## Pitfalls",
    "",
    "- Calibrating with a prior loaded and [priorPersistenceMode](help:settings:priorPersistenceMode) ≠ off changes the fit only where quotes fail to identify a feature; a sparse morning leans on yesterday by design.",
    "- **Save priors at the end of the session**, not the start — the prior is the fit you trust, transported tomorrow.",
    "- Calendar coupling ([enforceCalendar](help:settings:enforceCalendar)) runs on Calibrate in ascending T; a single-node refit after a quote edit re-couples only if [calendarOnRefit](help:settings:calendarOnRefit) is on.",
    "- Local Vol fits per ticker and can take longer than the slices on wide chains; the scope `▾` lets you skip it while iterating on quotes.",
    "- The graph solve uses committed calibrations; run it after Calibrate lands, not during.",
    "",
    "## Related settings",
    "",
    "[autoCalibrate](help:settings:autoCalibrate) · [autoLoadPrior](help:settings:autoLoadPrior) · [autoRollPriorOnFetch](help:settings:autoRollPriorOnFetch) · [localVolEnabled](help:settings:localVolEnabled) · [calendarOnRefit](help:settings:calendarOnRefit) · [schedulerUnifiedFetch](help:settings:schedulerUnifiedFetch)",
    "",
    "## Read more",
    "",
    "[Quality and publishing](help:guides:quality) · [Priors](help:guides:priors) · [The graph](help:guides:graph) · [System overview (Note 00), §3 the pipeline](help:docs:00_system_overview)",
  ].join("\n"),
};
