// Guides — shell group (HELP CENTER ARC, H1): getting-started, workbench,
// files. Markdown bodies written as arrays of lines joined with "\n" so a
// line of Markdown is a line of source. Every control named here exists in
// the live shell (App.tsx, components/shell/*, lib/shortcuts.ts,
// state/workspaceFile.tsx, state/snapshotFile.tsx). Link grammar:
// [label](help:<page>:<anchor>) and [label](cmd:<command.id>).
import type { GuidePage } from "../types";

export const GETTING_STARTED: GuidePage = {
  id: "getting-started",
  title: "Getting started",
  summary: "What VolFit is, the four-step workflow, and your first ten minutes from an empty universe to a published surface.",
  related: ["help:guides:workbench", "help:guides:workflow", "00_system_overview"],
  body: [
    "## What VolFit is",
    "",
    "VolFit fits implied-volatility smiles under explicit no-arbitrage control and then does one thing most fitters do not: it **extrapolates** sparse observations to a full universe of smiles, across expiries and across assets, by propagating signal through a graph whose nodes are smiles (underlying, T).",
    "",
    "Four models share one calibration spine — [LQD](help:glossary:lqd) (default), [SVI-JW](help:glossary:svi-jw), the [Multi-Core Sigmoid](help:glossary:mcs) and the jointly fitted [local-volatility surface](help:glossary:local-volatility). Every displayed slice is certified before it can be published.",
    "",
    "## The four-step workflow",
    "",
    "1. **Universe** — pick tickers and expiries, mark nodes [lit or dark](help:glossary:lit-dark). `Universe ▾ Manage universe…` (Ctrl+Shift+U).",
    "2. **Fetch** — pull quotes and spot at an [as-of](help:glossary:as-of) moment from the active [data source](help:glossary:data-source). `Fetch ▾ Snapshot (quotes + spot)`.",
    "3. **Calibrate** — fit every lit node (Parametric + LV, or one of them). The `Calibrate` button in the top bar; scope in its `▾`.",
    "4. **Read, repair, publish** — inspect smiles under the Parametric lens, check the Quality lens, run the Graph to fill the dark nodes, export.",
    "",
    "## Your first ten minutes",
    "",
    "1. Start the backend (`.\\restart.ps1` from the repo root). Without it the lenses show a *requires the live backend* card and the Parametric chart carries a `MOCK` badge.",
    "2. Open [Manage universe…](cmd:universe.manage). Type `SPY` in *Add underlying — search symbol or name*, pick it. Expand the row with `▸` and choose the **Monthly** rule, or click expiry chips directly.",
    "3. In the **Data sources** card on the right, pick a source with a green light. See [Data sources](help:guides:data-sources) for what each one carries.",
    "4. Close the dialog. The Nodes pane now lists `SPY` with its expiries. Every node is lit by default (the dot at the left of each row).",
    "5. `Fetch ▾` → **Snapshot (quotes + spot)**. The status bar narrates the fetch; the *Quotes* chip shows the age of what arrived.",
    "6. Press **Calibrate**. The gauge in the status bar counts nodes; each Nodes-pane row gains an RMS figure (bp) and a quality dot.",
    "7. Click an expiry row. A preview tab opens and the **Parametric** lens (Alt+3) draws its smile: bid/ask bands, the fit target, the fitted curve.",
    "8. Press Alt+5 for **Quality**: the *Publish ready* tile tells you how many nodes clear the gate and why the others do not.",
    "9. `File ▾` → **Save workspace as…** (Ctrl+Shift+S). Your universe, settings and layout are now a file you can reopen or drop onto the shell.",
    "",
    "## Reading the first smile",
    "",
    "- Grey bands are the market bid/ask in vol; the shaded **Target** is what the fit is measured against ([mid, band or haircut](help:glossary:fit-target)).",
    "- The solid curve is the current fit; a dashed one is the [prior](help:glossary:prior) when one is loaded.",
    "- `RMS` in the Fit diagnostics card is the weighted vol error against the target, in [vol bp](help:glossary:vol-bp). A `STALE` badge means inputs moved since that fit — press Calibrate.",
    "- The layer rail at the right of the chart toggles Target · Calib. quotes · Calib. fit · Weights.",
    "",
    "## Where things live",
    "",
    "| Need | Where |",
    "|---|---|",
    "| Tickers, expiries, lit/dark, data source | `Universe ▾` → Manage universe… |",
    "| Model, penalties, fit target, priors, filter, graph dials | `Options` (Ctrl+,) |",
    "| Timestamp to price from | `Fetch ▾` → As of rows |",
    "| Save / fetch priors | `Priors ▾` in the top bar |",
    "| Forwards, dividends, borrow | the **Forwards** lens (Alt+2) |",
    "| Colour scheme, expiry label format | `View ▾` |",
    "| Panes, split editors, Zen mode | `Layout ▾` |",
    "| Workspace and snapshot files, exports | `File ▾` |",
    "| Anything, by name | Ctrl+K (the command palette) |",
    "",
    "## Keyboard chords to learn first",
    "",
    "- `Ctrl+P` quick-open a node · `Ctrl+K` command palette · `Ctrl+B` Nodes pane",
    "- `Alt+1 … Alt+5` lens: Graph · Forwards · Parametric · Local Vol · Quality",
    "- `Alt+← / Alt+→` previous / next tab · `Alt+W` close tab · `Ctrl+\\` split",
    "- `Ctrl+,` Options · `Ctrl+Shift+U` Manage universe · `Ctrl+/` the shortcut list",
    "",
    "## Pitfalls",
    "",
    "- On the trigger-gated live server `autoCalibrate` defaults **off**: a fetch marks nodes stale and waits for an explicit Calibrate. Elsewhere the default is on. See [autoCalibrate](help:settings:autoCalibrate).",
    "- The **Local Vol** icon is inert while [localVolEnabled](help:settings:localVolEnabled) is off (the tooltip says so).",
    "- Yahoo yields a usable **mid** only; band fit modes need a source with a real bid/ask (an exchange's delayed book, Massive, Bloomberg).",
    "- A dark node has no fit of its own until the Graph has run; it shows *no fit* in Quality.",
    "",
    "## Related settings",
    "",
    "[autoCalibrate](help:settings:autoCalibrate) · [model](help:settings:model) · [fitMode](help:settings:fitMode) · [localVolEnabled](help:settings:localVolEnabled)",
    "",
    "## Read more",
    "",
    "[System overview (Note 00)](help:docs:00_system_overview) · [The workbench](help:guides:workbench) · [The daily workflow](help:guides:workflow) · [Take the walkthrough](cmd:help.walkthrough)",
  ].join("\n"),
};

export const WORKBENCH: GuidePage = {
  id: "workbench",
  title: "The workbench",
  summary: "The VS Code-like shell: top bar, activity bar, Nodes pane, editor groups and tabs, status bar, palette, and every chord.",
  related: ["help:guides:getting-started", "help:shortcuts", "help:commands"],
  body: [
    "## What it is",
    "",
    "The shell is a fixed-viewport workbench in the VS Code grammar. A **lens** (how you look) is applied to a **node tab** (what you look at); one to three editor groups can show different nodes at once. Every menu row is a registry command, so the menus and the Ctrl+K palette can never disagree.",
    "",
    "## Layout",
    "",
    "- **Top bar** — `Universe ▾` · `Options` · `Help ▾` on the left; the command center in the middle: `Fetch ▾` (Snapshot + the As-of rows), `Calibrate` with its scope `▾` (Parametric + LV / Parametric only / Local-Vol only), `Priors ▾`, and the market pill (active source · quote age); `View ▾` · `Layout ▾` · `File ▾` on the right.",
    "- **Activity bar** (left edge) — one icon per lens: Graph · Forwards · Parametric · Local Vol · Quality (Alt+1…5). At the bottom: Manage universe and Options.",
    "- **Nodes pane** — the universe as a tree (Ctrl+B shows / hides it; resizable).",
    "- **Main pane** — editor groups, each with a tab strip and the lens rendered for its active tab.",
    "- **Status bar** — engine narration and summary chips.",
    "- **Dialogs** — Manage universe, Options, Shortcuts, About, Quick open (Ctrl+P) and the palette (Ctrl+K). `Esc` closes any of them.",
    "",
    "## The Nodes pane",
    "",
    "A ticker row shows a chevron, the ticker, `lit/total`, and an amber **≠ as-of** pill when any expiry is served off the selected as-of; hovering reveals *Light every expiry* / *Darken every expiry*. An expiry row shows the lit/dark **dot** (click toggles it — shared with the Graph canvas and the Universe dialog), the expiry, its tenor, the `HH:MM` of the chain serving it (amber when inexact), the RMS in bp, and a quality glyph: emerald ready · amber stale · rose arb-flagged · grey no fit.",
    "",
    "The header counts `tickers · nodes · lit`; the filter box narrows the tree; the **lit only** toggle hides dark nodes; `⚙` opens the Universe dialog.",
    "",
    "Keyboard (the tree is one tab stop with a roving focused row): `↑ ↓ Home End` move · `← →` collapse / expand a ticker · letters jump to the next ticker · `Enter` preview tab · `Shift+Enter` or `Space` pinned tab · `Ctrl+Enter` open in the next editor group · `L` toggle lit/dark · `Tab` to the filter box.",
    "",
    "Drag a row onto the Graph canvas to light it (or pulse it in a what-if), or onto a tab strip to open it pinned.",
    "",
    "## Tabs: preview vs pinned",
    "",
    "A single click (or Enter) opens a **preview** tab — italic, reused by the next click. Double-click, middle-click, Shift+Enter or Space opens a **pinned** tab (pin glyph). Middle-click or `Alt+W` closes; drag reorders; right-click offers close / close others / close all / pin / move to another group. Each tab carries a quality glyph (amber stale, rose arb). `Ctrl+P` fuzzy-finds a node by ticker, formatted expiry or ISO date.",
    "",
    "## Editor groups",
    "",
    "`Ctrl+\\` adds a group after the focused one, up to three side by side; at three it folds back to one. `Ctrl+Shift+\\` splits **down** from a single group. Dragging a tab or a Nodes-pane row onto the right 20 % of the main pane splits, onto the bottom 20 % splits down. The focused group's active tab is the session selection; other groups fetch their own node, so you can hold two expiries under two lenses. The last tab closed in a group drops the group. Unfocused strips read dimmer.",
    "",
    "## Command palette and quick open",
    "",
    "`Ctrl+K` (or `Ctrl+Shift+P`, or `>` typed in quick open) lists every command: menu rows, verbs, lenses, layout toggles, dialogs, saved universes, server workspaces, recent files. A command with an argument (*Save workspace to server…*, *Save universe as…*) turns the box into its prompt. Legacy verbs — *Fetch spots only*, *Fetch option quotes only* — live only here.",
    "",
    "## The status bar",
    "",
    "Left: what the engine is doing (fetch / calibrate / LV / term / density …) with a gauge — determinate for a calibration job's node count — or *Ready*, then the last error, then `LENS · NODE`. Right: **Workspace** (file name, `· unsaved`), **Nodes** (lit / stale), **Next fetch** or **Next snapshot** (the scheduler), **As of**, the source light, **Quotes** age when not fresh, the **Last** action with its time, and the wall clock. Layout ▾ can hide it.",
    "",
    "## View ▾ and Layout ▾",
    "",
    "- **View ▾**: colour scheme (Dark · Light · High contrast · Warm), contrast and brightness, the expiry label format (`dd-mmm-yy` · `(dd)mmmyy` · `x.xxY` · `xx.xM` · `yyM zD`, cycled by [view.expiryFormat:cycle](cmd:view.expiryFormat:cycle)), live preview, *Save the look as default*, *Reset the look*.",
    "- **Layout ▾**: Nodes pane · Diagnostics aside (the fit / config side panels) · Status bar · [Zen mode](cmd:layout.zen) (charts only) · **Remember view per tab** (each tab keeps its sub-view, otherwise one view per lens) · Close all tabs · Reset layout.",
    "",
    "## Help ▾",
    "",
    "Keyboard shortcuts (Ctrl+/) · Command palette · API reference (OpenAPI `/docs`) · Quality report (HTML) · About. The Help Center itself: [Guides](cmd:help.walkthrough), [Settings reference](cmd:help.settings), [Command reference](cmd:help.commands), [Documentation](cmd:help.docs), [Ask](cmd:help.ask). `F1` opens the guide of the active lens.",
    "",
    "## Chart interaction (every lens)",
    "",
    "- Wheel zooms x and y around the cursor · `Shift+wheel` x only · `Alt+wheel` y only (bypasses the y auto-scale).",
    "- Drag pans; on a 3D surface drag rotates, `Shift+drag` or middle-drag pans, `Ctrl+drag` pitches. Double-click resets.",
    "- Hovering a 3D surface shows a crosshair — the smile at T and the term curve at k — linked across the ticker's surface charts.",
    "- The range brush under a smile sets the strike window.",
    "",
    "## Pitfalls",
    "",
    "- Browser-reserved chords are avoided on purpose: lenses ride `Alt+1…5`, tab cycling `Alt+← / →`, not `Ctrl+1…9` or `Ctrl+Tab`.",
    "- Each lens sits in its own error boundary keyed by the lens, so switching tabs keeps view state and a crash in one lens never takes the shell down — but the lens shows an error card until you switch away and back.",
    "- Graph and Quality are universe lenses: they render without a tab and highlight the active node instead of following it.",
    "- Layout and view preferences persist in the browser; a workspace file carries them too, so opening a file restores someone else's layout.",
    "",
    "## Related settings",
    "",
    "The shell has no backend settings of its own; the scheduler chips read [spotMode](help:settings:spotMode), [optionsFetchMode](help:settings:optionsFetchMode) and [schedulerUnifiedFetch](help:settings:schedulerUnifiedFetch).",
    "",
    "## Read more",
    "",
    "[Keyboard shortcuts](help:shortcuts) · [Command reference](help:commands) · [Files](help:guides:files) · [API and UI inventory](help:docs:handoff_api_ui)",
  ].join("\n"),
};

export const FILES: GuidePage = {
  id: "files",
  title: "Workspace and snapshot files",
  summary: "What the File menu saves and opens — workspace files, snapshot files, the server store, exports — and what each one does and does not contain.",
  related: ["help:guides:workbench", "help:guides:data-sources", "help:glossary:workspace-file", "help:glossary:snapshot-file"],
  body: [
    "## Three kinds of file",
    "",
    "| File | Contains | Does not contain |",
    "|---|---|---|",
    "| **Workspace** (`volfit-workspace/1`) | the backend workspace doc (settings, universe picks, quote edits, priors …) + the shell state (lens, tabs, layout, view preferences, expiry format, node-source policy) | quotes, fits |",
    "| **Snapshot** (`volfit-snapshot/1`) | the cached quotes + the prevailing calibrations of every ticker | settings, layout |",
    "| **Exports** | surfaces as JSON (fitted nodes + inputs + manifest) or CSV (one row per curve point); the HTML quality report; the active chart as PNG | — |",
    "",
    "## The File ▾ menu",
    "",
    "- [New workspace](cmd:file.new) — back to defaults (asks first).",
    "- [Open workspace…](cmd:file.open) (Ctrl+O) — or drop a `.json` anywhere on the shell; the schema decides whether it is a workspace or a snapshot.",
    "- [Save workspace](cmd:file.save) (Ctrl+S) — to the last target; the row's detail shows the target name and `· unsaved`.",
    "- [Save workspace as…](cmd:file.saveAs) (Ctrl+Shift+S) — Chromium file picker, or a download elsewhere.",
    "- **Snapshots — quotes + calibrations**: [Save snapshot…](cmd:file.saveSnapshot) (Ctrl+Alt+S) · [Open snapshot…](cmd:file.openSnapshot).",
    "- **Export**: [surfaces JSON](cmd:export.surfacesJson) · [surfaces CSV](cmd:export.surfacesCsv) · [quality report HTML](cmd:export.report) · [chart PNG](cmd:export.chartPng).",
    "- **Save to server…** (a name box) · **Open from server** (one row per stored workspace, with a delete `×`) · **Recent** (the last 8).",
    "",
    "## Saving and opening a workspace",
    "",
    "1. Arrange the shell the way you want it handed over: universe, options, tabs, split, colour scheme.",
    "2. Ctrl+Shift+S, name the file. On Chromium the browser keeps a file handle, so later Ctrl+S overwrites in place; on other browsers Ctrl+S re-downloads under the same name.",
    "3. To reopen: Ctrl+O, or drag the file onto the shell. Opening is a **backend state reset** (`POST /workspace/import`) followed by the shell blob — every lens refreshes, and nodes may come up stale until you fetch and calibrate.",
    "",
    "Dirty tracking: the status bar's **Workspace** chip shows `· unsaved` when the backend fingerprint or the shell blob moved since the last save or open. A fresh session baselines clean.",
    "",
    "## Snapshot files",
    "",
    "**Save snapshot…** exports what is cached — it never fetches or refits. **Open snapshot…** registers (or extends) the `file` [data source](help:glossary:data-source), switches to it, points the universe at the file's tickers and reinstalls the embedded fits with provenance *loaded* (the Fit diagnostics card shows a green `loaded` tag). It is the way to hand a colleague an exact market, or to work with no feed at all. The Data-sources card of the Universe dialog has the same *Open a snapshot file* action.",
    "",
    "## The server store",
    "",
    "When the backend runs with `VOLFIT_DB` set (restart.ps1 does this), **Save to server…** stores the workspace under a name and **Open from server** lists them with their timestamps. Server workspaces appear in the palette as `file.openServer:<name>`. Delete with the `×` on the row.",
    "",
    "## Exports, one line each",
    "",
    "- **Export surfaces (JSON)** — every published node: curves, inputs, and a reproducibility manifest (dated).",
    "- **Export surfaces (CSV)** — one row per curve point; for spreadsheets and downstream loaders.",
    "- **Export quality report (HTML)** — self-contained; opens in a new tab; the client-facing document.",
    "- **Export chart as PNG** — the active chart card of the focused group, as drawn.",
    "",
    "## Recent files and drop targets",
    "",
    "The **Recent** section keeps the last 8 files opened or saved (`file.recent:` rows in the palette). Any `.json` dropped anywhere on the shell is routed by its schema: a workspace opens as a workspace, a snapshot as a snapshot, anything else is rejected with a reason.",
    "",
    "## What lands where",
    "",
    "Every outcome — saved, opened, rejected, exported — lands in the status bar's **Last** chip with its time; a rejected file names what was wrong (unknown schema, missing backend doc …).",
    "",
    "## Pitfalls",
    "",
    "- A workspace file does not carry quotes. Reopening it on another day gives you the same configuration on today's market, not the market you saved.",
    "- A snapshot file does not carry settings. Open the workspace first, then the snapshot, when you want both.",
    "- Opening a workspace resets the backend state — unsaved priors or quote edits of the current session are gone. Save first.",
    "- Exports write the *published* surfaces: a node that fails the [publish gate](help:glossary:publish-gate) blocks the export with typed reasons (HTTP 409). Fix the Quality exceptions, then export.",
    "- The chart PNG exports the active chart card of the focused group only.",
    "",
    "## Related settings",
    "",
    "[autoCalibrate](help:settings:autoCalibrate) (whether an opened workspace's stale nodes refit by themselves) · [autoLoadPrior](help:settings:autoLoadPrior)",
    "",
    "## Read more",
    "",
    "[The workbench](help:guides:workbench) · [Data sources](help:guides:data-sources) · [Quality and publishing](help:guides:quality)",
  ].join("\n"),
};
