// Command reference — part 1 of 3 (HELP CENTER ARC, H2): the File · Export ·
// Universe · Fetch · Calibrate · Priors commands of lib/commands.ts. One
// CommandDoc per registry id; `enabledWhen` mirrors the bind() gate in
// state/commands.tsx, `details` says what happens and where the outcome shows
// (the status bar's "Last" chip, a new tab, a download). Concatenated with the
// other two parts by commandDocs.ts, which the completeness lock reads.
import type { CommandDoc } from "./types";

export const COMMAND_DOCS_FILE: CommandDoc[] = [
  // ---------------------------------------------------------------- File
  {
    id: "file.new",
    summary: "Reset the workspace to a blank configuration.",
    details: "Resets the server-side workspace (`POST /workspace/new`): Options return to their defaults; quote edits, priors, forward overrides, filter states, graph overrides and the open tabs are cleared. The universe keeps its tickers. From the File menu the row asks for a confirmation first; from the palette it runs at once. The status bar's **Last** chip reads \"New workspace\".",
    example: "You spent the morning trying wing settings on SPY 18-Dec-26 and want a clean slate before the afternoon fetch: File ▸ New workspace ▸ Reset. Every Options field is back to default; SPY, NVDA and AAPL stay in the universe with no fits.",
    enabledWhen: "Live backend, no file operation in flight",
    guide: "files",
    related: ["file.open", "file.save", "options.open"],
  },
  {
    id: "file.open",
    summary: "Open a workspace file (.json) from disk.",
    details: "Opens the browser's file picker for a `volfit-workspace/1` bundle — or drop the .json anywhere on the shell. The backend restores the workspace document (`POST /workspace/import`) and the shell restores its part: lens, editor groups and tabs, layout, view memory, colour scheme, expiry format. A file with another schema or version is refused with a diagnostic. The opened file becomes the Save target and joins **File ▸ Recent**.",
    example: "Drop `desk_2026-08-28.json` on the tab strip: the tabs SPY 18-Dec-26 and NVDA 20-Mar-27 reopen, the Parametric lens comes back, Options match the saved ones, and the status bar shows \"Workspace desk_2026-08-28\".",
    enabledWhen: "Live backend, no file operation in flight",
    guide: "files",
    related: ["file.save", "file.saveAs", "file.recent:", "file.openSnapshot"],
  },
  {
    id: "file.save",
    summary: "Save the workspace to its last target (file or server).",
    details: "Re-saves the whole configuration where it was last saved. A Chromium file handle rewrites the file in place; other browsers download a fresh copy; a server target re-posts under the same name. With no target yet it behaves like **Save as…**. The **unsaved** marker on the status-bar workspace chip clears; the **Last** chip reads \"Saved workspace\".",
    example: "You loaded `desk.json`, excluded two AAPL 19-Jun-26 quotes and moved the haircut. Ctrl+S rewrites `desk.json` on disk (Edge/Chrome) and the \"unsaved\" tag disappears.",
    enabledWhen: "Live backend, no file operation in flight",
    guide: "files",
    related: ["file.saveAs", "file.saveToServer", "file.open"],
  },
  {
    id: "file.saveAs",
    summary: "Save the workspace under a new file name.",
    details: "Builds the `volfit-workspace/1` bundle — backend workspace document plus the shell blob — and saves it through the Chromium file picker, or as a download elsewhere. The new file becomes the Save target and joins **File ▸ Recent**. Nothing about the fits changes: a workspace file is configuration, not quotes (use **Save snapshot…** for those).",
    example: "Before an experiment, Ctrl+Shift+S ▸ `spy_wings_experiment.json`. Later, File ▸ Recent lists it next to `desk.json`; open either to switch configurations in one click.",
    enabledWhen: "Live backend, no file operation in flight",
    guide: "files",
    related: ["file.save", "file.saveSnapshot", "export.surfacesJson"],
  },
  {
    id: "file.saveToServer",
    summary: "Store the workspace under a name on the server.",
    details: "Takes a name (the palette prompts for it; the File menu has an inline box) and posts the workspace to the named store (`POST /workspaces/{name}`). The name appears under **File ▸ Open from server** and in Recent, and becomes the Save target. Needs `VOLFIT_DB` on the server — without it the row is disabled and the menu says so.",
    example: "Type `morning-desk` and press Enter. Any browser pointed at this backend now finds \"Open workspace from server: morning-desk\" in Ctrl+K.",
    enabledWhen: "Live backend with a workspace store (VOLFIT_DB), no file operation in flight",
    guide: "files",
    related: ["file.openServer:", "file.deleteServer:", "file.save"],
  },
  {
    id: "file.saveSnapshot",
    summary: "Save the fetched quotes and the committed calibrations as a file.",
    details: "Writes a `volfit-snapshot/1` bundle (`POST /snapshot/export`): every cached chain with its spot and forwards, plus the committed fits (parameters, diagnostics, fit mode) per node. It never fetches and never refits — nothing fetched yet means nothing to save (the server answers 409). Chromium saves through the file picker, other browsers download. The **Last** chip reads \"Saved snapshot\".",
    example: "At 14:30 you have SPY, NVDA and AAPL fetched and calibrated. Ctrl+Alt+S ▸ `spy_0831_1430.json`. Tomorrow, File ▸ Open snapshot… brings back exactly those quotes and those fits.",
    enabledWhen: "Live backend, no snapshot operation in flight",
    guide: "files",
    related: ["file.openSnapshot", "export.surfacesJson", "file.saveAs"],
  },
  {
    id: "file.openSnapshot",
    summary: "Load a snapshot file as the File data source.",
    details: "Imports a snapshot (`POST /snapshot/import`): the backend registers a **File** data source serving the embedded chains at their embedded as-of, switches the active source to it, points the universe at the file's tickers and reinstalls the embedded calibrations as the committed fits (Quality shows them with provenance *loaded*). Several files union their tickers; the last loaded wins per node. Fetch under the File source re-serves the same chains; Calibrate refits them under the current Options.",
    example: "Open `spy_0831_1430.json`: the market pill reads \"File · spy_0831_1430 · 14:30\", the nodes pane lists SPY's embedded expiries, and SPY 18-Dec-26 shows its saved LQD fit with no fetch.",
    enabledWhen: "Live backend, no snapshot operation in flight",
    guide: "data-sources",
    related: ["file.saveSnapshot", "universe.manage", "fetch.snapshot"],
  },
  // -------------------------------------------------------------- Export
  {
    id: "export.surfacesJson",
    summary: "Download every published surface as JSON.",
    details: "Opens `GET /export/surfaces` in a new tab: the fitted nodes (curves on a strike grid, parameters, wing law), the inputs that produced them (quotes, forwards, settings) and a reproducibility manifest. Only publish-ready nodes are exported; the Quality lens tells you which are held back and why.",
    example: "After calibrating twelve nodes, the download `volfit_surfaces_<date>.json` holds SPY 18-Dec-26 with its LQD parameters and the exact quotes used — the same shape as the standing test fixture.",
    enabledWhen: "Live backend",
    guide: "quality",
    related: ["export.surfacesCsv", "export.report", "file.saveSnapshot"],
  },
  {
    id: "export.surfacesCsv",
    summary: "Download every published surface as CSV.",
    details: "Same content as the JSON export, flattened: one row per curve point (ticker, expiry, strike, moneyness, implied vol, model) so it drops straight into a spreadsheet or a risk system. Opens `GET /export/surfaces?format=csv` in a new tab.",
    example: "Load the CSV in Excel and pivot by expiry to compare SPY's 18-Dec-26 and 20-Mar-27 smiles at fixed strikes.",
    enabledWhen: "Live backend",
    guide: "quality",
    related: ["export.surfacesJson", "export.report"],
  },
  {
    id: "export.report",
    summary: "Open the HTML quality report in a new tab.",
    details: "Opens `GET /export/report`: the client-facing readiness report — per-node RMS against the fit target, wing slopes, calendar certificate, data age, as-of, and the blockers that hold a node back from publishing. It reads the cached calibrations and never refits. **Help ▸ Quality report** is the same document.",
    example: "Before sending marks, open the report and check that NVDA 20-Mar-27 is no longer flagged \"calendar\" after your refit.",
    enabledWhen: "Live backend",
    guide: "quality",
    related: ["help.report", "lens.quality", "export.surfacesJson"],
  },
  {
    id: "export.chartPng",
    summary: "Download the active chart card as a PNG.",
    details: "Rasterises the SVG of the active chart card (styles inlined, 2× canvas) and downloads `<ticker>_<expiry>_<view>.png`. Works offline too. The **Last** chip reads \"Exported <name>\" — or \"no chart on the active lens\" when the lens shows a table.",
    example: "On the Parametric lens, Smile view of SPY 18-Dec-26 with the Target layer on: Ctrl+K ▸ \"Export chart as PNG\" saves `SPY_2026-12-18_smile.png`.",
    guide: "parametric",
    related: ["export.report", "lens.parametric"],
  },
  // ------------------------------------------------------------ Universe
  {
    id: "universe.manage",
    summary: "Open the Manage universe dialog.",
    details: "Opens the dialog (Ctrl+Shift+U, or the ⚙ of the Nodes pane): add or remove underlyings from the catalogue search, pick each ticker's expiries, toggle nodes lit / dark on the expiry chips, choose the active data source in the Data-sources card, and save or load named universes. Edits flow into the nodes pane and every lens at once; tabs of removed nodes close.",
    example: "Add MSFT, expand its row, tick the 18-Dec-26 and 20-Mar-27 expiries and light both. The nodes pane shows \"MSFT 2/2\" and the next Fetch pulls its chains.",
    guide: "universe",
    related: ["universe.saveAs", "universe.load:", "layout.nodesPane"],
  },
  {
    id: "universe.saveAs",
    summary: "Save the active universe under a name.",
    details: "Takes a name (palette prompt or the inline box in Universe ▾) and stores the active ticker set with each ticker's expiry selection (`POST /universes/{name}`). The name appears under **Universe ▾ Load saved universe** as a `universe.load:` command. Needs `VOLFIT_DB` on the server.",
    example: "Type `us-tech` after building SPY + NVDA + AAPL + MSFT. Next week, \"Load universe: us-tech\" rebuilds the set in one click.",
    enabledWhen: "Live backend with a universe store (VOLFIT_DB), no universe operation in flight",
    guide: "universe",
    related: ["universe.load:", "universe.manage"],
  },
  // --------------------------------------------------------------- Fetch
  {
    id: "fetch.snapshot",
    summary: "Fetch option chains and spots in one pull, at the selected as-of.",
    details: "The one fetch verb (`POST /fetch/snapshot`): chains and spots for every ticker of the universe from the active data source, at the as-of chosen in the Fetch ▾ rows (Live / Previous close / a day and moment). Then, per Options: rolls the active priors to their latest saved snapshot ([autoRollPriorOnFetch](help:settings:autoRollPriorOnFetch)) and starts a calibration ([autoCalibrate](help:settings:autoCalibrate)). Fetched nodes whose inputs changed are marked **stale** until calibrated. Progress narrates in the status bar; the **Last** chip reads \"Fetched snapshot\". The menu shows a coverage line first (\"9/12 nodes exact · 3 fall back to Close\").",
    example: "Pick Previous close in Fetch ▾, then Snapshot. SPY 18-Dec-26 shows yesterday's close chain with the HH:MM stamp in the nodes pane; with auto-calibrate on, the fit lands a few seconds later.",
    enabledWhen: "Live backend, workflow idle",
    guide: "workflow",
    related: ["calibrate.both", "help:settings:schedulerUnifiedFetch", "fetch.spots", "fetch.options"],
  },
  {
    id: "fetch.spots",
    summary: "Fetch spots only (legacy split verb).",
    details: "Pulls the current spot per ticker (`POST /fetch/spots`) — transport only, no chain fetch and no refit. Retired from the Fetch ▾ menu; kept in the palette for power users. Prefer **Fetch snapshot** in daily use.",
    example: "Ctrl+K ▸ \"Fetch spots only (legacy)\": the Spot-move card of every Parametric tab updates its reference spot without touching the quotes.",
    enabledWhen: "Live backend, workflow idle",
    guide: "workflow",
    related: ["fetch.snapshot", "fetch.options"],
  },
  {
    id: "fetch.options",
    summary: "Fetch option chains only (legacy split verb).",
    details: "Pulls the chains without a spot refresh (`POST /fetch/options`); may start the auto-calibration job like Snapshot does. Retired from the Fetch ▾ menu; kept in the palette. Prefer **Fetch snapshot**.",
    example: "Ctrl+K ▸ \"Fetch option quotes only (legacy)\" to re-pull chains after the provider corrected a bad print, keeping the spots you have.",
    enabledWhen: "Live backend, workflow idle",
    guide: "workflow",
    related: ["fetch.snapshot", "fetch.spots"],
  },
  // ----------------------------------------------------------- Calibrate
  {
    id: "calibrate.both",
    summary: "Calibrate the parametric smiles, then the Local-Vol surfaces.",
    details: "Runs `POST /calibrate` as a background job: every lit node's parametric fit (LQD / SVI-JW / MCS per [model](help:settings:model), against the chosen [fit target](help:settings:fitMode)), then one Local-Vol surface per ticker when [localVolEnabled](help:settings:localVolEnabled) is on. Stale badges clear as nodes land; the status bar gauge counts nodes; the **Last** chip reads \"Calibrated parametric + LV\". The top-bar Calibrate face runs the LAST chosen scope and names it — this command selects this scope.",
    example: "Twelve nodes stale after a fetch: [Run it](cmd:calibrate.both). The gauge walks 0→12, the SPY LV surface follows, and the Quality tiles refresh.",
    enabledWhen: "Live backend, workflow idle",
    guide: "workflow",
    related: ["calibrate.parametric", "calibrate.lv", "help:settings:autoCalibrate"],
  },
  {
    id: "calibrate.parametric",
    summary: "Calibrate the parametric smiles only (the fast loop).",
    details: "Runs `POST /calibrate/parametric`: parametric slices for every lit node, no Local-Vol pass — the LV surfaces go or stay **stale** (the Local Vol lens says so). The **Last** chip reads \"Calibrated parametric\".",
    example: "You amended two mids on AAPL 19-Jun-26 and want the smile back in seconds: Parametric only. Run LV later, once the whole ladder is settled.",
    enabledWhen: "Live backend, workflow idle",
    guide: "parametric",
    related: ["calibrate.both", "calibrate.lv"],
  },
  {
    id: "calibrate.lv",
    summary: "Calibrate the Local-Vol surfaces only.",
    details: "Runs `POST /calibrate/lv`: one affine Local-Vol surface per ticker from the current quotes, no parametric refit, regardless of the LV toggle in Options. The stale-LV badge clears; the **Last** chip reads \"Calibrated local-vol\". Grid size and regularisers come from [Options ▸ Local Vol](help:settings:gridXNodes).",
    example: "You raised [gridXNodes](help:settings:gridXNodes) from 41 to 61: Local-Vol only refits the SPY surface without touching the twelve parametric smiles.",
    enabledWhen: "Live backend, workflow idle",
    guide: "localvol",
    related: ["calibrate.both", "calibrate.parametric", "lens.localvol"],
  },
  // -------------------------------------------------------------- Priors
  {
    id: "priors.saveVisible",
    summary: "Save the visible tab's fit as that node's prior.",
    details: "Posts the active tab's current fit as its prior (`POST /smiles/{ticker}/{expiry}/prior`). The dashed prior curve on the Smile chart refreshes to it, and the prior-anchor rows of the next calibration pull toward it (see [Options ▸ Prior](help:settings:priorPersistenceMode)). The **Last** chip reads \"Saved prior (visible tab)\".",
    example: "SPY 18-Dec-26 fits cleanly at 14:30. Save it as the prior; at 15:45 the wings of a thinner chain stay anchored to that shape.",
    enabledWhen: "Live backend, a tab is active",
    guide: "priors",
    related: ["priors.saveOpen", "priors.saveAll", "priors.fetch"],
  },
  {
    id: "priors.saveOpen",
    summary: "Save the fit of every open tab as its prior.",
    details: "Runs the per-node save for each open tab, one after another; a failure is counted, never fatal. The **Last** chip tallies \"Saved priors (3 tabs, 1 failed)\" and the charts' dashed priors refresh.",
    example: "Three SPY tabs open (18-Dec-26, 20-Mar-27, 19-Jun-26): one command snapshots the three fits you have been looking at, and nothing else.",
    enabledWhen: "Live backend, at least one tab open",
    guide: "priors",
    related: ["priors.saveVisible", "priors.saveAll"],
  },
  {
    id: "priors.saveAll",
    summary: "Save every calibrated fit in the universe as a prior.",
    details: "Runs `POST /priors/save-all`: every ticker's current calibration becomes its saved prior (persisted when the server has a store). The Priors ▾ face flashes \"Saved N ✓\"; the **Last** chip reads \"Saved priors (N nodes)\".",
    example: "End of day, twelve nodes publish-ready: Save priors — all calibrated. Tomorrow's first fetch can roll them forward automatically.",
    enabledWhen: "Live backend, workflow idle",
    guide: "priors",
    related: ["priors.fetch", "help:settings:autoRollPriorOnFetch"],
  },
  {
    id: "priors.fetch",
    summary: "Resolve and activate each ticker's prior along the freshness ladder.",
    details: "Runs `POST /priors/fetch`: for each ticker the freshest available prior is activated — the saved snapshot, else the 15-minutes-before-close fit, else the close fit. The Priors ▾ face flashes \"Activated N ✓\"; the **Last** chip reads \"Fetched priors (N active)\". Disabled until some prior has been saved.",
    example: "New session, empty fits: Fetch priors activates yesterday's saved SPY and NVDA surfaces so the first calibration starts anchored instead of cold.",
    enabledWhen: "Live backend, workflow idle",
    guide: "priors",
    related: ["priors.saveAll", "help:settings:autoLoadPrior"],
  },
];
