// Command reference — part 2 of 3 (HELP CENTER ARC, H2): the Lens · Layout ·
// Tabs · View commands of lib/commands.ts — the workbench chrome. One
// CommandDoc per registry id; `enabledWhen` mirrors the bind() gate in
// state/commands.tsx (most of these are always enabled and simply toggle
// state — the menu shows a ✓ / the palette a chip while they are active).
// Concatenated by commandDocs.ts.
import type { CommandDoc } from "./types";

export const COMMAND_DOCS_SHELL: CommandDoc[] = [
  // ---------------------------------------------------------------- Lens
  {
    id: "lens.graph",
    summary: "Switch to the Graph lens (Alt+1).",
    details: "Applies the Graph lens to the workspace: the smile universe as a network, observations propagated from lit nodes to dark ones. It is a universe-level lens — it renders without a tab and highlights the active tab's node in the canvas and the inspector. Double-click a node in the canvas to open its smile on the Parametric lens with the GRAPH overlay.",
    example: "Alt+1 with SPY 18-Dec-26 active: the canvas centres on SPY, the inspector shows the node's handles and the messages it receives from NVDA and AAPL.",
    guide: "graph",
    related: ["lens.parametric", "layout.nodesPane", "help:guides:graph"],
  },
  {
    id: "lens.forwards",
    summary: "Switch to the Forwards lens (Alt+2).",
    details: "Shows the active tab's ticker: the forward curve with dividend markers, the per-expiry ladder (parity, theoretical, manual, active, borrow) and the editor for the tab's expiry — forward mode, manual override, carry r / q, dividend schedule. An edit here refits every lens of that ticker.",
    example: "Alt+2 on AAPL 19-Jun-26: the ladder row 19-Jun-26 is highlighted; set the forward mode to Manual and type 231.40 — the Parametric smile of that node re-expresses its moneyness at once.",
    guide: "forwards",
    related: ["lens.parametric", "help:settings:dividendMode"],
  },
  {
    id: "lens.parametric",
    summary: "Switch to the Parametric lens (Alt+3).",
    details: "Shows the active tab's node under a parametric model (LQD / SVI-JW / MCS): NODE views Smile · Density · Compare · Table and TICKER views Term · Densities · Stacked IV · Surface, the layer rail (Target · Calib. quotes · Calib. fit · Weights) at the right of the chart, Y-center / Y-fit overlay buttons, the quote toolbar for select / exclude / amend, and the Spot move · Var-swap · Fit diagnostics cards.",
    example: "Alt+3 on SPY 18-Dec-26, click a wing quote and press Delete: it is excluded, the node turns stale, and Calibrate refits without it.",
    guide: "parametric",
    related: ["lens.localvol", "calibrate.parametric", "export.chartPng"],
  },
  {
    id: "lens.localvol",
    summary: "Switch to the Local Vol lens (Alt+4).",
    details: "Shows the active tab's ticker under the direct Local-Vol surface fit: Smile and Table for the tab's expiry; Term · Densities · Stacked IV · LV surface (3D mesh or heat map) · IV surface for the ladder; the fit-diagnostics card with the per-expiry table and the ⏵ replay of the solver's accepted steps. The lens icon is gated by [localVolEnabled](help:settings:localVolEnabled).",
    example: "Alt+4 on NVDA 20-Mar-27, LV surface view: drag to rotate, Shift+drag to pan, hover to read the crosshair badge \"T 0.55y · k −0.20 · 41.2%\".",
    guide: "localvol",
    related: ["calibrate.lv", "lens.parametric"],
  },
  {
    id: "lens.quality",
    summary: "Switch to the Quality lens (Alt+5).",
    details: "The universe fit-quality dashboard: eight headline tiles, the active node's certificate card, the per-ticker rollup (with LV surface health), and the per-node exception table with a sort selector and an \"exceptions only\" filter. Rows open the node's tab (click = preview, double-click = pin). Exports (JSON / CSV / HTML report) sit in the header. Nothing here refits.",
    example: "Alt+5 after a refit: the \"Publish-ready\" tile reads 11/12 and the table's first row, sorted by exceptions, names NVDA 20-Mar-27 with a calendar flag.",
    guide: "quality",
    related: ["export.report", "export.surfacesJson", "lens.graph"],
  },
  // -------------------------------------------------------------- Layout
  {
    id: "layout.nodesPane",
    summary: "Show or hide the Nodes pane (Ctrl+B).",
    details: "Toggles the universe tree at the left. Showing it also moves keyboard focus into the tree, so Ctrl+B then ↑/↓/Enter opens a node without the mouse; Tab jumps to the filter box. The pane is resizable by its edge; its width is part of the layout.",
    example: "Ctrl+B, type `nv` to jump to NVDA, → to expand it, ↓ to 20-Mar-27, Enter: the node opens as a preview tab.",
    guide: "workbench",
    related: ["layout.zen", "layout.reset", "tab.quickOpen"],
  },
  {
    id: "layout.aside",
    summary: "Show or hide the diagnostics aside.",
    details: "Toggles the right-hand column of the lenses — the Spot move · Var-swap · Fit diagnostics cards on Parametric and Local Vol, the inspector on Graph. In split editors the non-focused groups yield their aside to save room.",
    example: "Hide the aside on a laptop screen to give the SPY 18-Dec-26 smile the full width; the fit RMS stays readable in the status bar.",
    guide: "workbench",
    related: ["layout.zen", "layout.statusBar"],
  },
  {
    id: "layout.statusBar",
    summary: "Show or hide the status bar.",
    details: "Toggles the bottom bar: engine narration and gauge, lens · node, nodes lit / stale, next auto-fetch, as-of, source light, quote age, the **Last** action chip and the clock. Hiding it hides the narration too — the top-bar buttons keep their working cue.",
    example: "Turn it off for a screenshot of the Stacked IV chart; turn it back on before the next fetch to watch the gauge.",
    guide: "workbench",
    related: ["layout.zen", "layout.reset"],
  },
  {
    id: "layout.zen",
    summary: "Zen mode: charts only.",
    details: "Hides the Nodes pane, the diagnostics aside and the status bar in one step; running it again restores all three. The menu row shows ✓ while all three are hidden.",
    example: "Zen mode on the Local Vol lens, IV surface view of SPY: nothing on screen but the mesh and the tab strip.",
    guide: "workbench",
    related: ["layout.nodesPane", "layout.aside", "layout.statusBar"],
  },
  {
    id: "layout.rememberView",
    summary: "Remember the view per tab (on) or per lens (off).",
    details: "On (default): each tab keeps its own Parametric / Local Vol view — sub-view, axis unit, layers, density kind, compare chips — restored when you come back to it; a new tab inherits the current tab's view. Off: one view per lens, shared by every tab, so switching nodes keeps the same chart for comparison.",
    example: "Leave SPY 18-Dec-26 on Density and NVDA 20-Mar-27 on Table; Alt+← / Alt+→ between them brings each back as you left it.",
    guide: "workbench",
    related: ["tab.next", "layout.reset"],
  },
  {
    id: "layout.reset",
    summary: "Reset panes and widths to the default layout.",
    details: "Restores the default layout: Nodes pane shown at one fifth of the window, aside and status bar shown, per-tab view memory on. Tabs, fits and Options are untouched.",
    example: "After dragging the Nodes pane to a sliver and hiding the aside, Reset layout brings the standard workbench back.",
    guide: "workbench",
    related: ["layout.zen", "view.reset"],
  },
  // ---------------------------------------------------------------- Tabs
  {
    id: "tab.closeAll",
    summary: "Close every node tab in every group.",
    details: "Closes all tabs; editor groups fold back to one. Nothing is deleted — the nodes stay in the universe with their fits, and Ctrl+P or the Nodes pane reopens any of them.",
    example: "Twelve tabs after a comparison sweep: Close all tabs, then Ctrl+P `spy dec` to start again from SPY 18-Dec-26.",
    enabledWhen: "At least one tab open",
    guide: "workbench",
    related: ["tab.close", "tab.quickOpen"],
  },
  {
    id: "tab.close",
    summary: "Close the active tab (Alt+W).",
    details: "Closes the focused group's active tab; the group activates its neighbour. Closing the last tab of a split group unsplits. Middle-click a tab or its × does the same.",
    example: "Done with AAPL 19-Jun-26: Alt+W. The group returns to SPY 18-Dec-26.",
    enabledWhen: "A tab is active",
    guide: "workbench",
    related: ["tab.closeAll", "tab.next"],
  },
  {
    id: "tab.next",
    summary: "Activate the next tab (Alt+→).",
    details: "Cycles forward through the focused group's tabs and wraps around. The smile session follows the active tab, so every lens re-renders for the new node.",
    example: "Three SPY expiries open on the Term view: Alt+→ walks 18-Dec-26 → 20-Mar-27 → 19-Jun-26 → back.",
    enabledWhen: "More than one tab in the group",
    guide: "workbench",
    related: ["tab.prev", "layout.rememberView"],
  },
  {
    id: "tab.prev",
    summary: "Activate the previous tab (Alt+←).",
    details: "Cycles backward through the focused group's tabs and wraps around.",
    example: "Alt+← from the first tab lands on the last one.",
    enabledWhen: "More than one tab in the group",
    guide: "workbench",
    related: ["tab.next"],
  },
  {
    id: "tab.quickOpen",
    summary: "Quick open a node by fuzzy search (Ctrl+P).",
    details: "Opens the palette in node mode: type part of a ticker and expiry (formatted or ISO) — `spy dec`, `nvda 27` — and Enter opens the node as a preview tab, Shift+Enter as a pinned tab. Rows show the lit / dark dot and the quality glyph. Type `>` to switch the same box to commands.",
    example: "Ctrl+P `aapl jun` Enter opens AAPL 19-Jun-26 as an italic preview tab; double-click the tab to pin it.",
    guide: "workbench",
    related: ["help.palette", "layout.nodesPane"],
  },
  {
    id: "tab.split",
    summary: "Split the editor, or fold the groups back (Ctrl+\\).",
    details: "Adds an editor group after the focused one — two, then three side by side — and at three folds everything back into one group (tabs are kept). Each group has its own tab strip, active tab and, for the side groups, its own lens (Parametric left, Local Vol right, for instance). Dragging a tab or a node onto the right 20 % of the pane splits too. The row shows ✓ while more than one group exists.",
    example: "SPY 18-Dec-26 active, Ctrl+\\, then Ctrl+Enter on NVDA 20-Mar-27 in the Nodes pane: the two smiles sit side by side.",
    guide: "workbench",
    related: ["tab.splitDown", "tab.moveToOther", "tab.focusOther"],
  },
  {
    id: "tab.splitDown",
    summary: "Split the editor down: two groups stacked (Ctrl+Shift+\\).",
    details: "From a single group, opens a second group below it. Dragging onto the bottom 20 % of the pane does the same. Only meaningful from one group; with two or more groups already open the row is disabled.",
    example: "Term chart of SPY on top, its Stacked IV below: Ctrl+Shift+\\, move the tab down, set each group's view.",
    enabledWhen: "A single editor group",
    guide: "workbench",
    related: ["tab.split", "tab.moveToOther"],
  },
  {
    id: "tab.moveToOther",
    summary: "Move the active tab to the next editor group.",
    details: "Moves the focused group's active tab into the next group (cyclic). From a single group it splits first and moves the tab across. The tab's context menu offers the same as \"Move to group 1 / 2 / 3\".",
    example: "Two groups, AAPL 19-Jun-26 active on the left: Move to the next group puts it beside SPY on the right.",
    enabledWhen: "A tab is active",
    guide: "workbench",
    related: ["tab.split", "tab.focusOther"],
  },
  {
    id: "tab.focusOther",
    summary: "Focus the next editor group.",
    details: "Moves keyboard focus and the smile session to the next group (cyclic). The focused group is the one Alt+W, Alt+←/→ and the Priors ▾ \"visible tab\" act on; the other groups keep showing their own nodes.",
    example: "Left group SPY, right group NVDA: Focus the next group, then Alt+→ cycles the NVDA group's tabs.",
    enabledWhen: "More than one editor group",
    guide: "workbench",
    related: ["tab.split", "tab.moveToOther"],
  },
  // ---------------------------------------------------------------- View
  {
    id: "view.scheme:dark",
    summary: "Colour scheme: Dark (the default).",
    details: "Applies the dark palette at once (live preview). The change is unsaved until **Save the look as default**; a reload returns to the saved scheme. The row shows ✓ for the current scheme.",
    example: "Back from High contrast to Dark for the evening session.",
    guide: "workbench",
    related: ["view.scheme:light", "view.scheme:contrast", "view.scheme:warm", "view.saveDefault"],
  },
  {
    id: "view.scheme:light",
    summary: "Colour scheme: Light.",
    details: "Applies the light palette (live preview, unsaved until **Save the look as default**). Chart exports follow the scheme — a PNG exported under Light has a light background.",
    example: "Switch to Light before exporting the SPY smile for a printed report.",
    guide: "workbench",
    related: ["view.scheme:dark", "view.saveDefault", "export.chartPng"],
  },
  {
    id: "view.scheme:contrast",
    summary: "Colour scheme: High contrast.",
    details: "Near-black background with maximal legibility — for projectors and bright rooms. Live preview; unsaved until **Save the look as default**.",
    example: "Trading-floor screen in daylight: High contrast, then Save the look as default so it survives reloads.",
    guide: "workbench",
    related: ["view.scheme:dark", "view.saveDefault"],
  },
  {
    id: "view.scheme:warm",
    summary: "Colour scheme: Warm.",
    details: "A warm-tinted dark palette. Live preview; unsaved until **Save the look as default**. The View ▾ popover also has contrast and brightness sliders that stack on any scheme.",
    example: "Warm plus brightness 0.9 for late sessions; save it as default.",
    guide: "workbench",
    related: ["view.scheme:dark", "view.saveDefault"],
  },
  {
    id: "view.expiryFormat:cycle",
    summary: "Cycle the expiry label format.",
    details: "Advances the expiry format used everywhere (tabs, nodes pane, tables, status bar): `dd-mmm-yy` → `(dd)mmmyy` → `x.xxY` → `xx.xM` → `yyM zD` → back. Unsaved until **Save the look as default**.",
    example: "Two cycles turn the tab \"SPY 18-Dec-26\" into \"SPY 0.30Y\" — handy when comparing tenors across tickers.",
    guide: "workbench",
    related: ["view.saveDefault", "view.reset"],
  },
  {
    id: "view.saveDefault",
    summary: "Save the current look as this device's default.",
    details: "Persists the colour scheme, contrast, brightness and the expiry format so a reload restores them. Enabled only while something differs from the saved default (the View ▾ Save bar shows the same state).",
    example: "High contrast + `x.xxY` expiries: Save the look as default. Tomorrow's session opens the same way.",
    enabledWhen: "The look or the expiry format differs from the saved default",
    guide: "workbench",
    related: ["view.reset", "view.expiryFormat:cycle"],
  },
  {
    id: "view.reset",
    summary: "Reset the look to the built-in defaults.",
    details: "Returns the colour scheme to Dark and contrast / brightness to 1 (live, unsaved). The expiry format is not part of this reset — cycle it back or save. Layout panes are a separate command.",
    example: "Experimented with Warm at brightness 1.3: Reset the look, then Save the look as default to make Dark the saved state again.",
    guide: "workbench",
    related: ["view.saveDefault", "layout.reset"],
  },
];
