// Command reference — part 3 of 3 (HELP CENTER ARC, H2): the Help / dialog
// commands (the existing rows plus the Help Center rows added by H1) and the
// four DYNAMIC prefixes of lib/commands.ts (saved universes, server
// workspaces, recent files — rows generated at runtime, documented once per
// prefix). Concatenated by commandDocs.ts.
import type { CommandDoc } from "./types";

export const COMMAND_DOCS_HELP: CommandDoc[] = [
  // ------------------------------------------------------------- Dialogs
  {
    id: "options.open",
    summary: "Open the Options dialog (Ctrl+,).",
    details: "Opens the settings dialog with its section rail — Parametric · Local Vol · Calibration · Prior · Kalman filter · Events · Graph · Workflow · Dynamics — and the Apply / Save default / Reset bar. A field that affects fits marks the affected nodes stale when applied; workflow gates and display fields never do. The [Settings reference](help:settings) documents every field with its default, range and effect.",
    example: "Ctrl+, ▸ Calibration ▸ set the [haircut](help:settings:haircut) to 25 % ▸ Apply. Every lit node turns stale; Calibrate refits to the narrower band.",
    guide: "options",
    related: ["help.settings", "calibrate.both", "file.new"],
  },
  {
    id: "help.shortcuts",
    summary: "Open the Keyboard shortcuts page (Ctrl+/).",
    details: "Opens the Help Center on the Shortcuts page: the full chord table — workbench, nodes tree, smile editing, charts, graph canvas — searchable. The table is rendered from the same list the key handler reads, so what is listed is what fires.",
    example: "Ctrl+/ then type `split` to find Ctrl+\\ and Ctrl+Shift+\\.",
    guide: "workbench",
    related: ["help.palette", "help.commands"],
  },
  {
    id: "help.api",
    summary: "Open the backend's OpenAPI reference in a new tab.",
    details: "Opens `<backend>/docs` — the interactive OpenAPI page of the running server: every endpoint the UI calls (fetch, calibrate, smiles, graph, export, workspace, help…) with schemas and a Try-it button. Needs the backend to be reachable.",
    example: "Look up `POST /calibrate/parametric` to script the fast loop from a notebook.",
    guide: "getting-started",
    related: ["help.about", "help.copyDiagnostics"],
  },
  {
    id: "help.report",
    summary: "Open the HTML quality report in a new tab.",
    details: "Same document as **Export ▸ Export quality report**: the client-facing readiness report built from the cached calibrations (`GET /export/report`). Never refits.",
    example: "Open it after the afternoon calibration to see which nodes are publish-ready and which blockers remain.",
    enabledWhen: "Live backend",
    guide: "quality",
    related: ["export.report", "lens.quality"],
  },
  {
    id: "help.about",
    summary: "Open the About dialog with build and connection info.",
    details: "Shows the product statement, the app version and build mode, the backend URL and its connection state, the active data source — and a **Copy diagnostics** button that puts the same bundle on the clipboard for a support request.",
    example: "Help ▸ About VolFit ▸ Copy diagnostics, then paste into the ticket.",
    guide: "getting-started",
    related: ["help.copyDiagnostics", "help.whatsNew"],
  },
  {
    id: "help.palette",
    summary: "Open the command palette (Ctrl+K).",
    details: "Opens the palette in command mode: every menu row and verb of the registry — file, universe, fetch, calibrate, priors, lenses, layout, tabs, view, help — fuzzy-searchable; Enter runs the highlighted one, disabled rows are greyed. A command with an argument turns the box into its prompt. Ctrl+Shift+P and typing `>` in Ctrl+P do the same.",
    example: "Ctrl+K `lv only` Enter runs Calibrate — Local-Vol only without opening the top-bar menu.",
    guide: "workbench",
    related: ["tab.quickOpen", "help.commands", "help.shortcuts"],
  },
  // --------------------------------------------------------- Help Center
  {
    id: "help.welcome",
    summary: "Open the Help Center on the Welcome page.",
    details: "The landing page: the product statement, the four-step workflow (universe → fetch → calibrate → graph / publish), the tip of the day and links to every other page. It opens once by itself on a first run.",
    example: "New desk member: Help ▸ Welcome, then the Walkthrough link at the bottom of the page.",
    guide: "getting-started",
    related: ["help.walkthrough", "help.tips", "help.open"],
  },
  {
    id: "help.walkthrough",
    summary: "Start the spotlight Walkthrough of the shell.",
    details: "Draws a 12-step tour over the live workbench — brand, File, Options, Universe, the Fetch / Calibrate / Priors cluster, activity bar, Nodes pane, tabs, the workspace, View / Layout, status bar, Help — with Next / Back / Skip. Progress is kept, so a closed tour resumes where it stopped. Some steps offer a safe Try-it action. It ends on the Help menu.",
    example: "Start the tour; at the \"Fetch · Calibrate · Priors\" step press *Try it: fetch a snapshot* and watch the status bar narrate the pull.",
    guide: "getting-started",
    related: ["help.welcome", "help.context"],
  },
  {
    id: "help.context",
    summary: "Help for this view (F1).",
    details: "Opens the guide of what you are looking at: the active lens — Graph, Forwards, Parametric, Local Vol or Quality — or the open dialog (Options → the options guide, Manage universe → the universe guide). Browser F1 is intercepted.",
    example: "On the Local Vol lens wondering what the ⏵ button does: F1 opens the Local Vol guide at its replay section.",
    guide: "getting-started",
    related: ["help.open", "help.walkthrough"],
  },
  {
    id: "help.docs",
    summary: "Open the Documentation page.",
    details: "An in-app browser of the shipped documentation: the technical notes in Markdown (rendered in the dialog), the PDFs of the notes, the book and the LQD paper, and the handoff pack. Requires the backend; an install without the `Docs/` folder lists only what it has.",
    example: "Open Note 14 (graph messages) next to the Graph lens to read what a precision message is while inspecting one.",
    guide: "getting-started",
    related: ["help.glossary", "help.ask"],
  },
  {
    id: "help.commands",
    summary: "Open the Command reference page.",
    details: "This list: every registry command with what it does, when it is enabled, an example and a **Run** button, searchable and grouped by category. The dynamic rows (saved universes, server workspaces, recent files) are documented once per family.",
    example: "Search `prior` to see the four Priors ▾ verbs side by side and run \"Save priors — all calibrated\" from the page.",
    guide: "getting-started",
    related: ["help.palette", "help.settings", "help.shortcuts"],
  },
  {
    id: "help.settings",
    summary: "Open the Settings reference page.",
    details: "Every Fit / Options / Market field with its type, default, range, unit, when it is read, which cache it invalidates, an explanation, an example and an **Open in Options** button. Machine facts come from the generated schema; the page also shows the running server's defaults when they differ from the bundled ones.",
    example: "Look up [gridXNodes](help:settings:gridXNodes) to see that it only re-keys the Local-Vol fit and never invalidates the parametric smiles.",
    guide: "options",
    related: ["options.open", "help.open"],
  },
  {
    id: "help.glossary",
    summary: "Open the Glossary page.",
    details: "The vocabulary — smile, slice, node, [lit / dark](help:glossary:lit-dark), handle, prior, fit target, haircut, ζ … — with short and long definitions, cross-links and pointers into the notes.",
    example: "Read \"lit / dark\" to understand why a dark node draws a dashed smile.",
    guide: "getting-started",
    related: ["help.docs", "help.ask"],
  },
  {
    id: "help.tips",
    summary: "Open the Tips & tricks page.",
    details: "Curated tips per lens and for the shell, basic and pro, most with a **Try it** button that runs the related command. The Welcome page shows one of them as the tip of the day.",
    example: "Filter the tips to the Parametric lens and try \"Alt+wheel zooms the y-axis only\".",
    guide: "getting-started",
    related: ["help.welcome", "help.shortcuts"],
  },
  {
    id: "help.ask",
    summary: "Ask @Vol-Fitter a question (Ctrl+Shift+/).",
    details: "A question box answered from the help corpus — commands, settings, glossary, tips, guides, document abstracts. The local retrieval tier is always available and instant, and answers as ranked cards with actions (run the command, open the setting, open the doc). When the server is configured with an Anthropic key, Claude answers as well, grounded on those cards. The answer says which tier replied. The browser never sees a key.",
    example: "Ask \"why is my node stale after changing the haircut\" — the cards point to the haircut setting, the stale glossary entry and the Calibrate command.",
    guide: "getting-started",
    related: ["help.docs", "help.commands", "help.settings"],
  },
  {
    id: "help.whatsNew",
    summary: "Open What's new (release notes).",
    details: "Release notes in plain language, newest first — what changed in the shell, the fits, the data sources and the help.",
    example: "Check what the last update did to the Fetch menu before the morning pull.",
    guide: "getting-started",
    related: ["help.about"],
  },
  {
    id: "help.open",
    summary: "Open any Help Center page or entry by deep link.",
    details: "Takes an argument `page[:anchor]` — the palette prompts for it. Pages: welcome, guides, commands, settings, shortcuts, glossary, tips, docs, ask, whatsnew. Examples of anchors: `settings:gridXNodes`, `guides:graph`, `commands:calibrate.both`, `glossary:lit-dark`, `docs:14_graph_messages`. The same grammar drives the `help:` links inside help text.",
    example: "Ctrl+K ▸ \"help.open\" ▸ type `settings:haircut` ▸ Enter — or use this link: [Open the haircut setting](cmd:help.open?settings:haircut).",
    guide: "getting-started",
    related: ["help.commands", "help.settings", "help.glossary"],
  },
  {
    id: "help.copyDiagnostics",
    summary: "Copy a diagnostics bundle to the clipboard.",
    details: "Copies one text block for a support request: app version and build mode, backend URL and connection state, the active data source, the as-of, the fit and options settings versions, the active lens and node, the browser user agent, and the last action and last error from the status bar. No quotes, no fits, no keys. The **Last** chip reads \"Copied diagnostics\".",
    example: "A calibration fails twice on NVDA 20-Mar-27: Copy diagnostics, paste it into the ticket with the error text.",
    guide: "getting-started",
    related: ["help.about", "help.api"],
  },
  // ---------------------------------------------------- Dynamic prefixes
  {
    id: "universe.load:",
    summary: "Load a saved universe by name (one row per saved name).",
    details: "Rows generated from the universe store: `Load universe: <name>` replaces the active ticker set and expiry selection with the saved one and refetches its chains — minutes rather than seconds on a large set. Tabs of nodes that leave the universe close; the nodes pane rebuilds. Listed under **Universe ▾ Load saved universe** and in Ctrl+K.",
    example: "Ctrl+K `load us-tech` Enter: SPY, NVDA, AAPL and MSFT return with their saved expiries; the status bar narrates the fetch.",
    enabledWhen: "Live backend, no universe operation in flight",
    guide: "universe",
    related: ["universe.saveAs", "universe.manage"],
  },
  {
    id: "file.openServer:",
    summary: "Open a workspace stored on the server (one row per name).",
    details: "Rows generated from the named workspace store: `Open workspace from server: <name>` restores that configuration (same effect as opening the file) and makes it the Save target, so Ctrl+S re-posts under that name. The row of the current target shows ✓. Listed under **File ▸ Open from server**.",
    example: "Open `morning-desk` from a second machine: tabs, Options and layout match the first one.",
    enabledWhen: "Live backend with a workspace store (VOLFIT_DB), no file operation in flight",
    guide: "files",
    related: ["file.saveToServer", "file.deleteServer:", "file.recent:"],
  },
  {
    id: "file.deleteServer:",
    summary: "Delete a workspace stored on the server (one row per name).",
    details: "Removes the named workspace from the store (`DELETE /workspaces/{name}`). In the File menu it is the trash icon that appears when hovering a server row; in Ctrl+K it is a plain row. The **Last** chip reads \"Deleted workspace\". Nothing on disk or in the fits changes.",
    example: "Delete `spy_wings_experiment` once the experiment is folded into `morning-desk`.",
    enabledWhen: "Live backend, no file operation in flight",
    guide: "files",
    related: ["file.openServer:", "file.saveToServer"],
  },
  {
    id: "file.recent:",
    summary: "Reopen a recent workspace (one row per recent entry, last 8).",
    details: "Rows `Open recent: <name>` for the last eight workspaces saved or opened. A server entry reopens from the store; a file entry reopens through the stored file handle in Chromium (a permission prompt may appear) and falls back to the file picker in other browsers. Listed under **File ▸ Recent**.",
    example: "File ▸ Recent ▸ `desk_2026-08-28` (file) in Edge: one permission click and the workspace is back.",
    enabledWhen: "Live backend, no file operation in flight",
    guide: "files",
    related: ["file.open", "file.openServer:"],
  },
];
