// Glossary (HELP CENTER ARC, H1): the vocabulary of the desk and of the app,
// one entry per term, alphabetical by term (the Greek ζ closes the list).
// `short` is one sentence; `long` is Markdown — define the term, say why it
// matters on the desk, and name where it shows in the app. `related` are
// glossary ids; `links` are docsCatalog ids and help: deep links. Source of
// the definitions: Docs/handoff/notes/00_system_overview.md (the vocabulary
// paragraph and the invariants) and the notes each entry links.
import type { GlossaryEntry } from "./types";

export const GLOSSARY: GlossaryEntry[] = [
  { id: "as-of", term: "As-of",
    short: "The market timestamp the app is pricing from: Live, Previous close, or a historical day and moment.",
    long: "The as-of selector sits in the **Fetch ▾** menu (Live · Prev close · Historical: pick a day, then Close / Latest snapshot / n min before close). Every fetch, fit and view is served at that moment, and the status bar's *As of* chip and the market pill repeat it. A node whose chain was stamped in another session shows an amber **≠ as-of** pill in the Nodes pane; with `asOfMismatchGate` on, that mismatch fails readiness and blocks publish.",
    related: ["data-age", "data-source", "stale-node"], links: ["help:guides:data-sources", "help:settings:asOfMismatchGate"] },
  { id: "belly-certificate", term: "Belly butterfly certificate (Durrleman g)",
    short: "A dense-grid check that the displayed slice's implied density is non-negative across its traded range: Durrleman g ≥ −1e−4 on 801 points.",
    long: "Wing screens fence the tails; the *belly* — the curvature near the money — needs its own certificate. Every displayed slice, whatever its model, is checked on an 801-point grid from the model's own derivatives (a few dozen microseconds). An uncertified slice cannot become a mark: it fails readiness and the publish export blocks on it. The Quality lens shows the minimum g and its strike in the **Belly g** column (rose = uncertified, `·R` = a certified one-shot repair refit).",
    related: ["butterfly-arbitrage", "publish-gate", "svi-jw"], links: ["02_svi_jw", "02_svi_jw_moments", "help:settings:bellyRepair", "help:guides:quality"] },
  { id: "butterfly-arbitrage", term: "Butterfly arbitrage",
    short: "A static arbitrage inside one expiry: a smile whose implied risk-neutral density goes negative somewhere.",
    long: "Call prices must be convex in strike; where they are not, a butterfly spread has negative value and the implied density is negative. LQD and the LV surface are butterfly-free by construction; SVI and MCS are fenced by penalties and then certified at the gate. The **Density** and **Densities** views draw the density (≥ 0 everywhere is the test); SVI/MCS dips draw signed in red.",
    related: ["belly-certificate", "calendar-arbitrage", "density-quantile", "lqd"], links: ["01_lqd_model", "09_wings_lee_bounds", "help:guides:parametric"] },
  { id: "calendar-arbitrage", term: "Calendar arbitrage",
    short: "A static arbitrage across expiries: total variance w(k,T) decreasing in T at some fixed log-moneyness k.",
    long: "For forward-normalized slices, no calendar arbitrage means the stacked total-variance curves never cross: w(k, T_next) ≥ w(k, T) at every k. Stacked *vol* smiles carry no such content (clean surfaces cross freely in vol), so the app's **Stacked IV** view draws w = σ²T. Calibrate couples expiries in ascending T (`enforceCalendar`, the `symmetric` solver screens and jointly repairs violating runs); the Quality **Cal viol** column reports the sampled violation and the exact full-line ledger gap.",
    related: ["total-variance", "butterfly-arbitrage", "generalized-tails"], links: ["10_calendar_arbitrage", "10_calendar_unnamed_martingale", "help:settings:enforceCalendar", "help:settings:surfaceSolver"] },
  { id: "carry-borrow-dividends", term: "Carry, borrow and dividends",
    short: "The inputs that turn spot into a forward: rate, dividend yield or discrete dividends, and the implied borrow read from parity.",
    long: "Carry is resolved before any per-quote work because everything downstream consumes the forward. The Forwards lens shows the parity, theoretical and active forward per expiry, the implied **Borrow** in bp, and the dividend-schedule editor (continuous · discrete absolute · discrete proportional · mixed with a switch horizon). `jointCarry` opt-in runs a joint borrow / de-Am fixed point per expiry above a bp gate. Editing one name's carry bumps that ticker's version only.",
    related: ["forward", "de-americanization"], links: ["06_forwards_dividends", "06_forwards_dividends_inference", "help:guides:forwards", "help:settings:jointCarry"] },
  { id: "command-palette", term: "Command palette",
    short: "Ctrl+K: every menu row, verb, lens, layout toggle and dialog as a fuzzy-searchable list.",
    long: "The palette and the menus render the same command registry, so nothing in one can drift from the other. Ctrl+P is *quick open* over the nodes (Enter = preview tab, Shift+Enter = pinned); typing `>` switches to commands. A command that takes an argument (Save to server…, Save universe as…) turns the box into its prompt. Legacy verbs (Fetch spots only, Fetch option quotes only) live only here.",
    related: ["tab", "lens", "workspace-file"], links: ["help:guides:workbench", "help:commands", "cmd:help.palette"] },
  { id: "data-age", term: "Data age",
    short: "The age of the loaded live quotes — worst chain across the universe — with an amber and a red threshold.",
    long: "Live quotes older than `dataAgeAmberMin` (20 min by default) turn the market pill and the status bar's *Quotes* chip amber; past `dataAgeRedMin` (120 min) a node is *red-stale*, fails readiness (`stale data (… old)`) and blocks publish. Data age is null for a historical as-of, a synthetic source or nothing fetched. The Quality node card shows it per node under **Data age**.",
    related: ["as-of", "stale-node", "publish-gate"], links: ["help:settings:dataAgeAmberMin", "help:settings:dataAgeRedMin", "help:guides:quality"] },
  { id: "data-source", term: "Data source",
    short: "The market feed the whole universe fetches from: Yahoo, Bloomberg, Massive, an exchange's delayed book, Synthetic, or a snapshot File.",
    long: "The backend runs one *active* source; the **Data sources** card of the Manage-universe dialog (and the TopBar selector) switches it, with a green / amber / red light per source. Yahoo yields a usable mid only; the exchanges' delayed books (Cboe, Nasdaq, ASX, HKEX, SGX, Eurex) carry the full bid/ask; Massive is OPRA intraday plus flat-file history; Bloomberg needs the Terminal and an entitlement; Synthetic is a deterministic test universe; **File** is the source a snapshot file registers when opened. The active source is a *default*: a ticker can be **pinned** to another registered source on its row of the Manage-universe dialog and then fetches, streams and captures from there (the Nodes pane shows a source pill on it).",
    related: ["as-of", "snapshot-file", "universe"], links: ["help:guides:data-sources", "docs_exchange_delayed", "docs_bloomberg_setup"] },
  { id: "de-americanization", term: "De-Americanization (CRR)",
    short: "Converting an American option quote to its European-equivalent implied vol by inverting a Cox-Ross-Rubinstein tree.",
    long: "Listed equity options are American, and every smile model prices terminal expectations. Each kept quote is de-Americanized by bisection through a CRR tree (batch depth 192, Numba kernel for wide chains, content-digest cache so fit tuning never re-runs it). The early-exercise premium is largest for deep ITM puts under positive rates and calls near dividends — which is one reason the OTM side is selected first. Runs on the calendar clock, always.",
    related: ["forward", "carry-borrow-dividends"], links: ["05_deamericanization", "05_deamericanization_stopping", "help:settings:jointCarry"] },
  { id: "density-quantile", term: "Density, quantile function and log Q-density",
    short: "Three faces of one risk-neutral law: the pdf, its inverse CDF Q(u), and ℓ(u) = log Q′(u), the LQD backbone.",
    long: "A smile is a probability law seen through the Black formula. The **Density** view of the Parametric lens shows the pdf, the **Log Q-density** sub-view shows ℓ(u) — the object LQD parametrizes (two universal boundary terms plus a Legendre expansion) — and **CDF** the distribution function. Positivity of the density is the butterfly test; the quantile-density chart is where LQD's tails and shoulders read most directly.",
    related: ["lqd", "butterfly-arbitrage", "smile"], links: ["01_lqd_model_lecture", "01_lqd_model_percentile_ruler", "help:guides:parametric"] },
  { id: "dupire-pde", term: "Dupire PDE",
    short: "The forward equation in (T, K) that prices every vanilla from a local-variance surface in one march.",
    long: "The app reads Dupire as a *pricing map*, not as a formula to differentiate noisy data with: given the piecewise-affine local variance, a fully implicit march (M-matrix step, discrete maximum principle at any step size) prices the whole grid, and the fit adjusts the nodal variances until the priced smiles match the quotes. The `timeScheme` (implicit, Rannacher opt-in) and the Numba `lvFastKernel` govern the march.",
    related: ["local-volatility", "var-swap"], links: ["04_local_volatility", "04_local_volatility_forward", "help:settings:timeScheme"] },
  { id: "editor-group", term: "Editor group / split",
    short: "One to three side-by-side (or stacked) tab strips, each rendering the lens for its own active node.",
    long: "Ctrl+\\ adds a group after the focused one (at three, folds back to one); Ctrl+Shift+\\ splits down from a single group; dragging a tab or a Nodes-pane row onto the right 20 % (or bottom 20 %) of the main pane does the same. The focused group's active tab is the session selection; the other groups fetch their own node, so two expiries can be compared under two lenses at once. Ctrl+Enter in the Nodes tree opens the focused row in the next group.",
    related: ["tab", "lens", "zen-mode"], links: ["help:guides:workbench", "help:shortcuts", "cmd:tab.split"] },
  { id: "event-clock", term: "Event variance clock (event-dilated time)",
    short: "A second time axis τ in which a scheduled event counts as several extra equivalent days of variance.",
    long: "Total variance w is a property of the price; the clock that annualizes it is a choice. Under the event clock an earnings day adds N_e extra equivalent days, so at fixed price the *working* IV √(w/τ) drops while the market IV and the price are untouched — the vol crush becomes a reading error. Fits live on τ when `eventsEnabled` is on; the **Term** views offer a Real time / Event-dilated toggle. Events are per-ticker market state, edited in the Options ▸ Events card.",
    related: ["intraday-clock", "total-variance"], links: ["11_event_variance_clock", "11_event_market_clock", "help:settings:eventsEnabled", "help:settings:normalizeEvents"] },
  { id: "extrapolated-region-arb", term: "Extrapolated-region arbitrage",
    short: "Butterfly and calendar measurements taken beyond the last quote, where no fit error reports and the var-swap still integrates.",
    long: "On a live SPY surface about half the drawn strike range lies past the quoted board. The app always *measures* the worst Durrleman g and the calendar crossing (in bp) over the time-value envelope there — the Quality **Extrap g · cal** column, advisory — and, with `extrapEnforce` on, adds tapered hinges so SVI/MCS overlays and the LQD tail contract stay clean out there too. `—` means the envelope is worthless past the quoted range.",
    related: ["lee-bound", "generalized-tails", "calendar-arbitrage"], links: ["09_wings_last_quote", "help:settings:extrapEnforce", "help:guides:quality"] },
  { id: "fit-target", term: "Fit target (mid / bid-ask / haircut)",
    short: "What a residual is measured against: the mid, the whole bid-ask band (zero inside), or the band shrunk by a haircut.",
    long: "`fitMode` picks it for every model. *mid* fits the mid quote; *bidask* counts zero error anywhere inside the band; *haircut* shrinks the band by a fixed vol amount first, with a small `midAnchorWeight` pull toward the mid so the solution stays identified. The Parametric **Target** layer draws the active target on the chart; RMS figures everywhere are computed against it, so a band fit's RMS is legitimately smaller than a mid fit's.",
    related: ["haircut-band", "weight-scheme", "robust-loss", "tick-floor"], links: ["07_calibration_objective", "07_calibration_objective_measure", "help:settings:fitMode", "help:settings:haircut"] },
  { id: "forward", term: "Forward / parity forward",
    short: "F_T, the price everything is normalized by; read from the chain by a put-call parity regression C − P = D (F − K).",
    long: "Least squares identifies the line's *level* (the forward) superbly and its *slope* (the discount) poorly, so production keeps the price level and clamps the rate — a wrong forward gaps the whole smile at the money. The Forwards lens shows **Parity**, **Theo** (carry model) and **Manual** candidates and the **Active** one per expiry. Chains a delayed feed synthesized at zero carry are pinned to F = spot, D = 1 instead of regressed.",
    related: ["carry-borrow-dividends", "log-moneyness", "de-americanization"], links: ["06_forwards_dividends", "06_forwards_dividends_inference", "help:guides:forwards"] },
  { id: "functional-band", term: "Functional band",
    short: "The graph's full three-handle posterior covariance pushed through the slice map into a smile band, a var-swap sd and tail-mass sds.",
    long: "Three posterior sds do not make a smile band; the functional band propagates the joint covariance of (σ0, s0, κ0) through the retargeted slice so the shaded band on a reconstructed smile is the marginal of the curve itself. It is band-only — the posterior mean is untouched. The **GRAPH** badge on a drilled-in smile shows the posterior var-swap ± 1σ from it.",
    related: ["graph-extrapolation", "retargeting", "zeta"], links: ["14_graph_extrapolation", "help:guides:graph"] },
  { id: "generalized-tails", term: "Generalized tails α± / tail order",
    short: "Per-underlier tail exponents that let an LQD wing decay faster than exponential, plus the calendar rule that the far expiry's tails must not decay faster than the near one's.",
    long: "With `tailAlphaLeft` / `tailAlphaRight` at 0 the wing is a straight variance line (exp); positive α gives integrable or Gaussian-like tails. The exponents are common per underlier and fixed outside the optimizer (`tailAlphaByTicker`), and α = 0 is byte-identical to the historical model. The **Compare** view's *Tails L/R* column names each family's contract; the Quality **Tail order** column reports the adjacent-pair clause, advisory (amber) unless `ledgerTailOrderGate` promotes it to a gate.",
    related: ["lee-bound", "calendar-arbitrage", "lqd"], links: ["docs_generalized_tails", "book", "help:settings:tailAlphaLeft", "help:settings:ledgerTailOrderGate"] },
  { id: "graph-dials", term: "Graph dials κ · η · λ · ν",
    short: "The smooth-field solver's four scales: temporal precision, directed smoothness (reach), optimal-transport strength, and the unbalanced-OT source allowance.",
    long: "`graphKappaScale` (κ) weights how strongly a node's transported prior holds; `graphEtaScale` (η) sets how far a lit innovation reaches along edges; `graphLambdaScale` (λ) turns on the OT flux term (0 = off, the default); `graphNu` (ν) lets mass be created rather than moved. They apply to the *smooth field* operator only — the messages operator has none, its policy lives in the relation editor. Seeded from Options ▸ Graph, editable per session in the Relationships pane's **Advanced** card; the in-app autotune is a LOO over η.",
    related: ["precision-messages", "ot-flux", "graph-extrapolation"], links: ["14_graph_extrapolation", "help:settings:graphKappaScale", "help:settings:graphEtaScale", "help:settings:graphLambdaScale", "help:settings:graphNu"] },
  { id: "graph-extrapolation", term: "Graph extrapolation",
    short: "Reconstructing the dark nodes of the universe from the lit ones by propagating the lit innovation through a directed Bayesian graph.",
    long: "Nodes are smiles (underlying, T); calendar edges link a name's expiries, cross-asset edges link an index or ETF to its names. The graph carries each node's three ATM handles as a Gaussian signal, propagates the lit *increments* (so \"no change\" is the default dark answer) and retargets each dark node's transported prior smile to the posterior handles, wings intact. The Graph lens is the workflow: Configure → Preview → **Run** → Explain → Validate; the reconstructions flow into every other lens under a GRAPH badge.",
    related: ["lit-dark", "innovation", "retargeting", "precision-messages", "skill"], links: ["14_graph_extrapolation", "14_graph_messages", "14_graph_three_priors", "help:guides:graph"] },
  { id: "haircut-band", term: "Haircut band",
    short: "The bid-ask band shrunk on both sides by a fixed vol amount — the target of the haircut fit mode.",
    long: "A quoted band is wide where the market is uncertain; a haircut of `haircut` (0.005 = 0.5 vol point by default) shrinks it so the fit is pulled toward the interior without being forced to the mid. Zero residual inside the shrunk band, a `midAnchorWeight` pull to the mid, and the optional tick floor below which the band cannot shrink. The **Target** layer draws it as the shaded band.",
    related: ["fit-target", "tick-floor", "vol-bp"], links: ["07_calibration_objective", "help:settings:haircut", "help:settings:midAnchorWeight"] },
  { id: "handle", term: "Handle (σ0 · s0 · κ0)",
    short: "A scalar smile summary; the three ATM handles are level σ0, skew s0 and curvature κ0.",
    long: "Handles are what the graph propagates and what the observation filter tracks through time. They are exact for LQD (closed-form ATM identities) and read off the curve for the others. The Parametric **Fit diagnostics** card shows ATM / skew / curvature / RMS; the Graph inspector shows each handle's prior → posterior move; the filter table shows a gain per handle.",
    related: ["innovation", "observation-filter", "graph-extrapolation"], links: ["00_system_overview", "15_kalman_filtering"] },
  { id: "idio-floor", term: "Idiosyncratic band floor",
    short: "A causal floor on a dark node's credible band built from its own trailing unexplained moves while it was lit.",
    long: "In calm tape single-name moves are earnings-idiosyncratic and the graph carries shared repricing, so bands came out too narrow (std ζ ≈ 1.9). The floor keeps an EWMA (5-day half-life) of each node's innovation RMS while lit and requires sd² ≥ 0.30 σ_I² when it goes dark; the two calm cells moved to ζ ≈ 1.02 with the posterior mean untouched. On by default in production; band-only.",
    related: ["zeta", "functional-band", "graph-extrapolation"], links: ["14_graph_extrapolation", "help:guides:graph"] },
  { id: "innovation", term: "Innovation",
    short: "A lit node's fitted-minus-prior move in handle space — the signal the graph propagates and the filter measures.",
    long: "The prior is yesterday's fit transported to today's market; when today's calibration lands, the difference is the innovation. The graph propagates innovations, not levels, so a dark node with a silent neighbourhood stays at its transported prior. In the filter, innovation is measurement minus prediction (the table's *innov bp* column) and drives the adaptive process noise.",
    related: ["prior", "handle", "innovation-gate", "graph-extrapolation"], links: ["14_graph_extrapolation", "15_kalman_filtering"] },
  { id: "innovation-gate", term: "Innovation gate (adaptive σ)",
    short: "The filter's rule that a standardized innovation beyond `filterAdaptiveSigma` sigmas inflates the process noise instead of being damped.",
    long: "A Kalman filter with a fixed process clock damps a genuine overnight jump. The gate compares each handle's innovation to its predicted sd; past 3σ (default) it grows Q so the state follows the market, and 0 switches the mechanism off. This is the filter's answer to the \"jump the strike anchor damped\" case file; together with residual inflation it makes the gain an output rather than a dial.",
    related: ["observation-filter", "process-noise", "innovation"], links: ["15_kalman_filtering", "15_kalman_computed_trust", "help:settings:filterAdaptiveSigma"] },
  { id: "intraday-clock", term: "Intraday (session) clock",
    short: "A sub-day time base that values a node from the snapshot timestamp to the settlement instant and accrues variance through the trading session.",
    long: "Two knobs: `intradayClock` for the fits (0DTE research grade — settlement map, session-weighted variance profile, `sessionVarShare` of a day inside 09:30 ET–close) and `filterClock = session` for the observation filter (a session carries `filterSessionShare` = 0.60 of a day's variance, non-trading days 0). Both are off by default and byte-identical when off. Live 0DTE stays a client-entitled, post-hosting feature; the exit gates are certification-locked.",
    related: ["event-clock", "observation-filter"], links: ["help:settings:intradayClock", "help:settings:filterClock", "15_kalman_filtering"] },
  { id: "lee-bound", term: "Lee bound / Lee wing slope",
    short: "The total-variance wing slope β = lim w(k)/|k| of any arbitrage-free smile cannot exceed 2; the app caps SVI at 1.95.",
    long: "Lee's moment formula ties the slope to the tail's critical moment. The boundary β = 2 itself is a trap: it passes every wing screen with zero penalty while the tail density turns negative — a live SPY wing once sat at 2.0000. Hence `leeSlopeMax` = 1.95, strictly buffered. The Quality **Lee L/R** column shows both slopes (rose = beyond the bound, blocks publish); the Parametric fit diagnostics list them behind the expander.",
    related: ["generalized-tails", "svi-jw", "extrapolated-region-arb"], links: ["09_wings_lee_bounds", "02_svi_jw_moments", "help:settings:leeSlopeMax"] },
  { id: "lens", term: "Lens",
    short: "One of the five ways the workbench looks at the active node: Graph · Forwards · Parametric · Local Vol · Quality.",
    long: "The left activity bar (Alt+1…5) switches the lens; the lens applies to every open node tab of the focused group. Parametric, Local Vol and Forwards are node lenses (the tab's ticker and expiry drive them); Graph and Quality are universe lenses that render without a tab and highlight the active node. F1 opens the guide of the active lens. The Local Vol icon is inert while `localVolEnabled` is off.",
    related: ["tab", "editor-group", "node"], links: ["help:guides:workbench", "help:guides:parametric", "help:guides:localvol", "help:guides:graph"] },
  { id: "lit-dark", term: "Lit / dark",
    short: "A node is lit when its quotes are consumed and calibrated, dark when it is to be reconstructed by the graph.",
    long: "Dark means the quotes are absent, unusable, deliberately withheld or simply not consumed — not that nobody quoted. The designation is one shared map edited from three surfaces: the dot in the Nodes pane (or **L** on a focused row), the expiry chips of the Manage-universe dialog, and the Graph canvas (drop a node to light it). Lit nodes are the observations of the solve; dark nodes receive the propagated innovation and a credible band.",
    related: ["node", "graph-extrapolation", "universe"], links: ["14_graph_extrapolation", "help:guides:universe", "help:guides:graph"] },
  { id: "local-volatility", term: "Local volatility (piecewise-affine LV surface)",
    short: "A continuous piecewise-affine local-variance sheet on a strike × maturity grid, calibrated jointly to all expiries through the Dupire PDE.",
    long: "The fourth model stands apart from the per-expiry slices: one unknown surface for the whole ticker, positive by box bounds on the nodal variances, priced by an implicit march. The Local Vol lens shows the reconstructed smile per expiry, the **LV surface** (3D σ²_loc mesh or heatmap), the **IV surface**, Densities, Stacked IV, Term and Table, plus a calibration trace player. Grid and solver knobs are global (Options ▸ Local Vol) and fold into the affine cache key only.",
    related: ["dupire-pde", "var-swap", "ssr"], links: ["04_local_volatility", "04_local_volatility_forward", "docs_localvol_methodology", "help:guides:localvol"] },
  { id: "log-moneyness", term: "Log-moneyness k",
    short: "k = log(K / F_T): the strike measured against the forward, the x-axis every smile lives on internally.",
    long: "Forward-normalizing makes a smile spot-independent until a dynamics rule transports it. The charts' internal geometry (brush window, hit-testing, zoom) is always in k; the axis selector re-labels it as Strike K, % ATM, Delta, (K−F)/σF√T or k/σ√T without moving anything. Quotes from two frames (market vs calibration) are each placed at their own forward's k so the frames stay comparable.",
    related: ["forward", "total-variance", "smile"], links: ["00_system_overview", "help:guides:parametric"] },
  { id: "loo-backtest", term: "LOO backtest",
    short: "Leave-one-node-out: hide one lit node, solve, score the reconstruction against the hidden calibration.",
    long: "The graph's skill is measured, not asserted: each lit node is held out in turn, the posterior at that node is compared with its actual fit, and the errors are pooled into skill (ATM vol bp saved versus the transported prior) and ζ (standardized residual). The Graph drawer's **Validation** tab runs the current-day LOO side by side across operators; the multi-regime benchmark pack runs offline and the tab links its artifact. The in-app autotune is the same harness scoring η.",
    related: ["skill", "zeta", "graph-extrapolation"], links: ["14_graph_extrapolation", "help:guides:graph"] },
  { id: "lqd", term: "LQD (log-quantile-density model)",
    short: "The default smile model: log q(u) = −log u − log(1−u) + g(u), a Legendre expansion over two universal tail terms, butterfly-free by construction.",
    long: "Instead of drawing a vol curve and policing its density, LQD parametrizes an increasing quantile function and prices the smile from the resulting law, so every iterate the optimizer visits is a genuine distribution. Order `nOrder` (16 default, 4–24), a high-order ridge, the logistic coordinate chart and an analytic price Jacobian. Exact ATM handle identities, a closed-form var-swap, and the asset-share ledger that carries the full-line calendar certificate.",
    related: ["density-quantile", "svi-jw", "mcs", "generalized-tails"], links: ["01_lqd_model", "01_lqd_model_lecture", "lqd_paper", "help:settings:model", "help:settings:nOrder"] },
  { id: "mcs", term: "Multi-Core Sigmoid (MCS)",
    short: "The sigmoid family: a log-cosh convex base owning the wings plus signed zero-wing hat kernels for W-shaped and event smiles.",
    long: "No globally convex slice can carry a WW shape, so MCS superposes: the base sets level, skew, convexity and asymmetric wing steepness; `nCores` hats add local humps or notches whose kernels vanish in both tails, leaving the wing slopes exactly fixed. A Durrleman put-wing penalty (`sivWingPenaltyPct`) sits where the arb census located violations. Select it as `model = sigmoid`.",
    related: ["ww-smile", "lqd", "svi-jw"], links: ["03_multicore_siv", "03_multicore_mcs_corrections", "help:settings:nCores", "help:settings:sivWingPenaltyPct"] },
  { id: "node", term: "Node",
    short: "One (underlying, expiry) pair — a smile viewed as a vertex of the graph and as a tab of the workbench.",
    long: "The universe is a set of nodes; the Nodes pane lists them as a tree (ticker → expiry rows with lit/dark dot, tenor, chain time, RMS bp and a quality glyph). Opening a node opens a tab; the lens then renders that node. Nodes carry their own version (rate, dividends, events, prior), so editing one never invalidates the universe.",
    related: ["smile", "lit-dark", "tab", "universe"], links: ["00_system_overview", "help:guides:workbench"] },
  { id: "observation-filter", term: "Observation filter (Kalman; overlay / active)",
    short: "A per-handle Kalman / MAP estimator that denoises the ATM handles through time; off, overlay (display only) or active (enters the fit).",
    long: "Prior persistence is a gap regularizer; the filter is a temporal state estimator, and the two must not be confused. `off` is byte-identical to the feature never existing; `overlay` updates the filtered state and the **FILTER** badge after each fit; `active` inserts the prediction as a one-stage MAP prior before optimization (off by default, with a documented shock-day lag). Gains are per handle (no cross-handle updates), the measurement covariance comes from the fit's Jacobian, contradiction inflates it.",
    related: ["process-noise", "innovation-gate", "handle", "prior-persistence-modes"], links: ["15_kalman_filtering", "15_kalman_computed_trust", "help:guides:filter", "help:settings:observationFilterMode"] },
  { id: "ot-flux", term: "OT (optimal transport) flux",
    short: "The graph's optional regularizer that moves innovation mass along edges at a transport cost instead of letting it appear anywhere.",
    long: "With `graphLambdaScale` > 0 the smooth-field solve adds an unbalanced optimal-transport term: increments must be *transported* from lit sources through the edge structure, and `graphNu` allows a source term (mass created, not moved). It is off by default (λ = 0) because held-out adjudication did not favour it; the machinery stays for research. Smooth-field only.",
    related: ["graph-dials", "graph-extrapolation"], links: ["14_graph_extrapolation", "help:settings:graphLambdaScale", "help:settings:graphNu"] },
  { id: "precision-messages", term: "Precision messages vs smooth field",
    short: "The two production propagation operators: pairwise relation factors with per-edge precisions (messages) vs a screened directed-Laplacian smoothness prior (smooth field).",
    long: "*Messages* — the Options default since 2026-07-27 — make every edge a contract z_i ≈ β z_j at a stated relation variance: a receiver inherits its informer's move at full β regardless of confidence, competing messages are precision-averaged (never added), distance costs confidence not amplitude, and a silent neighbour costs nothing. *Smooth field* asserts only smoothness, is the wire default and the explicit rollback. *Layered* (dynamic-harmonic) adds residual memory through time and stays opt-in. The Graph top bar switches operators; `graphPropagationMode` seeds it.",
    related: ["graph-extrapolation", "graph-dials", "preflight"], links: ["14_graph_messages", "14_graph_three_priors", "docs_graph_precision_messages", "docs_graph_dynamic_harmonic", "help:settings:graphPropagationMode"] },
  { id: "preflight", term: "Preflight",
    short: "A dry run of the exact request Run would send, returning blockers and warnings without touching anything.",
    long: "The Graph top bar's preflight chip is live: rose = a blocker gates Run (empty universe, missing priors, unsupported components), amber = warnings (extreme β, precision outliers, directed cycles whose β product ≠ 1, conditioning, stale residuals, a residual-config mismatch), emerald = clean, slate = no report. The popover lists every finding. Run gates only on blockers.",
    related: ["precision-messages", "graph-extrapolation"], links: ["docs_graph_precision_messages", "help:guides:graph"] },
  { id: "prior", term: "Prior",
    short: "The saved previous fit of a node, transported to today's market (spot, forward, clock) before it is compared with or blended into today's fit.",
    long: "Priors are saved from the TopBar **Priors ▾** (visible tab / all open tabs / all calibrated) and fetched back; `autoLoadPrior` and `autoRollPriorOnFetch` automate the roll. A prior enters a fit only through the persistence gate (where quotes do not identify a feature), enters the graph as each node's baseline, and is drawn as the *prior* curve on the Smile chart. The provenance tier (active / nearest / bootstrap / flat) and its as-of show in the Graph inspector and the prior diagnostics table.",
    related: ["prior-persistence-modes", "innovation", "graph-extrapolation"], links: ["13_bayesian_prior_persistence", "help:guides:priors", "cmd:priors.saveVisible"] },
  { id: "prior-persistence-modes", term: "Prior persistence modes (operator / factor / hybrid / graph_only)",
    short: "How a fetched prior is persisted into the calibration: off, overlay, strike_gap, quote_operator, smile_factor, hybrid (default) or graph_only.",
    long: "*quote_operator* persists level-invariant baskets (ATM, RR25, BF25, VarSwap, optional wing slopes) each admitted through an activation gate that is exactly zero where quotes identify the basket; *smile_factor* persists ATM, skew, curvature and VarSwap factors; *hybrid* combines operators with a deep-tail anchor and won the held-out backtest by ~32 vol bp on the wing; *strike_gap* anchors delta locations; *graph_only* keeps the prior for the graph and out of the fit; *overlay* draws it only. Persist shape, not level: an overnight jump is never damped.",
    related: ["prior", "observation-filter"], links: ["13_bayesian_prior_persistence", "13_prior_flat_directions", "help:settings:priorPersistenceMode", "help:guides:priors"] },
  { id: "process-noise", term: "Process noise",
    short: "How much a filtered handle is allowed to wander per √day between observations — the Q of the Kalman filter.",
    long: "Three clocks: `filterProcessVolBpSqrtDay` (30 bp/√day on the ATM level), `filterProcessSkewSqrtDay` (0.02), `filterProcessCurvSqrtDay` (0.05), plus `filterTransportNoiseScale` per unit of spot-transport distance. Too small and the filter damps real moves; too large and it trusts every noisy print. The innovation gate inflates Q adaptively; `filterResetHours` (96) is the longest gap predicted across before the state resets.",
    related: ["observation-filter", "innovation-gate"], links: ["15_kalman_filtering", "help:settings:filterProcessVolBpSqrtDay", "help:guides:filter"] },
  { id: "publish-gate", term: "Publish readiness / publish gate",
    short: "A node is publish-ready when it has a fresh, certified, arbitrage-clean fit within the RMS budget; the export blocks (HTTP 409) otherwise.",
    long: "Readiness issues, per node: `stale`, `RMS > budget`, `Lee wing slope > 2`, calendar arbitrage, an uncertified belly, red-stale data age, and — when gated — an as-of mismatch or a tail-order failure. The Quality lens shows the **Publish ready** tile, the per-node **Status** column and the node card's certificate; the JSON / CSV export and the HTML report are the publish path, and a published manifest can be recalled (a lifecycle transition, not a delete).",
    related: ["quality-report", "belly-certificate", "data-age", "stale-node"], links: ["help:guides:quality", "help:settings:asOfMismatchGate", "help:settings:ledgerTailOrderGate", "cmd:export.report"] },
  { id: "quality-report", term: "Quality report",
    short: "The universe fit-quality dashboard and its self-contained HTML export: readiness, RMS, arbitrage diagnostics, data age and LV health per node.",
    long: "GET /quality never fits — it reads the committed calibrations. The Quality lens shows eight headline tiles (Publish ready · Fitted · Stale · No fit · Arb flags · Median RMS · Worst RMS · LV surfaces), the active node's certificate card, a per-ticker rollup and the per-node exception table (sort: exceptions first / worst RMS / ticker · expiry). **Export quality report (HTML)** opens the same content as a client-facing document.",
    related: ["publish-gate", "stale-node", "belly-certificate"], links: ["help:guides:quality", "cmd:export.report", "cmd:lens.quality"] },
  { id: "quarantine", term: "Quarantine",
    short: "Every quote the static no-arbitrage / wing screen drops is kept with a reason, never silently discarded.",
    long: "Prepare selects the OTM side, de-Americanizes, inverts to total variance and screens each quote; a dropped quote goes to the quarantine with its reason (intrinsic violation, wing order, tick noise …). The Parametric **Table** view and the quote layer show excluded quotes distinctly, and your own exclusions (Del on a selected quote) live in the same edit ledger with undo / redo.",
    related: ["tick-floor", "fit-target"], links: ["05_deamericanization", "07_calibration_objective", "help:guides:parametric"] },
  { id: "retargeting", term: "Retargeting",
    short: "Turning three posterior handles back into a full smile by moving a node's transported prior curve to those handles in an ATM-orthogonal chart, wings untouched.",
    long: "Three scalars do not make a smile. The dark node's transported prior — a complete arbitrage-clean curve, wings and event convexity included — is re-expressed in a chart whose first three coordinates are the ATM handles; those are set to the posterior values and the shape modes are left alone, so every reconstruction remains a valid slice. Double-click a graph node to see the result under the Parametric lens.",
    related: ["graph-extrapolation", "handle", "functional-band"], links: ["14_graph_extrapolation", "help:guides:graph"] },
  { id: "robust-loss", term: "Robust loss (Huber / Cauchy)",
    short: "An optional re-weighting of large residuals so a single bad quote cannot drag the whole slice.",
    long: "`robustLoss` = off (plain least squares, default), huber (quadratic inside `robustFScale`, linear beyond) or cauchy (log-quadratic, heavier down-weighting). The scale is in vol units (0.005 = 0.5 vol point). Use it on delayed or thin books where the tick floor and the screen still let an outlier through; check the **Weights** layer to see what the loss effectively did.",
    related: ["fit-target", "weight-scheme", "tick-floor"], links: ["07_calibration_objective", "help:settings:robustLoss", "help:settings:robustFScale"] },
  { id: "skill", term: "Skill (graph)",
    short: "The reduction in held-out ATM error versus the transported-prior baseline, in ATM vol bp; positive means the graph beat mechanical transport.",
    long: "Measured on the 25-asset, three-regime benchmark: neighbour-supported indexes gain +10 to +76 bp, ETFs +3 to +7, fully dark single names behind lit indexes +7.9 to +14.2 bp in the August-2024 spike and +3.8 to +7.2 out of sample in the October-2022 bear, ≈ 0 (never negative) in calm tape where moves are idiosyncratic. An exact 0.000 is a disconnection, not damping — the transient-name topology case file.",
    related: ["loo-backtest", "zeta", "graph-extrapolation"], links: ["14_graph_extrapolation", "handoff_pitfalls"] },
  { id: "slice", term: "Slice",
    short: "One smile's fitted model — the parametric object behind the curve of one (underlying, T).",
    long: "The four families produce slices differently: LQD, SVI-JW and MCS fit one slice per expiry along the calibration spine; the LV surface is one joint object whose per-expiry *reconstructed* smiles play the slice role in its views. Slices are what the belly certificate certifies, what calendar coupling orders, and what the graph retargets.",
    related: ["smile", "surface", "belly-certificate"], links: ["00_system_overview"] },
  { id: "smile", term: "Smile",
    short: "The implied-volatility curve of one (underlying, expiry) across strikes.",
    long: "The app treats a smile as a probability law seen through the Black formula, and every design choice follows from taking that literally: butterfly-freedom is positivity of the density, calendar-freedom is convex order across expiries, the prior ties the universe together. The Parametric **Smile** view draws quotes (bid/ask bands), the fit target, the prior and the current fit, with quote select / exclude / amend and undo.",
    related: ["slice", "surface", "node", "density-quantile"], links: ["00_system_overview", "help:guides:parametric"] },
  { id: "snapshot-file", term: "Snapshot file",
    short: "A JSON file (`volfit-snapshot/1`) holding the cached quotes and the prevailing calibrations of every ticker; opening one makes it the File data source.",
    long: "**File ▸ Save snapshot…** (Ctrl+Alt+S) exports what is cached — it never fetches or refits. **Open snapshot…** registers a `file` source, switches to it, points the universe at the file's tickers and reinstalls the embedded fits with provenance *loaded* (the Fit diagnostics card shows a green *loaded* tag). Use it to hand a colleague an exact market, or to work offline.",
    related: ["workspace-file", "data-source", "universe"], links: ["help:guides:files", "cmd:file.saveSnapshot", "cmd:file.openSnapshot"] },
  { id: "ssr", term: "SSR (skew-stickiness ratio) and the sticky regimes",
    short: "R = (dσ_ATM / d ln F) / skew: the fraction of the skew realized as an ATM-vol move per unit spot move; sticky moneyness R = 0, sticky strike R = 1, sticky local vol R ≈ 2.",
    long: "A snapshot gives σ(k, T) at one spot; hedging needs its spot derivative, which no surface contains, so the regime is a desk choice — on a long-dated SPY smile it moves an OTM put's delta by ~20 delta points. `dynamicsRegime` seeds it (sticky_strike default; `custom` uses `ssr`; `sticky_local_vol_grid` freezes the LV surface in absolute strike and derives its own answer). The **Spot move** card transports every lens live with that R — following the market spot or a scenario dial (the node's live tick stream follows the scenario too); **Recalibrate** is the top-bar Calibrate for that ticker alone.",
    related: ["local-volatility", "handle"], links: ["12_spot_vol_dynamics", "12_spotvol_missing_derivative", "help:settings:dynamicsRegime", "help:settings:ssr"] },
  { id: "stale-node", term: "Stale node",
    short: "A node whose inputs changed since its last calibration — quotes, forward, dividends, events, prior or settings — so the shown fit no longer matches them.",
    long: "With `autoCalibrate` on, a stale node refits in the background; on the trigger-gated live server (default off) the fit is kept, marked stale, and waits for an explicit **Calibrate**. Stale shows as an amber glyph in the Nodes pane and tab strip, a STALE badge on the chart toolbar, the *Stale* tile in Quality, and the readiness issue `stale`. Distinct from *stale data* (age), which is about the quotes' timestamp.",
    related: ["data-age", "publish-gate", "quality-report"], links: ["help:settings:autoCalibrate", "cmd:calibrate.both", "help:guides:workflow"] },
  { id: "structural-chart", term: "Structural chart",
    short: "An optimization coordinate system in which every iterate is fence-clean by construction, so the optimizer never visits an inadmissible slice.",
    long: "For SVI (`sviChart = structural`, default) the Lee wing slopes are lifted logistically against the buffered cap so no iterate can breach it; the raw chart is the historical rollback. MCS has the same option (`mcsChart`, raw by default). LQD's `lqdCoords = logistic` maps the right-tail scale so the admissibility wall is unreachable. The benchmark that ratified the SVI default had to condition on convergence first — its raw arm's lower arb rate was a survivorship artifact.",
    related: ["svi-jw", "mcs", "lqd", "lee-bound"], links: ["02_svi_jw", "help:settings:sviChart", "help:settings:mcsChart", "help:settings:lqdCoords"] },
  { id: "surface", term: "Surface",
    short: "All expiries of one underlying — the object the calendar constraint orders and the 3D views draw.",
    long: "Per-expiry slices become a surface through calendar coupling (ascending T, symmetric solver) and, for the LV model, through a single joint fit. The Parametric **Surface** and the Local Vol **IV surface** / **LV surface** views draw σ(k, T); hovering shows a crosshair linked across the ticker's surface charts (the smile at T, the term curve at k). Export surfaces (JSON / CSV) writes every published surface with its inputs and a manifest.",
    related: ["slice", "calendar-arbitrage", "local-volatility"], links: ["10_calendar_arbitrage", "cmd:export.surfacesJson"] },
  { id: "svi-jw", term: "SVI-JW",
    short: "Stochastic-volatility-inspired: total variance as a tilted hyperbola in k, re-coordinatized into five trader handles (ATM variance, ATM skew, two wing slopes, minimum variance).",
    long: "Smooth, strictly convex, linear in both wings, cheap to fit, unable to turn twice. The raw coefficients are good computational coordinates and poor market language; JW is the same curve in trader vocabulary. Wings are Lee-fenced at 1.95, the belly is certified at the gate and repaired once (`bellyRepair`) when it fails, and the structural chart keeps every iterate clean. Select it as `model = svi`.",
    related: ["lqd", "mcs", "lee-bound", "structural-chart"], links: ["02_svi_jw", "02_svi_jw_rewrite", "help:settings:sviPenaltyWeight", "help:settings:leeSlopeMax"] },
  { id: "tab", term: "Tab (preview vs pinned)",
    short: "One open node in an editor group; a preview tab (italic) is replaced by the next single click, a pinned tab stays.",
    long: "VS Code semantics: single click or Enter in the Nodes pane opens a *preview* tab that the next click reuses; double-click, middle-click, Shift+Enter or Space opens a *pinned* tab (pin glyph). Alt+← / Alt+→ cycle tabs, Alt+W closes, drag reorders, right-click offers close / close others / pin / move to another group. Each tab shows a quality glyph (amber stale, rose arb-flagged). With Layout ▸ **Remember view per tab** each tab keeps its own sub-view.",
    related: ["editor-group", "lens", "node"], links: ["help:guides:workbench", "help:shortcuts"] },
  { id: "tick-floor", term: "Tick floor",
    short: "A minimum half-width, in ticks of the quoted price, below which a bid-ask or haircut band is not allowed to shrink.",
    long: "Thin or delayed books quote bands narrower than the price grid can support, and a haircut can then shrink them to nothing. `bandTickFloorTicks` (0 = off) floors the band at that many ticks — tested against the *bid*, so a one-tick bid keeps its meaning. Part of the schema-v6 tick-noise fix; pairs naturally with the data-age staleness slice.",
    related: ["haircut-band", "fit-target", "robust-loss"], links: ["07_calibration_objective", "help:settings:bandTickFloorTicks"] },
  { id: "total-variance", term: "Total variance w(k, T)",
    short: "The clock-independent implied variance solving Bl(k, w) = C(k); σ² = w / t under the calendar clock, w / τ under the event clock.",
    long: "Four objects kept distinct: calendar time t, total variance w (a property of the price), the market IV √(w/t) and the working IV √(w/τ). Calendar arbitrage is a statement about w at fixed k, never about σ, which is why the **Stacked IV** views plot w = σ²T. The normalized Black call Bl(k, w) = Φ(d+) − e^k Φ(d−) is the one primitive every model shares.",
    related: ["calendar-arbitrage", "event-clock", "log-moneyness"], links: ["00_system_overview", "10_calendar_arbitrage"] },
  { id: "universe", term: "Universe (named universe)",
    short: "The set of tickers and selected expiries the app works on, with their lit/dark marks; a named universe is one saved on the server.",
    long: "**Universe ▾ Manage universe…** (Ctrl+Shift+U) adds tickers from the catalogue search, picks expiries by rule (0DTE · Weeklies · Monthly · Quarterly · ≤1Y · ≤2Y · All) or by chip, toggles lit/dark on the chips and removes tickers. **Save universe as…** names it; saved universes reload from the Universe menu. The universe lives on the server; edits flow into every lens at once, and tabs of removed nodes are pruned.",
    related: ["node", "lit-dark", "data-source", "workspace-file"], links: ["help:guides:universe", "cmd:universe.manage", "cmd:universe.saveAs"] },
  { id: "var-swap", term: "Var-swap (log contract)",
    short: "The fair variance-swap strike of a node — the log-contract payoff integrated against the terminal law — one number that pins the wing share option quotes leave free.",
    long: "Two models can agree to basis points at every quoted strike and differ by 30 vol bp in fair var-swap: the functional is global. A node carries at most one var-swap quote (the **Variance swap** card, seeded at the model's own fair level), entering the fit as a soft target weighted `varSwapWeightPct` of the summed quote weights. Each model evaluates it natively: closed form for LQD, arithmetic for SVI/MCS, a source PDE (or static replication, `varSwapMethod`) for the LV surface.",
    related: ["var-swap-hard-pin", "extrapolated-region-arb", "lee-bound"], links: ["08_variance_swaps", "08_varswap_representations", "help:settings:varSwapEnabled", "help:settings:varSwapWeightPct"] },
  { id: "var-swap-hard-pin", term: "Var-swap hard pin",
    short: "Turning the var-swap quote from a soft penalty into an exact constraint the fit must hit.",
    long: "With `varSwapHardPin` on, the slice's fair var-swap is pinned to the quote rather than pulled toward it; use it when the var-swap market is the better-identified object and the wings should absorb the difference. Off by default (byte-identical to the soft target). Watch the Quality Lee slopes and the extrapolated-region g afterwards — a hard pin moves mass in the tails.",
    related: ["var-swap", "lee-bound"], links: ["08_variance_swaps", "help:settings:varSwapHardPin"] },
  { id: "vol-bp", term: "Vol bp / vol point",
    short: "A vol point is 0.01 in volatility (1 %); a vol bp is 0.01 vol point (1e−4 in volatility).",
    long: "RMS and max fit errors, the graph's skill, the filter's process noise and the calendar gaps are all quoted in vol bp; the haircut, the amend step (↑ / ↓ moves a selected mid by 0.1 vol point, Shift = 0.5) and the tick floor's scale are in vol points. A 20 bp RMS on a band fit and a 20 bp RMS on a mid fit are not the same statement — the target differs.",
    related: ["fit-target", "haircut-band"], links: ["00_system_overview"] },
  { id: "weight-scheme", term: "Weight scheme (equal / tv-density / vega / delta)",
    short: "The per-quote weights the residuals are summed with — a quadrature rule over the smile.",
    long: "`weightScheme = equal` integrates the smile against the accident of the exchange's listing density; `tv_density` corrects by the time-value density so dense wings do not outvote the body; `vega_density` and `delta_density` weight by Black vega or by delta spacing. The Parametric **Weights** layer draws the effective weight strip under the smile so you can see what the optimizer sees.",
    related: ["fit-target", "robust-loss"], links: ["07_calibration_objective_measure", "help:settings:weightScheme"] },
  { id: "what-if-pulse", term: "What-if pulse",
    short: "A manual, non-persisting observation injected into the graph solve — shift one node's handles and watch the universe respond.",
    long: "Switch the Graph top bar's observation source to **Manual what-if**, then click a node (pulse / unpulse) or drop one from the Nodes pane (+1 vol pt), or pick a canonical scenario in the drawer's **Preview** tab (Calendar pulse · Competing signals · Cross basket). Run solves the active operator on the production machinery with those synthetic observations; nothing is written back.",
    related: ["graph-extrapolation", "precision-messages", "lit-dark"], links: ["help:guides:graph", "14_graph_messages"] },
  { id: "workspace-file", term: "Workspace file",
    short: "A JSON file (`volfit-workspace/1`) bundling the backend workspace (settings, universe picks, edits, priors) with the shell state (lens, tabs, layout, view preferences).",
    long: "**File ▸ Save workspace** (Ctrl+S) writes to the last target — a file (Chromium keeps the handle and overwrites in place; elsewhere it re-downloads) or the server store; **Save as…** (Ctrl+Shift+S) picks a new one; **Open** (Ctrl+O, or drop a .json on the shell) is a backend state reset followed by the shell blob. Dirty tracking shows *· unsaved* in the status bar's Workspace chip. Quotes are not inside — that is the snapshot file.",
    related: ["snapshot-file", "universe"], links: ["help:guides:files", "cmd:file.save", "cmd:file.saveAs"] },
  { id: "ww-smile", term: "WW smile",
    short: "A W-shaped smile — a central trough with a shoulder on each side — typical ahead of a binary event or in a bimodally-positioned name.",
    long: "No globally convex slice can carry a WW shape, so a hyperbola (SVI) is structurally disqualified and LQD needs enough Legendre order; MCS was built for it — signed hat kernels add the shoulders while the base keeps the wings. Look for it in the **Density** view as a bimodal law, and in the Compare view's validity chips.",
    related: ["mcs", "event-clock", "lqd"], links: ["03_multicore_siv", "03_multicore_mcs_corrections"] },
  { id: "zen-mode", term: "Zen mode",
    short: "Layout ▸ Zen mode: hide every pane but the charts.",
    long: "Zen mode collapses the Nodes pane, the diagnostics aside and the status bar so the editor groups fill the viewport — for a screen share or a chart-only screenshot (**Export chart as PNG** still works). Toggle it again, or **Reset layout**, to come back; the pane widths are restored.",
    related: ["editor-group", "lens"], links: ["cmd:layout.zen", "cmd:layout.reset", "help:guides:workbench"] },
  { id: "zeta", term: "ζ (standardized held-out score)",
    short: "Realized held-out error divided by the posterior credible band: std ζ = 1 means the bands are the right width, > 1 overconfident, < 1 conservative.",
    long: "ζ is the check on the graph's *uncertainty*, as skill is the check on its *mean*. Every LOO pool reports std ζ; the calm-regime dark-name cells sat at ≈ 1.9 until the idiosyncratic band floor brought them to ≈ 1.02. The observation filter reports the same statistic per node (the ζ strip in the filter timeline). Widening skew / curvature bands in idiosyncratic tape remains open.",
    related: ["skill", "loo-backtest", "idio-floor", "functional-band"], links: ["14_graph_extrapolation", "15_kalman_computed_trust", "help:guides:graph"] },
];

const BY_ID: Record<string, GlossaryEntry> = Object.fromEntries(GLOSSARY.map((g) => [g.id, g]));

/** Glossary lookup; undefined for an unknown id. */
export function glossaryEntry(id: string): GlossaryEntry | undefined {
  return BY_ID[id];
}
