"""F5 -- the curve between the quotes: interpolate in the clock.

Three quoted expiries (7, 30, 90 days) generated by a flat 30% clock
volatility with one four-extra-day event at day 45 -- between the second
and third quotes.  Linear-in-tau interpolation reproduces the true
readings; linear-in-t smears the event's variance across the whole
bracketing interval.
Panel (a): the two dense vol readings with the quotes.
Panel (b): the artifact -- calendar-interpolated minus true reading, in
vol bp.
"""

from __future__ import annotations

import matplotlib.pyplot as plt
import numpy as np

import clock8
import figstyle
from figstyle import PALETTE
from macros import STORE, num

SIGMA_CLK = 0.30
EVENT_DAY = 45.0
EXTRA_DAYS = 4.0
QUOTED_DAYS = np.array([7.0, 30.0, 90.0])
EVENTS = [(EVENT_DAY / 365.0, EXTRA_DAYS)]


def fig_clk_interp() -> str:
    tq = QUOTED_DAYS / 365.0
    wq = SIGMA_CLK**2 * clock8.tau_years(tq, EVENTS)

    # Dense curves live on the quoted span only -- interpolation, never
    # extrapolation (extrapolation is Chapter 5's subject, not this one's).
    T_days = np.linspace(QUOTED_DAYS[0], QUOTED_DAYS[-1], 1661)
    T = T_days / 365.0
    tau = clock8.tau_years(T, EVENTS)

    # True dense curve = the generator itself (flat clock vol); the
    # linear-in-tau interpolator through the quotes reproduces it exactly
    # because the quotes sit on w = sigma^2 tau (checked below).
    w_true = SIGMA_CLK**2 * tau
    tau_q = clock8.tau_years(tq, EVENTS)
    w_tau_interp = np.interp(tau, tau_q, wq)
    exact_bp = float(np.max(np.abs(
        np.sqrt(w_tau_interp / T) - np.sqrt(w_true / T)
    )) * 1e4)

    # Calendar interpolation: w linear in t between the quotes.
    w_cal_interp = np.interp(T, tq, wq)

    sig_true = np.sqrt(w_true / T)
    sig_cal = np.sqrt(w_cal_interp / T)
    artifact_bp = (sig_cal - sig_true) * 1e4

    inside = (T_days > QUOTED_DAYS[1]) & (T_days < QUOTED_DAYS[2])
    i_over = np.argmax(np.where(inside, artifact_bp, -np.inf))
    i_under = np.argmin(np.where(inside, artifact_bp, np.inf))
    STORE.add("interp", "ClkInterpEventDay", num(EVENT_DAY, 0),
              "event date of the interpolation construction (calendar day)")
    STORE.add("interp", "ClkInterpExactBp", num(exact_bp, 2),
              "max |linear-in-tau minus generator| reading gap (vol bp)")
    STORE.add("interp", "ClkInterpOverBp", num(artifact_bp[i_over], 0),
              "max phantom vol BEFORE the event (vol bp)")
    STORE.add("interp", "ClkInterpOverDay", num(T_days[i_over], 0),
              "calendar day of the max overshoot")
    STORE.add("interp", "ClkInterpUnderBp",
              num(abs(artifact_bp[i_under]), 0),
              "max understatement PAST the event (vol bp)")
    STORE.add("interp", "ClkInterpUnderDay", num(T_days[i_under], 0),
              "calendar day of the max understatement")

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=figstyle.ROW2)

    # (a) two dense readings.
    ax_a.plot(T_days, sig_true * 100, color=PALETTE["model"], lw=1.6,
              label=r"linear in $\tau$ (knows the event)")
    ax_a.plot(T_days, sig_cal * 100, color=PALETTE["data"], lw=1.4,
              ls="--", label=r"linear in $t$")
    ax_a.plot(QUOTED_DAYS, np.sqrt(wq / tq) * 100, "o",
              color=PALETTE["ink"], ms=5.0, zorder=5, label="quotes")
    ax_a.axvline(EVENT_DAY, color=PALETTE["muted"], lw=0.9, ls=":")
    figstyle.callout(
        ax_a, "the event sits\nbetween quotes", (EVENT_DAY, 30.02),
        (56.0, 30.12),
    )
    ax_a.set_xlabel("calendar days to expiry")
    ax_a.set_ylabel("ATM implied vol  (%)")
    ax_a.legend(loc="upper left")
    figstyle.panel(ax_a, "a", "two dense curves through three quotes")

    # (b) the artifact.
    ax_b.plot(T_days, artifact_bp, color=PALETTE["data"], lw=1.4)
    ax_b.axhline(0.0, color=PALETTE["grid"], lw=0.8)
    ax_b.axvline(EVENT_DAY, color=PALETTE["muted"], lw=0.9, ls=":")
    ax_b.fill_between(T_days, 0.0, artifact_bp, where=inside,
                      color=PALETTE["band"], alpha=0.9, lw=0)
    figstyle.callout(
        ax_b, f"+{artifact_bp[i_over]:.0f} bp phantom",
        (T_days[i_over], artifact_bp[i_over]),
        (16.0, artifact_bp[i_over] + 25.0),
    )
    figstyle.callout(
        ax_b, f"$-${abs(artifact_bp[i_under]):.0f} bp",
        (T_days[i_under], artifact_bp[i_under]),
        (64.0, artifact_bp[i_under] - 12.0),
    )
    ax_b.set_xlabel("calendar days to expiry")
    ax_b.set_ylabel("calendar-interp. error  (vol bp)")
    figstyle.panel(ax_b, "b", "the smear, quote by quote exact")

    figstyle.save(fig, "fig_clk_interp")
    return (f"artifact +{artifact_bp[i_over]:.0f} / "
            f"-{abs(artifact_bp[i_under]):.0f} bp")
