"""Figure suite for the three-representations edition of Note 08 (variance swaps).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_vs_representations.py

Every fair strike, fit, sensitivity and audit number is produced by PRODUCTION
machinery (``volfit.calib.varswap``, the LQD quadrature closed form, the
local-vol source PDE and calibrators); local formulae define only the synthetic
running smile.  The running character is the fitted index-like smile
``RawSVI(a=0.0106, b=0.0729, rho=-0.5, m=0.0583, sigma=0.1010)`` at T = 0.5,
shared with the Note-07 edition suite.  The hero figure reads the standing
real-data export ``tmp/volfit_surfaces_20260718_1324.json`` (SPY, Massive).

Outputs, written next to this script:

* ``fig_vsr_three.pdf``  -- THESIS: one number, three integrands (strike /
                            quantile / generator side);
* ``fig_vsr_mass.pdf``   -- where the number lives: cumulative wing mass +
                            truncation convergence of the replication;
* ``fig_vsr_ident.pdf``  -- identifiability: two production models, one quote
                            set, fair strikes 30 bp apart;
* ``fig_vsr_pull.pdf``   -- a var-swap target pulling a fit: smile + density;
* ``fig_vsr_dial.pdf``   -- the relative-weight dial (fraction of node weight);
* ``fig_vsr_audit.pdf``  -- source-PDE audit: analytic dI/dtheta vs FD, and
                            source vs static values across horizons;
* ``fig_vsr_hero.pdf``   -- real SPY term structure of published fair var-swap
                            vols, re-derived by the closed form;
* ``vs_repr_tables.tex`` / ``vs_repr_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from volfit.calib.varswap import (  # noqa: E402
    VS_HALF_WIDTH,
    VS_POINTS,
    VarSwapTarget,
    varswap_total_variance,
)
from volfit.core.black import black_call  # noqa: E402
from volfit.models.localvol import (  # noqa: E402
    AffineVarianceSurface,
    OptionQuote,
    calibrate_affine,
    solve_affine_dupire,
    solve_varswap_source,
    varswap_const,
    varswap_weights,
)
from volfit.models.lqd.basis import LQDParams  # noqa: E402
from volfit.models.lqd.calibrate import calibrate_slice  # noqa: E402
from volfit.models.lqd.quadrature import build_slice  # noqa: E402
from volfit.models.svi_jw.svi import RawSVI  # noqa: E402

setup()
TEAL, BLUE, RUST, AMBER, SLATE, VIOLET, GREEN = (
    PALETTE["teal"], PALETTE["blue"], PALETTE["rust"], PALETTE["amber"],
    PALETTE["muted"], PALETTE["violet"], PALETTE["green"],
)

RAW = RawSVI(a=0.0106, b=0.0729, rho=-0.5, m=0.0583, sigma=0.1010)
T = 0.5
K_QUOTES = np.linspace(-0.35, 0.30, 23)
W_QUOTES = RAW.total_variance(K_QUOTES)

MACROS: list[str] = ["% Auto-generated by gen_vs_representations.py — do not edit."]
NUMBERS: dict = {}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def sci_macro(name: str, value: float) -> None:
    """Emit a tiny value as \\ensuremath{m\\times10^{e}} (house number format)."""
    e = int(np.floor(np.log10(abs(value))))
    m = value / 10.0**e
    MACROS.append(r"\newcommand{\%s}{\ensuremath{%.1f\times10^{%d}}}"
                  % (name, m, e))
    NUMBERS[name] = float(value)


def strike_integrand(w_of_k, k: np.ndarray) -> np.ndarray:
    """The production replication integrand 2 [B + (e^k-1)^-] e^{-k} (varswap.py)."""
    w = np.maximum(np.asarray(w_of_k(k), dtype=float), 1e-12)
    integ = black_call(k, w) * np.exp(-k)
    put = k < 0.0
    integ[put] += 1.0 - np.exp(-k[put])
    return 2.0 * integ


# ---------------------------------------------------------------------------
# The running LQD slice and its two exact numbers (parity with the original).
# ---------------------------------------------------------------------------

BASE = calibrate_slice(K_QUOTES, W_QUOTES, T, n_order=6, reg_lambda=1e-6)
W_VS_CLOSED = BASE.slice.var_swap_strike()
W_VS_REPL = varswap_total_variance(BASE.slice.implied_w)
VOL_CLOSED = float(np.sqrt(W_VS_CLOSED / T))
VOL_REPL = float(np.sqrt(W_VS_REPL / T))


# ---------------------------------------------------------------------------
# The local-vol companion: production affine fit to the same smile (flat-in-t
# scaled term structure), for the generator-side representation.
# ---------------------------------------------------------------------------

XI = np.array([0.0, 0.70, 0.90, 1.00, 1.10, 1.30, 2.20])
TAU = np.array([0.0, 0.25, 0.5])
X_GRID = 0.01 * np.arange(221)
T_GRID = 0.005 * np.arange(101)


def _w_at(t: float, k: np.ndarray) -> np.ndarray:
    return RAW.total_variance(k) * (t / T)


def _t_to(expiry: float) -> np.ndarray:
    return 0.005 * np.arange(int(round(expiry / 0.005)) + 1)


def fit_lv_surface() -> AffineVarianceSurface:
    xs = np.array([0.75, 0.85, 0.92, 1.00, 1.08, 1.20, 1.35])
    quotes = []
    for t in (0.25, 0.5):
        k = np.log(xs)
        prices = black_call(k, _w_at(t, k))
        quotes += [OptionQuote(t=t, x=float(x), price=float(p), tol=2e-4)
                   for x, p in zip(xs, prices)]
    flat = AffineVarianceSurface(t_nodes=TAU, x_nodes=XI,
                                 theta=np.full((TAU.size, XI.size), 0.06))
    cal = calibrate_affine(flat, quotes, X_GRID, T_GRID,
                           reg_lambda=5.0, bounds=(0.005, 0.5))
    return cal.surface


LV = fit_lv_surface()
I_SOURCE, _ = solve_varswap_source(LV, X_GRID, _t_to(T))
Q_W, Q_C = varswap_weights(X_GRID, 0.01), varswap_const(X_GRID, 0.01)


def lv_static(expiry: float, sol=None):
    if sol is None:
        sol = solve_affine_dupire(LV, X_GRID, T_GRID, [expiry])
        return float(Q_W @ sol.prices[0] + Q_C)
    return sol


# ---------------------------------------------------------------------------
# Figure 1 (thesis): one number, three integrands.
# ---------------------------------------------------------------------------


def figure_three() -> None:
    macro("vsrclosed", "%.2f", 100 * VOL_CLOSED)
    macro("vsrrepl", "%.2f", 100 * VOL_REPL)
    macro("vsragreebp", "%.2f", 1e4 * abs(VOL_CLOSED - VOL_REPL))
    vol_lv = float(np.sqrt(I_SOURCE / T))
    macro("vsrlvvol", "%.2f", 100 * vol_lv)
    macro("vsrlvgapbp", "%.0f", 1e4 * abs(vol_lv - VOL_CLOSED))

    fig, axes = plt.subplots(1, 3, figsize=(7.9, 2.9))

    ax = axes[0]  # strike side
    kk = np.linspace(-1.25, 1.25, 401)
    integ = strike_integrand(BASE.slice.implied_w, kk)
    ax.fill_between(kk, integ, color=TEAL, alpha=0.20, lw=0)
    ax.plot(kk, integ, color=TEAL, lw=1.8)
    ax.plot(K_QUOTES, strike_integrand(BASE.slice.implied_w, K_QUOTES), "o",
            ms=2.8, color=RUST)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("integrand")
    label_panel(ax, "A")

    ax = axes[1]  # quantile side
    s = BASE.slice
    m = np.abs(s.z) <= 12.0
    integ_z = -2.0 * s.q_z[m] * s.u[m] * (1.0 - s.u[m])
    ax.fill_between(s.z[m], integ_z, 0.0, where=integ_z >= 0, color=TEAL,
                    alpha=0.20, lw=0)
    ax.fill_between(s.z[m], integ_z, 0.0, where=integ_z < 0, color=RUST,
                    alpha=0.20, lw=0)
    ax.plot(s.z[m], integ_z, color=TEAL, lw=1.8)
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.7, ls=":")
    ax.set_xlabel(r"logit coordinate $z$")
    label_panel(ax, "B")

    ax = axes[2]  # generator side
    tt = np.linspace(0.0, T, 60)
    xx = np.linspace(0.72, 1.40, 90)
    nu = np.array([LV.variance(xx, float(t)) for t in tt])
    pc = ax.pcolormesh(xx, tt, nu, cmap="viridis", shading="auto",
                       rasterized=True)
    # Occupation-measure contours: rho = d^2 C / dx^2 from production prices.
    exps = [round(0.02 * i, 2) for i in range(1, 26)]
    sol = solve_affine_dupire(LV, X_GRID, T_GRID, exps)
    dens = np.array([np.gradient(np.gradient(p, 0.01), 0.01)
                     for p in sol.prices])
    mx = (X_GRID >= xx[0]) & (X_GRID <= xx[-1])
    ax.contour(X_GRID[mx], exps, dens[:, mx], levels=[1.0, 3.0],
               colors="white", linewidths=0.9, alpha=0.9)
    ax.plot([1.0], [0.0], marker="v", ms=6, color="white", clip_on=False)
    ax.set_xlabel(r"spot ratio $x$")
    ax.set_ylabel(r"time $t$")
    cb = fig.colorbar(pc, ax=ax, pad=0.02, fraction=0.055)
    cb.ax.tick_params(labelsize=8)
    label_panel(ax, "C")

    fig.subplots_adjust(wspace=0.32)
    save(fig, OUT / "fig_vsr_three.pdf")


# ---------------------------------------------------------------------------
# Figure 2: where the number lives (wing mass) + truncation convergence.
# ---------------------------------------------------------------------------


def figure_mass() -> None:
    k = np.linspace(-VS_HALF_WIDTH, VS_HALF_WIDTH, VS_POINTS)
    integ = strike_integrand(BASE.slice.implied_w, k)
    cum = np.concatenate([[0.0], np.cumsum(0.5 * (integ[1:] + integ[:-1])
                                           * np.diff(k))])
    cum /= cum[-1]
    span = (k >= K_QUOTES[0]) & (k <= K_QUOTES[-1])
    inside = float(np.trapezoid(integ[span], k[span])
                   / np.trapezoid(integ, k))
    macro("vsrwingsharepct", "%.0f", 100 * (1.0 - inside))
    atm = np.abs(k) <= 0.10
    macro("vsratmsharepct", "%.0f",
          100 * float(np.trapezoid(integ[atm], k[atm]) / np.trapezoid(integ, k)))

    # Error budget vs the EXACT closed form: truncation alone (fixed fine
    # spacing dk = 0.001, whose own discretization floor is ~0.007 bp) vs the
    # production rule (801 points, spacing grows with H).  Same production
    # integrator, different grids.
    hws = np.linspace(1.0, 8.0, 29)

    def repl_vol(h: float, pts: int) -> float:
        return float(np.sqrt(varswap_total_variance(
            BASE.slice.implied_w, half_width=h, points=pts) / T))

    fine = np.array([abs(repl_vol(float(h), 2 * int(h / 0.001) + 1)
                         - VOL_CLOSED) for h in hws]) * 1e4
    prod = np.array([abs(repl_vol(float(h), VS_POINTS) - VOL_CLOSED)
                     for h in hws]) * 1e4
    i6 = int(np.argmin(np.abs(hws - 6.0)))
    macro("vsrtruncsixbp", "%.3f", fine[i6])
    macro("vsrtruncplateau", "%.1f", hws[np.argmax(fine < 0.02)])
    macro("vsrprodeightbp", "%.2f", prod[-1])
    macro("vsrreplfinebp", "%.2f",
          1e4 * abs(repl_vol(6.0, 4001) - VOL_CLOSED))

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    disp = np.abs(k) <= 1.4
    ax.axvspan(K_QUOTES[0], K_QUOTES[-1], color=AMBER, alpha=0.14, lw=0,
               label="quoted strikes")
    ax.plot(k[disp], cum[disp], color=TEAL, lw=2.0,
            label="cumulative share of $w_{\\mathrm{vs}}$")
    ax.axhline(1.0, color=PALETTE["ink"], lw=0.7, ls=":")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("cumulative share")
    ax.legend(fontsize=8.5, loc="upper left")
    label_panel(ax, "A")
    ax = axes[1]
    ax.semilogy(hws, np.maximum(fine, 1e-5), color=TEAL, lw=1.8,
                label=r"fixed spacing $\Delta k=0.001$ (truncation)")
    ax.semilogy(hws, np.maximum(prod, 1e-5), color=RUST, lw=1.8, ls="--",
                label=r"fixed 801 points ($\Delta k$ grows)")
    ax.plot([6.0], [prod[i6]], "o", ms=6, color=RUST)
    callout(ax, "production grid", (6.0, prod[i6]), (4.1, 6.0))
    ax.set_ylim(1e-5, 30)
    ax.set_xlabel(r"replication half-width $H$")
    ax.set_ylabel("error vs closed form (vol bp)")
    ax.legend(fontsize=8, loc="lower right")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_vsr_mass.pdf")


# ---------------------------------------------------------------------------
# Figure: identifiability — two production models, one quote set.
# ---------------------------------------------------------------------------


def figure_ident() -> None:
    kk = np.linspace(-0.85, 0.72, 200)
    sol = solve_affine_dupire(LV, X_GRID, T_GRID, [T])
    from volfit.core.black import implied_total_variance
    w_lv = implied_total_variance(kk, sol.price_at(0, np.exp(kk)))
    iv_lv = np.sqrt(w_lv / T)
    iv_lqd = BASE.slice.implied_vol(kk, T)
    span = (kk >= K_QUOTES[0]) & (kk <= K_QUOTES[-1])
    macro("vsrlvbellybp", "%.0f",
          1e4 * np.nanmax(np.abs(iv_lv[span] - iv_lqd[span])))
    macro("vsrlvwingpts", "%.1f",
          100 * np.nanmax(np.abs(iv_lv - iv_lqd)))

    fig, ax = plt.subplots(figsize=(6.9, 3.8))
    ax.axvspan(K_QUOTES[0], K_QUOTES[-1], color=AMBER, alpha=0.14, lw=0,
               label="quoted strikes")
    ax.plot(kk, 100 * iv_lqd, color=TEAL, lw=2.0, label="parametric fit (LQD)")
    ax.plot(kk, 100 * iv_lv, color=VIOLET, lw=1.8, ls="--",
            label="local-vol fit, same quotes")
    ax.plot(K_QUOTES, 100 * np.sqrt(W_QUOTES / T), "o", ms=3.4, color=RUST,
            zorder=5, label="option quotes")
    ax.annotate(f"fair strikes {100*VOL_CLOSED:.2f}% vs "
                f"{100*float(np.sqrt(I_SOURCE/T)):.2f}%",
                xy=(0.03, 0.93), xycoords="axes fraction", fontsize=9,
                color=PALETTE["ink"])
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    save(fig, OUT / "fig_vsr_ident.pdf")


# ---------------------------------------------------------------------------
# Figures 3+4: the target's pull, and the relative-weight dial.
# ---------------------------------------------------------------------------


def target_for(pct: float, vol_quote: float) -> VarSwapTarget:
    # Production semantics (service.varswap_target): weight is a fraction of
    # the node's summed option weight (= quote count under equal weights).
    weight = (pct / 100.0) * K_QUOTES.size
    return VarSwapTarget(total_var=float(vol_quote**2 * T), weight=weight, t=T)


VOL_TARGET = VOL_CLOSED + 0.015


def figure_pull() -> None:
    pulled = calibrate_slice(K_QUOTES, W_QUOTES, T, n_order=6, reg_lambda=1e-6,
                             var_swap=target_for(10.0, VOL_TARGET))
    vol_pulled = float(np.sqrt(pulled.slice.var_swap_strike() / T))
    macro("vsrbasefitbp", "%.1f", 1e4 * float(np.max(np.abs(
        BASE.slice.implied_vol(K_QUOTES, T) - np.sqrt(W_QUOTES / T)))))
    macro("vsrtarget", "%.2f", 100 * VOL_TARGET)
    macro("vsrpulled", "%.2f", 100 * vol_pulled)
    macro("vsrpullsharepct", "%.0f",
          100 * (vol_pulled - VOL_CLOSED) / (VOL_TARGET - VOL_CLOSED))
    fit_bp = 1e4 * float(np.max(np.abs(
        pulled.slice.implied_vol(K_QUOTES, T) - np.sqrt(W_QUOTES / T))))
    macro("vsrpullfitbp", "%.0f", fit_bp)

    kk = np.linspace(-0.85, 0.65, 400)
    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.plot(kk, 100 * BASE.slice.implied_vol(kk, T), color=SLATE, lw=1.8,
            label="no target")
    ax.plot(kk, 100 * pulled.slice.implied_vol(kk, T), color=TEAL, ls="--",
            lw=1.9, label="with var-swap target")
    ax.plot(K_QUOTES, 100 * np.sqrt(W_QUOTES / T), "o", ms=3.2, color=RUST,
            label="option quotes", zorder=5)
    ax.axhline(100 * VOL_TARGET, color=RUST, ls=":", lw=1.1)
    ax.annotate("var-swap quote", xy=(0.02, 100 * VOL_TARGET + 0.25),
                fontsize=8.5, color=RUST)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "A")
    ax = axes[1]
    for res, col, ls, lab in ((BASE, SLATE, "-", "no target"),
                              (pulled, TEAL, "--", "with target")):
        x, f = res.slice.density()
        m = (x >= -1.6) & (x <= 1.2) & (f > 0)
        ax.semilogy(x[m], f[m], color=col, ls=ls, lw=1.8, label=lab)
    ax.set_xlabel(r"log return $x$")
    ax.set_ylabel(r"density $f_X$ (log scale)")
    ax.set_ylim(1e-6, 5)
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_vsr_pull.pdf")


def figure_dial() -> None:
    pcts = np.array([2.5, 5.0, 7.5, 10.0, 15.0, 20.0, 30.0, 40.0, 50.0])
    vols = []
    for p in pcts:
        res = calibrate_slice(K_QUOTES, W_QUOTES, T, n_order=6,
                              reg_lambda=1e-6,
                              var_swap=target_for(float(p), VOL_TARGET))
        vols.append(np.sqrt(res.slice.var_swap_strike() / T))
    vols = np.array(vols)

    fig, ax = plt.subplots(figsize=(6.9, 3.7))
    ax.plot(pcts, 100 * vols, "o-", ms=4.5, color=TEAL, lw=1.8)
    ax.axhline(100 * VOL_TARGET, color=RUST, ls=":", lw=1.1)
    ax.axhline(100 * VOL_CLOSED, color=SLATE, ls=":", lw=1.1)
    ax.annotate("the quote", xy=(41, 100 * VOL_TARGET + 0.04), fontsize=8.5,
                color=RUST)
    ax.annotate("natural fair strike (no target)", xy=(28, 100 * VOL_CLOSED + 0.04),
                fontsize=8.5, color=SLATE)
    ax.axvline(10.0, color=SLATE, lw=0.8, ls="--")
    ax.annotate("shipped default 10%", xy=(10.6, 100 * VOL_CLOSED + 0.42),
                fontsize=8.5, color=SLATE)
    ax.set_xlabel(r"var-swap weight (% of node option weight)")
    ax.set_ylabel("fitted fair var-swap vol (%)")
    save(fig, OUT / "fig_vsr_dial.pdf")


# ---------------------------------------------------------------------------
# Figure 5: the source-PDE audit (sensitivities + values across horizons).
# ---------------------------------------------------------------------------


def figure_audit() -> None:
    _, d_i = solve_varswap_source(LV, X_GRID, _t_to(T), sensitivities=True)
    eps = 1e-7
    flat = LV.theta.ravel()
    fd = np.empty_like(d_i)
    for n in range(flat.size):
        th = flat.copy()
        th[n] += eps
        ip, _ = solve_varswap_source(LV.with_theta(th), X_GRID, _t_to(T))
        th[n] -= 2 * eps
        im, _ = solve_varswap_source(LV.with_theta(th), X_GRID, _t_to(T))
        fd[n] = (ip - im) / (2 * eps)
    # Two t = 0 far-wing corners have true sensitivity ~1e-11 (no path mass);
    # relative error is meaningful only on nodes the horizon actually sees.
    live = np.abs(fd) > 1e-6 * np.abs(fd).max()
    sci_macro("vsrsensabs", float(np.max(np.abs(d_i - fd))))
    sci_macro("vsrsensrel",
              float(np.max(np.abs(d_i[live] - fd[live]) / np.abs(fd[live]))))
    macro("vsrsenslive", "%d", int(live.sum()))
    macro("vsrsenstotal", "%d", int(fd.size))

    exps = [0.1, 0.2, 0.3, 0.4, 0.5]
    sol = solve_affine_dupire(LV, X_GRID, T_GRID, exps)
    i_static = np.array([float(Q_W @ p + Q_C) for p in sol.prices])
    i_source = np.array([solve_varswap_source(LV, X_GRID, _t_to(e))[0]
                         for e in exps])
    gap_bp = 1e4 * np.max(np.abs(i_source - i_static) / np.array(exps))
    macro("vsrlvagreebp", "%.2f", gap_bp)

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    lo = min(np.abs(fd[live]).min(), np.abs(d_i[live]).min())
    hi = max(np.abs(fd[live]).max(), np.abs(d_i[live]).max())
    ax.loglog([lo, hi], [lo, hi], color=PALETTE["ink"], lw=0.8, ls=":")
    ax.loglog(np.abs(fd[live]), np.abs(d_i[live]), "o", ms=4.5, color=TEAL,
              mfc="none")
    ax.set_xlabel(r"finite-difference $|\partial I/\partial\theta_\ell|$")
    ax.set_ylabel(r"analytic $|\partial I/\partial\theta_\ell|$")
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(exps, i_static, "s", ms=6, color=RUST, mfc="none",
            label=r"static $1/K^2$ replication")
    ax.plot(exps, i_source, "o-", ms=4, color=TEAL, lw=1.6,
            label="source PDE $g(0,1)$")
    ax.set_xlabel(r"horizon $T$")
    ax.set_ylabel(r"total variance $I(T)$")
    ax.legend(fontsize=8.5, loc="upper left")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_vsr_audit.pdf")


# ---------------------------------------------------------------------------
# Figure 6 (hero): real SPY published fair strikes, re-derived.
# ---------------------------------------------------------------------------


def figure_hero() -> None:
    fixture = REPO / "tmp" / "volfit_surfaces_20260718_1324.json"
    if not fixture.exists():
        raise FileNotFoundError(
            f"standing reference export not found: {fixture} — regenerate via "
            "the app's surfaces export (see memory: reference-live-fixture)")
    doc = json.loads(fixture.read_text(encoding="utf-8"))
    spy = next(tk for tk in doc["tickers"] if tk["ticker"] == "SPY")
    ts, published, rebuilt, atm = [], [], [], []
    for node in spy["nodes"]:
        p = node["lqdParams"]
        s = build_slice(LQDParams(L=p["L"], R=p["R"], a=np.array(p["a"])))
        ts.append(node["t"])
        published.append(node["varSwapVol"])
        rebuilt.append(float(np.sqrt(s.var_swap_strike() / node["t"])))
        ks = np.array([c["k"] for c in node["curve"]])
        ivs = np.array([c["iv"] for c in node["curve"]])
        atm.append(float(np.interp(0.0, ks, ivs)))
    ts, published = np.array(ts), np.array(published)
    rebuilt, atm = np.array(rebuilt), np.array(atm)
    macro("vsrheroagreebp", "%.2f", 1e4 * np.max(np.abs(rebuilt - published)))
    macro("vsrherospreadbp", "%.0f", 1e4 * np.max(rebuilt - atm))
    macro("vsrheronodes", "%d", ts.size)

    fig, ax = plt.subplots(figsize=(6.9, 3.8))
    ax.semilogx(ts, 100 * published, "o-", ms=5, color=TEAL, lw=1.8,
                label="published fair var-swap vol")
    ax.semilogx(ts, 100 * rebuilt, "x", ms=7, color=RUST, mew=1.6,
                label="closed form $-2\\,\\mathbb{E}[X]$, re-derived")
    ax.semilogx(ts, 100 * atm, "s--", ms=4, color=SLATE, lw=1.4,
                label="ATM implied vol")
    ax.set_xlabel(r"expiry $T$ (years, log scale)")
    ax.set_ylabel("volatility (%)")
    ax.legend(fontsize=8.5, loc="lower right")
    save(fig, OUT / "fig_vsr_hero.pdf")


# ---------------------------------------------------------------------------
# Appendix D verification: the listings against production.
# ---------------------------------------------------------------------------


def listing_replication(implied_w, half=6.0, points=801):
    k = np.linspace(-half, half, points)
    w = np.maximum(implied_w(k), 1e-12)
    integ = black_call(k, w) * np.exp(-k)
    put = k < 0
    integ[put] += 1 - np.exp(-k[put])
    return 2.0 * np.trapezoid(integ, k)


def listing_var_swap_strike(z, q_z, u):
    return -2.0 * np.trapezoid(q_z * u * (1 - u), z)


def verify_listings() -> None:
    d1 = abs(listing_replication(BASE.slice.implied_w)
             - varswap_total_variance(BASE.slice.implied_w))
    s = BASE.slice
    d2 = abs(listing_var_swap_strike(s.z, s.q_z, s.u) - s.var_swap_strike())
    macro("vsrrefagree", "%.0f", np.floor(np.log10(max(d1, d2, 1e-17))))


# ---------------------------------------------------------------------------


def main() -> None:
    figure_three()
    print("three done")
    figure_mass()
    print("mass done")
    figure_ident()
    print("ident done")
    figure_pull()
    print("pull done")
    figure_dial()
    print("dial done")
    figure_audit()
    print("audit done")
    figure_hero()
    print("hero done")
    verify_listings()

    macro("vsrhalfwidth", "%.0f", VS_HALF_WIDTH)
    macro("vsrpoints", "%d", VS_POINTS)
    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("vsrgencommit", "%s", commit)
    macro("vsrgendate", "%s", date.today().isoformat())

    (OUT / "vs_repr_tables.tex").write_text("\n".join(MACROS) + "\n",
                                            encoding="utf-8")
    (OUT / "vs_repr_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
