"""Figure suite for the unnamed-martingale edition of Note 10 (calendar).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_cal_martingale.py

Every fit, floor, repair and violation number is produced by PRODUCTION
machinery (``volfit.calib.calendar``, the LQD/SVI calibrators, the sequential
``calibrate_surface`` and the symmetric ``calibrate_surface_symmetric``);
local formulae define only the synthetic targets.  The acute phantom-drag
scenario reproduces the literals of the shipped confinement lock
(``tests/test_calendar_confinement.py``); the overlay phantom reproduces
``tests/test_overlay_calendar.py``.  The hero figure reads the standing
real-data export ``tmp/volfit_surfaces_20260718_1324.json`` (SPY, Massive).

Outputs, written next to this script:

* ``fig_calm_hero.pdf``    -- real SPY: six expiries in convex order where
                              quoted; extrapolations disagreeing beyond;
* ``fig_calm_faces.pdf``   -- THESIS: one ordered pair inspected in all four
                              coordinates (calls / densities / G / w);
* ``fig_calm_drag.pdf``    -- why the floor lives in price space: the
                              phantom drag under four floors;
* ``fig_calm_solver.pdf``  -- who pays: sequential bulldoze vs the symmetric
                              split on a genuine inverted-wing violation;
* ``fig_calm_phantom.pdf`` -- the overlay phantom and the confinement cure
                              (parity with the original edition);
* ``cal_martingale_tables.tex`` / ``cal_martingale_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from scipy.special import expit  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from volfit.calib import ExpiryQuotes, calibrate_surface  # noqa: E402
from volfit.calib.calendar import (  # noqa: E402
    calendar_floor_targets,
    calendar_violation,
    calendar_violation_windowed,
    common_support,
    confined_calendar_floor,
    variance_floor_grid,
    variance_floor_grid_from,
    variance_floor_targets,
)
from volfit.calib.symmetric import calibrate_surface_symmetric  # noqa: E402
from volfit.models.lqd.basis import LQDParams  # noqa: E402
from volfit.models.lqd.calibrate import calibrate_slice  # noqa: E402
from volfit.models.lqd.quadrature import build_slice  # noqa: E402
from volfit.models.svi_jw.calibrate import calibrate_svi  # noqa: E402
from volfit.models.svi_jw.svi import RawSVI  # noqa: E402

setup()
TEAL, BLUE, RUST, AMBER, SLATE, VIOLET, GREEN = (
    PALETTE["teal"], PALETTE["blue"], PALETTE["rust"], PALETTE["amber"],
    PALETTE["muted"], PALETTE["violet"], PALETTE["green"],
)

MACROS: list[str] = ["% Auto-generated by gen_cal_martingale.py — do not edit."]
NUMBERS: dict = {}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def sci_macro(name: str, value: float) -> None:
    """Emit a tiny value as \\ensuremath{m\\times10^{e}} (house format)."""
    v = max(abs(value), 1e-17)
    e = int(np.floor(np.log10(v)))
    m = v / 10.0**e
    MACROS.append(r"\newcommand{\%s}{\ensuremath{%.1f\times10^{%d}}}"
                  % (name, m, e))
    NUMBERS[name] = float(value)


def max_iv_err_bp(res, k, w, t) -> float:
    return 1e4 * float(np.max(np.abs(res.slice.implied_vol(k, t)
                                     - np.sqrt(w / t))))


# ---------------------------------------------------------------------------
# Figure 1 (hero): the promise held live, on the real SPY surface.
# ---------------------------------------------------------------------------


def figure_hero() -> None:
    fixture = REPO / "tmp" / "volfit_surfaces_20260718_1324.json"
    if not fixture.exists():
        raise FileNotFoundError(
            f"standing reference export not found: {fixture} — regenerate via "
            "the app's surfaces export (see memory: reference-live-fixture)")
    doc = json.loads(fixture.read_text(encoding="utf-8"))
    spy = next(tk for tk in doc["tickers"] if tk["ticker"] == "SPY")
    nodes = []
    for n in spy["nodes"]:
        ks = np.array([c["k"] for c in n["curve"]])
        ws = np.array([c["w"] for c in n["curve"]])
        cols = n["inputs"]["preparedColumns"]
        prep = np.array(n["inputs"]["prepared"], dtype=float)
        kq = prep[:, cols.index("k")]
        nodes.append((n["expiry"], ks, ws, kq.min(), kq.max()))
    macro("calmheronodes", "%d", len(nodes))

    # Adjacent-pair order: margin on the common traded span, crossing beyond.
    margin, phantom = np.inf, 0.0
    for (e1, k1, w1, qlo1, qhi1), (e2, k2, w2, qlo2, qhi2) in zip(nodes, nodes[1:]):
        lo, hi = max(k1.min(), k2.min()), min(k1.max(), k2.max())
        kk = np.linspace(lo, hi, 600)
        diff = np.interp(kk, k1, w1) - np.interp(kk, k2, w2)  # near - far
        tlo, thi = max(qlo1, qlo2), min(qhi1, qhi2)
        m = (kk >= tlo) & (kk <= thi)
        margin = min(margin, -float(diff[m].max()))
        phantom = max(phantom, float(diff.max()))
    macro("calmheromarginbp", "%.1f", 1e4 * margin)
    macro("calmherophantombp", "%.0f", 1e4 * phantom)

    fig, ax = plt.subplots(figsize=(6.9, 4.1))
    cmap = plt.get_cmap("viridis")
    for i, (exp, ks, ws, qlo, qhi) in enumerate(nodes):
        col = cmap(0.12 + 0.75 * i / (len(nodes) - 1))
        ax.semilogy(ks, ws, color=col, lw=1.0, alpha=0.45)
        m = (ks >= qlo) & (ks <= qhi)
        ax.semilogy(ks[m], ws[m], color=col, lw=2.6, label=exp)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"total variance $w(k)$ (log scale)")
    ax.legend(fontsize=7.5, loc="lower left", ncol=2, title="expiry",
              title_fontsize=8)
    callout(ax, "quoted spans: strict convex order\n(thick segments never touch)",
            xy=(0.05, float(np.interp(0.05, nodes[2][1], nodes[2][2]))),
            xytext=(0.25, 3e-3))
    callout(ax, "drawn extrapolations\ndisagree out here",
            xy=(-1.1, float(np.interp(-1.1, nodes[0][1], nodes[0][2]))),
            xytext=(-1.32, 2.5e-1))
    save(fig, OUT / "fig_calm_hero.pdf")


# ---------------------------------------------------------------------------
# Figure 2 (thesis): one ordered pair, four inspection coordinates.
# ---------------------------------------------------------------------------


def smile_w(k, atm_vol, wing, t):
    vol = atm_vol + wing * (np.sqrt(k * k + 0.01) - 0.1) - 0.10 * k
    return (vol**2) * t


K_PAIR = np.linspace(-0.32, 0.28, 21)


def figure_faces() -> None:
    near = calibrate_slice(K_PAIR, smile_w(K_PAIR, 0.20, 0.30, 0.25), 0.25,
                           n_order=6, reg_lambda=1e-6)
    far = calibrate_slice(K_PAIR, smile_w(K_PAIR, 0.21, 0.30, 0.50), 0.50,
                          n_order=6, reg_lambda=1e-6)
    kk = np.linspace(-0.60, 0.50, 300)
    c_n, c_f = near.slice.call_price(kk), far.slice.call_price(kk)
    sci_macro("calmfacesminspread", float(np.min(c_f - c_n)))

    fig, axes = plt.subplots(2, 2, figsize=(7.6, 6.4))
    ax = axes[0, 0]
    spread = 1e4 * (c_f - c_n)
    ax.fill_between(kk, spread, color=TEAL, alpha=0.18, lw=0)
    ax.plot(kk, spread, color=TEAL, lw=1.9)
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8, ls=":")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"calendar spread $C_{T_2}-C_{T_1}$ ($10^{-4}$)")
    ax.set_ylim(bottom=-6)
    label_panel(ax, "A")
    ax = axes[0, 1]
    for res, col, lab in ((near, SLATE, "near"), (far, TEAL, "far")):
        x, f = res.slice.density()
        m = (x >= -0.8) & (x <= 0.7)
        ax.plot(x[m], f[m], color=col, lw=1.8, label=lab)
    ax.set_xlabel(r"log return $x$")
    ax.set_ylabel(r"density $f_X$")
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "B")
    ax = axes[1, 0]
    u = expit(near.slice.z)
    sel = (u > 0.005) & (u < 0.995)
    gdiff = 1e4 * (far.slice.a_z[sel] - near.slice.a_z[sel])
    ax.fill_between(u[sel], gdiff, color=TEAL, alpha=0.18, lw=0)
    ax.plot(u[sel], gdiff, color=TEAL, lw=1.9)
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8, ls=":")
    ax.set_xlabel(r"quantile level $\alpha$")
    ax.set_ylabel(r"$G_{T_2}-G_{T_1}$ ($10^{-4}$)")
    ax.set_ylim(bottom=-6)
    label_panel(ax, "C")
    ax = axes[1, 1]
    ax.plot(kk, near.slice.implied_w(kk), color=SLATE, lw=1.8, label="near $w$")
    ax.plot(kk, far.slice.implied_w(kk), color=TEAL, lw=1.9, label="far $w$")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"total variance $w(k)$")
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "D")
    fig.subplots_adjust(wspace=0.30, hspace=0.34)
    save(fig, OUT / "fig_calm_faces.pdf")


# ---------------------------------------------------------------------------
# Figure 3: the phantom drag under four floors — why price space.
# The exact acute scenario of the shipped confinement lock.
# ---------------------------------------------------------------------------

T_NEAR, T_FAR = 0.02, 0.25
K_NEAR = np.linspace(-0.06, 0.06, 13)
W_NEAR = 0.0008 + 0.6 * K_NEAR**2
K_FAR = np.linspace(-0.30, 0.30, 25)
W_FAR = 0.010 + 0.004 * K_FAR**2


def figure_drag() -> None:
    near = calibrate_slice(K_NEAR, W_NEAR, t=T_NEAR)
    window = common_support(K_NEAR, K_FAR)
    cz, cfloor = calendar_floor_targets(near.slice)
    q_at_cz = np.interp(cz, near.slice.z, near.slice.q_z)
    win_mask = (q_at_cz >= window[0]) & (q_at_cz <= window[1])
    ck, cpfloor, ctaper = confined_calendar_floor(near.slice, window)

    fits = {
        "free": calibrate_slice(K_FAR, W_FAR, t=T_FAR),
        "full": calibrate_slice(K_FAR, W_FAR, t=T_FAR,
                                calendar_z=cz, calendar_floor=cfloor),
        "win": calibrate_slice(K_FAR, W_FAR, t=T_FAR,
                               calendar_z=cz[win_mask],
                               calendar_floor=cfloor[win_mask]),
        "price": calibrate_slice(K_FAR, W_FAR, t=T_FAR, calendar_k=ck,
                                 calendar_price_floor=cpfloor,
                                 calendar_taper=ctaper),
    }
    errs = {n: max_iv_err_bp(r, K_FAR, W_FAR, T_FAR) for n, r in fits.items()}
    macro("calmdragfreebp", "%.1f", errs["free"])
    macro("calmdragfullbp", "%.0f", errs["full"])
    macro("calmdragwinbp", "%.0f", errs["win"])
    macro("calmdragpricebp", "%.1f", errs["price"])

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.25, 1.0]})
    ax = axes[0]
    kk = np.linspace(-0.34, 0.34, 400)
    ax.axvspan(window[0], window[1], color=AMBER, alpha=0.16, lw=0,
               label="common support")
    ax.plot(kk, near.slice.implied_w(kk), color=RUST, lw=1.8,
            label="acute near slice (fit + extrapolation)")
    ax.plot(kk, np.interp(kk, K_FAR, W_FAR), color=TEAL, lw=1.8,
            label="far slice quotes (true)")
    ax.plot(K_NEAR, W_NEAR, "o", ms=3.0, color=RUST)
    ax.plot(K_FAR, W_FAR, "o", ms=3.0, color=TEAL)
    ax.set_ylim(0, 0.028)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"total variance $w(k)$")
    ax.legend(fontsize=8, loc="upper center")
    label_panel(ax, "A")
    ax = axes[1]
    names = ["no floor", "full-grid\n$G$ floor", "$z$-windowed\n$G$ floor",
             "confined\nprice floor"]
    vals = [errs["free"], errs["full"], errs["win"], errs["price"]]
    cols = [SLATE, RUST, AMBER, TEAL]
    bars = ax.bar(names, vals, color=cols, width=0.62)
    for b, v in zip(bars, vals):
        ax.annotate(f"{v:.0f}", xy=(b.get_x() + b.get_width() / 2, v),
                    xytext=(0, 3), textcoords="offset points", ha="center",
                    fontsize=8.5)
    ax.set_ylabel("far-fit worst quote error (vol bp)")
    ax.tick_params(axis="x", labelsize=8)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_calm_drag.pdf")


# ---------------------------------------------------------------------------
# Figure 4: who pays — sequential bulldoze vs the symmetric split.
# ---------------------------------------------------------------------------


def figure_solver() -> None:
    t_n, t_f = 0.25, 0.50
    w_n = smile_w(K_PAIR, 0.30, 0.60, t_n)
    w_f = smile_w(K_PAIR, 0.20, 0.25, t_f)
    quotes = [ExpiryQuotes(t=t_n, k=K_PAIR, w=w_n),
              ExpiryQuotes(t=t_f, k=K_PAIR, w=w_f)]

    free_n = calibrate_slice(K_PAIR, w_n, t_n)
    free_f = calibrate_slice(K_PAIR, w_f, t_f)
    macro("calmviolfree", "%.4f",
          calendar_violation(free_n.slice, free_f.slice))

    seq = calibrate_surface(quotes, enforce_calendar=True)
    sym_fit, repair = calibrate_surface_symmetric(quotes)
    sym_slices = [build_slice(LQDParams.from_vector(th))
                  for th in repair.thetas]
    window = common_support(K_PAIR, K_PAIR)
    sci_macro("calmviolcured", max(0.0, calendar_violation_windowed(
        sym_slices[0], sym_slices[1], window)))

    def err_bp(slice_, w, t):
        return 1e4 * float(np.max(np.abs(slice_.implied_vol(K_PAIR, t)
                                         - np.sqrt(w / t))))

    seq_e = [err_bp(seq.results[0].slice, w_n, t_n),
             err_bp(seq.results[1].slice, w_f, t_f)]
    sym_e = [err_bp(sym_slices[0], w_n, t_n),
             err_bp(sym_slices[1], w_f, t_f)]
    macro("calmseqnearbp", "%.1f", seq_e[0])
    macro("calmseqfarbp", "%.0f", seq_e[1])
    macro("calmsymnearbp", "%.0f", sym_e[0])
    macro("calmsymfarbp", "%.0f", sym_e[1])

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.0, 1.25]})
    ax = axes[0]
    x = np.arange(2)
    ax.bar(x - 0.18, seq_e, width=0.34, color=RUST, label="sequential")
    ax.bar(x + 0.18, sym_e, width=0.34, color=TEAL, label="symmetric")
    ax.set_xticks(x, ["near expiry", "far expiry"])
    ax.set_ylabel("worst quote error (vol bp)")
    ax.legend(fontsize=8.5, loc="upper left")
    label_panel(ax, "A")
    ax = axes[1]
    kk = np.linspace(-0.40, 0.34, 300)
    ax.plot(kk, free_n.slice.implied_w(kk), color=SLATE, lw=1.2, ls=":",
            label="free fits (crossing)")
    ax.plot(kk, free_f.slice.implied_w(kk), color=SLATE, lw=1.2, ls=":")
    wn_free, wf_free = free_n.slice.implied_w(kk), free_f.slice.implied_w(kk)
    ax.fill_between(kk, wn_free, wf_free, where=wf_free < wn_free,
                    color=RUST, alpha=0.15, lw=0)
    ax.plot(kk, sym_slices[1].implied_w(kk), color=TEAL, lw=2.4,
            label="far, symmetric repair")
    ax.plot(kk, sym_slices[0].implied_w(kk), color=RUST, lw=1.6, ls="--",
            label="near, symmetric repair (coincides)")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"total variance $w(k)$")
    ax.legend(fontsize=8, loc="upper right")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.28)
    save(fig, OUT / "fig_calm_solver.pdf")


# ---------------------------------------------------------------------------
# Figure 5: the overlay phantom and the confinement cure (parity).
# ---------------------------------------------------------------------------


def figure_phantom() -> None:
    near_steep = RawSVI(a=0.01, b=0.20, rho=-0.7, m=0.0, sigma=0.05)
    far_flat = RawSVI(a=0.08, b=0.08, rho=-0.3, m=0.0, sigma=0.10)
    k_narrow = np.linspace(-0.25, 0.20, 21)
    w_far = far_flat.total_variance(k_narrow)
    t = 1.0

    wide_k, wide_w = variance_floor_targets(near_steep, variance_floor_grid())
    wide = calibrate_svi(k_narrow, w_far, t=t, calendar_k=wide_k,
                         calendar_floor=wide_w)
    data_k, data_w = variance_floor_targets(
        near_steep, variance_floor_grid_from(k_narrow))
    data = calibrate_svi(k_narrow, w_far, t=t, calendar_k=data_k,
                         calendar_floor=data_w)
    macro("calmphantomwidebp", "%.0f", wide.max_iv_error * 1e4)
    macro("calmphantomdatabp", "%.1f", data.max_iv_error * 1e4)

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.2, 1.0]})
    ax = axes[0]
    kk = np.linspace(-1.05, 1.05, 400)
    wn, wf = near_steep.total_variance(kk), far_flat.total_variance(kk)
    ax.axvspan(k_narrow.min(), k_narrow.max(), color=AMBER, alpha=0.16, lw=0)
    ax.plot(kk, wn, color=RUST, lw=1.8, label="near (steep wings)")
    ax.plot(kk, wf, color=TEAL, lw=1.8, label="far (flat, true)")
    ax.fill_between(kk, wf, wn, where=wn > wf, color=RUST, alpha=0.13, lw=0)
    ax.plot(wide_k, np.full(wide_k.size, -0.006), "|", ms=5, color=SLATE,
            label="wide floor grid")
    ax.plot(data_k, np.full(data_k.size, -0.022), "|", ms=5, color=TEAL,
            label="confined floor grid")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"total variance $w(k)$")
    ax.legend(fontsize=8, loc="center right")
    callout(ax, "phantom: near extrapolates\nabove far, no data here",
            xy=(-0.80, float(near_steep.total_variance(-0.80))),
            xytext=(-0.55, 0.31))
    label_panel(ax, "A")
    ax = axes[1]
    kz = np.linspace(k_narrow.min() - 0.03, k_narrow.max() + 0.03, 200)
    ax.scatter(k_narrow, 100 * np.sqrt(w_far / t), s=14, color="black",
               zorder=5, label="far quotes")
    ax.plot(kz, 100 * wide.raw.implied_vol(kz, t), color=RUST, ls="--",
            lw=1.8, label="fit under the wide floor")
    ax.plot(kz, 100 * data.raw.implied_vol(kz, t), color=TEAL, lw=1.9,
            label="fit under the confined floor")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(fontsize=8, loc="upper right")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_calm_phantom.pdf")


# ---------------------------------------------------------------------------
# Appendix verification: the confined-grid listing against production.
# ---------------------------------------------------------------------------


def listing_variance_floor_grid_from(k_quotes, n=41):
    k = np.asarray(k_quotes, float)
    if k.size == 0:
        return variance_floor_grid()
    return np.linspace(float(k.min()), float(k.max()), n)


def verify_listings() -> None:
    d = 0.0
    for probe in (np.linspace(-0.25, 0.20, 21), np.array([0.05]),
                  np.array([])):
        a = listing_variance_floor_grid_from(probe)
        b = variance_floor_grid_from(probe)
        d = max(d, float(np.max(np.abs(a - b))))
    sci_macro("calmrefagree", d)


# ---------------------------------------------------------------------------


def main() -> None:
    figure_hero()
    print("hero done")
    figure_faces()
    print("faces done")
    figure_drag()
    print("drag done")
    figure_solver()
    print("solver done")
    figure_phantom()
    print("phantom done")
    verify_listings()

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("calmgencommit", "%s", commit)
    macro("calmgendate", "%s", date.today().isoformat())

    (OUT / "cal_martingale_tables.tex").write_text("\n".join(MACROS) + "\n",
                                                   encoding="utf-8")
    (OUT / "cal_martingale_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
