"""Figure suite for the "Three Priors for a Dark Universe" edition of Note 14.

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_graph_three_priors.py

Every curve, posterior and golden number is produced by the PRODUCTION graph
modules — ``volfit.graph.{build,prior,posterior}`` (smooth field),
``volfit.graph.{message,message_posterior}`` (precision messages) and
``volfit.graph.{temporal_state,directed_state,harmonic_posterior}`` (the
layered dynamic-harmonic mode). Empirical Phase-0 numbers are read from the
STORED design-study artifact ``backend/backtest/results/message_phase0.json``;
Campaign-2 adjudication numbers are quoted VERBATIM from
``backend/backtest/FINDINGS_dynamic_phase5.md`` (HISTORICAL dict below) —
nothing is re-run. The asynchronous A/B replay is asserted against the SAME
golden fixture as the production test suite
(``backend/tests/fixtures/graph_dynamic_golden.json``).

Outputs, written next to this script:

* ``fig_g3p_asyncab.pdf``       -- the A/B staircase: desk path (temporal
                                   state) vs the memoryless symmetric replay;
* ``fig_g3p_smooth.pdf``        -- smooth-field chain propagation + eta reach;
* ``fig_g3p_contract.pdf``      -- means invariant in p, bands not;
* ``fig_g3p_deadinformer.pdf``  -- pairwise vs row form + repeated path;
* ``fig_g3p_compete.pdf``       -- cancel / outvote / beta-mapped vote;
* ``fig_g3p_amplitude.pdf``     -- corroboration curve vs stored slopes;
* ``fig_g3p_hops.pdf``          -- mean pays no toll, variance accumulates;
* ``fig_g3p_calendar.pdf``      -- amplitude shape vs measured gap-flat noise;
* ``fig_g3p_halflife.pdf``      -- residual decay under H + Campaign-2 arms;
* ``fig_g3p_boundary.pdf``      -- Dirichlet clamp vs soft stale demotion;
* ``fig_g3p_decomposition.pdf`` -- four-part identity bars + chi surprise;
* ``fig_g3p_spectrum.pdf``      -- the six-node universe solved three ways;
* ``graph_three_priors_tables.tex`` / ``graph_three_priors_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))
RESULTS = REPO / "backend" / "backtest" / "results"
FIXTURES = REPO / "backend" / "tests" / "fixtures"

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from volfit.graph.beta import beta_matrix, directed_residual_beta  # noqa: E402
from volfit.graph.build import build_graph  # noqa: E402
from volfit.graph.directed_state import (  # noqa: E402
    build_directed_graph,
    directed_pass,
    directed_relation,
    residual_surprise,
)
from volfit.graph.harmonic_posterior import harmonic_posterior  # noqa: E402
from volfit.graph.message import (  # noqa: E402
    MessageEdge,
    anchor_precisions,
    build_message_operator,
    calendar_beta,
    cycle_beta_products,
    expand_calendar_ladder,
    message_edge,
)
from volfit.graph.message_posterior import message_posterior_update  # noqa: E402
from volfit.graph.posterior import posterior_update  # noqa: E402
from volfit.graph.prior import build_increment_prior  # noqa: E402
from volfit.graph.temporal_state import (  # noqa: E402
    empty_residual,
    observation_state,
    residual_dynamics,
    residual_measurement,
    residual_measurement_variance,
)

setup()
TEAL, RUST, AMBER, SLATE, VIOLET, BLUE = (
    PALETTE["teal"], PALETTE["rust"], PALETTE["amber"], PALETTE["muted"],
    PALETTE["violet"], PALETTE["blue"],
)

MACROS: list[str] = ["% Auto-generated by gen_graph_three_priors.py — do not edit."]
NUMBERS: dict = {}
CLAMP = 1e9  # "effectively known informer": huge observation precision

#: Recorded verdicts quoted VERBATIM from FINDINGS_dynamic_phase5.md
#: (Campaign 2, adjudicated 2026-07-23) — historical artifacts, never re-run.
#: ATM RMS bp (full_loo, all pairs); stress deltas bp vs base; zeta stds;
#: wing RMS bp (full_loo / liquid_split vs transport).
HISTORICAL = {
    "gtpcampprior": "286.3", "gtpcampbase": "279.3", "gtpcampmsg": "280.9",
    "gtpcampmemoryless": "280.2", "gtpcamphlone": "285.1",
    "gtpcamphlfive": "290.1", "gtpcamphltwenty": "305.5", "gtpcampdesk": "333.1",
    "gtpstressspike": "-14.7", "gtpstresshigh": "-9.2", "gtpcalmcost": "+6.2",
    "gtpzetahl": "1.68", "gtpzetabase": "0.74", "gtpzetamsg": "2.07",
    "gtpwingfull": "131", "gtpwingtransport": "126",
    "gtpwingliquid": "193", "gtpwingliquidtransport": "121",
    "gtpcamppairs": "21,958",
    # Smooth-field record + idio floor (FINDINGS_graph_loo.md, stored):
    "gtpspikeskilllo": "7.9", "gtpspikeskillhi": "14.2",
    "gtphighskilllo": "3.8", "gtphighskillhi": "7.2",
    "gtpcalmskilllo": "0.7", "gtpcalmskillhi": "0.8",
    "gtpidiobefore": "1.91", "gtpidiobeforetwo": "1.85",
    "gtpidioafter": "1.02", "gtpidioaftertwo": "1.03",
}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def sci_macro(name: str, value: float) -> None:
    v = max(abs(value), 1e-17)
    e = int(np.floor(np.log10(v)))
    MACROS.append(r"\newcommand{\%s}{\ensuremath{%.1f\times10^{%d}}}"
                  % (name, v / 10.0**e, e))
    NUMBERS[name] = float(value)


def solve(nodes, edges, lit, z_lit, r=CLAMP, kappa=None, handle=0):
    """Production message operator + posterior for one handle."""
    op = build_message_operator(nodes, edges, handle=handle)
    obs = np.array([nodes.index(n) for n in lit])
    return op, message_posterior_update(
        op, obs, np.asarray(z_lit, dtype=float),
        np.full(obs.size, float(r)), anchor_precision=kappa,
    )


# ---------------------------------------------------------------------------
# Figure 1: the asynchronous A/B story — desk path vs the memoryless mirror.
# ---------------------------------------------------------------------------


def _replay(obs_a, obs_b, snapshots, beta, dynamics):
    """Doc §10 Steps 2-4 through the PRODUCTION state objects — the exact
    replay of tests/test_graph_temporal_state.py::_replay: source lease
    (carried flat, D4), advance-then-update ordering, hard certified residual
    updates (D3), published mark = beta * m_source + u."""
    res = empty_residual("cfg-v1")
    a_state = None
    a_marks, b_marks, updates, u_trace = [], [], [], []
    for t in snapshots:
        if t in obs_a:
            a_state = observation_state([obs_a[t], 0, 0], 1e-4, t, f"A@{t}")
        m_a, _ = a_state.carried_to(t)
        res = res.advance(t, dynamics)
        if t in obs_b:
            e = residual_measurement([obs_b[t], 0, 0], beta, m_a)
            r = residual_measurement_variance(1e-4, beta, a_state.variance, 1e4)
            res = res.updated_hard(e, r, t, f"B@{t}")
            updates.append(t)
        a_marks.append(m_a[0])
        b_marks.append(beta * m_a[0] + res.mean[0])
        u_trace.append(res.mean[0])
    return a_marks, b_marks, updates, u_trace


def _smooth_replay(obs_a, obs_b, snapshots):
    """The same observation sequence through the PRODUCTION smooth-field
    solver, run per snapshot with NO memory: only the nodes observed exactly
    at t are lit; when nothing is lit the previous PUBLISHED marks are carried
    in the plotting arrays only — the solver itself forgets everything."""
    graph = build_graph(["A", "B"], {("A", "B"): 1.0, ("B", "A"): 1.0})
    prior = build_increment_prior(graph, kappa=1e-3, eta=50.0)
    a_pub, b_pub = [], []
    for t in snapshots:
        idx, vals = [], []
        if t in obs_a:
            idx.append(0); vals.append(obs_a[t])
        if t in obs_b:
            idx.append(1); vals.append(obs_b[t])
        if not idx:  # dark snapshot: republish (display only — no state)
            assert a_pub, "first snapshot must be lit to seed the published arrays"
            a_pub.append(a_pub[-1]); b_pub.append(b_pub[-1])
            continue
        post = posterior_update(
            prior, np.zeros(2), np.full(2, 2.0),
            np.array(idx), np.array(vals), np.full(len(idx), 1e6),
        )
        a_pub.append(post.mean[0]); b_pub.append(post.mean[1])
    return a_pub, b_pub


def figure_asyncab() -> None:
    fx = json.loads((FIXTURES / "graph_dynamic_golden.json").read_text())["async_ab"]
    obs_a = {float(k): v for k, v in fx["obs_a"].items()}
    obs_b = {float(k): v for k, v in fx["obs_b"].items()}
    snaps = fx["snapshots"]
    a, b, _, u = _replay(obs_a, obs_b, snaps, fx["beta"], residual_dynamics())
    assert np.max(np.abs(np.array(a) - fx["expected_a"])) < 1e-9, \
        "desk-path replay diverged from the golden expected_a"
    assert np.max(np.abs(np.array(b) - fx["expected_b"])) < 1e-9, \
        "desk-path replay diverged from the golden expected_b"
    i35, i40 = snaps.index(3.5), snaps.index(4.0)
    assert abs(u[i35] - fx["expected_u_after_3_5"]) < 1e-9, \
        "the -3 residual at t=3.5 diverged from the golden fixture"
    macro("gtpabresidual", "%.0f", u[i35])
    macro("gtpabbfour", "%.0f", b[i40])

    a_sm, b_sm = _smooth_replay(obs_a, obs_b, snaps)
    assert abs(a_sm[i35] - obs_b[3.5]) < 0.05, \
        "memoryless symmetric path should drag dark A to B's print at 3.5"
    assert abs(b_sm[i40] - obs_a[4.0]) < 0.05, \
        "memoryless symmetric path should forget the -3 dislocation at 4.0"
    macro("gtpabbadafive", "%.1f", a_sm[i35])
    macro("gtpabbadbfour", "%.1f", b_sm[i40])

    fig, axes = plt.subplots(1, 2, figsize=WIDE, sharey=True)
    ax = axes[0]
    ax.step(snaps, a, where="post", color=TEAL, lw=3.6, alpha=0.5,
            label="A (lease carried)")
    ax.step(snaps, b, where="post", color=AMBER, lw=1.8,
            label="B (mark = $\\beta m_A + u$)")
    ax.scatter(sorted(obs_b), [obs_b[t] for t in sorted(obs_b)], s=70,
               marker="D", color=RUST, zorder=6, label="B observed")
    callout(ax, "B prints 10 against A at 13:\nresidual $u=-3$ is born and kept",
            xy=(3.5, 10.1), xytext=(0.4, 8.6))
    ax.set_xlabel("session time $t$")
    ax.set_ylabel("published mark (handle level)")
    ax.set_ylim(8.2, 15.8)
    ax.legend(loc="upper left", fontsize=8.4)
    label_panel(ax, "A")
    ax = axes[1]
    ax.step(snaps, a_sm, where="post", color=TEAL, lw=3.6, alpha=0.5,
            label="A published")
    ax.step(snaps, b_sm, where="post", color=AMBER, lw=1.8, label="B published")
    ax.scatter(sorted(obs_b), [obs_b[t] for t in sorted(obs_b)], s=70,
               marker="D", color=RUST, zorder=6, label="B observed")
    callout(ax, "wrong way twice: dark A is\ndragged to 10 at 3.5, then the\n$-3$ is forgotten when A prints",
            xy=(3.55, a_sm[i35] + 0.15), xytext=(0.12, 13.55))
    ax.set_xlabel("session time $t$")
    ax.legend(loc="lower right", fontsize=8.4)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.14)
    save(fig, OUT / "fig_g3p_asyncab.pdf")


# ---------------------------------------------------------------------------
# Figure 2: assert smoothness — chain propagation and the reach dial.
# ---------------------------------------------------------------------------


def _solve_chain(eta: float):
    """8-node calendar chain, symmetric unit trust, one lit node (+1)."""
    tenors = ["1W", "1M", "2M", "3M", "6M", "9M", "1Y", "2Y"]
    weights: dict[tuple[str, str], float] = {}
    for near, far in zip(tenors, tenors[1:]):
        weights[(near, far)] = 1.0   # far informs near
        weights[(far, near)] = 1.0   # near informs far
    graph = build_graph(tenors, weights)
    prior = build_increment_prior(graph, kappa=0.2, eta=eta)
    post = posterior_update(
        prior, np.zeros(8), np.full(8, 2.0),
        np.array([3]), np.array([1.0]), np.array([100.0]),
    )
    return tenors, post


def figure_smooth() -> None:
    lit = 3
    tenors, post = _solve_chain(eta=6.0)
    assert abs(post.mean[lit]) > 1e-9, "lit node lost its own innovation"
    std = np.sqrt(post.marginal_variance)
    macro("gtpsmoothfar", "%.0f", 100.0 * post.mean[-1] / post.mean[lit])
    macro("gtpsmoothlitsd", "%.2f", std[lit])
    macro("gtpsmoothfarsd", "%.2f", std[-1])

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.25, 1.0]})
    ax = axes[0]
    idx = np.arange(len(tenors))
    lo, hi = post.credible_band(z_score=1.96)
    ax.fill_between(idx, lo, hi, color=TEAL, alpha=0.15, label="95% band")
    ax.plot(idx, post.mean, "-o", color=TEAL, label="posterior mean")
    ax.scatter([lit], [post.mean[lit]], s=90, color=RUST, zorder=6,
               label="lit calibration")
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8)
    ax.set_xticks(idx, tenors)
    ax.set_xlabel("calendar node")
    ax.set_ylabel("posterior innovation")
    callout(ax, "no contract, only smoothness:\nthe move fades with distance",
            xy=(5.9, post.mean[6] + 0.06), xytext=(3.6, 0.95))
    ax.legend(loc="upper left", fontsize=8.6)
    label_panel(ax, "A")

    ax = axes[1]
    etas = np.array([0.5, 2.0, 6.0, 20.0, 60.0])
    far, sd_lit, sd_far = [], [], []
    for e in etas:
        _, p = _solve_chain(eta=float(e))
        assert abs(p.mean[lit]) > 1e-9, "lit node lost its own innovation"
        far.append(100.0 * p.mean[-1] / p.mean[lit])
        s = np.sqrt(p.marginal_variance)
        sd_lit.append(s[lit]); sd_far.append(s[-1])
    macro("gtpsmoothfarsixty", "%.0f", far[-1])
    l_far, = ax.semilogx(etas, far, "o-", color=TEAL, lw=2.0,
                         label="far-node transfer (%)")
    ax.set_xlabel(r"directed smoothness $\eta$")
    ax.set_ylabel("far-node transfer (% of lit)", color=TEAL)
    ax2 = ax.twinx()
    ax2.grid(False)
    ax2.spines["right"].set_visible(True)
    l_lit, = ax2.semilogx(etas, sd_lit, "s--", color=SLATE, lw=1.4, ms=4,
                          label="lit sd")
    l_fsd, = ax2.semilogx(etas, sd_far, "^--", color=VIOLET, lw=1.4, ms=4,
                          label="far sd")
    ax2.set_ylabel("posterior sd", color=SLATE)
    handles = [l_far, l_lit, l_fsd]
    ax.legend(handles, [h.get_label() for h in handles], loc="center right",
              fontsize=8.4)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.44)
    save(fig, OUT / "fig_g3p_smooth.pdf")


# ---------------------------------------------------------------------------
# Figure 3: the three-expiry contract (means invariant in p; ported from the
# messages edition — spec §8.2 / golden 21.1).
# ---------------------------------------------------------------------------


def figure_contract() -> None:
    nodes = ["3M", "6M", "1Y"]
    p_grid = np.geomspace(1e2, 1e5, 25)
    means, sds = [], []
    for p in p_grid:
        edges = [
            MessageEdge("3M", "6M", p, (calendar_beta(0.25, 0.5),) * 3, "calendar"),
            MessageEdge("6M", "1Y", p, (calendar_beta(0.5, 1.0),) * 3, "calendar"),
        ]
        _, post = solve(nodes, edges, ["6M"], [1.0])
        means.append([post.mean[0], post.mean[2]])
        sds.append(np.sqrt([post.marginal_variance[0], post.marginal_variance[2]]))
    means = np.array(means)
    sds = np.array(sds)
    macro("gtpthreem", "%.2f", means[-1, 0])
    macro("gtponey", "%.2f", means[-1, 1])

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.semilogx(p_grid, means[:, 0], color=TEAL, lw=2.0,
                label=r"$\widehat z_{3M}$ ($\beta=2$)")
    ax.semilogx(p_grid, means[:, 1], color=AMBER, lw=2.0,
                label=r"$\widehat z_{1Y}$ ($\beta=1/2$)")
    ax.set_ylim(0, 2.4)
    ax.set_xlabel("calendar edge precision $p$ (all edges)")
    ax.set_ylabel("posterior innovation (vol pts)")
    callout(ax, "the contract: amplitude is\nnot a function of confidence",
            xy=(3e3, 2.02), xytext=(2.2e2, 1.45))
    ax.legend(loc="center right", fontsize=8.7)
    label_panel(ax, "A")
    ax = axes[1]
    ax.loglog(p_grid, sds[:, 0], color=TEAL, lw=2.0, label="3M posterior sd")
    ax.loglog(p_grid, sds[:, 1], color=AMBER, lw=2.0, label="1Y posterior sd")
    ax.set_xlabel("calendar edge precision $p$ (all edges)")
    ax.set_ylabel("posterior sd (vol units)")
    ax.legend(loc="upper right", fontsize=8.7)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.36)
    save(fig, OUT / "fig_g3p_contract.pdf")


# ---------------------------------------------------------------------------
# Figure 4: the accountant — dead informers and repeated paths (ported).
# ---------------------------------------------------------------------------


def _row_form_transfer(p_lit: float, p_dead: float, anchor: float = 1e-6) -> float:
    """The spec's REJECTED row-normalized operator on the dead-informer
    fixture, solved exactly (local wrong-way reference; production has no
    such code path, deliberately)."""
    q = p_lit + p_dead
    u = np.array([1.0, -p_lit / q, -p_dead / q])
    Q = q * np.outer(u, u) + anchor * np.eye(3)
    r = CLAMP
    Q[1, 1] += r
    b = np.zeros(3)
    b[1] = r * 1.0
    return float(np.linalg.solve(Q, b)[0])


def figure_deadinformer() -> None:
    ratios = np.geomspace(0.1, 100.0, 40)
    p_lit = 1.0e3
    pairwise, rowform = [], []
    for ratio in ratios:
        edges = [message_edge("R", "L", p_lit, 1.0),
                 message_edge("R", "D", p_lit * ratio, 1.0)]
        _, post = solve(["R", "L", "D"], edges, ["L"], [1.0])
        pairwise.append(post.mean[0])
        rowform.append(_row_form_transfer(p_lit, p_lit * ratio))
    i_eq = int(np.argmin(np.abs(ratios - 1.0)))
    macro("gtpdeadhalf", "%.2f", rowform[i_eq])
    macro("gtppairflat", "%.2f", min(pairwise))

    # Repeated path: T hears A directly and through M; A observed at r = p.
    p = 1.0e3
    edges = [message_edge("T", "A", p, 1.0), message_edge("M", "A", p, 1.0),
             message_edge("T", "M", p, 1.0)]
    _, post = solve(["T", "A", "M"], edges, ["A"], [1.0], r=p)
    var_global = float(post.marginal_variance[0])
    v_a = 1.0 / p                       # source posterior variance at r = p
    var_direct = v_a + 1.0 / p          # §12 effective message variance
    var_path = v_a + 1.0 / p + 1.0 / p  # two relation legs
    var_naive = 1.0 / (1.0 / var_direct + 1.0 / var_path)
    macro("gtprepeatvar", "%.2f", var_global * p)
    macro("gtpnaivevar", "%.2f", var_naive * p)
    macro("gtprepeatratio", "%.2f", var_global / var_naive)

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.25, 1.0]})
    ax = axes[0]
    ax.semilogx(ratios, pairwise, color=TEAL, lw=2.2,
                label="pairwise factors (production)")
    ax.semilogx(ratios, rowform, color=RUST, lw=2.0, ls="--",
                label="row-normalized alternative")
    ax.set_ylim(-0.05, 1.15)
    ax.set_xlabel(r"dead informer's configured precision $p_{\mathrm{dead}}/p_{\mathrm{lit}}$")
    ax.set_ylabel(r"receiver transfer $\widehat z_R / z_L$")
    callout(ax, "a dead informer dilutes the row\nform toward zero; the pairwise\nfactor marginalizes it away exactly",
            xy=(20.0, rowform[-8] + 0.03), xytext=(0.14, 0.36))
    ax.legend(loc="lower left", fontsize=8.7)
    label_panel(ax, "A")
    ax = axes[1]
    bars = [1e3 * var_global, 1e3 * var_naive]
    ax.bar([0, 1], bars, width=0.55, color=[TEAL, RUST])
    ax.set_xticks([0, 1], ["global solve\n(production)", "naive message\naccounting"])
    ax.set_ylabel(r"posterior variance at T ($\times p^{-1}$)")
    for i, v in enumerate(bars):
        ax.text(i, v + 0.04, f"{v:.2f}/p", ha="center", fontsize=9.5)
    ax.set_ylim(0, 2.2)
    callout(ax, "two routes, one source: treating\nthem as independent messages\noverstates precision by "
                f"{var_global / var_naive:.0%}$-$1",
            xy=(1.0, bars[1] + 0.06), xytext=(0.02, 1.9))
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_g3p_deadinformer.pdf")


# ---------------------------------------------------------------------------
# Figure 5: competing signals (ported; goldens 21.2 / 21.3 / the +0.75 map).
# ---------------------------------------------------------------------------


def figure_compete() -> None:
    nodes = ["6M", "3M", "1Y"]
    cases = []
    edges = [message_edge("6M", "3M", 1e3, 1.0), message_edge("6M", "1Y", 1e3, 1.0)]
    _, post = solve(nodes, edges, ["3M", "1Y"], [-1.0, 1.0])
    cases.append(("equal $p$, $\\beta=1$", post.mean[0]))
    edges = [message_edge("6M", "3M", 3e3, 1.0), message_edge("6M", "1Y", 1e3, 1.0)]
    _, post = solve(nodes, edges, ["3M", "1Y"], [-1.0, 1.0])
    cases.append(("$p_{3M}=3p$", post.mean[0]))
    edges = [message_edge("6M", "3M", 1e3, calendar_beta(0.5, 0.25)),
             message_edge("6M", "1Y", 1e3, calendar_beta(0.5, 1.0))]
    _, post = solve(nodes, edges, ["3M", "1Y"], [-1.0, 1.0])
    cases.append((r"$\alpha_T=1$ betas", post.mean[0]))
    macro("gtpcompetecancel", "%.2f", cases[0][1])
    macro("gtpcompeteout", "%.2f", cases[1][1])
    macro("gtpcompetebeta", "%.2f", cases[2][1])

    fig, ax = plt.subplots(figsize=(6.9, 3.6))
    x = np.arange(3)
    vals = [c[1] for c in cases]
    ax.bar(x, vals, width=0.5, color=[SLATE, AMBER, TEAL])
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8)
    ax.set_xticks(x, [c[0] for c in cases])
    ax.set_ylabel(r"$\widehat z_{6M}$ (vol pts)")
    for i, v in enumerate(vals):
        ax.text(i, v + (0.05 if v >= 0 else -0.12), f"{v:+.2f}", ha="center",
                fontsize=10)
    ax.set_ylim(-0.8, 1.1)
    callout(ax, "same raw signals $\\mp1$: the betas map\nthem into 6M units before the vote",
            xy=(1.82, vals[2] + 0.02), xytext=(-0.38, 0.82))
    save(fig, OUT / "fig_g3p_compete.pdf")


# ---------------------------------------------------------------------------
# Figure 6: amplitude as a measured level — the corroboration curve (ported).
# ---------------------------------------------------------------------------


def figure_amplitude() -> None:
    study = json.loads((RESULTS / "message_phase0.json").read_text())
    corr = study["corroboration"]
    rho = corr["indexOnly"]["b"]
    measured = {1: corr["indexOnly"]["b"], 2: corr["combinedEqualWeight"]["b"]}
    macro("gtprhoindex", "%.3f", rho)
    macro("gtprhopeer", "%.3f", corr["peersOnly"]["b"])
    macro("gtptwosource", "%.3f", measured[2])
    macro("gtpuplift", "%.0f", 100 * corr["uplift"])
    macro("gtpupliftbar", "%.0f", 100 * corr["upliftBar"])
    macro("gtpphasen", "%d", corr["indexOnly"]["n"])

    ks = np.arange(1, 7)
    transfer = []
    for k in ks:
        nodes = ["X"] + [f"S{i}" for i in range(k)]
        edges = [message_edge("X", f"S{i}", 1e3, 1.0, "broad_index")
                 for i in range(k)]
        kappa = anchor_precisions(nodes, edges, {"broad_index": rho})
        _, post = solve(nodes, edges, [f"S{i}" for i in range(k)],
                        np.ones(k), kappa=kappa)
        transfer.append(post.mean[0])
    transfer = np.array(transfer)
    pred2 = transfer[1]
    macro("gtppredtwo", "%.3f", pred2)
    macro("gtppredgap", "%.1f", 100 * abs(pred2 - measured[2]) / measured[2])

    fig, ax = plt.subplots(figsize=(6.9, 4.0))
    ax.plot(ks, transfer, "o-", ms=6, color=TEAL, lw=2.0,
            label=r"node-linked anchor (production): $k\rho/(1-\rho+k\rho)$")
    ax.axhline(rho, color=RUST, lw=1.7, ls="--",
               label="edge-linked alternative (constant transfer)")
    ax.scatter([1, 2], [measured[1], measured[2]], s=90, marker="D",
               color=PALETTE["ink"], zorder=6,
               label="measured on stored rows (Phase 0)")
    callout(ax,
            "calibrated on the one-source slope alone,\n"
            f"the anchor predicts {pred2:.3f} for two sources;\n"
            f"measured: {measured[2]:.3f} — zero free parameters",
            xy=(2.02, measured[2]), xytext=(2.6, 0.44))
    ax.set_xlabel("number of equal corroborating lit sources $k$")
    ax.set_ylabel("effective transfer per unit message")
    ax.set_ylim(0.30, 0.85)
    ax.legend(loc="upper left", fontsize=8.6)
    save(fig, OUT / "fig_g3p_amplitude.pdf")


# ---------------------------------------------------------------------------
# Figure 7: multi-hop — mean pays no toll, variance accumulates (ported).
# ---------------------------------------------------------------------------


def figure_hops() -> None:
    n_hops = 6
    p = 1.0e3
    nodes = [f"N{i}" for i in range(n_hops + 1)]
    edges = [message_edge(f"N{i+1}", f"N{i}", p, 1.0) for i in range(n_hops)]
    _, post = solve(nodes, edges, ["N0"], [1.0])
    means = post.mean
    sds = np.sqrt(post.marginal_variance)
    hops = np.arange(n_hops + 1)
    predicted_sd = np.sqrt(hops / p)  # §13 accumulation at beta=1, clamped source
    macro("gtphopmean", "%.3f", means[-1])
    macro("gtphopsdgap", "%.4f", float(np.max(np.abs(sds[1:] - predicted_sd[1:]))))

    fig, ax = plt.subplots(figsize=(6.9, 3.8))
    ax.plot(hops, means, "o-", ms=5, color=TEAL, lw=2.0,
            label=r"posterior mean $\widehat z$")
    ax.fill_between(hops, means - 1.96 * sds, means + 1.96 * sds, color=TEAL,
                    alpha=0.14, label=r"95% band ($\pm1.96\,$sd)")
    ax.plot(hops, means + 1.96 * predicted_sd, color=SLATE, lw=1.1, ls=":",
            label=r"accumulation $\sqrt{k/p}$ (exact)")
    ax.plot(hops, means - 1.96 * predicted_sd, color=SLATE, lw=1.1, ls=":")
    callout(ax, "the mean crosses six hops undamped;\nconfidence pays the toll",
            xy=(5.2, means[-1] + 0.005), xytext=(2.7, 0.878))
    ax.set_xlabel("hops from the lit source (chain, $\\beta=1$)")
    ax.set_ylabel("posterior innovation (vol pts)")
    ax.legend(loc="lower left", fontsize=8.6)
    save(fig, OUT / "fig_g3p_hops.pdf")


# ---------------------------------------------------------------------------
# Figure 8: the calendar relation — shape vs measured noise (ported).
# ---------------------------------------------------------------------------


def figure_calendar() -> None:
    study = json.loads((RESULTS / "message_phase0.json").read_text())
    cal = study["calendarPrecision"]
    p0, eps = cal["fit"]["p0"], cal["fit"]["epsT"]
    macro("gtppzero", "%.0f", p0)
    macro("gtpepst", "%.2f", eps)
    macro("gtptauonem", "%.1f", cal["tau1mVolPts"])
    macro("gtpcalpairs", "%d", cal["alphaT1Level"]["n"])
    macro("gtpcallevel", "%.2f", cal["alphaT1Level"]["b"])
    sp = cal["shapePreview"]
    macro("gtpshaperzero", "%.3f", sp["0.0"]["r2"])
    macro("gtpshaperone", "%.3f", sp["1.0"]["r2"])

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    t_recv = np.linspace(0.05, 2.0, 200)
    t_inf = 0.5
    for a, c in ((0.0, SLATE), (0.5, AMBER), (1.0, TEAL)):
        ax.plot(t_recv, (t_inf / t_recv) ** a, color=c, lw=1.9,
                label=fr"$\alpha_T={a}$" + ("  (locked)" if a == 1.0 else ""))
    ax.axvline(t_inf, color=PALETTE["ink"], lw=0.7, ls=":")
    ax.annotate("informer $T=0.5$", xy=(0.56, 1.5), fontsize=8.5, color=SLATE)
    ax.set_xlabel("receiver maturity $T$ (years)")
    ax.set_ylabel(r"calendar amplitude $\beta=(T_j/T_i)^{\alpha_T}$")
    ax.set_ylim(0, 4.2)
    ax.legend(loc="upper right", fontsize=8.6)
    label_panel(ax, "A")

    ax = axes[1]
    buckets = cal["gapBuckets"]
    g = [b["gapSqrtYears"] for b in buckets]
    rms = [b["residRmsVolPts"] for b in buckets]
    ax.plot(g, rms, "o", ms=7, color=PALETTE["ink"], zorder=5,
            label="measured residual RMS (stored rows)")
    gg = np.linspace(0.05, 0.45, 100)
    ax.plot(gg, 100 * np.sqrt((eps + gg) / p0), color=TEAL, lw=1.9,
            label=fr"family fit: $p_0={p0:.0f}$, $\epsilon_T={eps:.2f}$")
    ax.set_xlabel(r"maturity gap $\sqrt{|\Delta T|}$ ($\sqrt{\mathrm{years}}$)")
    ax.set_ylabel("relation noise (vol pts)")
    ax.set_ylim(0, 3.6)
    callout(ax, "nearly gap-flat at the day\nhorizon: $\\epsilon_T$ dominates",
            xy=(0.28, 2.8), xytext=(0.06, 1.0))
    ax.legend(loc="lower right", fontsize=8.4)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_g3p_calendar.pdf")


# ---------------------------------------------------------------------------
# Figure 9: the residual half-life — decay curves + the Campaign-2 verdict.
# ---------------------------------------------------------------------------


def figure_halflife() -> None:
    # Panel A: a planted -3 dislocation at t=0 advanced by the PRODUCTION
    # ResidualState under residual_dynamics(half_life=H) — scalars broadcast
    # to all three handles; H = inf is the random-walk default (phi = 1).
    base = empty_residual("note-fig").updated_hard([-3.0, 0.0, 0.0], 1e-4,
                                                   0.0, "planted@0")
    t_grid = np.linspace(0.0, 10.0, 201)
    curves = {}
    for label, dyn in (("H=1", residual_dynamics(half_life=1.0)),
                       ("H=5", residual_dynamics(half_life=5.0)),
                       ("H=20", residual_dynamics(half_life=20.0)),
                       (r"H=$\infty$ (RW)", residual_dynamics())):
        curves[label] = np.array([base.advance(float(t), dyn).mean[0]
                                  for t in t_grid])
    analytic = -3.0 * np.power(2.0, -t_grid)
    assert np.max(np.abs(curves["H=1"] - analytic)) < 1e-9, \
        "H=1 decay must equal -3 * 2^(-t) exactly (D2 semigroup)"

    # Panel B: the Campaign-2 full_loo ATM RMS per arm — STORED verbatim.
    arms = [("smooth-field base", "gtpcampbase", TEAL),
            ("layered memoryless", "gtpcampmemoryless", BLUE),
            ("message learned", "gtpcampmsg", AMBER),
            ("layered $H{=}1$d", "gtpcamphlone", BLUE),
            ("transported prior", "gtpcampprior", SLATE),
            ("layered $H{=}5$d", "gtpcamphlfive", BLUE),
            ("layered $H{=}20$d", "gtpcamphltwenty", BLUE),
            ("layered desk ($H{=}\\infty$)", "gtpcampdesk", BLUE)]
    arms = sorted(arms, key=lambda a: float(HISTORICAL[a[1]]))

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.0, 1.25]})
    ax = axes[0]
    for (label, curve), c in zip(curves.items(), (TEAL, AMBER, VIOLET, SLATE)):
        ax.plot(t_grid, curve, color=c, lw=1.9, label=label)
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8)
    ax.set_xlabel("days since the dislocation")
    ax.set_ylabel("residual mean $u$ (handle level)")
    ax.legend(loc="lower right", fontsize=8.5)
    callout(ax, "what the desk asserts:\nhow long a private\ndislocation is believed",
            xy=(2.0, curves["H=5"][40]), xytext=(0.35, -1.35))
    label_panel(ax, "A")
    ax = axes[1]
    y = np.arange(len(arms))
    vals = [float(HISTORICAL[k]) for _, k, _ in arms]
    ax.barh(y, vals, height=0.62, color=[c for _, _, c in arms], alpha=0.9)
    ax.set_yticks(y, [lbl for lbl, _, _ in arms], fontsize=8.6)
    ax.invert_yaxis()
    ax.set_xlim(270, 342)
    ax.set_xlabel("Campaign-2 full LOO ATM RMS (vol bps, stored)")
    for i, v in enumerate(vals):
        ax.text(v + 1.0, i, f"{v:.1f}", va="center", fontsize=8.6)
    callout(ax, "monotone in $H$: the optimum is\n$H\\to0$ at the one-day horizon",
            xy=(306.5, 5.75), xytext=(296, 0.9))
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.52)
    save(fig, OUT / "fig_g3p_halflife.pdf")


# ---------------------------------------------------------------------------
# Figure 10: the boundary — Dirichlet clamp vs soft stale demotion.
# ---------------------------------------------------------------------------

SPX_T = {"SPX1M": 1.0 / 12.0, "SPX3M": 0.25, "SPX6M": 0.5}


def figure_boundary() -> None:
    nodes = ["SPX1M", "SPX3M", "SPX6M"]
    edges = expand_calendar_ladder(SPX_T)
    d, v_obs = 0.01, 2.5e-7  # +1 vol pt, calibration sd = 0.05 vol pt

    # (A) fresh certified: hard Dirichlet boundary; Omega carries V_S.
    clamp = harmonic_posterior(nodes, edges, {"SPX3M": d}, handle=0,
                               boundary_variance={"SPX3M": v_obs})
    assert clamp.mean[1] == d, "the boundary node must own its value exactly"
    beta_1m = calendar_beta(SPX_T["SPX1M"], SPX_T["SPX3M"])  # = 3.0
    assert abs(clamp.mean[0] - beta_1m * d) < 1e-12, \
        "1M must land at the exact harmonic extension beta * d"
    macro("gtpclamponem", "%.2f", 100 * clamp.mean[0])
    macro("gtpclampsd", "%.2f", 100 * np.sqrt(clamp.variance[2]))

    # (B) the SAME print stale-demoted: a unary anchor, no boundary; a screen
    # (kappa = 50 on every node) makes the shrink visible.
    soft = harmonic_posterior(nodes, edges, {}, handle=0,
                              unary={"SPX3M": (d, 2.25e-4)},
                              screen={n: 400.0 for n in nodes})
    assert soft.mean[1] < d, \
        "a screened soft anchor must shrink below the raw print"
    macro("gtpsoftthreem", "%.2f", 100 * soft.mean[1])
    macro("gtpsoftsd", "%.2f", 100 * np.sqrt(soft.variance[2]))

    x = np.arange(3)
    fig, axes = plt.subplots(1, 2, figsize=WIDE, sharey=True)
    ax = axes[0]
    ax.errorbar(x, 100 * clamp.mean, yerr=196 * np.sqrt(clamp.variance),
                fmt="o-", color=TEAL, lw=2.0, capsize=4, label="clamped (fresh certified)")
    ax.scatter([1], [100 * d], s=95, color=RUST, zorder=6, label="the calibration")
    ax.set_xticks(x, nodes)
    ax.set_ylabel("posterior innovation (vol pts)")
    callout(ax, "the graph harmonically\nextends the contract:\n1M $=\\beta\\,d$ exactly,\nbands widen with $\\Omega$",
            xy=(0.07, 100 * clamp.mean[0] + 0.15), xytext=(0.78, 5.2))
    ax.legend(loc="lower left", fontsize=8.4)
    label_panel(ax, "A")
    ax = axes[1]
    ax.errorbar(x - 0.06, 100 * clamp.mean, yerr=196 * np.sqrt(clamp.variance),
                fmt="o-", color=TEAL, lw=1.6, capsize=4, alpha=0.55,
                label="clamped")
    ax.errorbar(x + 0.06, 100 * soft.mean, yerr=196 * np.sqrt(soft.variance),
                fmt="s--", color=AMBER, lw=2.0, capsize=4,
                label="stale-demoted (unary + screen)")
    ax.set_xticks(x, nodes)
    callout(ax, "demoted, the print is one voice\namong the screen and the ladder:\nits own node no longer sits at $d$",
            xy=(1.08, 100 * soft.mean[1] - 0.25), xytext=(0.5, -4.4))
    ax.legend(loc="upper right", fontsize=8.4)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.12)
    save(fig, OUT / "fig_g3p_boundary.pdf")


# ---------------------------------------------------------------------------
# Figure 11: the four-part decomposition + the chi surprise gauge.
# ---------------------------------------------------------------------------

SIX_NODES = ["SPX1M", "SPX3M", "SPX6M", "XLK3M", "AAPL3M", "MSFT3M"]


def _desk_relations():
    """The §9.2 desk-force directed arcs of the six-node case file:
    directed_relation(target, source, beta, precision, class)."""
    return [
        directed_relation("XLK3M", "SPX3M", (1.0, 1.0, 1.0), 1.3e4, "broad_index"),
        directed_relation("AAPL3M", "SPX3M", (1.0, 1.0, 1.0), 1.3e4, "broad_index"),
        directed_relation("MSFT3M", "SPX3M", (1.0, 1.0, 1.0), 1.3e4, "broad_index"),
        directed_relation("AAPL3M", "XLK3M", (1.0, 1.0, 1.0), 0.9e4, "sector_etf"),
        directed_relation("MSFT3M", "XLK3M", (1.0, 1.0, 1.0), 0.9e4, "sector_etf"),
    ]


SIX_OBS = {"SPX3M": ([0.01, 0.0, 0.0], [1e-8] * 3),
           "XLK3M": ([0.0055, 0.0, 0.0], [1e-8] * 3)}


def figure_decomposition() -> None:
    graph = build_directed_graph(SIX_NODES, _desk_relations())
    # AAPL carries a planted persistent residual: observed -0.4 vol pt below
    # its systematic yesterday (t = -1), advanced one day under H = 5.
    res = (empty_residual("note-fig")
           .updated_hard([-0.004, 0.0, 0.0], 1e-8, -1.0, "AAPL3M@-1")
           .advance(0.0, residual_dynamics(half_life=5.0)))
    dp = directed_pass(graph, SIX_OBS, {"AAPL3M": res})
    assert set(dp.unsupported) == {"SPX1M", "SPX6M"}, \
        "calendar-only nodes have no directed parents — must stay unsupported"
    pa = dp.predictions["AAPL3M"]
    pm = dp.predictions["MSFT3M"]
    assert abs(pa.systematic[0] + pa.residual_mean[0] - pa.mean[0]) < 1e-15, \
        "systematic + residual must sum to the mean (the decomposition identity)"
    macro("gtpdecompsys", "%.2f", 100 * pa.systematic[0])
    macro("gtpdecompres", "%.2f", 100 * pa.residual_mean[0])
    macro("gtpdecomptotal", "%.2f", 100 * pa.mean[0])

    # chi for a hypothetical fresh AAPL print, swept over d (vol units).
    v_new = 1e-6  # a fresh calibration at 0.1 vol pt sd
    d_grid = np.linspace(-0.02, 0.02, 401)
    chi = np.array([residual_surprise([dd, 0.0, 0.0], [v_new] * 3, pa)[0]
                    for dd in d_grid])
    m0 = pa.mean[0]
    s0 = float(np.sqrt(v_new + pa.variance[0]))
    assert s0 > 0.0, "surprise scale must be positive"
    macro("gtpchione", "%.1f", 100 * (m0 + s0))  # first |chi|=1 crossing above

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.15, 1.0]})
    ax = axes[0]
    labels, vals, colors = [], [], []
    for name, p in (("AAPL3M", pa), ("MSFT3M", pm)):
        labels += [f"{name}\nsystematic $s$", f"{name}\nresidual $u$",
                   f"{name}\ntotal $m^D$"]
        vals += [100 * p.systematic[0], 100 * p.residual_mean[0], 100 * p.mean[0]]
        colors += [TEAL, VIOLET, PALETTE["ink"]]
    y = np.arange(len(vals))
    ax.barh(y, vals, height=0.6, color=colors, alpha=0.88)
    ax.axvline(0.0, color=PALETTE["ink"], lw=0.8)
    ax.set_yticks(y, labels, fontsize=8.0)
    ax.invert_yaxis()
    ax.set_xlabel("ATM contribution (vol pts)")
    ax.set_xlim(-0.72, 1.12)
    for i, v in enumerate(vals):
        ax.text(v + (0.03 if v >= 0 else -0.03), i, f"{v:+.2f}",
                va="center", ha="left" if v >= 0 else "right", fontsize=8.4)
    ax.text(0.02, 0.95, f"$q_{{\\mathrm{{in}}}}$ = {pa.q_incoming[0]:.0f} (ATM)",
            transform=ax.transAxes, fontsize=8.6, color=SLATE)
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(100 * d_grid, chi, color=TEAL, lw=2.0)
    for k, c, al in ((1.0, AMBER, 0.14), (2.0, RUST, 0.12)):
        ax.axvspan(100 * (m0 + k * s0), 100 * d_grid[-1], color=c, alpha=al)
        ax.axvspan(100 * d_grid[0], 100 * (m0 - k * s0), color=c, alpha=al)
    for lvl in (-2, -1, 1, 2):
        ax.axhline(lvl, color=SLATE, lw=0.7, ls=":")
    ax.axvline(100 * m0, color=PALETTE["ink"], lw=0.8, ls="--")
    ax.set_xlabel("fresh AAPL print $d$ (vol pts)")
    ax.set_ylabel(r"residual surprise $\chi$ (ATM)")
    callout(ax, "the badge thresholds:\namber $|\\chi|>1$, rose $|\\chi|>2$",
            xy=(100 * (m0 + 1.35 * s0), 1.5), xytext=(-1.9, 2.0))
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_g3p_decomposition.pdf")


# ---------------------------------------------------------------------------
# Figure 12 (thesis): one universe, three answers.
# ---------------------------------------------------------------------------


def figure_spectrum() -> None:
    study = json.loads((RESULTS / "message_phase0.json").read_text())

    # (a) SMOOTH FIELD — production build_graph/prior/posterior with weights
    # mirroring the taxonomy. Solved in vol-POINT units (lit 1.00 / 0.55, the
    # same convention as the note's chain figures): kappa/eta/baseline
    # precisions are quoted per vol-pt^2, so means AND sds are already vol pts
    # (means are scale-invariant either way; sds are only honest in the units
    # the prior was stated in).
    weights = {
        ("SPX1M", "SPX3M"): 1.0, ("SPX3M", "SPX1M"): 1.0,   # calendar
        ("SPX3M", "SPX6M"): 1.0, ("SPX6M", "SPX3M"): 1.0,
        ("AAPL3M", "SPX3M"): 0.7, ("MSFT3M", "SPX3M"): 0.7,  # names listen
        ("AAPL3M", "XLK3M"): 0.7, ("MSFT3M", "XLK3M"): 0.7,
        ("XLK3M", "SPX3M"): 0.7,
        ("SPX3M", "AAPL3M"): 0.1, ("SPX3M", "MSFT3M"): 0.1,  # weak feedback
        ("XLK3M", "AAPL3M"): 0.1, ("XLK3M", "MSFT3M"): 0.1,  # (irreducible)
    }
    g = build_graph(SIX_NODES, weights)
    prior = build_increment_prior(g, kappa=0.2, eta=6.0)
    sm_post = posterior_update(
        prior, np.zeros(6), np.full(6, 2.0),
        np.array([1, 3]), np.array([1.0, 0.55]), np.full(2, 1e6),
    )
    sm_mean = sm_post.mean
    sm_sd = np.sqrt(sm_post.marginal_variance)

    # (b) PRECISION MESSAGES — the learned presets (Phase-0 rho + precision
    # seeds), exactly the six-node case file of the messages edition.
    rho_idx = study["corroboration"]["indexOnly"]["b"]
    rho_peer = study["corroboration"]["peersOnly"]["b"]
    rho_cal = study["calendarPrecision"]["alphaT1Level"]["b"]
    p_idx = study["crossClassNoise"]["indexToName"]["precisionVolUnits"]
    p_peer = study["crossClassNoise"]["sectorPeer"]["precisionVolUnits"]
    edges = list(expand_calendar_ladder(SPX_T))
    edges += [
        message_edge("XLK3M", "SPX3M", p_idx, 1.0, "broad_index"),
        message_edge("AAPL3M", "SPX3M", p_idx, 1.0, "broad_index"),
        message_edge("MSFT3M", "SPX3M", p_idx, 1.0, "broad_index"),
        message_edge("AAPL3M", "XLK3M", p_peer, 1.0, "sector_etf"),
        message_edge("MSFT3M", "XLK3M", p_peer, 1.0, "sector_etf"),
    ]
    rho = {"calendar": rho_cal, "broad_index": rho_idx, "sector_etf": rho_peer,
           "sector_peer": rho_peer, "custom": 1.0}
    kappa = anchor_precisions(SIX_NODES, edges, rho)
    _, msg_post = solve(SIX_NODES, edges, ["SPX3M", "XLK3M"], [0.01, 0.0055],
                        r=1e6, kappa=kappa)
    msg_mean = 100 * msg_post.mean
    msg_sd = 100 * np.sqrt(msg_post.marginal_variance)

    # (c) LAYERED at desk force — directed pass (no planted residual) for the
    # names + hard-boundary harmonic completion for the SPX calendar.
    dp = directed_pass(build_directed_graph(SIX_NODES, _desk_relations()),
                       SIX_OBS)
    hp = harmonic_posterior(["SPX1M", "SPX3M", "SPX6M"],
                            expand_calendar_ladder(SPX_T), {"SPX3M": 0.01},
                            handle=0, boundary_variance={"SPX3M": 1e-8})
    assert abs(100 * hp.mean[0] - 3.00) < 1e-9, \
        "layered 1M must carry the full alphaT=1 boundary extension (+3.00)"
    pa, pm = dp.predictions["AAPL3M"], dp.predictions["MSFT3M"]
    lay_mean = 100 * np.array([hp.mean[0], hp.mean[1], hp.mean[2],
                               0.0055, pa.mean[0], pm.mean[0]])
    lay_sd = 100 * np.sqrt(np.array([hp.variance[0], hp.variance[1],
                                     hp.variance[2], 1e-8,
                                     pa.variance[0], pm.variance[0]]))

    macro("gtpspecsmoothonem", "%.2f", sm_mean[0])
    macro("gtpspecmsgonem", "%.2f", msg_mean[0])
    macro("gtpspeclayonem", "%.2f", lay_mean[0])
    macro("gtpspecsmoothaapl", "%.2f", sm_mean[4])
    macro("gtpspecmsgaapl", "%.2f", msg_mean[4])
    macro("gtpspeclayaapl", "%.2f", lay_mean[4])

    fig, ax = plt.subplots(figsize=(7.0, 4.6))
    x = np.arange(6)
    w = 0.26
    err = dict(capsize=2.5, ecolor=PALETTE["ink"], error_kw={"elinewidth": 0.8})
    ax.bar(x - w, sm_mean, w, yerr=sm_sd, color=TEAL, alpha=0.9,
           label="smooth field (assert smoothness)", **err)
    ax.bar(x, msg_mean, w, yerr=msg_sd, color=AMBER, alpha=0.9,
           label="precision messages, learned (assert relations)", **err)
    ax.bar(x + w, lay_mean, w, yerr=lay_sd, color=BLUE, alpha=0.9,
           label="layered desk force (assert dependencies)", **err)
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8)
    ax.set_xticks(x, [n + ("\n(lit)" if n in ("SPX3M", "XLK3M") else "")
                      for n in SIX_NODES], fontsize=9)
    ax.set_ylabel("posterior ATM innovation (vol pts, $\\pm1$ sd)")
    ax.set_ylim(-2.3, 7.4)
    callout(ax, "same universe, three assertions:\nlayered extends the full contract\nto 1M; the learned level shrinks it;\nthe smooth field decays it",
            xy=(x[0] + w + 0.05, lay_mean[0] + 0.05), xytext=(1.55, 3.0))
    ax.legend(loc="upper right", fontsize=8.4)
    save(fig, OUT / "fig_g3p_spectrum.pdf")


# ---------------------------------------------------------------------------
# Appendix D: the three reference listings verified against production.
# ---------------------------------------------------------------------------


def _listing_operator(nodes, factors):
    """Note listing: assemble Q_msg from the factor rows (i, j, p, beta)."""
    n = len(nodes)
    Q = np.zeros((n, n))
    for i, j, p, b in factors:
        u = np.zeros(n)
        u[i] = 1.0
        u[j] = -b
        Q += p * np.outer(u, u)
    return Q


def _listing_solve(Q, kappa, obs, d, r):
    Qp = Q + np.diag(kappa)
    b = np.zeros(len(Q))
    Qp[obs, obs] += r
    b[obs] += r * d
    sigma = np.linalg.inv(Qp)
    return sigma @ b, sigma


def _listing_stationary(K):
    """Note listing (14_graph_extrapolation.tex lst:graph): pi^T K = pi^T."""
    n = len(K)
    S = K.T - np.eye(n)
    S[-1] = 1.0  # last row = mass constraint
    rhs = np.zeros(n)
    rhs[-1] = 1.0
    return np.linalg.solve(S, rhs)


def _listing_directed_laplacian_beta(K, pi, B):
    """Note listing: L_dir^beta = M^T Pi M, M = I - K∘B (PSD for any B)."""
    M = np.eye(len(K)) - K * B
    return M.T @ (pi[:, None] * M)


def verify_reference() -> None:
    # (i) MESSAGE: listing operator + dense solve vs production, and the
    # cycle gauge on a consistent / inconsistent triangle.
    nodes = ["A", "B", "C", "D"]
    edges = [message_edge("B", "A", 800.0, 1.3), message_edge("C", "B", 500.0, 0.8),
             message_edge("D", "C", 300.0, 1.1), message_edge("D", "A", 200.0, 0.9)]
    op = build_message_operator(nodes, edges)
    kappa = anchor_precisions(nodes, edges, {"custom": 0.5})
    obs, d, r = np.array([0]), np.array([1.0]), np.array([1e6])
    post = message_posterior_update(op, obs, d, r, anchor_precision=kappa)
    Q_ref = _listing_operator(nodes, op.factors)
    mean_ref, sigma_ref = _listing_solve(Q_ref, kappa, obs, d, r)
    dev_msg = max(
        float(np.max(np.abs(Q_ref - op.q_matrix))),
        float(np.max(np.abs(mean_ref - post.mean))),
        float(np.max(np.abs(np.diag(sigma_ref) - post.marginal_variance))),
    )
    good = [message_edge("B", "A", 1.0, 2.0), message_edge("C", "B", 1.0, 3.0),
            message_edge("C", "A", 1.0, 6.0)]
    bad = [message_edge("B", "A", 1.0, 2.0), message_edge("C", "B", 1.0, 3.0),
           message_edge("C", "A", 1.0, 5.0)]
    macro("gtpcycleflags", "%d", len(cycle_beta_products(["A", "B", "C"], good)))
    flags_bad = cycle_beta_products(["A", "B", "C"], bad)
    macro("gtpcyclebad", "%.3f", flags_bad[0].product if flags_bad else float("nan"))
    sci_macro("gtprefagreemsg", dev_msg)

    # (ii) LAYERED: hand-rolled chain S -> M -> T vs directed_pass, plus the
    # Dirichlet closed form -Q_FF^{-1} Q_FS d_S vs harmonic_posterior.
    p1, p2, b1, b2, v_s = 1e3, 2e3, 1.5, 0.8, 1e-4
    dg = build_directed_graph(
        ["S", "M", "T"],
        [directed_relation("M", "S", b1, p1), directed_relation("T", "M", b2, p2)],
    )
    dp = directed_pass(dg, {"S": ([1.0, 0.0, 0.0], [v_s] * 3)})
    m_m, v_m = b1 * 1.0, b1**2 * v_s + 1.0 / p1        # hand: one arc
    m_t, v_t = b2 * m_m, b2**2 * v_m + 1.0 / p2        # hand: composed
    dev_lay = max(
        abs(dp.predictions["M"].mean[0] - m_m),
        abs(dp.predictions["M"].variance[0] - v_m),
        abs(dp.predictions["T"].mean[0] - m_t),
        abs(dp.predictions["T"].variance[0] - v_t),
    )
    lad_t = {"1M": 1.0 / 12.0, "3M": 0.25, "6M": 0.5}
    lad_nodes = ["1M", "3M", "6M"]
    lad_edges = expand_calendar_ladder(lad_t)
    idx = {n: k for k, n in enumerate(lad_nodes)}
    Q = np.zeros((3, 3))
    for e in lad_edges:  # pairwise factors by hand (handle 0)
        i, j, p, b = idx[e.receiver], idx[e.informer], e.precision, e.beta[0]
        Q[i, i] += p
        Q[j, j] += p * b * b
        Q[i, j] -= p * b
        Q[j, i] -= p * b
    free, bound = [0, 2], [1]
    mean_free = -np.linalg.solve(Q[np.ix_(free, free)],
                                 Q[np.ix_(free, bound)] @ np.array([1.0]))
    hp = harmonic_posterior(lad_nodes, lad_edges, {"3M": 1.0})
    dev_lay = max(dev_lay, float(np.max(np.abs(mean_free - hp.mean[free]))))
    sci_macro("gtprefagreelay", dev_lay)

    # (iii) SMOOTH: the tex listing (stationary + L_dir^beta) vs production
    # build_graph / directed_residual_beta on a 4-node irreducible graph.
    w4 = {("A", "B"): 1.0, ("B", "C"): 0.8, ("C", "D"): 1.2, ("D", "A"): 0.6,
          ("B", "A"): 0.5, ("C", "B"): 0.5, ("D", "C"): 0.5, ("A", "D"): 0.5}
    g4 = build_graph(["A", "B", "C", "D"], w4)
    B = beta_matrix(g4, {("A", "B"): 1.2, ("C", "D"): 0.8})
    dev_sm = max(
        float(np.max(np.abs(_listing_stationary(g4.kernel) - g4.stationary))),
        float(np.max(np.abs(
            _listing_directed_laplacian_beta(g4.kernel, g4.stationary, B)
            - directed_residual_beta(g4, B)
        ))),
    )
    sci_macro("gtprefagreesm", dev_sm)


# ---------------------------------------------------------------------------


def main() -> None:
    figure_asyncab(); print("asyncab done")
    figure_smooth(); print("smooth done")
    figure_contract(); print("contract done")
    figure_deadinformer(); print("deadinformer done")
    figure_compete(); print("compete done")
    figure_amplitude(); print("amplitude done")
    figure_hops(); print("hops done")
    figure_calendar(); print("calendar done")
    figure_halflife(); print("halflife done")
    figure_boundary(); print("boundary done")
    figure_decomposition(); print("decomposition done")
    figure_spectrum(); print("spectrum done")
    verify_reference(); print("reference listings verified")
    for name, value in HISTORICAL.items():
        macro(name, "%s", value)

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("gtpgencommit", "%s", commit)
    macro("gtpgendate", "%s", date.today().isoformat())

    (OUT / "graph_three_priors_tables.tex").write_text(
        "\n".join(MACROS) + "\n", encoding="utf-8")
    (OUT / "graph_three_priors_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
