"""Figure suite for the units/measure/tolerance edition of Note 07 (objective).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_obj_measure.py

Every weight, band, residual, fit and RMS is produced by the PRODUCTION
objective machinery (``volfit.calib.{weights,band,rms}`` and the LQD slice
calibrator); local formulae define only the synthetic running smile and its
deterministic noise.  The running character is the fitted index-like smile
``RawSVI(a=0.0106, b=0.0729, rho=-0.5, m=0.0583, sigma=0.1010)`` shared with
the original Note-07 suite.

Outputs, written next to this script:

* ``fig_objm_units.pdf``   -- the change of units: price residuals vs vega-normalized;
* ``fig_objm_measure.pdf`` -- weights as quadrature: cumulative measure audit;
* ``fig_objm_tube.pdf``    -- the loss shapes: mid parabola vs banded tube + anchor;
* ``fig_objm_flex.pdf``    -- band value scales with model flexibility (real fits);
* ``fig_objm_dial.pdf``    -- the haircut dial sweeping mid -> band, honest RMS;
* ``fig_objm_anchor.pdf``  -- the tube's flat valley and the anchor's selection;
* ``obj_measure_tables.tex`` / ``obj_measure_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))

from style import PALETTE, WIDE, label_panel, save, setup  # noqa: E402

from volfit.calib.band import (  # noqa: E402
    DEFAULT_HAIRCUT,
    MID_ANCHOR_WEIGHT,
    band_residuals,
    band_violation,
    band_violation_sign,
    resolve_band,
)
from volfit.calib.rms import node_error_terms, rms  # noqa: E402
from volfit.calib.weights import otm_time_value, resolve_weights  # noqa: E402
from volfit.core.black import black_call, black_vega_sigma  # noqa: E402
from volfit.models.lqd.calibrate import calibrate_slice  # noqa: E402
from volfit.models.svi_jw.svi import RawSVI  # noqa: E402

setup()
TEAL, BLUE, RUST, AMBER, SLATE, VIOLET = (
    PALETTE["teal"], PALETTE["blue"], PALETTE["rust"], PALETTE["amber"],
    PALETTE["muted"], PALETTE["violet"],
)

RAW = RawSVI(a=0.0106, b=0.0729, rho=-0.5, m=0.0583, sigma=0.1010)
T = 0.5

MACROS: list[str] = ["% Auto-generated by gen_obj_measure.py — do not edit."]
NUMBERS: dict = {}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


# ---------------------------------------------------------------------------
# Figure 1: the change of units.
# ---------------------------------------------------------------------------


def figure_units() -> None:
    k = np.linspace(-0.42, 0.35, 41)
    w = RAW.total_variance(k)
    iv = np.sqrt(w / T)
    vega = black_vega_sigma(k, iv, T)
    eta = 1e-4

    def residuals(dv: float) -> tuple[np.ndarray, np.ndarray]:
        w2 = ((iv + dv) ** 2) * T
        dprice = black_call(k, w2) - black_call(k, w)
        return dprice, dprice / (vega + eta)

    dp_small, r_small = residuals(0.005)   # a uniform 50 vol bp misfit
    dp_big, r_big = residuals(0.030)       # a 300 vol bp misfit
    macro("objmunitserrsmall", "%.1f", 1e4 * np.max(np.abs(r_small - 0.005)))
    macro("objmunitserrbig", "%.0f", 1e4 * np.max(np.abs(r_big - 0.030)))

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.plot(k, 1e4 * dp_small, "o-", ms=3.2, lw=1.3, color=RUST)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"price residual ($10^{-4}$ of forward)")
    ax.annotate("a uniform 50 vol bp misfit, in price units",
                xy=(0.5, 0.04), xycoords="axes fraction", fontsize=8.5,
                ha="center", color=SLATE)
    label_panel(ax, "A")
    ax = axes[1]
    ax.axhline(50.0, color=PALETTE["ink"], lw=0.9, ls=":")
    ax.plot(k, 1e4 * r_small, "o", ms=3.6, color=TEAL,
            label="vega-normalized (50 bp misfit)")
    ax.plot(k, 1e4 * r_big / 6.0, "s", ms=3.2, color=AMBER,
            label=r"300 bp misfit ($\div 6$)")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("vega-normalized residual (vol bp)")
    ax.set_ylim(36, 74)
    ax.legend(fontsize=8.5, loc="lower center")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_objm_units.pdf")


# ---------------------------------------------------------------------------
# Figure 2: weights as quadrature of the time-value measure.
# ---------------------------------------------------------------------------

K_LADDER = np.concatenate([
    np.linspace(-0.35, -0.12, 4),
    np.linspace(-0.10, 0.10, 13),
    np.linspace(0.13, 0.30, 4),
])


def figure_measure() -> None:
    k = K_LADDER
    w = RAW.total_variance(k)
    tv_w = resolve_weights("tv_density", k, w)
    equal = np.ones_like(k) / k.size
    tvn = tv_w / tv_w.sum()

    # The continuum benchmark: the normalized time-value measure on [k_lo, k_hi].
    kk = np.linspace(k[0], k[-1], 800)
    tv_cont = otm_time_value(kk, RAW.total_variance(kk))
    cum_cont = np.cumsum(tv_cont)
    cum_cont /= cum_cont[-1]
    cum_equal = np.cumsum(equal)
    cum_tv = np.cumsum(tvn)
    interp_cont = np.interp(k, kk, cum_cont)
    macro("objmmeaserrtv", "%.3f", np.max(np.abs(cum_tv - interp_cont)))
    macro("objmmeaserreq", "%.2f", np.max(np.abs(cum_equal - interp_cont)))
    i_atm = int(np.argmin(np.abs(k)))
    macro("objmwingratio", "%.1f", tv_w.max() / tv_w[i_atm])

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    width = 0.006
    ax.bar(k - width / 2, np.ones_like(k), width=width, color=SLATE, alpha=0.55,
           label="equal")
    ax.bar(k + width / 2, tv_w, width=width, color=TEAL, label="tv-density")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("normalized quote weight")
    ax.legend(fontsize=9, loc="upper right")
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(kk, cum_cont, color=PALETTE["ink"], lw=1.6,
            label=r"continuum $\int\mathrm{TV}\,\mathrm{d}k$ (target measure)")
    ax.step(k, cum_tv, where="post", color=TEAL, lw=1.8, label="tv-density weights")
    ax.step(k, cum_equal, where="post", color=RUST, lw=1.6, ls="--",
            label="equal weights (quote histogram)")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("cumulative weight")
    ax.legend(fontsize=8.5, loc="upper left")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_objm_measure.pdf")


# ---------------------------------------------------------------------------
# Figure 3: the loss shapes for one quote.
# ---------------------------------------------------------------------------


def figure_tube() -> None:
    mid, half = 0.24, 0.012  # one quote: 24% mid, 1.2-vol-point half spread
    lo, hi = mid - half, mid + half
    m = np.linspace(mid - 0.035, mid + 0.035, 400)

    def band_loss(mm: np.ndarray, anchor: float) -> np.ndarray:
        return np.array([float(np.sum(band_residuals(
            np.array([x]), np.array([lo]), np.array([hi]), np.array([mid]),
            1.0, anchor) ** 2)) for x in mm])

    loss_mid = (m - mid) ** 2
    loss_band = band_loss(m, MID_ANCHOR_WEIGHT)
    loss_tube = band_loss(m, 0.0)
    scale = 1e4  # display in (vol pts)^2 * 1e4 for readability

    fig, ax = plt.subplots(figsize=(6.9, 4.0))
    ax.axvspan(100 * lo, 100 * hi, color=AMBER, alpha=0.14, lw=0)
    ax.plot(100 * m, scale * loss_mid, color=RUST, ls="--", label="mid mode: $(m-\\mathrm{mid})^2$")
    ax.plot(100 * m, scale * loss_tube, color=SLATE, lw=1.4,
            label="band hinge alone (flat tube)")
    ax.plot(100 * m, scale * loss_band, color=TEAL, lw=2.2,
            label=r"band mode: hinge$^2$ + $\theta_{\mathrm{mid}}$ anchor")
    ax.annotate("zero hinge cost\ninside the quoted band", xy=(100 * mid - 0.6, 0.18),
                xytext=(100 * mid - 3.3, 1.2), fontsize=8.5, color=SLATE,
                arrowprops={"arrowstyle": "->", "color": SLATE, "lw": 1.0})
    ax.set_xlabel("model value $m$ (vol %)")
    ax.set_ylabel(r"per-quote loss ($10^{-4}$)")
    ax.set_ylim(0, 10)
    ax.legend(fontsize=9, loc="upper center")
    save(fig, OUT / "fig_objm_tube.pdf")
    macro("objmanchor", "%.2f", MID_ANCHOR_WEIGHT)
    macro("objmhaircut", "%.3f", DEFAULT_HAIRCUT)


# ---------------------------------------------------------------------------
# Shared noisy wide-wing smile for the fit figures.
# ---------------------------------------------------------------------------

K_FIT = np.linspace(-0.32, 0.28, 19)
W_MID = RAW.total_variance(K_FIT)
IV_TRUE = np.sqrt(W_MID / T)
SPREAD = 0.006 + 0.025 * np.abs(K_FIT)
# Deterministic tick-bounce: alternating-sign mid noise, larger in the wings
# where spreads are wide -- the classic pathology a mid fit must chase.
NOISE = 0.006 * np.where(np.arange(K_FIT.size) % 2 == 0, 1.0, -1.0) \
    * (1.0 + 2.5 * np.abs(K_FIT))
IV_MID = IV_TRUE + NOISE
IV_BID, IV_ASK = IV_MID - SPREAD, IV_MID + SPREAD
KK = np.linspace(-0.35, 0.30, 300)
#: Ridge strength for the fit figures: strong enough that the regularizer is
#: a genuine counterforce inside the band's tube, weak enough that the
#: full-weight mid residuals overrule it -- the regime where the band's
#: factor-1/theta relief of the data term is the objective's own property
#: (near-zero ridge separates the fits too, but partly by optimizer stall).
REG_FIT = 1e-6


def fit(n_order: int, band=None):
    return calibrate_slice(K_FIT, (IV_MID ** 2) * T, T, n_order=n_order,
                           reg_lambda=REG_FIT, band=band)


# ---------------------------------------------------------------------------
# Figure 4: the band's value scales with model flexibility.
# ---------------------------------------------------------------------------


def figure_flex() -> None:
    band = resolve_band(IV_BID, IV_MID, IV_ASK, "bidask")
    fits = {}
    for lab, n in (("rigid", 5), ("flexible", 16)):  # noqa: B007
        m = fit(n)
        b = fit(n, band=band)
        fits[lab] = (m, b, 1e4 * float(np.max(np.abs(
            m.slice.implied_vol(KK, T) - b.slice.implied_vol(KK, T)))))
    macro("objmflexrigid", "%.0f", fits["rigid"][2])
    macro("objmflexflex", "%.0f", fits["flexible"][2])

    def roughness(res) -> float:
        v = 100 * res.slice.implied_vol(KK, T)
        return float(np.sum(np.abs(np.diff(v, 2))))

    macro("objmroughmid", "%.1f", roughness(fits["flexible"][0]))
    macro("objmroughband", "%.1f", roughness(fits["flexible"][1]))

    # Residual-to-truth view: at smile scale a 50 bp story is invisible.
    iv_true_kk = np.sqrt(RAW.total_variance(KK) / T)
    fig, axes = plt.subplots(1, 2, figsize=WIDE, sharey=True)
    for ax, lab, letter in ((axes[0], "rigid", "A"), (axes[1], "flexible", "B")):
        m, b, gap = fits[lab]
        ax.fill_between(K_FIT, 1e4 * (IV_BID - IV_TRUE), 1e4 * (IV_ASK - IV_TRUE),
                        color=AMBER, alpha=0.18, lw=0, label="bid–ask band")
        ax.plot(K_FIT, 1e4 * NOISE, "x", ms=5, color=SLATE, label="noisy mids")
        ax.axhline(0.0, color=PALETTE["ink"], lw=0.8, ls=":")
        ax.plot(KK, 1e4 * (m.slice.implied_vol(KK, T) - iv_true_kk), color=RUST,
                ls="--", lw=1.6, label="mid fit")
        ax.plot(KK, 1e4 * (b.slice.implied_vol(KK, T) - iv_true_kk), color=TEAL,
                lw=2.0, label="band fit")
        ax.set_xlabel(r"log-moneyness $k$")
        label_panel(ax, letter)
    axes[0].set_ylabel("fitted vol $-$ truth (vol bp)")
    axes[0].legend(fontsize=8, loc="lower left", ncol=2, columnspacing=0.9)
    fig.subplots_adjust(wspace=0.12)
    save(fig, OUT / "fig_objm_flex.pdf")


# ---------------------------------------------------------------------------
# Figure 5: the haircut dial, and the honest RMS.
# ---------------------------------------------------------------------------


def figure_dial() -> None:
    haircuts = np.linspace(0.0, 0.032, 13)
    rms_band, rms_mid = [], []
    for h in haircuts:
        band = resolve_band(IV_BID, IV_MID, IV_ASK, "haircut", haircut=float(h))
        res = fit(16, band=band)
        iv_fit = res.slice.implied_vol(K_FIT, T)
        num_b, den_b = node_error_terms(iv_fit, IV_MID, None, band, None)
        rms_band.append(1e4 * rms(num_b, den_b))
        num_m, den_m = node_error_terms(iv_fit, IV_MID, None, None, None)
        rms_mid.append(1e4 * rms(num_m, den_m))
    rms_band, rms_mid = np.array(rms_band), np.array(rms_mid)
    macro("objmdialbandzero", "%.1f", rms_band[0])
    macro("objmdialmidzero", "%.0f", rms_mid[0])
    macro("objmdialmidfull", "%.0f", rms_mid[-1])
    macro("objmdialbandfull", "%.0f", rms_band[-1])

    fig, ax = plt.subplots(figsize=(6.9, 4.0))
    ax.plot(100 * haircuts, rms_mid, "o-", ms=4, color=RUST,
            label="distance to mid (mid-mode metric)")
    ax.plot(100 * haircuts, rms_band, "s-", ms=4, color=TEAL,
            label="distance to band (band-mode metric)")
    ax.annotate("raw bid–ask:\nfree inside the tube", xy=(0.05, rms_band[0] + 2),
                xytext=(0.25, 18), fontsize=8.5, color=SLATE,
                arrowprops={"arrowstyle": "->", "color": SLATE, "lw": 1.0})
    ax.annotate("band collapsed\nto the mids", xy=(100 * haircuts[-1], rms_mid[-1]),
                xytext=(-72, -26), textcoords="offset points", fontsize=8.5,
                color=SLATE)
    ax.set_xlabel("haircut $h$ (vol points)")
    ax.set_ylabel("reported RMS (vol bp)")
    ax.legend(fontsize=9, loc="center right")
    save(fig, OUT / "fig_objm_dial.pdf")


# ---------------------------------------------------------------------------
# Figure 6: the tube's flat valley, and the anchor's selection.
# ---------------------------------------------------------------------------


def figure_anchor() -> None:
    # Clean quotes (no bounce): the tube's flat valley is then the spread
    # itself, undistorted by noise-vs-spread interference.
    band = resolve_band(IV_TRUE - SPREAD, IV_TRUE, IV_TRUE + SPREAD, "bidask")
    res = calibrate_slice(K_FIT, (IV_TRUE ** 2) * T, T, n_order=8,
                          reg_lambda=REG_FIT, band=band)
    iv_fit = res.slice.implied_vol(K_FIT, T)
    shifts = np.linspace(-0.012, 0.012, 241)

    def cost(anchor: float) -> np.ndarray:
        out = []
        for d in shifts:
            r = band_residuals(iv_fit + d, band.iv_lo, band.iv_hi, IV_TRUE, 1.0,
                               anchor)
            out.append(float(np.sum(r ** 2)))
        return np.array(out)

    c0, ca = cost(0.0), cost(MID_ANCHOR_WEIGHT)
    flat = shifts[c0 <= c0.min() + 1e-14]
    macro("objmvalley", "%.0f", 1e4 * (flat.max() - flat.min()))

    fig, ax = plt.subplots(figsize=(6.9, 3.9))
    ax.plot(1e4 * shifts, 1e4 * c0, color=SLATE, lw=1.5,
            label="hinge alone: a flat valley of minimizers")
    ax.plot(1e4 * shifts, 1e4 * ca, color=TEAL, lw=2.2,
            label=r"with the $\theta_{\mathrm{mid}}$ anchor: one selected point")
    ax.axvspan(1e4 * flat.min(), 1e4 * flat.max(), color=SLATE, alpha=0.10, lw=0)
    ax.annotate("every level shift in here\nis inside every quoted band",
                xy=(0.0, float(1e4 * c0.min())), xytext=(-95, 22),
                textcoords="offset points", fontsize=8.5, color=SLATE,
                arrowprops={"arrowstyle": "->", "color": SLATE, "lw": 1.0})
    ax.set_xlabel("level shift of the fitted curve (vol bp)")
    ax.set_ylabel(r"band objective ($10^{-4}$)")
    ax.legend(fontsize=9, loc="upper center")
    save(fig, OUT / "fig_objm_anchor.pdf")


# ---------------------------------------------------------------------------
# Appendix D verification: the listings against production.
# ---------------------------------------------------------------------------


def listing_band_violation(model, lo, hi):
    return np.maximum(model - hi, 0.0) + np.maximum(lo - model, 0.0)


def listing_band_violation_sign(model, lo, hi):
    return np.where(model > hi, 1.0, 0.0) - np.where(model < lo, 1.0, 0.0)


def listing_band_residuals(model, lo, hi, mid, scale, mid_anchor_weight):
    viol = scale * listing_band_violation(model, lo, hi)
    anchor = np.sqrt(mid_anchor_weight) * scale * (model - mid)
    return np.concatenate([viol, anchor])


def verify_listings() -> None:
    rng = np.random.default_rng(7)
    m = 0.24 + 0.03 * rng.standard_normal(200)
    lo = np.full(200, 0.228)
    hi = np.full(200, 0.252)
    mid = np.full(200, 0.24)
    d1 = np.max(np.abs(listing_band_violation(m, lo, hi) - band_violation(m, lo, hi)))
    d2 = np.max(np.abs(listing_band_violation_sign(m, lo, hi)
                       - band_violation_sign(m, lo, hi)))
    d3 = np.max(np.abs(listing_band_residuals(m, lo, hi, mid, 1.3, 0.05)
                       - band_residuals(m, lo, hi, mid, 1.3, 0.05)))
    macro("objmrefagree", "%.0f", np.floor(np.log10(max(d1, d2, d3, 1e-16))))


# ---------------------------------------------------------------------------


def main() -> None:
    figure_units()
    print("units done")
    figure_measure()
    print("measure done")
    figure_tube()
    print("tube done")
    figure_flex()
    print("flex done")
    figure_dial()
    print("dial done")
    figure_anchor()
    print("anchor done")
    verify_listings()

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("objmgencommit", "%s", commit)
    macro("objmgendate", "%s", date.today().isoformat())

    (OUT / "obj_measure_tables.tex").write_text("\n".join(MACROS) + "\n",
                                                encoding="utf-8")
    (OUT / "obj_measure_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
