"""Figure suite for the market's-own-clock edition of Note 11 (event time).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_event_market_clock.py

Every clock value, interpolation and solved calendar is produced by
PRODUCTION machinery (``volfit.calib.weighted_time`` and
``volfit.calib.event_autocalib``); local formulae define only synthetic
targets.  The hero figure runs the production auto-calibrator on the real
AAPL ATM term structure of the standing export
``tmp/volfit_surfaces_20260718_1324.json``.

Outputs, written next to this script:

* ``fig_emc_hero.pdf``   -- reading the clock off live AAPL: forward
                            variance per calendar vs per event-time unit,
                            with the solver's installed extra days;
* ``fig_emc_clock.pdf``  -- the dilated clock and the term-structure
                            read-off (parity with the original edition);
* ``fig_emc_interp.pdf`` -- wrong-way demo: interpolating the dense curve
                            in calendar time vs in the variance clock;
* ``fig_emc_ident.pdf``  -- identifiability audit: planted vs recovered
                            event sizes, and the flat-input null;
* ``event_market_tables.tex`` / ``event_market_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from volfit.calib.event_autocalib import autocalibrate_events  # noqa: E402
from volfit.calib.weighted_time import (  # noqa: E402
    DAYS_PER_YEAR,
    interp_total_variance,
    weighted_variance_years,
)

setup()
TEAL, BLUE, RUST, AMBER, SLATE, VIOLET, GREEN = (
    PALETTE["teal"], PALETTE["blue"], PALETTE["rust"], PALETTE["amber"],
    PALETTE["muted"], PALETTE["violet"], PALETTE["green"],
)

MACROS: list[str] = ["% Auto-generated by gen_event_market_clock.py — do not edit."]
NUMBERS: dict = {}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def sci_macro(name: str, value: float) -> None:
    v = max(abs(value), 1e-17)
    e = int(np.floor(np.log10(v)))
    m = v / 10.0**e
    MACROS.append(r"\newcommand{\%s}{\ensuremath{%.1f\times10^{%d}}}"
                  % (name, m, e))
    NUMBERS[name] = float(value)


def fwd_var(t: np.ndarray, w: np.ndarray, tau=None) -> np.ndarray:
    """Forward variance per unit of the given clock (prepend the origin)."""
    x = t if tau is None else tau
    xx = np.concatenate([[0.0], x])
    ww = np.concatenate([[0.0], w])
    return np.diff(ww) / np.diff(xx)


# ---------------------------------------------------------------------------
# Figure 1 (hero): reading the clock off the live AAPL term structure.
# ---------------------------------------------------------------------------


def figure_hero() -> None:
    fixture = REPO / "tmp" / "volfit_surfaces_20260718_1324.json"
    if not fixture.exists():
        raise FileNotFoundError(
            f"standing reference export not found: {fixture} — regenerate via "
            "the app's surfaces export (see memory: reference-live-fixture)")
    doc = json.loads(fixture.read_text(encoding="utf-8"))
    aapl = next(tk for tk in doc["tickers"] if tk["ticker"] == "AAPL")
    ts, w0s, labels = [], [], []
    for n in aapl["nodes"]:
        ks = np.array([c["k"] for c in n["curve"]])
        ws = np.array([c["w"] for c in n["curve"]])
        ts.append(n["t"])
        w0s.append(float(np.interp(0.0, ks, ws)))
        labels.append(n["expiry"][2:])  # YY-MM-DD
    ts, w0s = np.array(ts), np.array(w0s)

    # Production auto-calibration: events allowed before the first three
    # expiries; the last interval anchors the tail (the shipped design).
    events = autocalibrate_events(ts, w0s, n_events=3)
    taus = np.array([weighted_variance_years(float(t), events) for t in ts])
    fv_cal = fwd_var(ts, w0s)
    fv_evt = fwd_var(ts, w0s, tau=taus)
    macro("emcheronodes", "%d", ts.size)
    macro("emcherodays", "%.1f", sum(n for _, n in events))
    macro("emcheroeventcount", "%d", len(events))
    macro("emcherospreadbefore", "%.0f",
          1e4 * (fv_cal.max() - fv_cal.min()))
    macro("emcherospreadafter", "%.0f",
          1e4 * (fv_evt.max() - fv_evt.min()))

    fig, ax = plt.subplots(figsize=(6.9, 3.9))
    x = np.arange(ts.size)
    names = ["today$\\to$" + labels[0]] + [f"{a}$\\to${b}" for a, b in
                                           zip(labels, labels[1:])]
    ax.bar(x - 0.18, fv_cal, width=0.34, color=RUST,
           label="per calendar year")
    ax.bar(x + 0.18, fv_evt, width=0.34, color=TEAL,
           label="per variance year (solved clock)")
    for xi, (_, n_days) in zip(x, events):
        ax.annotate(f"+{n_days:.1f}d", xy=(xi, max(fv_cal[xi], fv_evt[xi])),
                    xytext=(0, 4), textcoords="offset points", ha="center",
                    fontsize=8.5, color=PALETTE["ink"])
    ax.set_xticks(x, names, fontsize=8)
    ax.set_ylabel("forward variance rate")
    ax.set_ylim(0, 0.112)
    ax.legend(fontsize=8.5, loc="upper right")
    save(fig, OUT / "fig_emc_hero.pdf")


# ---------------------------------------------------------------------------
# Figure 2 (parity): the dilated clock, and what it does to the read-off.
# ---------------------------------------------------------------------------

TE, EXTRA = 0.25, 4.0
EVENTS = [(TE, EXTRA)]
SIGMA = 0.20


def figure_clock() -> None:
    T = np.linspace(0.01, 1.0, 400)
    tau = np.array([weighted_variance_years(float(t), EVENTS) for t in T])
    tau_n = np.array([weighted_variance_years(float(t), EVENTS,
                                              normalize=True) for t in T])
    w = SIGMA**2 * tau                      # flat vol on the variance clock
    iv_cal = np.sqrt(w / T)

    t_probe = 0.30
    tau_probe = weighted_variance_years(t_probe, EVENTS)
    macro("emctauprobe", "%.4f", tau_probe)
    macro("emcdropbp", "%.0f",
          1e4 * SIGMA * (1.0 - np.sqrt(t_probe / tau_probe)))

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.plot(T, T, color=SLATE, ls=":", lw=1.4, label=r"calendar $\tau=T$")
    ax.plot(T, tau, color=TEAL, lw=1.9, label=r"variance clock $\tau(T)$")
    ax.plot(T, tau_n, color=RUST, ls="--", lw=1.6, label="normalized")
    ax.axvline(TE, color=PALETTE["ink"], lw=0.8, alpha=0.5)
    callout(ax, "jump $N_e/365$", (TE + 0.005, TE + EXTRA / 365.0 + 0.005),
            (0.36, 0.13))
    ax.set_xlabel(r"calendar time $T$ (years)")
    ax.set_ylabel(r"variance years $\tau$")
    ax.legend(fontsize=8.5, loc="upper left")
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(T, 100 * SIGMA * np.ones_like(T), color=SLATE, ls=":", lw=1.4,
            label=r"clock vol $\sqrt{w/\tau}$ (flat by construction)")
    ax.plot(T, 100 * iv_cal, color=TEAL, lw=1.9,
            label=r"calendar reading $\sqrt{w/T}$")
    ax.axvline(TE, color=PALETTE["ink"], lw=0.8, alpha=0.5)
    ax.set_xlabel(r"calendar time $T$ (years)")
    ax.set_ylabel("ATM implied volatility (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_emc_clock.pdf")


# ---------------------------------------------------------------------------
# Figure 3 (wrong-way): interpolating the dense curve in the wrong clock.
# ---------------------------------------------------------------------------


def figure_interp() -> None:
    # Quoted expiries straddling the event; flat 20% vol on the event clock.
    t_nodes = np.array([0.10, 0.20, 0.35, 0.60, 1.00])
    tau_nodes = np.array([weighted_variance_years(float(t), EVENTS)
                          for t in t_nodes])
    w_nodes = SIGMA**2 * tau_nodes

    tq = np.linspace(0.05, 1.05, 500)
    tau_q = np.array([weighted_variance_years(float(t), EVENTS) for t in tq])
    w_right = interp_total_variance(tau_q, tau_nodes, w_nodes)
    w_wrong = interp_total_variance(tq, t_nodes, w_nodes)
    iv_right = 100 * np.sqrt(w_right / tq)
    iv_wrong = 100 * np.sqrt(w_wrong / tq)
    macro("emcinterpgapbp", "%.0f", 1e2 * np.max(np.abs(iv_wrong - iv_right)))

    fig, ax = plt.subplots(figsize=(6.9, 3.9))
    iv_nodes = 100 * np.sqrt(w_nodes / t_nodes)
    ax.plot(tq, iv_right, color=TEAL, lw=2.0,
            label="interpolated in the variance clock (production)")
    ax.plot(tq, iv_wrong, color=RUST, lw=1.8, ls="--",
            label="interpolated in calendar time")
    ax.plot(t_nodes, iv_nodes, "o", ms=5, color="black", zorder=5,
            label="quoted expiries")
    ax.axvline(TE, color=PALETTE["ink"], lw=0.8, alpha=0.5)
    ax.annotate("event", xy=(TE + 0.01, float(iv_right.min()) - 0.12),
                fontsize=8.5, color=SLATE)
    ax.set_xlabel(r"calendar time $T$ (years)")
    ax.set_ylabel("ATM implied volatility (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    save(fig, OUT / "fig_emc_interp.pdf")


# ---------------------------------------------------------------------------
# Figure 4: identifiability audit — planted vs recovered event sizes.
# ---------------------------------------------------------------------------


def figure_ident() -> None:
    t_nodes = np.array([0.10, 0.20, 0.35, 0.60])
    planted = np.array([1.0, 2.0, 3.0, 5.0, 8.0])

    def sweep(sigma: float) -> np.ndarray:
        rec = []
        for n_days in planted:
            tau_nodes = np.array([weighted_variance_years(
                float(t), [(0.15, float(n_days))]) for t in t_nodes])
            ev = autocalibrate_events(t_nodes, sigma**2 * tau_nodes,
                                      n_events=3)
            rec.append(sum(n for te, n in ev if 0.10 < te <= 0.20))
        return np.array(rec)

    rec_hi = sweep(0.40)
    rec_lo = sweep(0.20)
    macro("emcidentshrink", "%.2f", float(np.max(planted - rec_hi)))
    macro("emcidentlowfloor", "%.0f",
          float(planted[rec_lo <= 0.0].max()) if np.any(rec_lo <= 0.0) else 0)

    ev_flat = autocalibrate_events(t_nodes, 0.40**2 * t_nodes, n_events=3)
    macro("emcidentflat", "%d", len(ev_flat))

    fig, ax = plt.subplots(figsize=(6.6, 3.9))
    lim = (-0.3, planted.max() * 1.1)
    ax.plot(lim, lim, color=PALETTE["ink"], lw=0.8, ls=":")
    ax.plot(planted, rec_hi, "o", ms=7, color=TEAL, mfc="none", mew=1.8,
            label=r"$\sigma=40\%$: recovered (mild shrinkage)")
    ax.plot(planted, rec_lo, "x", ms=7, color=RUST, mew=1.8,
            label=r"$\sigma=20\%$: below materiality until large")
    ax.plot([0.0], [len(ev_flat)], "s", ms=7, color=SLATE,
            label="flat term structure: no events")
    ax.set_xlabel("planted event size (extra days)")
    ax.set_ylabel("recovered size (extra days)")
    ax.set_xlim(*lim)
    ax.set_ylim(*lim)
    ax.legend(fontsize=8.5, loc="upper left")
    save(fig, OUT / "fig_emc_ident.pdf")


# ---------------------------------------------------------------------------
# Appendix verification: the clock listing against production.
# ---------------------------------------------------------------------------


def listing_weighted_variance_years(t_cal, events, normalize=False, dpy=365.0):
    if t_cal <= 0:
        return t_cal
    tau_days = t_cal * dpy + sum(n for te, n in events
                                 if te <= t_cal and n > 0)
    if normalize:
        e1 = sum(n for te, n in events if te <= 1.0 and n > 0)
        tau_days *= dpy / (dpy + e1)
    return tau_days / dpy


def verify_listings() -> None:
    rng_t = np.linspace(0.01, 2.0, 97)
    evs = [(0.1, 2.0), (0.25, 4.0), (0.9, 1.5), (1.4, 3.0)]
    d = 0.0
    for norm in (False, True):
        for t in rng_t:
            d = max(d, abs(listing_weighted_variance_years(float(t), evs, norm)
                           - weighted_variance_years(float(t), evs,
                                                     normalize=norm)))
    sci_macro("emcrefagree", d)
    macro("emcdays", "%.0f", DAYS_PER_YEAR)


# ---------------------------------------------------------------------------


def main() -> None:
    figure_hero()
    print("hero done")
    figure_clock()
    print("clock done")
    figure_interp()
    print("interp done")
    figure_ident()
    print("ident done")
    verify_listings()

    macro("emcte", "%.2f", TE)
    macro("emcextra", "%d", int(EXTRA))
    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("emcgencommit", "%s", commit)
    macro("emcgendate", "%s", date.today().isoformat())

    (OUT / "event_market_tables.tex").write_text("\n".join(MACROS) + "\n",
                                                 encoding="utf-8")
    (OUT / "event_market_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
