"""Figures for Note 13 (Bayesian prior persistence).

(1) The universal activation gate gap = max(1 - obs/req, 0)^gamma.
(2) "Don't damp the signal": an overnight ATM jump is densely quoted (gate off at
    ATM, market wins) while the wings are unquoted (gate on, prior holds them) --
    built with the REAL build_prior_anchor + calibrate_slice prior block.

  fig_prior_gate.pdf    activation gate vs observation precision
  fig_prior_nodamp.pdf  market-only vs prior-persisted fit
  prior_tables.tex      \\input-able macros
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from volfit.calib.precision import activation_gap
from volfit.calib.prior import build_prior_anchor
from volfit.models.lqd.calibrate import calibrate_slice
from volfit.models.svi_jw.svi import RawSVI

OUT = Path(__file__).resolve().parent
plt.rcParams.update(
    {
        "figure.figsize": (7.2, 4.3),
        "font.size": 11,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "lines.linewidth": 1.8,
        "savefig.bbox": "tight",
        "savefig.dpi": 200,
    }
)
TEAL, RUST, SLATE, AMBER, VIOLET = "#0f766e", "#b91c1c", "#334155", "#b45309", "#6d28d9"


def gate_fig():
    obs = np.linspace(0, 2, 300)
    req = 1.0
    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    for gamma, c in [(0.5, AMBER), (1.0, TEAL), (2.0, VIOLET)]:
        ax.plot(obs, activation_gap(obs, req, gamma), color=c,
                label=fr"$\gamma={gamma}$")
    ax.axvline(req, color=SLATE, ls=":", label="required precision")
    ax.set_xlabel(r"observation precision / required")
    ax.set_ylabel(r"prior gate $\mathrm{gap}$")
    ax.set_title(r"Prior off where data is sufficient ($\mathrm{obs}\geq\mathrm{req}$)",
                 fontsize=10)
    ax.legend(frameon=False)
    fig.savefig(OUT / "fig_prior_gate.pdf")
    plt.close(fig)


def nodamp_fig():
    t = 0.25
    # Yesterday's prior: calm 20% ATM, moderate skew.
    prior = RawSVI(a=0.018, b=0.05, rho=-0.45, m=0.04, sigma=0.11)
    # Today's market: ATM jumped to ~25% with steeper skew (a vol spike).
    today = RawSVI(a=0.030, b=0.07, rho=-0.55, m=0.05, sigma=0.10)

    # Only the ATM region is quoted today; the wings have no fresh quotes.
    k_q = np.linspace(-0.10, 0.10, 11)
    w_q = today.total_variance(k_q)

    market_only = calibrate_slice(k_q, w_q, t, n_order=6, reg_lambda=1e-6)

    target, unmet = build_prior_anchor(
        prior_w=lambda k: prior.total_variance(k),
        prior_tau=t, k_quotes=k_q, tau=t,
        total_budget=float(k_q.size),     # 100%-class budget
    )
    persisted = calibrate_slice(k_q, w_q, t, n_order=6, reg_lambda=1e-6,
                                prior_anchor=target)

    kk = np.linspace(-0.40, 0.34, 300)
    fig, ax = plt.subplots()
    ax.plot(kk, 100 * prior.implied_vol(kk, t), color=SLATE, ls=":",
            label="prior (yesterday)")
    ax.plot(kk, 100 * market_only.slice.implied_vol(kk, t), color=RUST, ls="--",
            label="market-only fit (wings unpinned)")
    ax.plot(kk, 100 * persisted.slice.implied_vol(kk, t), color=TEAL,
            label="prior-persisted fit")
    ax.scatter(k_q, 100 * np.sqrt(w_q / t), s=16, color="black", zorder=5,
               label="today's ATM quotes")
    ax.axvspan(-0.10, 0.10, color="black", alpha=0.04)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"implied volatility (\%)")
    ax.set_title("ATM follows the market jump; wings held by the prior", fontsize=10)
    ax.legend(frameon=False, fontsize=9)
    fig.savefig(OUT / "fig_prior_nodamp.pdf")
    plt.close(fig)

    # ATM is preserved (not damped toward the calmer prior)
    atm_market = 100 * np.sqrt(today.total_variance(0.0) / t)
    atm_prior = 100 * np.sqrt(prior.total_variance(0.0) / t)
    atm_persisted = 100 * persisted.slice.implied_vol(np.array([0.0]), t)[0]
    # wing pulled toward prior
    kw = -0.30
    wing_market_only = 100 * market_only.slice.implied_vol(np.array([kw]), t)[0]
    wing_persisted = 100 * persisted.slice.implied_vol(np.array([kw]), t)[0]
    wing_prior = 100 * prior.implied_vol(np.array([kw]), t)[0]
    return dict(atm_market=atm_market, atm_prior=atm_prior, atm_persisted=atm_persisted,
                wing_prior=wing_prior, wing_mo=wing_market_only, wing_ps=wing_persisted,
                unmet=unmet)


def main():
    gate_fig()
    d = nodamp_fig()
    L = ["% Auto-generated by gen_prior.py — do not edit."]
    L.append(r"\newcommand{\priatmmarket}{%.1f}" % d["atm_market"])
    L.append(r"\newcommand{\priatmprior}{%.1f}" % d["atm_prior"])
    L.append(r"\newcommand{\priatmpersist}{%.1f}" % d["atm_persisted"])
    L.append(r"\newcommand{\priwingprior}{%.1f}" % d["wing_prior"])
    L.append(r"\newcommand{\priwingmo}{%.1f}" % d["wing_mo"])
    L.append(r"\newcommand{\priwingps}{%.1f}" % d["wing_ps"])
    L.append(r"\newcommand{\priunmet}{%.0f}" % (100 * d["unmet"]))
    (OUT / "prior_tables.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("ATM: prior %.1f market %.1f persisted %.1f | wing: prior %.1f mkt-only %.1f persisted %.1f"
          % (d["atm_prior"], d["atm_market"], d["atm_persisted"],
             d["wing_prior"], d["wing_mo"], d["wing_ps"]))


if __name__ == "__main__":
    main()
