"""Figures and tables for Note 08 (variance-swap targets).

(1) Convergence of the log-contract replication vs integration half-width, and the
    agreement between LQD's closed-form var-swap and the generic replication.
(2) A fit pulled by a var-swap target above the smile's natural fair var-swap.

Outputs:
  fig_vs_convergence.pdf  fair var-swap vol vs replication half-width
  fig_vs_fit.pdf          smile with / without a var-swap target
  vs_tables.tex           \\input-able macros
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from volfit.calib.varswap import VarSwapTarget, varswap_total_variance
from volfit.models.lqd.calibrate import calibrate_slice
from volfit.models.svi_jw.svi import RawSVI

OUT = Path(__file__).resolve().parent
import sys  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
from style import PALETTE, setup  # noqa: E402

setup()
TEAL, RUST, SLATE = PALETTE['teal'], PALETTE['rust'], PALETTE['muted']
RAW = RawSVI(a=0.0106, b=0.0729, rho=-0.5, m=0.0583, sigma=0.1010)


def main():
    t = 0.5
    k = np.linspace(-0.35, 0.30, 23)
    w = RAW.total_variance(k)
    base = calibrate_slice(k, w, t, n_order=6, reg_lambda=1e-6)

    # closed form vs replication
    w_vs_closed = base.slice.var_swap_strike()
    w_vs_repl = varswap_total_variance(base.slice.implied_w)
    vs_vol_closed = np.sqrt(w_vs_closed / t)
    vs_vol_repl = np.sqrt(w_vs_repl / t)
    agree_bp = 1e4 * abs(vs_vol_closed - vs_vol_repl)

    # convergence vs half-width
    hws = np.linspace(1.0, 8.0, 30)
    vols = [np.sqrt(varswap_total_variance(base.slice.implied_w, half_width=h) / t)
            for h in hws]
    fig, ax = plt.subplots(figsize=(7.2, 3.6))
    ax.plot(hws, 100 * np.array(vols), color=TEAL)
    ax.axvline(6.0, color=SLATE, ls=":", label=r"production half-width $=6$")
    ax.set_xlabel(r"replication half-width (log-moneyness)")
    ax.set_ylabel(r"fair var-swap vol (%)")
    ax.legend(frameon=False)
    fig.savefig(OUT / "fig_vs_convergence.pdf")
    plt.close(fig)

    # fit pulled by a var-swap target above the natural level
    target_vol = vs_vol_closed + 0.015          # +1.5 vol points
    target = VarSwapTarget(total_var=float(target_vol**2 * t),
                           weight=float(8.0), t=t)
    pulled = calibrate_slice(k, w, t, n_order=6, reg_lambda=1e-6, var_swap=target)
    pulled_vol = np.sqrt(pulled.slice.var_swap_strike() / t)

    kk = np.linspace(-0.40, 0.34, 300)
    fig, ax = plt.subplots()
    ax.plot(kk, 100 * base.slice.implied_vol(kk, t), color=SLATE,
            label=fr"no target (var-swap {100*vs_vol_closed:.2f}%)")
    ax.plot(kk, 100 * pulled.slice.implied_vol(kk, t), color=TEAL, ls="--",
            label=fr"with target (var-swap {100*pulled_vol:.2f}%)")
    ax.scatter(k, 100 * np.sqrt(w / t), s=12, color=RUST, zorder=5, label="option quotes")
    ax.axhline(100 * target_vol, color=RUST, ls=":", lw=1.0,
               label=fr"var-swap quote {100*target_vol:.2f}%")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"implied volatility (%)")
    ax.legend(frameon=False, fontsize=9)
    fig.savefig(OUT / "fig_vs_fit.pdf")
    plt.close(fig)

    L = ["% Auto-generated by gen_varswap.py — do not edit."]
    L.append(r"\newcommand{\vsclosed}{%.2f}" % (100 * vs_vol_closed))
    L.append(r"\newcommand{\vsrepl}{%.2f}" % (100 * vs_vol_repl))
    L.append(r"\newcommand{\vsagreebp}{%.2f}" % agree_bp)
    L.append(r"\newcommand{\vstarget}{%.2f}" % (100 * target_vol))
    L.append(r"\newcommand{\vspulled}{%.2f}" % (100 * pulled_vol))
    L.append(r"\newcommand{\vshalfwidth}{6.0}")
    L.append(r"\newcommand{\vspoints}{801}")
    (OUT / "vs_tables.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    (OUT / "vs_numbers.json").write_text(json.dumps(
        {"closed_pct": 100 * vs_vol_closed, "repl_pct": 100 * vs_vol_repl,
         "agree_bp": agree_bp, "target_pct": 100 * target_vol,
         "pulled_pct": 100 * pulled_vol}, indent=2), encoding="utf-8")
    print("var-swap closed %.3f%% repl %.3f%% (agree %.2f bp); target %.2f%% -> pulled %.2f%%"
          % (100 * vs_vol_closed, 100 * vs_vol_repl, agree_bp, 100 * target_vol, 100 * pulled_vol))


if __name__ == "__main__":
    main()
