"""Figures for Note 06 (forwards, discounting, dividends).

(1) Put-call parity regression: C - P = D (F - K) recovers the forward F and the
    discount D from option mids.
(2) The discount clamp: the parity slope is the worst-identified parameter; on a
    noisy feed it drifts to an unphysical rate, which the clamp pins to a band.

  fig_fwd_parity.pdf   C-P vs K with the parity regression line
  fig_fwd_clamp.pdf    implied rate vs slope noise, with the clamp band
  fwd_tables.tex       \\input-able macros
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from volfit.core.black import black_call

OUT = Path(__file__).resolve().parent
import sys  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
from style import PALETTE, setup  # noqa: E402

setup()
TEAL, RUST, SLATE, AMBER = (PALETTE['teal'], PALETTE['rust'],
                            PALETTE['muted'], PALETTE['amber'])
RATE_MIN, RATE_MAX = -0.05, 0.30


def main():
    s, t, r, q, sig = 100.0, 0.5, 0.04, 0.01, 0.22
    fwd = s * np.exp((r - q) * t)
    disc = np.exp(-r * t)
    strikes = np.linspace(82, 120, 16)
    k = np.log(strikes / fwd)
    w = sig**2 * t
    call = disc * fwd * black_call(k, w * np.ones_like(k))
    put = disc * fwd * (black_call(k, w * np.ones_like(k)) - 1.0 + np.exp(k))
    diff = call - put                          # = D (F - K)

    # parity regression: diff = a + b K, b = -D, a = D F
    A = np.column_stack([np.ones_like(strikes), strikes])
    (a, b), *_ = np.linalg.lstsq(A, diff, rcond=None)
    D_hat = -b
    F_hat = a / D_hat
    r_hat = -np.log(D_hat) / t

    fig, ax = plt.subplots()
    ax.scatter(strikes, diff, s=22, color=RUST, zorder=5, label="$C-P$ (mids)")
    kk = np.linspace(80, 122, 50)
    ax.plot(kk, a + b * kk, color=TEAL, label="parity fit $D(F-K)$")
    ax.axhline(0, color="black", lw=0.7)
    ax.axvline(F_hat, color=SLATE, ls=":", label=fr"forward $F={F_hat:.2f}$")
    ax.set_xlabel("strike $K$")
    ax.set_ylabel("$C-P$")
    ax.set_title(fr"slope $=-D$ gives rate ${100*r_hat:.2f}\%$, intercept gives $F$",
                 fontsize=10)
    ax.legend(frameon=False, fontsize=9)
    fig.savefig(OUT / "fig_fwd_parity.pdf")
    plt.close(fig)

    # clamp: as slope noise scales the discount, the implied rate leaves the band
    scales = np.linspace(0.7, 1.6, 200)        # multiplicative slope error
    D_noisy = D_hat * scales
    rate_noisy = -np.log(np.clip(D_noisy, 1e-6, None)) / t
    rate_clamped = np.clip(rate_noisy, RATE_MIN, RATE_MAX)
    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    ax.axhspan(100 * RATE_MIN, 100 * RATE_MAX, color=TEAL, alpha=0.08,
               label="physical band")
    ax.plot(scales, 100 * rate_noisy, color=RUST, ls="--", label="raw parity rate")
    ax.plot(scales, 100 * rate_clamped, color=TEAL, label="clamped rate")
    ax.axhline(100 * RATE_MIN, color=SLATE, lw=0.7)
    ax.axhline(100 * RATE_MAX, color=SLATE, lw=0.7)
    ax.set_xlabel("parity-slope error (multiplicative)")
    ax.set_ylabel(r"implied rate (%)")
    ax.set_ylim(-40, 60)
    ax.set_title("A noisy slope drifts the rate out of the band; the clamp pins it",
                 fontsize=10)
    ax.legend(frameon=False, fontsize=9)
    fig.savefig(OUT / "fig_fwd_clamp.pdf")
    plt.close(fig)

    L = ["% Auto-generated by gen_forwards.py — do not edit."]
    L.append(r"\newcommand{\fwdtrue}{%.2f}" % fwd)
    L.append(r"\newcommand{\fwdhat}{%.2f}" % F_hat)
    L.append(r"\newcommand{\fwdrate}{%.2f}" % (100 * r_hat))
    L.append(r"\newcommand{\fwdratemin}{%d}" % int(100 * RATE_MIN))
    L.append(r"\newcommand{\fwdratemax}{%d}" % int(100 * RATE_MAX))
    (OUT / "fwd_tables.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("true F %.2f recovered %.2f, rate %.2f%%" % (fwd, F_hat, 100 * r_hat))


if __name__ == "__main__":
    main()
