"""Figure and macros for Note 05: the de-Americanization wedge on a REAL chain.

Note-figures variant of Docs/deck/gen_deam_real_fig.py (deck slide 15). Uses the
production CRR machinery (volfit.core.american) on the true-weekly Massive
capture (backend/tests/fixtures/lv_weekly_massive.json, SPY, as-of 2026-06-25):
for every put of the December-2026 expiry (~6 months out), invert the observed
American mid two ways --- naively through a EUROPEAN tree (what a fitter that
ignores early exercise would see) and properly through the AMERICAN tree (the
de-Americanized European-equivalent vol). The wedge that opens on in-the-money
puts IS the early-exercise premium, on live market prices.

Carry note: this delayed-tier capture's parity-implied rate is unphysical
(negative, clamped; see Note 06), so the carry is supplied: r = 4.3%
money-market, q = 1.2% SPY dividend yield (mid-2026). The note's caption and
prose state this.

Outputs (next to this file):
  fig_deam_real.pdf       naive-European vs de-Americanized IV, live SPY puts
  deam_real_tables.tex    \\input-able macros (median/max ITM bias, put count)
  deam_real_numbers.json  the same numbers, machine-readable

Run from the repo root with the project venv:
  .\\.venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_deam_real.py
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import brentq

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))  # shared figure style (STYLE_GUIDE.md section 6)
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))  # lv_benchmark fixture loader

from style import PALETTE, save, setup  # noqa: E402

from lv_benchmark import load_benchmark  # noqa: E402
from volfit.core.american import binomial_price, deamericanize_batch  # noqa: E402

setup()
TEAL, RUST, SLATE = PALETTE["teal"], PALETTE["rust"], PALETTE["muted"]

FIXTURE = REPO / "backend" / "tests" / "fixtures" / "lv_weekly_massive.json"
EXPIRY = date(2026, 12, 18)  # ~6 months from the capture as-of
R, Q = 0.043, 0.012  # supplied carry (see module docstring / Note 06)


def naive_european_iv(mid: float, s: float, k: float, t: float) -> float:
    """The biased vol: invert the AMERICAN market price through a EUROPEAN tree."""
    try:
        return brentq(
            lambda v: binomial_price(False, s, k, t, v, R, Q, american=False) - mid,
            1e-3, 3.0, xtol=1e-8,
        )
    except ValueError:
        return np.nan


def main() -> None:
    data, chains = load_benchmark(FIXTURE)
    ref = date.fromisoformat(data["as_of"])
    snap = chains["SPY"]
    s = float(snap.spot)
    t = (EXPIRY - ref).days / 365.0

    puts = sorted(
        (x for x in snap.quotes_for(EXPIRY)
         if x.call_put == "P" and x.mid is not None and x.bid and x.bid > 0),
        key=lambda x: x.strike,
    )
    ks = np.array([p.strike for p in puts], dtype=float)
    mids = np.array([p.mid for p in puts], dtype=float)

    keep = (ks >= 0.55 * s) & (ks <= 1.38 * s)
    ks, mids = ks[keep], mids[keep]

    deam = deamericanize_batch(np.zeros(ks.size, dtype=bool), mids, s, ks, t, R, Q)
    naive = np.array([naive_european_iv(m, s, float(k), t) for k, m in zip(ks, mids)])

    ok = np.isfinite(deam) & np.isfinite(naive)
    ks, deam, naive = ks[ok], deam[ok], naive[ok]
    pct = 100.0 * ks / s
    bias_bp = 1e4 * (naive - deam)
    itm = pct > 100.0
    med_itm = float(np.median(bias_bp[itm]))
    max_bias = float(bias_bp.max())

    fig, ax = plt.subplots(figsize=(6.9, 4.2))
    ax.fill_between(pct, 100 * deam, 100 * naive, where=pct >= 100.0,
                    color=RUST, alpha=0.10, lw=0)
    ax.plot(pct, 100 * naive, color=RUST, lw=1.8,
            label="American mid inverted as European — biased")
    ax.plot(pct, 100 * deam, color=TEAL, ls="--", lw=2.0,
            label="de-Americanized (CRR-inverted) — European-equivalent")
    ax.axvline(100.0, color=SLATE, ls=":", lw=1.1, alpha=0.8)
    ax.annotate("ATM", xy=(100.0, 0.02), xycoords=("data", "axes fraction"),
                xytext=(3, 0), textcoords="offset points", color=SLATE, fontsize=9)
    i = int(np.argmin(np.abs(pct - 124.0)))
    ax.annotate(
        "the wedge = early-exercise premium\n(median ITM +%.0f bp, max +%.0f bp)"
        % (med_itm, max_bias),
        xy=(pct[i], 50 * (naive[i] + deam[i])), xytext=(-160, 46),
        textcoords="offset points", color=PALETTE["ink"], fontsize=9,
        arrowprops={"arrowstyle": "-", "color": SLATE, "lw": 0.9},
    )
    ax.set_xlabel("put strike (% of spot)")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(frameon=False, loc="upper left", fontsize=9)
    fig.tight_layout()
    save(fig, OUT / "fig_deam_real.pdf")

    lines = [
        "% Auto-generated by gen_deam_real.py — do not edit.",
        r"\newcommand{\deamrealmedianitm}{%.0f}" % med_itm,
        r"\newcommand{\deamrealmaxbias}{%.0f}" % max_bias,
        r"\newcommand{\deamrealnputs}{%d}" % ks.size,
    ]
    (OUT / "deam_real_tables.tex").write_text("\n".join(lines) + "\n",
                                              encoding="utf-8")
    (OUT / "deam_real_numbers.json").write_text(json.dumps(
        {"median_itm_bias_bp": med_itm, "max_bias_bp": max_bias,
         "n_puts": int(ks.size), "spot": s, "t_years": t,
         "expiry": EXPIRY.isoformat(), "as_of": ref.isoformat(),
         "r": R, "q": Q}, indent=2), encoding="utf-8")
    print(f"SPY {EXPIRY} (as-of {ref}), {ks.size} puts, spot {s:.2f}, t={t:.3f}")
    print(f"max bias {max_bias:.0f} bp at K={ks[bias_bp.argmax()]:.0f} "
          f"({pct[bias_bp.argmax()]:.0f}% of spot)")
    print(f"median ITM-put bias {med_itm:.0f} bp; "
          f"median OTM-put bias {np.median(bias_bp[~itm]):.1f} bp")


if __name__ == "__main__":
    main()
