"""Figures for Note 12 (spot-vol dynamics / SSR).

A base smile is transported under a spot move in the three canonical stickiness
regimes (sticky-moneyness SSR=0, sticky-strike SSR=1, sticky-local-vol SSR=2),
and the ATM-vol response is shown as a function of the spot move.

  fig_ssr_transport.pdf   base smile + three transported smiles
  fig_ssr_response.pdf    ATM vol vs spot move for the three regimes
  ssr_tables.tex          \\input-able macros
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from volfit.dynamics.ssr import shifted_smile
from volfit.models.svi_jw.svi import RawSVI

OUT = Path(__file__).resolve().parent
import sys  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
from style import PALETTE, setup  # noqa: E402

setup()
SLATE, TEAL, RUST, AMBER = (PALETTE['muted'], PALETTE['teal'],
                            PALETTE['rust'], PALETTE['amber'])
RAW = RawSVI(a=0.0106, b=0.0729, rho=-0.5, m=0.0583, sigma=0.1010)
T = 0.5
REGIMES = [("sticky moneyness", 0.0, TEAL),
           ("sticky strike", 1.0, AMBER),
           ("sticky local vol", 2.0, RUST)]


def vol_curve(k):
    return RAW.implied_vol(k, T)


def main():
    skew = float((vol_curve(0.01) - vol_curve(-0.01)) / 0.02)
    spot_return = -0.05                     # 5% down move
    k = np.linspace(-0.35, 0.30, 300)

    fig, ax = plt.subplots()
    ax.plot(k, 100 * vol_curve(k), color=SLATE, lw=2.2, label="pre-move smile")
    for name, ssr, c in REGIMES:
        sig = shifted_smile(k, vol_curve, skew, spot_return, regime=ssr)
        ax.plot(k, 100 * sig, color=c, ls="--", label=f"{name} (SSR={ssr:.0f})")
    ax.axvline(0, color="black", lw=0.6, alpha=0.4)
    ax.set_xlabel(r"new-forward log-moneyness $k$")
    ax.set_ylabel(r"implied volatility (%)")
    ax.set_title(r"Smile after a $-5\%$ spot move", fontsize=10)
    ax.legend(frameon=False, fontsize=9)
    fig.savefig(OUT / "fig_ssr_transport.pdf")
    plt.close(fig)

    # ATM vol response vs spot move
    moves = np.linspace(-0.10, 0.10, 41)
    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    for name, ssr, c in REGIMES:
        atm = [shifted_smile(np.array([0.0]), vol_curve, skew, float(m), regime=ssr)[0]
               for m in moves]
        ax.plot(100 * moves, 100 * np.array(atm), color=c, label=f"{name} (SSR={ssr:.0f})")
    ax.set_xlabel(r"spot move (%)")
    ax.set_ylabel(r"ATM implied volatility (%)")
    ax.set_title(r"$\Delta\sigma_{\rm atm}=\mathrm{SSR}\cdot\mathrm{skew}\cdot\delta$",
                 fontsize=10)
    ax.legend(frameon=False, fontsize=9)
    fig.savefig(OUT / "fig_ssr_response.pdf")
    plt.close(fig)

    L = ["% Auto-generated by gen_ssr.py — do not edit."]
    L.append(r"\newcommand{\ssrskew}{%.3f}" % skew)
    L.append(r"\newcommand{\ssrmove}{%d}" % int(100 * spot_return))
    (OUT / "ssr_tables.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("ATM skew %.3f; transported under 3 regimes" % skew)


if __name__ == "__main__":
    main()
