"""Figures for Note 07 (calibration objective: weighting, bands, fit quality).

(1) Density-corrected time-value weights vs equal weights on a non-uniform strike
    set (the real resolve_weights).
(2) A bid-ask band fit vs a mid fit (the real band objective), showing the band
    fit free to sit anywhere inside a wide wing spread.

Outputs:
  fig_obj_weights.pdf   equal vs tv-density weights
  fig_obj_band.pdf      mid fit vs band fit with the quoted band shaded
  obj_tables.tex        \\input-able macros
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from volfit.calib.band import resolve_band
from volfit.calib.weights import resolve_weights
from volfit.models.lqd.calibrate import calibrate_slice
from volfit.models.svi_jw.svi import RawSVI

OUT = Path(__file__).resolve().parent
import sys  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
from style import PALETTE, setup  # noqa: E402

setup()
TEAL, RUST, SLATE, AMBER = (PALETTE['teal'], PALETTE['rust'],
                            PALETTE['muted'], PALETTE['amber'])
RAW = RawSVI(a=0.0106, b=0.0729, rho=-0.5, m=0.0583, sigma=0.1010)


def weights_fig():
    t = 0.5
    # Non-uniform strikes: dense near ATM, sparse in the wings.
    k = np.concatenate([
        np.linspace(-0.35, -0.12, 4),
        np.linspace(-0.10, 0.10, 13),
        np.linspace(0.13, 0.30, 4),
    ])
    w = RAW.total_variance(k)
    equal = np.ones_like(k)
    equal /= equal.mean()
    tv = resolve_weights("tv_density", k, w)

    fig, ax = plt.subplots()
    width = 0.004
    ax.bar(k - width / 2, equal, width=width, color=SLATE, alpha=0.6, label="equal")
    ax.bar(k + width / 2, tv, width=width, color=TEAL, label="tv-density")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("normalized quote weight")
    ax.set_title("Dense ATM down-weighted, sparse wings up-weighted", fontsize=10)
    ax.legend(frameon=False)
    fig.savefig(OUT / "fig_obj_weights.pdf")
    plt.close(fig)
    return float(tv.max() / tv[np.argmin(np.abs(k))])


def band_fig():
    t = 0.5
    k = np.linspace(-0.32, 0.28, 19)
    w_mid = RAW.total_variance(k)
    iv_mid = np.sqrt(w_mid / t)
    # Spread widens into the wings (illiquidity); add a deliberate noise wiggle so
    # the mid fit and band fit visibly differ.
    spread = 0.006 + 0.025 * np.abs(k)
    noise = 0.009 * np.sin(9 * k)
    iv_mid_noisy = iv_mid + noise
    iv_bid = iv_mid_noisy - spread
    iv_ask = iv_mid_noisy + spread

    mid_res = calibrate_slice(k, (iv_mid_noisy**2) * t, t, n_order=10, reg_lambda=1e-8)
    band = resolve_band(iv_bid, iv_mid_noisy, iv_ask, "bidask")
    band_res = calibrate_slice(k, (iv_mid_noisy**2) * t, t, n_order=10,
                               reg_lambda=1e-8, band=band)

    kk = np.linspace(-0.35, 0.30, 300)
    fig, ax = plt.subplots()
    ax.fill_between(k, 100 * iv_bid, 100 * iv_ask, color=AMBER, alpha=0.18,
                    label="bid-ask band")
    ax.plot(kk, 100 * mid_res.slice.implied_vol(kk, t), color=RUST, ls="--",
            label="mid fit (chases noise)")
    ax.plot(kk, 100 * band_res.slice.implied_vol(kk, t), color=TEAL,
            label="band fit (sits in band)")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"implied volatility (%)")
    ax.legend(frameon=False)
    fig.savefig(OUT / "fig_obj_band.pdf")
    plt.close(fig)
    # smoothness proxy: integrated |curvature| of each fit
    def roughness(res):
        v = 100 * res.slice.implied_vol(kk, t)
        return float(np.sum(np.abs(np.diff(v, 2))))
    return roughness(mid_res), roughness(band_res)


def main():
    atm_ratio = weights_fig()
    rough_mid, rough_band = band_fig()
    L = ["% Auto-generated by gen_objective.py — do not edit."]
    L.append(r"\newcommand{\objwingratio}{%.1f}" % atm_ratio)
    L.append(r"\newcommand{\objroughmid}{%.1f}" % rough_mid)
    L.append(r"\newcommand{\objroughband}{%.1f}" % rough_band)
    L.append(r"\newcommand{\objmidanchor}{%.2f}" % 0.05)
    (OUT / "obj_tables.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wing/ATM weight ratio %.1f; roughness mid %.1f band %.1f"
          % (atm_ratio, rough_mid, rough_band))


if __name__ == "__main__":
    main()
