"""Figure suite for the beyond-the-last-quote edition of Note 09 (wings).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_wings_lastquote.py

Every slope, fit, repair and audit number is produced by PRODUCTION machinery
(``volfit.models.lqd.basis`` Lee maps, the three calibrators, the sigmoid
Durrleman kernels, the calendar floor grids, the local-vol source PDE); local
formulae define only the synthetic targets.  The running character is the
series benchmark slice ``jw_to_raw(SVIJW(t=0.5, v=0.0425, psi=-0.25, p=0.75,
c=0.25, v_tilde=0.034))`` shared with the original Note-09 suite.  The hero
figure reads the standing real-data export
``tmp/volfit_surfaces_20260718_1324.json`` (SPY, Massive).

Historical backtest numbers (census, ablation, EEM/EFA) are NEVER recomputed
here — the note quotes them from the stored artifacts
``backend/backtest/FINDINGS_calibration_arb.md``,
``FINDINGS_ablation_arb.md`` and
``results/spike_aug2024_ablation_arb_EEM_EFA_2d.json``.

Outputs, written next to this script:

* ``fig_wlq_hero.pdf``    -- real SPY wing: quoted span vs published curve,
                             structural Lee slopes from the stored params;
* ``fig_wlq_ceiling.pdf`` -- the Lee map, and the beta > 2 pathology (call
                             prices that refuse to die);
* ``fig_wlq_extrap.pdf``  -- three models, one window, three admissible tails;
* ``fig_wlq_limit.pdf``   -- THESIS: the limit is not the wing (a hat with
                             untouched slopes dents the finite density);
* ``fig_wlq_hinge.pdf``   -- the put-wing hinge repairing the synthetic arb
                             slice; byte-identity on the clean one;
* ``fig_wlq_confine.pdf`` -- the phantom calendar crossing between two
                             extrapolations, and the confined floor grid;
* ``fig_wlq_lv.pdf``      -- the LV deep-put slope knob and its var-swap;
* ``wings_lastquote_tables.tex`` / ``wings_lastquote_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from volfit.calib.calendar import (  # noqa: E402
    variance_floor_grid,
    variance_floor_grid_from,
)
from volfit.core.black import black_call  # noqa: E402
from volfit.models.localvol import (  # noqa: E402
    AffineVarianceSurface,
    solve_varswap_source,
)
from volfit.models.lqd.basis import LQDParams, lee_psi, lee_slopes  # noqa: E402
from volfit.models.lqd.calibrate import calibrate_slice  # noqa: E402
from volfit.models.sigmoid.calibrate import calibrate_sigmoid  # noqa: E402
from volfit.models.sigmoid.kernels import gatheral_g_from_z  # noqa: E402
from volfit.models.sigmoid.sigmoid import HatCore, MultiCoreSiv  # noqa: E402
from volfit.models.svi_jw.calibrate import calibrate_svi  # noqa: E402
from volfit.models.svi_jw.svi import SVIJW, RawSVI, jw_to_raw  # noqa: E402

setup()
TEAL, BLUE, RUST, AMBER, SLATE, VIOLET, GREEN = (
    PALETTE["teal"], PALETTE["blue"], PALETTE["rust"], PALETTE["amber"],
    PALETTE["muted"], PALETTE["violet"], PALETTE["green"],
)

T = 0.5
RAW = jw_to_raw(SVIJW(t=T, v=0.0425, psi=-0.25, p=0.75, c=0.25, v_tilde=0.034))
K_QUOTES = np.linspace(-0.35, 0.30, 23)
W_QUOTES = RAW.total_variance(K_QUOTES)

MACROS: list[str] = ["% Auto-generated by gen_wings_lastquote.py — do not edit."]
NUMBERS: dict = {}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def sci_macro(name: str, value: float) -> None:
    """Emit a tiny value as \\ensuremath{m\\times10^{e}} (house number format)."""
    e = int(np.floor(np.log10(abs(value))))
    m = value / 10.0**e
    MACROS.append(r"\newcommand{\%s}{\ensuremath{%.1f\times10^{%d}}}"
                  % (name, m, e))
    NUMBERS[name] = float(value)


def siv_g(model: MultiCoreSiv, z: np.ndarray) -> np.ndarray:
    """Durrleman g of a sigmoid slice via the production analytic kernels."""
    v, vz, vzz = model.variance_z(z)
    return gatheral_g_from_z(z, v, vz, vzz, model.t, model.sigma_ref)


# ---------------------------------------------------------------------------
# Figure 1 (hero): the real SPY wing and its structural slopes.
# ---------------------------------------------------------------------------


def figure_hero() -> None:
    fixture = REPO / "tmp" / "volfit_surfaces_20260718_1324.json"
    if not fixture.exists():
        raise FileNotFoundError(
            f"standing reference export not found: {fixture} — regenerate via "
            "the app's surfaces export (see memory: reference-live-fixture)")
    doc = json.loads(fixture.read_text(encoding="utf-8"))
    spy = next(tk for tk in doc["tickers"] if tk["ticker"] == "SPY")
    node = spy["nodes"][-1]  # 2027-06-17, the longest expiry
    p = node["lqdParams"]
    beta_l, beta_r = lee_slopes(LQDParams(L=p["L"], R=p["R"], a=np.array(p["a"])))
    macro("wlqherobetaL", "%.3f", beta_l)
    macro("wlqherobetaR", "%.3f", beta_r)
    # The moment exponent the left slope implies, via the inverse Lee map.
    qstar = 1.0 / (2.0 * beta_l) + beta_l / 8.0 - 0.5
    macro("wlqheroqstar", "%.2f", qstar)

    ks = np.array([c["k"] for c in node["curve"]])
    ivs = np.array([c["iv"] for c in node["curve"]])
    cols = node["inputs"]["preparedColumns"]
    prep = np.array(node["inputs"]["prepared"], dtype=float)
    kq = prep[:, cols.index("k")]
    ivq = prep[:, cols.index("ivMid")]
    span = (ks.max() - ks.min())
    extrap = (kq.min() - ks.min()) + (ks.max() - kq.max())
    macro("wlqheroextrapshare", "%.0f", 100 * extrap / span)

    fig, ax = plt.subplots(figsize=(6.9, 3.9))
    ax.axvspan(kq.min(), kq.max(), color=AMBER, alpha=0.14, lw=0,
               label="quoted strikes")
    ax.plot(ks, 100 * ivs, color=TEAL, lw=2.0, label="published fitted curve")
    ax.plot(kq, 100 * ivq, "o", ms=1.8, color=RUST, label="prepared quotes")
    ax.annotate(f"structural slopes $\\beta_L={beta_l:.2f}$, "
                f"$\\beta_R={beta_r:.2f}$\n(from the stored parameters)",
                xy=(0.02, 0.86), xycoords="axes fraction", fontsize=9,
                color=PALETTE["ink"])
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    save(fig, OUT / "fig_wlq_hero.pdf")


# ---------------------------------------------------------------------------
# Figure 2: the Lee map, and the ceiling made visible.
# ---------------------------------------------------------------------------


def figure_ceiling() -> None:
    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    pp = np.linspace(1e-6, 4, 300)
    ax.plot(pp, lee_psi(pp), color=TEAL, lw=2.0)
    ax.axhline(2.0, color=RUST, ls="--", lw=1.1)
    ax.annotate(r"the ceiling $\beta=2$", xy=(2.4, 1.90), fontsize=9,
                color=RUST)
    ax.set_xlabel(r"moment critical exponent $p$")
    ax.set_ylabel(r"wing slope $\beta=\psi(p)$")
    ax.set_ylim(0, 2.15)
    label_panel(ax, "A")
    ax = axes[1]
    kk = np.linspace(0.5, 25.0, 400)
    for beta, col in ((1.2, TEAL), (2.0, AMBER), (2.8, RUST)):
        ax.plot(kk, black_call(kk, beta * kk), color=col, lw=1.9,
                label=rf"$\beta={beta}$")
    ax.axhline(0.5, color=PALETTE["ink"], lw=0.7, ls=":")
    ax.annotate(r"$1/2$", xy=(0.9, 0.515), fontsize=9,
                color=PALETTE["ink"])
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"normalized call $B(k,\beta k)$")
    ax.legend(fontsize=8.5, loc="center right", title=r"along $w=\beta k$",
              title_fontsize=8.5)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_wlq_ceiling.pdf")


# ---------------------------------------------------------------------------
# Figure 3: three models, one window, three admissible tails (+ beta macros).
# ---------------------------------------------------------------------------


def figure_extrap() -> None:
    lqd = calibrate_slice(K_QUOTES, W_QUOTES, T, n_order=6, reg_lambda=1e-6).slice
    svi = calibrate_svi(K_QUOTES, W_QUOTES, T).raw
    siv = calibrate_sigmoid(K_QUOTES, W_QUOTES, T, n_cores=0)

    bL_lqd, bR_lqd = lee_slopes(lqd.params)
    svl, svr = svi.wing_slopes()
    wl_z, wr_z = siv.wing_slopes()
    scale = np.sqrt(siv.t) / siv.sigma_ref
    betas = {"LQD": (bL_lqd, bR_lqd), "SVI": (svl, svr),
             "MCS": (abs(wl_z) * scale, abs(wr_z) * scale)}
    for name, (bl, br) in betas.items():
        macro("wlqbeta%sL" % name, "%.4f", bl)
        macro("wlqbeta%sR" % name, "%.4f", br)
    macro("wlqsvicap", "%.4f", svi.b * (1.0 + abs(svi.rho)))

    fig, ax = plt.subplots(figsize=(6.9, 4.0))
    kk = np.linspace(-0.95, 0.80, 400)
    for name, iw, col, ls in (("LQD", lqd.implied_w, TEAL, "-"),
                              ("SVI", svi.implied_w, RUST, "--"),
                              ("MCS", siv.implied_w, AMBER, ":")):
        ax.plot(kk, iw(kk), color=col, lw=1.9, ls=ls, label=name)
    ax.axvspan(K_QUOTES.min(), K_QUOTES.max(), color="black", alpha=0.05,
               label="fit window")
    ax.scatter(K_QUOTES, W_QUOTES, s=10, color="black", zorder=5)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"total variance $w(k)$")
    ax.legend(fontsize=8.5, loc="upper right")
    callout(ax, "inside: agreement to vol bps",
            xy=(0.0, float(lqd.implied_w(np.array([0.0]))[0])),
            xytext=(-0.42, 0.075))
    callout(ax, "outside: each model's own law",
            xy=(-0.85, float(svi.implied_w(np.array([-0.85]))[0])),
            xytext=(-0.55, 0.150))
    save(fig, OUT / "fig_wlq_extrap.pdf")


# ---------------------------------------------------------------------------
# Figure 4 (thesis): the limit is not the wing.
# ---------------------------------------------------------------------------

# A milder cousin of the production test suite's synthetic arb slice (same
# base, same hat placement, amplitude -0.10 instead of -0.90): the variance
# stays strictly positive everywhere -- no floored quotes -- yet the hat's
# CURVATURE still drives the Durrleman density negative at finite z while
# leaving the asymptotic slopes untouched.
ARB = MultiCoreSiv(
    v0=0.04, s0=-0.02, k0=0.5, z0=0.0, kappa_p=8.0, kappa_c=3.0,
    sigma_ref=0.2, t=0.25,
    cores=(HatCore(alpha=-0.10, c=-1.3, h=0.5, kappa=8.0),),
)
K_ARB = np.linspace(-0.35, 0.30, 21)
W_ARB = ARB.implied_w(K_ARB)


LIMIT_BASE = MultiCoreSiv(
    v0=0.06, s0=-0.005, k0=0.03, z0=0.0, kappa_p=1.0, kappa_c=0.9,
    sigma_ref=0.2, t=0.25, cores=(),
)
LIMIT_HAT = MultiCoreSiv(
    v0=0.06, s0=-0.005, k0=0.03, z0=0.0, kappa_p=1.0, kappa_c=0.9,
    sigma_ref=0.2, t=0.25,
    cores=(HatCore(alpha=-0.07, c=-2.0, h=0.7, kappa=4.0),),
)


def figure_limit() -> None:
    # Realized far slopes: numerically identical with and without the hat.
    k_far = 2.5
    d = 0.0
    for sgn in (-1.0, 1.0):
        ka = np.array([sgn * k_far])
        d = max(d, abs(float(LIMIT_HAT.implied_w(ka)[0])
                       - float(LIMIT_BASE.implied_w(ka)[0])) / k_far)
    sci_macro("wlqhatslopediff", max(d, 1e-17))

    z = np.linspace(-6.0, 2.5, 600)
    g_arb = siv_g(LIMIT_HAT, z)
    g_base = siv_g(LIMIT_BASE, z)
    i_min = int(np.nanargmin(g_arb))
    macro("wlqhatgdent", "%.1f", float(g_arb[i_min]))
    macro("wlqhatzmin", "%.1f", float(z[i_min]))
    macro("wlqhatbasegmin", "%.2f", float(np.nanmin(g_base)))

    v_arb = LIMIT_HAT.variance_z(z)[0]
    v_base = LIMIT_BASE.variance_z(z)[0]

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.plot(z, v_base, color=SLATE, lw=1.8, label="base (no hat)")
    ax.plot(z, v_arb, color=TEAL, lw=1.9, ls="--", label="base + one hat")
    ax.set_xlabel(r"standardized moneyness $z$")
    ax.set_ylabel(r"variance $v(z)$")
    ax.legend(fontsize=8.5, loc="upper right")
    callout(ax, "tails coincide:\nthe hat is zero-wing",
            xy=(-5.4, float(v_base[np.argmin(np.abs(z + 5.4))]) - 0.012),
            xytext=(-4.3, 0.10))
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(z, g_base, color=SLATE, lw=1.8, label="base: $g>0$ everywhere shown")
    ax.plot(z, g_arb, color=RUST, lw=1.9, ls="--", label="base + hat")
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8, ls=":")
    callout(ax, "the dent: $g<0$ at finite $z$,\nslopes untouched",
            xy=(float(z[i_min]) + 0.12, float(g_arb[i_min]) + 0.15),
            xytext=(-0.6, -2.6))
    ax.set_xlabel(r"standardized moneyness $z$")
    ax.set_ylabel(r"Durrleman $g(z)$")
    ax.legend(fontsize=8.5, loc="lower right")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_wlq_limit.pdf")


# ---------------------------------------------------------------------------
# Figure 5: the put-wing hinge repairing the arb slice; byte-identity.
# ---------------------------------------------------------------------------


def figure_hinge() -> None:
    off = calibrate_sigmoid(K_ARB, W_ARB, 0.25, n_cores=2, wing_penalty=0.0)
    on = calibrate_sigmoid(K_ARB, W_ARB, 0.25, n_cores=2, wing_penalty=1e3)
    z_q = K_ARB / (off.sigma_ref * np.sqrt(off.t))
    z = np.linspace(z_q.min() - 2.0, z_q.max() + 2.0, 400)
    g_off, g_on = siv_g(off, z), siv_g(on, z)
    macro("wlqarbgraw", "%.1f", float(np.nanmin(g_off)))
    macro("wlqarbgfixed", "%.3f", float(np.nanmin(g_on)))

    # Byte-identity on the clean benchmark slice.
    clean_off = calibrate_sigmoid(K_QUOTES, W_QUOTES, T, n_cores=2,
                                  wing_penalty=0.0)
    clean_on = calibrate_sigmoid(K_QUOTES, W_QUOTES, T, n_cores=2,
                                 wing_penalty=1e3)
    kk = np.linspace(-0.5, 0.45, 201)
    diff = float(np.max(np.abs(clean_on.implied_w(kk) - clean_off.implied_w(kk))))
    sci_macro("wlqbyteid", max(diff, 1e-17))

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    kk2 = np.linspace(-0.42, 0.36, 300)
    ax.plot(kk2, 1e2 * np.sqrt(off.implied_w(kk2) / off.t), color=RUST,
            ls="--", lw=1.8, label="penalty off")
    ax.plot(kk2, 1e2 * np.sqrt(on.implied_w(kk2) / on.t), color=TEAL, lw=1.9,
            label="penalty on")
    ax.plot(K_ARB, 1e2 * np.sqrt(W_ARB / 0.25), "o", ms=3.0, color="black",
            zorder=5, label="quotes")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "A")
    ax = axes[1]
    ax.axvspan(z.min(), z_q.min(), color=AMBER, alpha=0.14, lw=0)
    ax.axvspan(z_q.max(), z.max(), color=AMBER, alpha=0.14, lw=0)
    ax.plot(z, g_off, color=RUST, ls="--", lw=1.8, label="penalty off")
    ax.plot(z, g_on, color=TEAL, lw=1.9, label="penalty on")
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8, ls=":")
    ax.annotate("hinge grid extends 2 units\npast the traded range",
                xy=(0.985, 0.05), xycoords="axes fraction", ha="right",
                fontsize=8.5, color=SLATE)
    ax.set_xlabel(r"standardized moneyness $z$")
    ax.set_ylabel(r"Durrleman $g(z)$")
    ax.legend(fontsize=8.5, loc="center left")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_wlq_hinge.pdf")


# ---------------------------------------------------------------------------
# Figure 6: the phantom calendar crossing, and the confined floor grid.
# ---------------------------------------------------------------------------


def figure_confine() -> None:
    near_target = RawSVI(a=0.0010, b=0.0860, rho=-0.5, m=0.0583, sigma=0.1010)
    k_n = np.linspace(-0.35, 0.30, 23)
    near = calibrate_svi(k_n, near_target.total_variance(k_n), 0.25).raw
    far = calibrate_svi(K_QUOTES, W_QUOTES, T).raw

    kk = np.linspace(-1.15, 0.95, 500)
    w_n, w_f = near.total_variance(kk), far.total_variance(kk)
    inside = (kk >= k_n.min()) & (kk <= k_n.max())
    macro("wlqphantominside", "%.1f",
          1e4 * max(0.0, float(np.max(w_n[inside] - w_f[inside]))))
    macro("wlqphantomwide", "%.1f",
          1e4 * max(0.0, float(np.max(w_n - w_f))))
    grid_data = variance_floor_grid_from(k_n)
    grid_wide = variance_floor_grid()

    fig, ax = plt.subplots(figsize=(6.9, 4.0))
    ax.axvspan(k_n.min(), k_n.max(), color=AMBER, alpha=0.14, lw=0,
               label="traded range (both expiries)")
    ax.plot(kk, w_f, color=TEAL, lw=2.0, label="far slice $w(k,T_2)$")
    ax.plot(kk, w_n, color=RUST, lw=1.9, ls="--",
            label="near slice $w(k,T_1)$ (steep wings)")
    cross = kk[(w_n > w_f)]
    if cross.size:
        ax.plot(cross, np.interp(cross, kk, w_f), color=VIOLET, lw=4.0,
                alpha=0.45, solid_capstyle="butt",
                label="phantom inversion (extrapolation only)")
    ax.plot(grid_data, np.full_like(grid_data, -0.006), "|", ms=7, color=TEAL,
            label="confined floor grid")
    ax.plot(grid_wide, np.full_like(grid_wide, -0.013), "|", ms=7, color=SLATE,
            alpha=0.5, label="wide grid $[-1,1]$")
    ax.set_ylim(-0.02, None)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"total variance $w(k)$")
    ax.legend(fontsize=8, loc="upper right")
    save(fig, OUT / "fig_wlq_confine.pdf")


# ---------------------------------------------------------------------------
# Figure 7: the LV deep-put slope knob, and what the var-swap sees.
# ---------------------------------------------------------------------------


def figure_lv() -> None:
    # The a-sensitivity lock's surface: a high-vol two-year single-name where
    # the deep-put region below the last strike vertex is actually reachable.
    xi = np.array([0.70, 0.85, 0.95, 1.00, 1.10, 1.30, 2.20])
    tn = np.array([0.0, 1.0, 2.0])
    theta = 0.16 + 0.30 * (1.0 - xi[None, :]) ** 2 + 0.0 * tn[:, None]
    x_grid = 0.01 * np.arange(221)
    tg = 0.01 * np.arange(201)  # T = 2.0
    surf0 = AffineVarianceSurface(t_nodes=tn, x_nodes=xi, theta=theta)

    slopes = (0.0, 1.5, 5.0)
    cols = (SLATE, TEAL, VIOLET)
    xs = np.linspace(0.25, 1.10, 300)
    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    vols = []
    for a, col in zip(slopes, cols):
        s = surf0.with_left_extrap_a(float(a))
        nu = s.variance(xs, 1.0)
        ax.plot(xs, nu, color=col, lw=1.9,
                label=rf"slope multiplier $a={a:g}$")
        i_t, _ = solve_varswap_source(s, x_grid, tg)
        vols.append(float(np.sqrt(i_t / 2.0)))
    ax.axvline(xi[0], color=PALETTE["ink"], lw=0.8, ls=":")
    ax.annotate("deepest strike vertex", xy=(xi[0] + 0.012, 0.02),
                fontsize=8.5, color=SLATE, rotation=90, va="bottom")
    ax.set_xlabel(r"spot ratio $x$")
    ax.set_ylabel(r"local variance $\nu(x,\,t=1)$")
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "A")
    macro("wlqlvswingbp", "%.0f", 1e4 * (max(vols) - min(vols)))
    ax = axes[1]
    ax.plot(slopes, [100 * v for v in vols], "o-", ms=5, color=TEAL, lw=1.8)
    ax.set_xlabel(r"left-wing slope multiplier $a$")
    ax.set_ylabel("fair var-swap vol at $T=2$ (%)")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.32)
    save(fig, OUT / "fig_wlq_lv.pdf")


# ---------------------------------------------------------------------------
# Appendix D verification: the listings against production.
# ---------------------------------------------------------------------------


def listing_lee_psi(p):
    p = np.asarray(p, dtype=float)
    with np.errstate(divide="ignore"):
        return 2.0 - 4.0 / (np.sqrt(1.0 + 1.0 / p) + 1.0)


def listing_lee_slopes(a_l, a_r):
    beta_l = float(listing_lee_psi(1.0 / a_l)) if a_l > 0.0 else 0.0
    if a_r >= 1.0:
        beta_r = 2.0
    elif a_r > 0.0:
        beta_r = float(listing_lee_psi(1.0 / a_r - 1.0))
    else:
        beta_r = 0.0
    return beta_l, beta_r


def verify_listings() -> None:
    from volfit.models.lqd.basis import endpoint_scales
    lqd = calibrate_slice(K_QUOTES, W_QUOTES, T, n_order=6,
                          reg_lambda=1e-6).slice
    d_psi = float(np.max(np.abs(listing_lee_psi(np.linspace(1e-4, 50, 999))
                                - lee_psi(np.linspace(1e-4, 50, 999)))))
    a_l, a_r = endpoint_scales(lqd.params)
    d_sl = float(np.max(np.abs(np.array(listing_lee_slopes(a_l, a_r))
                               - np.array(lee_slopes(lqd.params)))))
    # Naive-vs-stable psi: the cancellation at extreme p.
    p_big = 1e16
    naive = 2.0 - 4.0 * (np.sqrt(p_big * p_big + p_big) - p_big)
    macro("wlqnaivepsi", "%.1f", naive)
    macro("wlqstablepsi", "%.1f", float(lee_psi(p_big)))
    sci_macro("wlqrefagree", max(d_psi, d_sl, 1e-17))


# ---------------------------------------------------------------------------


def main() -> None:
    figure_hero()
    print("hero done")
    figure_ceiling()
    print("ceiling done")
    figure_extrap()
    print("extrap done")
    figure_limit()
    print("limit done")
    figure_hinge()
    print("hinge done")
    figure_confine()
    print("confine done")
    figure_lv()
    print("lv done")
    verify_listings()

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("wlqgencommit", "%s", commit)
    macro("wlqgendate", "%s", date.today().isoformat())

    (OUT / "wings_lastquote_tables.tex").write_text("\n".join(MACROS) + "\n",
                                                    encoding="utf-8")
    (OUT / "wings_lastquote_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
