"""Figure suite for the computed-trust edition of Note 15 (observation filter).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_kalman_trust.py

Every gain, covariance and clock number is produced by PRODUCTION machinery
(``volfit.calib.observation_filter``, ``volfit.calib.observation_measurement``,
``volfit.calib.intraday_time``, the LQD calibrator); every backtest number is
read from the STORED artifacts under ``backend/backtest/results`` (the merged
v1/v2 sweeps and the 0DTE ``intraday_filter`` campaign) — nothing is re-run.

Outputs, written next to this script:

* ``fig_ktr_case.pdf``     -- the case file through the production update:
                              computed gains, posterior on the segment;
* ``fig_ktr_contra.pdf``   -- the r-anatomy: a growing 2-strike contradiction
                              inflates rho and R_curv, the gain falls;
* ``fig_ktr_units.pdf``    -- the units contract (R vs stated noise) and the
                              eigen-clamp on sparse chains;
* ``fig_ktr_clock.pdf``    -- the session clock: accrued variance-days over
                              the July-4th week + stored cadence calibration;
* ``fig_ktr_offdiag.pdf``  -- matrix trust: a junk curvature innovation drags
                              the level through off-diagonal gains;
* ``fig_ktr_backtest.pdf`` -- stored v1 sweep: zeta calibration + error bars;
* ``fig_ktr_active.pdf``   -- stored v2 sweep: active vs overlay vs raw;
* ``kalman_trust_tables.tex`` / ``kalman_trust_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))
RESULTS = REPO / "backend" / "backtest" / "results"

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from volfit.calib.intraday_time import intraday_variance_days  # noqa: E402
from volfit.calib.observation_filter import (  # noqa: E402
    build_filter_prior,
    kalman_update,
    prediction_prior_residual,
    process_noise,
)
from volfit.calib.observation_measurement import (  # noqa: E402
    covariance_from_information,
    handle_jacobian_fd,
    information_matrix,
    measurement_from_jacobian,
)
from volfit.models.lqd.atm import atm_handles  # noqa: E402
from volfit.models.lqd.basis import LQDParams  # noqa: E402
from volfit.models.lqd.calibrate import OPT_N_POINTS, calibrate_slice  # noqa: E402
from volfit.models.lqd.quadrature import build_slice  # noqa: E402

setup()
TEAL, RUST, AMBER, SLATE, VIOLET = (PALETTE["teal"], PALETTE["rust"],
                                    PALETTE["amber"], PALETTE["muted"],
                                    PALETTE["violet"])
HANDLE_LABELS = ("ATM level", "ATM skew", "ATM curvature")
REGIMES = (("spike_aug2024", "spike", "Aug 2024\nspike"),
           ("high_oct2022", "high", "Oct 2022\nhigh-vol"),
           ("low_jul2023", "low", "Jul 2023\nlow-vol"))
BUCKET = ">30d"

MACROS: list[str] = ["% Auto-generated by gen_kalman_trust.py — do not edit."]
NUMBERS: dict = {}

#: Recorded in FINDINGS_observation_filter.md / the F10+session-clock commit
#: messages and NOT reproducible from the merged artifacts (the F1 incident ran
#: pre-fix; the EEM/EFA post-fix cells come from the Phase-5 single-pair run).
FINDINGS = {
    "ktrblowupminpts": "3", "ktrblowupmaxpts": "28",
    "ktreempost": "4.5", "ktreemmeas": "8.1", "ktreemzeta": "0.14",
    "ktrefazeta": "0.26",
    "ktrsglshockwinbefore": "0.42", "ktrsglshockwinafter": "1.00",
    "ktrsglzetabefore": "3.8", "ktrsglzetaafter": "0.8",
}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def sci_macro(name: str, value: float) -> None:
    v = max(abs(value), 1e-17)
    e = int(np.floor(np.log10(v)))
    MACROS.append(r"\newcommand{\%s}{\ensuremath{%.1f\times10^{%d}}}"
                  % (name, v / 10.0**e, e))
    NUMBERS[name] = float(value)


# ---------------------------------------------------------------------------
# Shared synthetic chain (the case-file market): a smooth quadratic smile.
# ---------------------------------------------------------------------------
TAU = 0.5
K21 = np.linspace(-0.25, 0.25, 21)
NOISE = 0.001  # 10 bp stated per-quote noise


def base_sigma(k):
    k = np.asarray(k, dtype=float)
    return 0.20 - 0.35 * k + 0.6 * k * k


def fit_measurement(k, w, noise_scale, n_order=6, reg_lambda=1e-6):
    """Production fit -> production Jacobian-route measurement (z, R)."""
    sd: dict = {}
    fit = calibrate_slice(k, w, TAU, n_order=n_order, reg_lambda=reg_lambda,
                          solver_diag=sd)
    h = atm_handles(fit.slice, TAU)
    z = np.array([h.sigma0, h.skew, h.curvature])

    def handle_fn(theta):
        s = build_slice(LQDParams.from_vector(theta), n_points=OPT_N_POINTS)
        hh = atm_handles(s, TAU)
        return np.array([hh.sigma0, hh.skew, hh.curvature])

    g = handle_jacobian_fd(handle_fn, sd["theta"])
    meas = measurement_from_jacobian(
        z, sd["jac"], g, sd["residual"], sd["n_fit_rows"], sd["n_quotes"],
        noise_scale=noise_scale,
    )
    return meas, sd, g


# ---------------------------------------------------------------------------
# Figure 1: the case file through the production update.
# ---------------------------------------------------------------------------


def figure_case() -> None:
    m_pred = np.array([0.20, -0.35, 0.10])
    sd_pred = np.array([0.0030, 0.08, 0.05])
    z = np.array([0.204, -0.37, 0.55])
    sd_obs = np.array([0.0015, 0.05, 0.30])
    upd = kalman_update(m_pred, np.diag(sd_pred**2), z, np.diag(sd_obs**2))
    gains = np.diag(upd.gain)
    macro("ktrgainlevel", "%.2f", gains[0])
    macro("ktrgainskew", "%.2f", gains[1])
    macro("ktrgaincurv", "%.3f", gains[2])
    macro("ktrpostlevel", "%.2f", 100 * upd.mean[0])
    macro("ktrpostcurv", "%.3f", upd.mean[2])

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=WIDE)
    y = np.arange(3)[::-1]
    ax_a.barh(y, gains, height=0.55, color=[TEAL, TEAL, RUST])
    for yi, g in zip(y, gains):
        ax_a.text(g + 0.02, yi, f"{g:.2f}" if g > 0.1 else f"{g:.3f}",
                  va="center", fontsize=10, color=PALETTE["ink"])
    ax_a.set_yticks(y, HANDLE_LABELS)
    ax_a.set_xlim(0.0, 1.08)
    ax_a.set_xlabel(r"computed gain $K=p/(p+r)$")
    label_panel(ax_a, "A")

    ax_b.hlines(y, 0.0, 1.0, color=PALETTE["grid"], lw=2.0, zorder=1)
    ax_b.scatter(np.zeros(3), y, s=55, color=SLATE, zorder=3,
                 label=r"prediction $m^-$")
    ax_b.scatter(np.ones(3), y, s=55, color=RUST, marker="s", zorder=3,
                 label=r"observation $z$")
    ax_b.scatter(gains, y, s=80, color=TEAL, marker="D", zorder=4,
                 label=r"posterior $m^+$")
    ax_b.annotate("the stale-strike kink is\naccepted at 3%, not vetoed",
                  xy=(gains[2], y[2]), xytext=(0.30, y[2] - 0.45),
                  arrowprops={"arrowstyle": "->", "color": SLATE, "lw": 1.1},
                  fontsize=9.3, color=SLATE)
    ax_b.set_yticks(y, HANDLE_LABELS)
    ax_b.set_xlim(-0.08, 1.10)
    ax_b.set_ylim(-0.85, 2.55)
    ax_b.set_xlabel(r"position between $m^-$ (0) and $z$ (1)")
    ax_b.legend(loc="upper center", bbox_to_anchor=(0.58, 1.20), ncol=3,
                fontsize=8.6)
    label_panel(ax_b, "B")
    fig.subplots_adjust(wspace=0.42)
    save(fig, OUT / "fig_ktr_case.pdf")


# ---------------------------------------------------------------------------
# Figure 2: the r-anatomy — a growing contradiction turns the gain down.
# ---------------------------------------------------------------------------


def figure_contra() -> None:
    i, j = 12, 13  # adjacent strikes just right of the money
    eps_grid = np.linspace(0.0, 0.03, 13)
    q_diag, _ = process_noise(1.0, 0.0, vol_bp_sqrt_day=30.0)
    m_pred = None
    rows = []
    for eps in eps_grid:
        sig = base_sigma(K21).copy()
        sig[i] += eps
        sig[j] -= eps
        meas, _, _ = fit_measurement(K21, sig * sig * TAU, NOISE)
        if m_pred is None:  # the clean fit is the transported prediction
            m_pred = meas.handles.copy()
        p_diag = q_diag + np.array([0.003, 0.08, 0.5]) ** 2
        upd = kalman_update(m_pred, np.diag(p_diag), meas.handles,
                            np.diag(np.diag(meas.cov)))
        rows.append((meas.breakdown["rho"], np.sqrt(np.diag(meas.cov)),
                     np.diag(upd.gain)))
    rho = np.array([r[0] for r in rows])
    r_std = np.array([r[1] for r in rows])
    gains = np.array([r[2] for r in rows])
    macro("ktrcontrarho", "%.0f", rho[-1])
    macro("ktrcontragainclean", "%.2f", gains[0, 2])
    macro("ktrcontragainkink", "%.2f", gains[-1, 2])
    macro("ktrcontragainatm", "%.2f", gains[-1, 0])

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    x = 100 * eps_grid
    ax.plot(x, r_std[:, 2], color=RUST, lw=1.9,
            label=r"$\sqrt{R_{\kappa\kappa}}$ (curvature)")
    ax.set_xlabel("contradiction size (vol points)")
    ax.set_ylabel("stated curvature noise", color=RUST)
    ax2 = ax.twinx()
    ax2.plot(x, rho, color=SLATE, lw=1.8, ls="--")
    ax2.set_ylabel(r"inflation $\rho=\chi^2/(m-d)$", color=SLATE)
    ax2.grid(False)
    ax2.spines["top"].set_visible(False)
    ax.legend(loc="upper left")
    label_panel(ax, "A")
    ax = axes[1]
    for h, c in ((0, TEAL), (1, AMBER), (2, RUST)):
        ax.plot(x, gains[:, h], color=c, lw=1.9, label=HANDLE_LABELS[h])
    callout(ax, "nobody turned this dial down:\nthe misfit did",
            xy=(2.4, gains[-3, 2] + 0.015), xytext=(1.02, 0.44))
    ax.set_xlabel("contradiction size (vol points)")
    ax.set_ylabel("computed gain $K$")
    ax.set_ylim(-0.03, 1.05)
    ax.legend(loc="lower left", fontsize=8.7)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.5)
    save(fig, OUT / "fig_ktr_contra.pdf")


# ---------------------------------------------------------------------------
# Figure 3: the units contract and the eigen-clamp.
# ---------------------------------------------------------------------------


def figure_units() -> None:
    w = base_sigma(K21) ** 2 * TAU
    noises = np.geomspace(5e-4, 1e-2, 9)
    atm_std = [float(np.sqrt(fit_measurement(K21, w, s)[0].cov[0, 0]))
               for s in noises]
    macro("ktrunitslope", "%.2f",
          float(np.polyfit(np.log(noises), np.log(atm_std), 1)[0]))

    counts = (21, 13, 9, 7, 5)
    curv_std, clamped = [], []
    for n in counts:
        kq = np.linspace(-0.25, 0.25, n)
        meas, sd, g = fit_measurement(kq, base_sigma(kq) ** 2 * TAU, NOISE)
        curv_std.append(float(np.sqrt(meas.cov[2, 2])))
        # re-derive the clamp count from the production algebra
        jac2 = sd["jac"].copy()
        jac2[: sd["n_fit_rows"]] /= NOISE
        _, n_cl = covariance_from_information(g, information_matrix(jac2))
        clamped.append(n_cl)
    macro("ktrclampsparse", "%d", clamped[-1])
    # the clamp as the LAST fence: same sparse chain with the intrinsic
    # regularization rows removed (reg 0) — the information is genuinely
    # rank-deficient and the eigen-clamp keeps R finite.
    kq = np.linspace(-0.25, 0.25, counts[-1])
    _, sd0, g0 = fit_measurement(kq, base_sigma(kq) ** 2 * TAU, NOISE,
                                 reg_lambda=0.0)
    jac0 = sd0["jac"].copy()
    jac0[: sd0["n_fit_rows"]] /= NOISE
    _, n_cl0 = covariance_from_information(g0, information_matrix(jac0))
    macro("ktrclampnoreg", "%d", n_cl0)

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.loglog(1e4 * noises, atm_std, "o-", ms=5, color=TEAL, lw=1.8)
    ax.set_xlabel("stated per-quote noise $s_q$ (vol bp)")
    ax.set_ylabel(r"$\sqrt{R_{\sigma\sigma}}$ (ATM)")
    callout(ax, "slope 1: double the stated\nnoise, quadruple the covariance",
            xy=(1e4 * noises[5], atm_std[5]), xytext=(1e4 * noises[0], atm_std[-3]))
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(counts, curv_std, "o-", ms=5, color=RUST, lw=1.8)
    for n, cs, cl in zip(counts, curv_std, clamped):
        if cl > 0:
            ax.annotate(f"{cl} clamped", xy=(n, cs), xytext=(n + 0.2, cs * 0.82),
                        fontsize=8.5, color=SLATE)
    ax.set_xlabel("quotes on the chain")
    ax.set_ylabel(r"$\sqrt{R_{\kappa\kappa}}$ (curvature)")
    ax.set_yscale("log")
    ax.invert_xaxis()
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.42)
    save(fig, OUT / "fig_ktr_units.pdf")


# ---------------------------------------------------------------------------
# Figure 4: the session clock — accrual over the July-4th week + calibration.
# ---------------------------------------------------------------------------


def _cadence_moves() -> dict[str, float]:
    """Median |dz_ATM| per step type from the stored 0DTE measurement tables."""
    steps: dict[str, list[float]] = {"intraday": [], "overnight": [], "weekend": []}
    for tk in ("SPY", "QQQ", "IWM"):
        files = sorted(RESULTS.glob(f"intraday_filter/{tk}_*.json"))
        by_exp: dict[str, list[tuple[float, float]]] = {}
        for f in files:
            for row in json.loads(f.read_text()):
                ts = datetime.fromisoformat(row["ts"]).timestamp()
                by_exp.setdefault(row["expiry"], []).append(
                    (ts, float(row["z"][0])))
        for series in by_exp.values():
            series.sort()
            for (t0, z0), (t1, z1) in zip(series, series[1:]):
                gap_h = (t1 - t0) / 3600.0
                if gap_h <= 0:
                    continue
                if gap_h < 8:
                    steps["intraday"].append(abs(z1 - z0))
                elif gap_h < 40:
                    steps["overnight"].append(abs(z1 - z0))
                else:
                    steps["weekend"].append(abs(z1 - z0))
    return {k: 1e4 * float(np.median(v)) for k, v in steps.items() if v}


def figure_clock() -> None:
    moves = _cadence_moves()
    macro("ktrmoveintra", "%.0f", moves["intraday"])
    macro("ktrmoveovernight", "%.0f", moves["overnight"])
    macro("ktrmoveweekend", "%.0f", moves["weekend"])

    t0 = datetime(2026, 7, 1, 4, 0)  # Wed 00:00 ET as naive UTC
    grid = [t0 + timedelta(minutes=30 * i) for i in range(7 * 48 + 1)]
    cal = [(t - t0).total_seconds() / 86400.0 for t in grid]
    ses = [intraday_variance_days(t0, t, 0.60, 0.0) for t in grid]

    sweep = json.loads((RESULTS / "intraday_filter" / "sweep.json").read_text())
    cal_rows = {(r["process_bp"], r["step"]): r for r in sweep
                if r["clock"] == "calendar"}
    bps = sorted({bp for bp, _ in cal_rows})
    best_bp = min(bps, key=lambda bp: abs(cal_rows[(bp, "intraday")]["zeta_std"][0] - 1.0))
    ses_rows = {r["step"]: r for r in sweep
                if r["clock"] == "session60w0" and r["process_bp"] == 90.0}
    steps = ("intraday", "overnight", "weekend")
    z_cal = [cal_rows[(best_bp, s)]["zeta_std"][0] for s in steps]
    z_ses = [ses_rows[s]["zeta_std"][0] for s in steps]
    macro("ktrcalbestq", "%.0f", best_bp)
    for s, zc, zs in zip(("intra", "overnight", "weekend"), z_cal, z_ses):
        macro("ktrzcal" + s, "%.2f", zc)
        macro("ktrzses" + s, "%.2f", zs)

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.3, 1.0]})
    ax = axes[0]
    ax.plot(cal, cal, color=SLATE, lw=1.7, ls="--", label="calendar clock")
    ax.plot(cal, ses, color=TEAL, lw=1.9,
            label="session clock (share 0.60, closed days 0)")
    ax.axvspan(1.0 + 16.0 / 24.0, 5.0 + 9.5 / 24.0, color="black", alpha=0.05)
    ax.annotate("Jul 3 holiday + weekend:\nthe market is closed,\nvariance stops accruing",
                xy=(3.6, 0.55), fontsize=8.8, color=SLATE, ha="center")
    ax.set_xlabel("days since Wed 00:00 ET (2026-07-01)")
    ax.set_ylabel("accrued variance-days")
    ax.legend(loc="upper left", fontsize=8.7)
    label_panel(ax, "A")
    ax = axes[1]
    x = np.arange(3)
    ax.bar(x - 0.19, z_cal, width=0.36, color=SLATE,
           label=f"calendar, best $q$ ({best_bp:.0f} bp)")
    ax.bar(x + 0.19, z_ses, width=0.36, color=TEAL,
           label="session, $q=90$ bp")
    ax.axhline(1.0, color=AMBER, lw=1.4, ls="--")
    ax.text(-0.38, 1.045, "calibrated", color=AMBER, fontsize=8.2)
    ax.set_xticks(x, ("30-min", "overnight", "weekend"))
    ax.set_ylabel(r"$\zeta$ std (ATM)")
    ax.set_ylim(0, 1.34)
    ax.legend(loc="upper right", fontsize=8.0)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_ktr_clock.pdf")


# ---------------------------------------------------------------------------
# Figure 5: matrix trust — the off-diagonal drag, in vitro.
# ---------------------------------------------------------------------------


def figure_offdiag() -> None:
    sd_p = np.array([0.0030, 0.08, 0.05])
    sd_r = np.array([0.0015, 0.05, 0.30])
    m = np.array([0.20, -0.35, 0.10])
    z = m + np.array([0.0, 0.0, 0.45])  # junk curvature innovation only
    cs = np.linspace(0.0, 0.95, 40)
    err_full, err_diag = [], []
    for c in cs:
        corr = np.eye(3)
        corr[0, 2] = corr[2, 0] = c
        R = corr * np.outer(sd_r, sd_r)
        upd_f = kalman_update(m, np.diag(sd_p**2), z, R)
        upd_d = kalman_update(m, np.diag(sd_p**2), z, np.diag(sd_r**2))
        err_full.append(1e4 * abs(upd_f.mean[0] - m[0]))
        err_diag.append(1e4 * abs(upd_d.mean[0] - m[0]))
    macro("ktroffdiagdrag", "%.0f", err_full[-1])

    fig, ax = plt.subplots(figsize=(6.9, 3.8))
    ax.plot(cs, err_full, color=RUST, lw=2.0,
            label="full-covariance update")
    ax.plot(cs, err_diag, color=TEAL, lw=2.0,
            label="diagonal update (production)")
    callout(ax, "a junk curvature innovation drags the\nATM level through "
                "$K_{13}$ — the level was\nnever observed to move",
            xy=(0.86, err_full[-5]), xytext=(0.05, 0.62 * max(err_full)))
    ax.set_xlabel("level–curvature correlation stated in $R$")
    ax.set_ylabel("ATM posterior error (vol bp)")
    ax.legend(loc="upper left")
    save(fig, OUT / "fig_ktr_offdiag.pdf")


# ---------------------------------------------------------------------------
# Figures 6-7: the stored sweeps (never re-run).
# ---------------------------------------------------------------------------


def _rows(stem: str, v2: bool = False) -> list[dict]:
    suffix = "_observation_filter_v2_merged.json" if v2 else "_observation_filter_merged.json"
    return json.loads((RESULTS / f"{stem}{suffix}").read_text())["summary"]


def _cell(rows, scenario, cov, bp, bucket, mode=None):
    for r in rows:
        if (r["scenario"] == scenario and r["cov_mode"] == cov
                and float(r["process_bp"]) == bp and r["bucket"] == bucket
                and (mode is None or r.get("mode") == mode)):
            return r
    raise KeyError((scenario, cov, bp, bucket, mode))


def figure_backtest() -> None:
    z10, z30, post, meas, pred = [], [], [], [], []
    total = 0
    shock_ratios = []
    for stem, suf, _ in REGIMES:
        rows = _rows(stem)
        total += sum(r["n"] for r in rows)
        r10 = _cell(rows, "thinned", "jacobian", 10.0, BUCKET)
        r30 = _cell(rows, "thinned", "jacobian", 30.0, BUCKET)
        z10.append(r10["zeta_std"][0]); z30.append(r30["zeta_std"][0])
        post.append(1e4 * r30["med_err_post"][0])
        meas.append(1e4 * r30["med_err_meas"][0])
        pred.append(1e4 * r30["med_err_pred"][0])
        macro("ktrzstd%sten" % suf, "%.2f", r10["zeta_std"][0])
        macro("ktrzstd%sthirty" % suf, "%.2f", r30["zeta_std"][0])
        macro("ktrerrpost%s" % suf, "%.1f", 1e4 * r30["med_err_post"][0])
        macro("ktrerrmeas%s" % suf, "%.1f", 1e4 * r30["med_err_meas"][0])
        macro("ktrerrpred%s" % suf, "%.0f", 1e4 * r30["med_err_pred"][0])
        macro("ktrwin%s" % suf, "%.2f", r30["win_vs_meas"][0])
        cj = _cell(rows, "contradiction", "jacobian", 30.0, BUCKET)
        cf = _cell(rows, "contradiction", "factors", 30.0, BUCKET)
        macro("ktrcontrajac%s" % suf, "%.1f", 1e4 * cj["med_err_post"][0])
        macro("ktrcontrafac%s" % suf, "%.1f", 1e4 * cf["med_err_post"][0])
        sj = _cell(rows, "shock", "jacobian", 30.0, BUCKET)
        sf = _cell(rows, "shock", "factors", 30.0, BUCKET)
        macro("ktrshockjac%s" % suf, "%.1f", 1e4 * sj["med_err_post"][0])
        macro("ktrshockfac%s" % suf, "%.1f", 1e4 * sf["med_err_post"][0])
        for cov in ("jacobian", "factors"):
            s10 = _cell(rows, "shock", cov, 10.0, BUCKET)
            s30 = _cell(rows, "shock", cov, 30.0, BUCKET)
            shock_ratios.append(s10["med_err_post"][0] / s30["med_err_post"][0])
    macro("ktrstepstotal", "%s", f"{total:,}".replace(",", r"\,"))
    macro("ktrshockimprovemin", "%.0f", min(shock_ratios))
    macro("ktrshockimprovemax", "%.0f", max(shock_ratios))

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=WIDE)
    x = np.arange(3)
    labels = [lab for _, _, lab in REGIMES]
    ax_a.bar(x - 0.19, z10, width=0.36, color=SLATE,
             label=r"clock $10$ bp$/\sqrt{\mathrm{day}}$ (design)")
    ax_a.bar(x + 0.19, z30, width=0.36, color=TEAL,
             label=r"clock $30$ bp$/\sqrt{\mathrm{day}}$ (shipped)")
    ax_a.axhline(1.0, color=AMBER, lw=1.4, ls="--", zorder=1)
    ax_a.text(1.5, 1.09, "calibrated", color=AMBER, fontsize=8.6, ha="center")
    ax_a.set_xticks(x, labels)
    ax_a.set_ylabel(r"$\zeta$ std (ATM, thinned, $>30$d)")
    ax_a.legend(fontsize=8.4, loc="upper right")
    label_panel(ax_a, "A")
    ax_b.bar(x - 0.25, pred, width=0.24, color=SLATE, label="prediction (gain 0)")
    ax_b.bar(x, meas, width=0.24, color=RUST, label="raw measurement")
    ax_b.bar(x + 0.25, post, width=0.24, color=TEAL, label="filter posterior")
    ax_b.set_xticks(x, labels)
    ax_b.set_ylabel("median held-out ATM error (bp)")
    ax_b.legend(fontsize=8.4)
    label_panel(ax_b, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_ktr_backtest.pdf")


def figure_active() -> None:
    act_t, ovl_t, raw_t = [], [], []
    shock_p7, shock_ovl, shock_act = [], [], []
    total = 0
    zetas = []
    for stem, suf, _ in REGIMES:
        v1 = _rows(stem)
        v2 = _rows(stem, v2=True)
        total += sum(r["n"] for r in v2)
        at = _cell(v2, "thinned", "jacobian", 30.0, BUCKET, mode="active")
        ot = _cell(v2, "thinned", "jacobian", 30.0, BUCKET, mode="overlay")
        act_t.append(1e4 * at["med_err_post"][0])
        ovl_t.append(1e4 * ot["med_err_post"][0])
        raw_t.append(1e4 * ot["med_err_meas"][0])
        macro("ktractthin%s" % suf, "%.1f", 1e4 * at["med_err_post"][0])
        ac = _cell(v2, "contradiction", "jacobian", 30.0, BUCKET, mode="active")
        oc = _cell(v2, "contradiction", "jacobian", 30.0, BUCKET, mode="overlay")
        macro("ktractcontra%s" % suf, "%.1f", 1e4 * ac["med_err_post"][0])
        macro("ktrovlcontra%s" % suf, "%.1f", 1e4 * oc["med_err_post"][0])
        macro("ktrrawcontra%s" % suf, "%.1f", 1e4 * oc["med_err_meas"][0])
        zetas += [at["zeta_std"][0], ac["zeta_std"][0]]
        s7 = _cell(v1, "shock", "jacobian", 30.0, BUCKET)
        so = _cell(v2, "shock", "jacobian", 30.0, BUCKET, mode="overlay")
        sa = _cell(v2, "shock", "jacobian", 30.0, BUCKET, mode="active")
        shock_p7.append(1e4 * s7["med_err_post"][0])
        shock_ovl.append(1e4 * so["med_err_post"][0])
        shock_act.append(1e4 * sa["med_err_post"][0])
        macro("ktrovlshock%s" % suf, "%.1f", 1e4 * so["med_err_post"][0])
        macro("ktractshock%s" % suf, "%.1f", 1e4 * sa["med_err_post"][0])
    macro("ktrstepsvtwo", "%s", f"{total:,}".replace(",", r"\,"))
    macro("ktractzetamin", "%.1f", min(zetas))
    macro("ktractzetamax", "%.1f", max(zetas))

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=WIDE)
    x = np.arange(3)
    labels = [lab for _, _, lab in REGIMES]
    ax_a.bar(x - 0.25, raw_t, width=0.24, color=RUST, label="raw fit")
    ax_a.bar(x, ovl_t, width=0.24, color=SLATE, label="overlay posterior")
    ax_a.bar(x + 0.25, act_t, width=0.24, color=TEAL, label="active MAP")
    ax_a.set_xticks(x, labels)
    ax_a.set_ylabel("median ATM error, thinned (bp)")
    ax_a.set_ylim(0, 1.30 * max(ovl_t))
    ax_a.legend(fontsize=8.4, loc="upper right")
    label_panel(ax_a, "A")
    ax_b.bar(x - 0.25, shock_p7, width=0.24, color=SLATE,
             label="overlay, no gate (tuning sweep)")
    ax_b.bar(x, shock_ovl, width=0.24, color=TEAL,
             label="overlay + adaptive gate (v2)")
    ax_b.bar(x + 0.25, shock_act, width=0.24, color=VIOLET,
             label="active MAP (v2)")
    ax_b.set_xticks(x, labels)
    ax_b.set_ylabel("median ATM shock lag (bp)")
    ax_b.set_ylim(0, 1.38 * max(shock_p7))
    ax_b.legend(fontsize=8.2, loc="upper right")
    label_panel(ax_b, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_ktr_active.pdf")


# ---------------------------------------------------------------------------
# Appendix verification: the reference listings against production.
# ---------------------------------------------------------------------------


def kalman_update_ref(mean_pred, cov_pred, obs, obs_cov, H=None):
    m = np.asarray(mean_pred, dtype=float)
    P = np.asarray(cov_pred, dtype=float)
    z = np.asarray(obs, dtype=float)
    R = np.asarray(obs_cov, dtype=float)
    H = np.eye(m.size) if H is None else np.asarray(H, dtype=float)
    innovation = z - H @ m
    S = H @ P @ H.T + R
    K = np.linalg.solve(S.T, (P @ H.T).T).T
    out_mean = m + K @ innovation
    I_KH = np.eye(m.size) - K @ H
    out_cov = I_KH @ P @ I_KH.T + K @ R @ K.T
    return out_mean, 0.5 * (out_cov + out_cov.T), innovation, S, K


def verify_listings() -> None:
    rng = np.random.default_rng(15)
    a = rng.standard_normal((3, 3))
    b = rng.standard_normal((3, 3))
    P = a @ a.T + 0.5 * np.eye(3)
    R = b @ b.T + 0.5 * np.eye(3)
    m = rng.standard_normal(3)
    z = rng.standard_normal(3)
    ref = kalman_update_ref(m, P, z, R)
    upd = kalman_update(m, P, z, R)
    dev = max(float(np.max(np.abs(r - u))) for r, u in zip(
        ref, (upd.mean, upd.cov, upd.innovation, upd.innovation_cov, upd.gain)))
    # the whitened MAP rows and the lambda identity of build_filter_prior
    rows, jitter = prediction_prior_residual(z, m, P)
    dev = max(dev, float(np.max(np.abs(
        np.linalg.cholesky(P) @ rows - (z - m)))), jitter)
    tgt = build_filter_prior(m, np.diag(P), tau=0.5, quote_noise=0.002)
    lam_ref = 0.002**2 / (np.array([1.0, 2 * 0.06, 0.06**2]) ** 2 * np.diag(P))
    dev = max(dev, float(np.max(np.abs(tgt.active_lambda - lam_ref))))
    sci_macro("ktrrefagree", dev)


# ---------------------------------------------------------------------------


def main() -> None:
    figure_case(); print("case done")
    figure_contra(); print("contra done")
    figure_units(); print("units done")
    figure_clock(); print("clock done")
    figure_offdiag(); print("offdiag done")
    figure_backtest(); print("backtest done")
    figure_active(); print("active done")
    verify_listings()
    for name, value in FINDINGS.items():
        macro(name, "%s", value)

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("ktrgencommit", "%s", commit)
    macro("ktrgendate", "%s", date.today().isoformat())

    (OUT / "kalman_trust_tables.tex").write_text("\n".join(MACROS) + "\n",
                                                 encoding="utf-8")
    (OUT / "kalman_trust_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
