"""Figure suite for the messages-not-smoothness rewrite of Note 14 (graph).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_graph_messages.py

Every golden number, transfer curve and case-file posterior is produced by the
PRODUCTION message modules (``volfit.graph.message`` /
``volfit.graph.message_posterior``); the Phase-0 empirical numbers are read
from the STORED design-study artifact
``backend/backtest/results/message_phase0.json`` — nothing is re-run.  The
row-normalized comparator in the dead-informer figure is the spec's REJECTED
operator, implemented locally as the wrong-way reference (production has no
such code path, deliberately).

Outputs, written next to this script:

* ``fig_gm_contract.pdf``  -- the three-expiry contract: means invariant in
                              edge precision, bands not (Invariants 1-2);
* ``fig_gm_accountant.pdf``-- dead-informer zero dilution vs the rejected row
                              form + repeated-path no-double-count;
* ``fig_gm_compete.pdf``   -- competing signals: cancel / outvote / beta-map;
* ``fig_gm_amplitude.pdf`` -- the node-linked anchor's corroboration curve vs
                              the stored measured slopes (0.3% validation);
* ``fig_gm_hops.pdf``      -- multi-hop: the mean pays no toll, the variance
                              accumulates;
* ``fig_gm_calendar.pdf``  -- amplitude shape vs measured relation noise
                              (gap-flat residuals, stored seeds);
* ``fig_gm_sixnode.pdf``   -- the six-node case file under message semantics;
* ``graph_messages_tables.tex`` / ``graph_messages_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))
RESULTS = REPO / "backend" / "backtest" / "results"

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from volfit.graph.message import (  # noqa: E402
    MessageEdge,
    anchor_precisions,
    build_message_operator,
    calendar_beta,
    calendar_message_precision,
    cycle_beta_products,
    expand_calendar_ladder,
    message_edge,
)
from volfit.graph.message_posterior import message_posterior_update  # noqa: E402

setup()
TEAL, RUST, AMBER, SLATE, VIOLET, BLUE = (
    PALETTE["teal"], PALETTE["rust"], PALETTE["amber"], PALETTE["muted"],
    PALETTE["violet"], PALETTE["blue"],
)

MACROS: list[str] = ["% Auto-generated by gen_graph_messages.py — do not edit."]
NUMBERS: dict = {}
CLAMP = 1e9  # "effectively known informer": huge observation precision

#: Recorded verdicts that are historical artifacts of other campaigns
#: (FINDINGS_graph_loo.md 25-asset verdict, FINDINGS_message_phase4.md smoke
#: pair, R3 item-14 closure) — quoted, never re-run.
FINDINGS = {
    "gmspikeskilllo": "7.9", "gmspikeskillhi": "14.2",
    "gmhighskilllo": "3.8", "gmhighskillhi": "7.2",
    "gmcalmskilllo": "0.7", "gmcalmskillhi": "0.8",
    "gmidiobefore": "1.91", "gmidiobeforetwo": "1.85",
    "gmidioafter": "1.02", "gmidioaftertwo": "1.03",
    "gmsmokemsgfull": "5.8", "gmsmokemsgfullr": "1.9",
    "gmsmokelegfull": "0.7", "gmsmokelegfullr": "0.3",
    "gmsmokemsgzeta": "1.2--1.4", "gmsmokelegzeta": "0.6",
}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def sci_macro(name: str, value: float) -> None:
    v = max(abs(value), 1e-17)
    e = int(np.floor(np.log10(v)))
    MACROS.append(r"\newcommand{\%s}{\ensuremath{%.1f\times10^{%d}}}"
                  % (name, v / 10.0**e, e))
    NUMBERS[name] = float(value)


def solve(nodes, edges, lit, z_lit, r=CLAMP, kappa=None, handle=0):
    """Production operator + posterior for one handle, informers clamped."""
    op = build_message_operator(nodes, edges, handle=handle)
    obs = np.array([nodes.index(n) for n in lit])
    return op, message_posterior_update(
        op, obs, np.asarray(z_lit, dtype=float),
        np.full(obs.size, float(r)), anchor_precision=kappa,
    )


# ---------------------------------------------------------------------------
# Figure 1: the three-expiry contract (spec §8.2 / golden 21.1).
# ---------------------------------------------------------------------------


def figure_contract() -> None:
    nodes = ["3M", "6M", "1Y"]
    t = {"3M": 0.25, "6M": 0.5, "1Y": 1.0}
    p_grid = np.geomspace(1e2, 1e5, 25)
    means, sds = [], []
    for p in p_grid:
        edges = [
            MessageEdge("3M", "6M", p, (calendar_beta(0.25, 0.5),) * 3, "calendar"),
            MessageEdge("6M", "1Y", p, (calendar_beta(0.5, 1.0),) * 3, "calendar"),
        ]
        _, post = solve(nodes, edges, ["6M"], [1.0])
        means.append([post.mean[0], post.mean[2]])
        sds.append(np.sqrt([post.marginal_variance[0], post.marginal_variance[2]]))
    means = np.array(means)
    sds = np.array(sds)
    macro("gmthreem", "%.2f", means[-1, 0])
    macro("gmoney", "%.2f", means[-1, 1])

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.semilogx(p_grid, means[:, 0], color=TEAL, lw=2.0,
                label=r"$\widehat z_{3M}$ ($\beta=2$)")
    ax.semilogx(p_grid, means[:, 1], color=AMBER, lw=2.0,
                label=r"$\widehat z_{1Y}$ ($\beta=1/2$)")
    ax.set_ylim(0, 2.4)
    ax.set_xlabel("calendar edge precision $p$ (all edges)")
    ax.set_ylabel("posterior innovation (vol pts)")
    callout(ax, "the contract: amplitude is\nnot a function of confidence",
            xy=(3e3, 2.02), xytext=(2.2e2, 1.45))
    ax.legend(loc="center right", fontsize=8.7)
    label_panel(ax, "A")
    ax = axes[1]
    ax.loglog(p_grid, sds[:, 0], color=TEAL, lw=2.0, label="3M posterior sd")
    ax.loglog(p_grid, sds[:, 1], color=AMBER, lw=2.0, label="1Y posterior sd")
    ax.set_xlabel("calendar edge precision $p$ (all edges)")
    ax.set_ylabel("posterior sd (vol units)")
    ax.legend(loc="upper right", fontsize=8.7)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.36)
    save(fig, OUT / "fig_gm_contract.pdf")


# ---------------------------------------------------------------------------
# Figure 2: the accountant — dead informers and repeated paths.
# ---------------------------------------------------------------------------


def _row_form_transfer(p_lit: float, p_dead: float, anchor: float = 1e-6) -> float:
    """The spec's REJECTED row-normalized operator on the dead-informer
    fixture, solved exactly (local reference, not production): receiver R fed
    by lit L and dead D, energy q_R (z_R - (p_lit z_L + p_dead z_D)/q_R)^2
    with q_R = p_lit + p_dead, plus a small anchor on every node."""
    q = p_lit + p_dead
    nodes = ["R", "L", "D"]
    n = 3
    u = np.array([1.0, -p_lit / q, -p_dead / q])
    Q = q * np.outer(u, u) + anchor * np.eye(n)
    r = CLAMP
    Q[1, 1] += r
    b = np.zeros(n)
    b[1] = r * 1.0
    return float(np.linalg.solve(Q, b)[0])


def figure_accountant() -> None:
    ratios = np.geomspace(0.1, 100.0, 40)
    p_lit = 1.0e3
    pairwise, rowform = [], []
    for ratio in ratios:
        edges = [
            message_edge("R", "L", p_lit, 1.0),
            message_edge("R", "D", p_lit * ratio, 1.0),
        ]
        _, post = solve(["R", "L", "D"], edges, ["L"], [1.0])
        pairwise.append(post.mean[0])
        rowform.append(_row_form_transfer(p_lit, p_lit * ratio))
    i_eq = int(np.argmin(np.abs(ratios - 1.0)))
    macro("gmdeadhalf", "%.2f", rowform[i_eq])
    macro("gmpairflat", "%.2f", min(pairwise))

    # Repeated path: T hears A directly and through M, and A is observed at
    # FINITE precision r = p (the golden fixture); naive accounting treats the
    # two routes as independent messages with the §12 effective precisions.
    p = 1.0e3
    edges = [
        message_edge("T", "A", p, 1.0),
        message_edge("M", "A", p, 1.0),
        message_edge("T", "M", p, 1.0),
    ]
    _, post = solve(["T", "A", "M"], edges, ["A"], [1.0], r=p)
    var_global = float(post.marginal_variance[0])
    v_a = 1.0 / p                       # source posterior variance at r = p
    var_direct = v_a + 1.0 / p          # §12 effective message variance
    var_path = v_a + 1.0 / p + 1.0 / p  # two relation legs
    var_naive = 1.0 / (1.0 / var_direct + 1.0 / var_path)
    macro("gmrepeatvar", "%.2f", var_global * p)
    macro("gmnaivevar", "%.2f", var_naive * p)
    macro("gmrepeatratio", "%.2f", var_global / var_naive)

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.25, 1.0]})
    ax = axes[0]
    ax.semilogx(ratios, pairwise, color=TEAL, lw=2.2,
                label="pairwise factors (production)")
    ax.semilogx(ratios, rowform, color=RUST, lw=2.0, ls="--",
                label="row-normalized alternative")
    ax.set_ylim(-0.05, 1.15)
    ax.set_xlabel(r"dead informer's configured precision $p_{\mathrm{dead}}/p_{\mathrm{lit}}$")
    ax.set_ylabel(r"receiver transfer $\widehat z_R / z_L$")
    callout(ax, "a dead informer dilutes the row\nform toward zero; the pairwise\nfactor marginalizes it away exactly",
            xy=(20.0, rowform[-8] + 0.03), xytext=(0.14, 0.36))
    ax.legend(loc="lower left", fontsize=8.7)
    label_panel(ax, "A")
    ax = axes[1]
    bars = [1e3 * var_global, 1e3 * var_naive]
    ax.bar([0, 1], bars, width=0.55, color=[TEAL, RUST])
    ax.set_xticks([0, 1], ["global solve\n(production)", "naive message\naccounting"])
    ax.set_ylabel(r"posterior variance at T ($\times p^{-1}$)")
    for i, v in enumerate(bars):
        ax.text(i, v + 0.04, f"{v:.2f}/p", ha="center", fontsize=9.5)
    ax.set_ylim(0, 2.2)
    callout(ax, "two routes, one source: treating\nthem as independent messages\noverstates precision by "
                f"{var_global / var_naive:.0%}$-$1",
            xy=(1.0, bars[1] + 0.06), xytext=(0.02, 1.9))
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_gm_accountant.pdf")


# ---------------------------------------------------------------------------
# Figure 3: competing signals (goldens 21.2 / 21.3 / the +0.75 map).
# ---------------------------------------------------------------------------


def figure_compete() -> None:
    nodes = ["6M", "3M", "1Y"]
    cases = []
    # (a) equal precision, beta one: cancel.
    edges = [message_edge("6M", "3M", 1e3, 1.0),
             message_edge("6M", "1Y", 1e3, 1.0)]
    _, post = solve(nodes, edges, ["3M", "1Y"], [-1.0, 1.0])
    cases.append(("equal $p$, $\\beta=1$", post.mean[0]))
    # (b) 3M at 3p: outvoted.
    edges = [message_edge("6M", "3M", 3e3, 1.0),
             message_edge("6M", "1Y", 1e3, 1.0)]
    _, post = solve(nodes, edges, ["3M", "1Y"], [-1.0, 1.0])
    cases.append(("$p_{3M}=3p$", post.mean[0]))
    # (c) calendar betas map the signals into receiver units first.
    edges = [message_edge("6M", "3M", 1e3, calendar_beta(0.5, 0.25)),
             message_edge("6M", "1Y", 1e3, calendar_beta(0.5, 1.0))]
    _, post = solve(nodes, edges, ["3M", "1Y"], [-1.0, 1.0])
    cases.append((r"$\alpha_T=1$ betas", post.mean[0]))
    macro("gmcompetecancel", "%.2f", cases[0][1])
    macro("gmcompeteout", "%.2f", cases[1][1])
    macro("gmcompetebeta", "%.2f", cases[2][1])

    fig, ax = plt.subplots(figsize=(6.9, 3.6))
    x = np.arange(3)
    vals = [c[1] for c in cases]
    ax.bar(x, vals, width=0.5, color=[SLATE, AMBER, TEAL])
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8)
    ax.set_xticks(x, [c[0] for c in cases])
    ax.set_ylabel(r"$\widehat z_{6M}$ (vol pts)")
    for i, v in enumerate(vals):
        ax.text(i, v + (0.05 if v >= 0 else -0.12), f"{v:+.2f}", ha="center",
                fontsize=10)
    ax.set_ylim(-0.8, 1.1)
    callout(ax, "same raw signals $\\mp1$: the betas map\nthem into 6M units before the vote",
            xy=(1.82, vals[2] + 0.02), xytext=(-0.38, 0.82))
    save(fig, OUT / "fig_gm_compete.pdf")


# ---------------------------------------------------------------------------
# Figure 4 (hero): amplitude as a measured level — the corroboration curve.
# ---------------------------------------------------------------------------


def figure_amplitude() -> None:
    study = json.loads((RESULTS / "message_phase0.json").read_text())
    corr = study["corroboration"]
    rho = corr["indexOnly"]["b"]
    measured = {1: corr["indexOnly"]["b"], 2: corr["combinedEqualWeight"]["b"]}
    macro("gmrhoindex", "%.3f", rho)
    macro("gmrhopeer", "%.3f", corr["peersOnly"]["b"])
    macro("gmtwosource", "%.3f", measured[2])
    macro("gmuplift", "%.0f", 100 * corr["uplift"])
    macro("gmupliftbar", "%.0f", 100 * corr["upliftBar"])
    macro("gmphasen", "%d", corr["indexOnly"]["n"])

    ks = np.arange(1, 7)
    transfer = []
    for k in ks:
        nodes = ["X"] + [f"S{i}" for i in range(k)]
        edges = [message_edge("X", f"S{i}", 1e3, 1.0, "broad_index")
                 for i in range(k)]
        kappa = anchor_precisions(nodes, edges, {"broad_index": rho})
        _, post = solve(nodes, edges, [f"S{i}" for i in range(k)],
                        np.ones(k), kappa=kappa)
        transfer.append(post.mean[0])
    transfer = np.array(transfer)
    pred2 = transfer[1]
    macro("gmpredtwo", "%.3f", pred2)
    macro("gmpredgap", "%.1f", 100 * abs(pred2 - measured[2]) / measured[2])

    fig, ax = plt.subplots(figsize=(6.9, 4.0))
    ax.plot(ks, transfer, "o-", ms=6, color=TEAL, lw=2.0,
            label=r"node-linked anchor (production): $k\rho/(1-\rho+k\rho)$")
    ax.axhline(rho, color=RUST, lw=1.7, ls="--",
               label="edge-linked alternative (constant transfer)")
    ax.scatter([1, 2], [measured[1], measured[2]], s=90, marker="D",
               color=PALETTE["ink"], zorder=6,
               label="measured on stored rows (Phase 0)")
    callout(ax,
            "calibrated on the one-source slope alone,\n"
            f"the anchor predicts {pred2:.3f} for two sources;\n"
            f"measured: {measured[2]:.3f} — zero free parameters",
            xy=(2.02, measured[2]), xytext=(2.6, 0.44))
    ax.set_xlabel("number of equal corroborating lit sources $k$")
    ax.set_ylabel("effective transfer per unit message")
    ax.set_ylim(0.30, 0.85)
    ax.legend(loc="upper left", fontsize=8.6)
    save(fig, OUT / "fig_gm_amplitude.pdf")


# ---------------------------------------------------------------------------
# Figure 5: multi-hop — the mean pays no toll, the variance accumulates.
# ---------------------------------------------------------------------------


def figure_hops() -> None:
    n_hops = 6
    p = 1.0e3
    beta = 1.0
    nodes = [f"N{i}" for i in range(n_hops + 1)]
    edges = [message_edge(f"N{i+1}", f"N{i}", p, beta) for i in range(n_hops)]
    _, post = solve(nodes, edges, ["N0"], [1.0])
    means = post.mean
    sds = np.sqrt(post.marginal_variance)
    hops = np.arange(n_hops + 1)
    predicted_sd = np.sqrt(hops / p)  # §13 accumulation at beta=1, clamped source
    macro("gmhopmean", "%.3f", means[-1])
    macro("gmhopsdgap", "%.4f", float(np.max(np.abs(sds[1:] - predicted_sd[1:]))))

    fig, ax = plt.subplots(figsize=(6.9, 3.8))
    ax.plot(hops, means, "o-", ms=5, color=TEAL, lw=2.0,
            label=r"posterior mean $\widehat z$")
    ax.fill_between(hops, means - 1.96 * sds, means + 1.96 * sds, color=TEAL,
                    alpha=0.14, label=r"95% band ($\pm1.96\,$sd)")
    ax.plot(hops, means + 1.96 * predicted_sd, color=SLATE, lw=1.1, ls=":",
            label=r"§13 accumulation $\sqrt{k/p}$ (exact)")
    ax.plot(hops, means - 1.96 * predicted_sd, color=SLATE, lw=1.1, ls=":")
    callout(ax, "the mean crosses six hops undamped;\nconfidence pays the toll",
            xy=(5.2, means[-1] + 0.005), xytext=(2.7, 0.878))
    ax.set_xlabel("hops from the lit source (chain, $\\beta=1$)")
    ax.set_ylabel("posterior innovation (vol pts)")
    ax.legend(loc="lower left", fontsize=8.6)
    save(fig, OUT / "fig_gm_hops.pdf")


# ---------------------------------------------------------------------------
# Figure 6: the calendar relation — shape vs measured noise.
# ---------------------------------------------------------------------------


def figure_calendar() -> None:
    study = json.loads((RESULTS / "message_phase0.json").read_text())
    cal = study["calendarPrecision"]
    p0, eps = cal["fit"]["p0"], cal["fit"]["epsT"]
    macro("gmpzero", "%.0f", p0)
    macro("gmepst", "%.2f", eps)
    macro("gmtauonem", "%.1f", cal["tau1mVolPts"])
    macro("gmcalpairs", "%d", cal["alphaT1Level"]["n"])
    macro("gmcallevel", "%.2f", cal["alphaT1Level"]["b"])
    sp = cal["shapePreview"]
    macro("gmshaperzero", "%.3f", sp["0.0"]["r2"])
    macro("gmshaperone", "%.3f", sp["1.0"]["r2"])

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    t_recv = np.linspace(0.05, 2.0, 200)
    t_inf = 0.5
    for a, c in ((0.0, SLATE), (0.5, AMBER), (1.0, TEAL)):
        ax.plot(t_recv, (t_inf / t_recv) ** a, color=c, lw=1.9,
                label=fr"$\alpha_T={a}$" + ("  (locked)" if a == 1.0 else ""))
    ax.axvline(t_inf, color=PALETTE["ink"], lw=0.7, ls=":")
    ax.annotate("informer $T=0.5$", xy=(0.56, 1.5), fontsize=8.5, color=SLATE)
    ax.set_xlabel("receiver maturity $T$ (years)")
    ax.set_ylabel(r"calendar amplitude $\beta=(T_j/T_i)^{\alpha_T}$")
    ax.set_ylim(0, 4.2)
    ax.legend(loc="upper right", fontsize=8.6)
    label_panel(ax, "A")

    ax = axes[1]
    buckets = cal["gapBuckets"]
    g = [b["gapSqrtYears"] for b in buckets]
    rms = [b["residRmsVolPts"] for b in buckets]
    ax.plot(g, rms, "o", ms=7, color=PALETTE["ink"], zorder=5,
            label="measured residual RMS (stored rows)")
    gg = np.linspace(0.05, 0.45, 100)
    ax.plot(gg, 100 * np.sqrt((eps + gg) / p0), color=TEAL, lw=1.9,
            label=fr"family fit: $p_0={p0:.0f}$, $\epsilon_T={eps:.2f}$")
    ax.set_xlabel(r"maturity gap $\sqrt{|\Delta T|}$ ($\sqrt{\mathrm{years}}$)")
    ax.set_ylabel("relation noise (vol pts)")
    ax.set_ylim(0, 3.6)
    callout(ax, "nearly gap-flat at the day\nhorizon: $\\epsilon_T$ dominates",
            xy=(0.28, 2.8), xytext=(0.06, 1.0))
    ax.legend(loc="lower right", fontsize=8.4)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_gm_calendar.pdf")


# ---------------------------------------------------------------------------
# Figure 7: the six-node case file under message semantics.
# ---------------------------------------------------------------------------


def figure_sixnode() -> None:
    study = json.loads((RESULTS / "message_phase0.json").read_text())
    rho_idx = study["corroboration"]["indexOnly"]["b"]
    rho_peer = study["corroboration"]["peersOnly"]["b"]
    p_idx = study["crossClassNoise"]["indexToName"]["precisionVolUnits"]
    p_peer = study["crossClassNoise"]["sectorPeer"]["precisionVolUnits"]

    nodes = ["SPX1M", "SPX3M", "SPX6M", "XLK3M", "AAPL3M", "MSFT3M"]
    t = {"SPX1M": 1 / 12, "SPX3M": 0.25, "SPX6M": 0.5}
    edges = list(expand_calendar_ladder(t))
    for e in edges:
        pass
    # rename calendar receivers/informers already correct; add cross relations
    edges += [
        message_edge("XLK3M", "SPX3M", p_idx, 1.0, "broad_index"),
        message_edge("AAPL3M", "SPX3M", p_idx, 1.0, "broad_index"),
        message_edge("MSFT3M", "SPX3M", p_idx, 1.0, "broad_index"),
        message_edge("AAPL3M", "XLK3M", p_peer, 1.0, "sector_etf"),
        message_edge("MSFT3M", "XLK3M", p_peer, 1.0, "sector_etf"),
    ]
    # Lit innovations in VOL units (0.01 = 1 vol point), matching the 1/vol^2
    # precision seeds; the amplitude presets are the learned levels.
    z_lit = [0.01, 0.0055]
    rho = {"calendar": 0.232, "broad_index": rho_idx, "sector_etf": rho_peer,
           "sector_peer": rho_peer, "custom": 1.0}
    kappa = anchor_precisions(nodes, edges, rho)
    op, post = solve(nodes, edges, ["SPX3M", "XLK3M"], z_lit, r=1e6, kappa=kappa)
    q = op.receiver_precision
    desk = {k: 1.0 for k in rho}
    _, post_desk = solve(nodes, edges, ["SPX3M", "XLK3M"], z_lit, r=1e6,
                         kappa=anchor_precisions(nodes, edges, desk))
    macro("gmsixaapl", "%.2f", 100 * post.mean[nodes.index("AAPL3M")])
    macro("gmsixaapldesk", "%.2f", 100 * post_desk.mean[nodes.index("AAPL3M")])
    macro("gmsixspxm", "%.2f", 100 * post.mean[nodes.index("SPX1M")])
    macro("gmsixspxmdesk", "%.2f", 100 * post_desk.mean[nodes.index("SPX1M")])
    macro("gmsixspxsix", "%.2f", 100 * post.mean[nodes.index("SPX6M")])
    body = " \\\\\n".join(
        f"\\texttt{{{n}}} & {'lit' if n in ('SPX3M', 'XLK3M') else 'dark'} & "
        f"${100 * post.mean[i]:+.2f}$ & ${100 * np.sqrt(post.marginal_variance[i]):.2f}$ & "
        f"${100 * post_desk.mean[i]:+.2f}$ & ${q[i]:.0f}$"
        for i, n in enumerate(nodes)
    )
    MACROS.append("\\newcommand{\\gmsixrows}{%s \\\\}" % body)

    pos = {"SPX1M": (0.0, 1.0), "SPX3M": (1.15, 1.0), "SPX6M": (2.3, 1.0),
           "XLK3M": (1.15, 0.0), "AAPL3M": (0.0, -0.9), "MSFT3M": (2.3, -0.9)}
    fig, ax = plt.subplots(figsize=(6.9, 4.4))
    for e in edges:
        x0, y0 = pos[e.informer]
        x1, y1 = pos[e.receiver]
        ax.annotate("", xy=(x1, y1), xytext=(x0, y0),
                    arrowprops={"arrowstyle": "-|>", "color": SLATE,
                                "lw": 0.9 + 0.9 * (e.relation_class == "calendar"),
                                "shrinkA": 24, "shrinkB": 24, "alpha": 0.8})
    for i, n in enumerate(nodes):
        x, y = pos[n]
        lit = n in ("SPX3M", "XLK3M")
        ax.scatter([x], [y], s=1500, color=(RUST if lit else TEAL), alpha=0.14,
                   edgecolors=(RUST if lit else TEAL), linewidths=1.6, zorder=3)
        ax.text(x, y + 0.09, n, ha="center", fontsize=9.5, zorder=5,
                fontweight="bold", color=PALETTE["ink"])
        ax.text(x, y - 0.14,
                f"$\\widehat z={100 * post.mean[i]:+.2f}\\pm"
                f"{100 * np.sqrt(post.marginal_variance[i]):.2f}$",
                ha="center", fontsize=8.4, zorder=5, color=PALETTE["ink"])
    ax.text(0.0, 1.35, "arrows: informer $\\to$ receiver", fontsize=8.6,
            color=SLATE)
    ax.set_xlim(-0.62, 2.92)
    ax.set_ylim(-1.35, 1.55)
    ax.axis("off")
    save(fig, OUT / "fig_gm_sixnode.pdf")


# ---------------------------------------------------------------------------
# Appendix verification: reference listings vs production.
# ---------------------------------------------------------------------------


def listing_operator(nodes, factors):
    n = len(nodes)
    Q = np.zeros((n, n))
    for i, j, p, b in factors:
        u = np.zeros(n)
        u[i] = 1.0
        u[j] = -b
        Q += p * np.outer(u, u)
    return Q


def listing_solve(Q, kappa, obs, d, r):
    Qp = Q + np.diag(kappa)
    b = np.zeros(len(Q))
    Qp[obs, obs] += r
    b[obs] += r * d
    sigma = np.linalg.inv(Qp)
    return sigma @ b, sigma


def verify_listings() -> None:
    nodes = ["A", "B", "C", "D"]
    edges = [message_edge("B", "A", 800.0, 1.3), message_edge("C", "B", 500.0, 0.8),
             message_edge("D", "C", 300.0, 1.1), message_edge("D", "A", 200.0, 0.9)]
    op = build_message_operator(nodes, edges)
    kappa = anchor_precisions(nodes, edges, {"custom": 0.5})
    obs = np.array([0])
    d = np.array([1.0])
    r = np.array([1e6])
    post = message_posterior_update(op, obs, d, r, anchor_precision=kappa)
    Q_ref = listing_operator(nodes, op.factors)
    mean_ref, sigma_ref = listing_solve(Q_ref, kappa, obs, d, r)
    dev = max(
        float(np.max(np.abs(Q_ref - op.q_matrix))),
        float(np.max(np.abs(mean_ref - post.mean))),
        float(np.max(np.abs(np.diag(sigma_ref) - post.marginal_variance))),
    )
    # cycle gauge cross-check: consistent potentials flag nothing, an
    # inconsistent triangle flags its closing edge product.
    good = [message_edge("B", "A", 1.0, 2.0), message_edge("C", "B", 1.0, 3.0),
            message_edge("C", "A", 1.0, 6.0)]
    bad = [message_edge("B", "A", 1.0, 2.0), message_edge("C", "B", 1.0, 3.0),
           message_edge("C", "A", 1.0, 5.0)]
    flags_good = cycle_beta_products(["A", "B", "C"], good)
    flags_bad = cycle_beta_products(["A", "B", "C"], bad)
    macro("gmcycleflags", "%d", len(flags_good))
    macro("gmcyclebad", "%.3f", flags_bad[0].product if flags_bad else float("nan"))
    sci_macro("gmrefagree", dev)


# ---------------------------------------------------------------------------


def main() -> None:
    figure_contract(); print("contract done")
    figure_accountant(); print("accountant done")
    figure_compete(); print("compete done")
    figure_amplitude(); print("amplitude done")
    figure_hops(); print("hops done")
    figure_calendar(); print("calendar done")
    figure_sixnode(); print("sixnode done")
    verify_listings()
    for name, value in FINDINGS.items():
        macro(name, "%s", value)

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("gmgencommit", "%s", commit)
    macro("gmgendate", "%s", date.today().isoformat())

    (OUT / "graph_messages_tables.tex").write_text("\n".join(MACROS) + "\n",
                                                   encoding="utf-8")
    (OUT / "graph_messages_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
