"""Figure suite for the missing-derivative edition of Note 12 (spot-vol).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_ssr_derivative.py

Every transport, delta and repriced smile is produced by PRODUCTION machinery
(``volfit.dynamics.{ssr,transport}``, the Black core, and the affine Dupire
solver); local code only wraps the real SPY curve of the standing export
``tmp/volfit_surfaces_20260718_1324.json`` as callables and differencing.

Outputs, written next to this script:

* ``fig_smd_fan.pdf``     -- the fan of tomorrows: the real SPY smile
                             transported in the three regimes + ATM response;
* ``fig_smd_signs.pdf``   -- the two signs: curve rule (k + h) vs quote rule
                             (k - h) under one up-move;
* ``fig_smd_delta.pdf``   -- the stakes: total smile delta per regime;
* ``fig_smd_exact.pdf``   -- exact sticky-LV (Hagan map) vs the linear
                             transport: wing gap and quadratic error;
* ``fig_smd_reprice.pdf`` -- SSR as an output: realized SSR of the exact
                             frozen-grid Dupire reprice across maturities;
* ``ssr_derivative_tables.tex`` / ``ssr_derivative_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from volfit.core.black import black_call, implied_total_variance  # noqa: E402
from volfit.dynamics.ssr import Regime, shifted_smile  # noqa: E402
from volfit.dynamics.transport import transported_w  # noqa: E402
from volfit.models.localvol import (  # noqa: E402
    AffineVarianceSurface,
    solve_affine_dupire,
)

setup()
TEAL, BLUE, RUST, AMBER, SLATE, VIOLET, GREEN = (
    PALETTE["teal"], PALETTE["blue"], PALETTE["rust"], PALETTE["amber"],
    PALETTE["muted"], PALETTE["violet"], PALETTE["green"],
)

MACROS: list[str] = ["% Auto-generated by gen_ssr_derivative.py — do not edit."]
NUMBERS: dict = {}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def sci_macro(name: str, value: float) -> None:
    v = max(abs(value), 1e-17)
    e = int(np.floor(np.log10(v)))
    m = v / 10.0**e
    MACROS.append(r"\newcommand{\%s}{\ensuremath{%.1f\times10^{%d}}}"
                  % (name, m, e))
    NUMBERS[name] = float(value)


# ---------------------------------------------------------------------------
# The running character: the real SPY 2027-06 smile from the standing export.
# ---------------------------------------------------------------------------

FIXTURE = REPO / "tmp" / "volfit_surfaces_20260718_1324.json"
if not FIXTURE.exists():
    raise FileNotFoundError(
        f"standing reference export not found: {FIXTURE} — regenerate via "
        "the app's surfaces export (see memory: reference-live-fixture)")
_DOC = json.loads(FIXTURE.read_text(encoding="utf-8"))
_SPY = next(tk for tk in _DOC["tickers"] if tk["ticker"] == "SPY")
_NODE = _SPY["nodes"][-1]  # 2027-06-17
K_CURVE = np.array([c["k"] for c in _NODE["curve"]])
IV_CURVE = np.array([c["iv"] for c in _NODE["curve"]])
T = float(_NODE["t"])


def vol_curve(k):
    return np.interp(np.asarray(k, dtype=float), K_CURVE, IV_CURVE)


def w_curve(k):
    return vol_curve(k) ** 2 * T


SKEW = float((vol_curve(0.01) - vol_curve(-0.01)) / 0.02)
MOVE = -0.05
REGIMES = [("sticky moneyness", Regime.STICKY_MONEYNESS, 0.0, TEAL),
           ("sticky strike", Regime.STICKY_STRIKE, 1.0, AMBER),
           ("sticky local vol", Regime.STICKY_LOCAL_VOL, 2.0, RUST)]


# ---------------------------------------------------------------------------
# Figure 1: the fan of tomorrows (real smile, production transport).
# ---------------------------------------------------------------------------


def figure_fan() -> None:
    macro("smdskew", "%.3f", SKEW)
    macro("smdmove", "%d", int(round(100 * MOVE)))
    k = np.linspace(-0.45, 0.40, 300)

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.25, 1.0]})
    ax = axes[0]
    ax.plot(k, 100 * vol_curve(k), color=SLATE, lw=2.2, label="today (SPY, live)")
    for name, reg, ssr, col in REGIMES:
        sig = shifted_smile(k, vol_curve, SKEW, MOVE, regime=reg)
        ax.plot(k, 100 * sig, color=col, ls="--", lw=1.7,
                label=f"{name} ($R={ssr:.0f}$)")
    ax.axvline(0, color=PALETTE["ink"], lw=0.6, alpha=0.4)
    ax.set_xlabel(r"new-forward log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(fontsize=8, loc="upper right")
    label_panel(ax, "A")
    ax = axes[1]
    moves = np.linspace(-0.10, 0.10, 41)
    for name, reg, ssr, col in REGIMES:
        atm = [float(shifted_smile(np.array([0.0]), vol_curve, SKEW,
                                   float(m), regime=reg)[0]) for m in moves]
        ax.plot(100 * moves, 100 * np.array(atm), color=col, lw=1.8,
                label=f"$R={ssr:.0f}$")
    ax.set_xlabel("spot move (%)")
    ax.set_ylabel("ATM implied volatility (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.30)
    save(fig, OUT / "fig_smd_fan.pdf")


# ---------------------------------------------------------------------------
# Figure 2: the two signs (curve rule vs quote rule) under one up-move.
# ---------------------------------------------------------------------------


def figure_signs() -> None:
    h = 0.04
    k = np.linspace(-0.30, 0.26, 300)
    new_curve = shifted_smile(k, vol_curve, SKEW, np.expm1(h),
                              regime=Regime.STICKY_STRIKE)
    k_star = -0.12  # a fixed strike, marked before and after

    fig, ax = plt.subplots(figsize=(6.9, 4.0))
    ax.plot(k, 100 * vol_curve(k), color=SLATE, lw=2.0,
            label="curve before (old forward)")
    ax.plot(k, 100 * new_curve, color=TEAL, lw=2.0, ls="--",
            label="curve after (new forward, sticky-strike)")
    v_star = float(vol_curve(k_star))
    ax.plot([k_star], [100 * v_star], "o", ms=7, color=RUST, zorder=6)
    ax.plot([k_star - h], [100 * v_star], "o", ms=7, color=RUST, mfc="none",
            mew=1.8, zorder=6)
    ax.annotate("", xy=(k_star - h, 100 * v_star + 0.35),
                xytext=(k_star, 100 * v_star + 0.35),
                arrowprops={"arrowstyle": "->", "color": RUST, "lw": 1.6})
    callout(ax, "quote rule: a fixed strike's\nlabel moves to $k-h$\n(vol unchanged)",
            xy=(k_star - h / 2, v_star * 100 + 0.4), xytext=(-0.29, 19.2))
    k_read = 0.10
    ax.annotate("", xy=(k_read, 100 * float(vol_curve(k_read + h))),
                xytext=(k_read + h, 100 * float(vol_curve(k_read + h))),
                arrowprops={"arrowstyle": "->", "color": TEAL, "lw": 1.6})
    callout(ax, "curve rule: the new curve at $k$\nreads the old curve at $k+h$",
            xy=(k_read + h / 2, float(vol_curve(k_read + h)) * 100),
            xytext=(0.02, 17.6))
    ax.set_xlabel(r"log-moneyness $k$ (prevailing forward)")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    save(fig, OUT / "fig_smd_signs.pdf")


# ---------------------------------------------------------------------------
# Figure 3: the stakes — total smile delta per regime (production Black).
# ---------------------------------------------------------------------------


def figure_delta() -> None:
    k_grid = np.linspace(-0.35, 0.25, 121)
    eps = 5e-4

    def total_delta(ssr_regime) -> np.ndarray:
        out = []
        for k0 in k_grid:
            def price(ret: float) -> float:
                f = 1.0 + ret
                k_new = k0 - np.log(f)          # fixed strike, new moneyness
                sig = float(shifted_smile(np.array([k_new]), vol_curve, SKEW,
                                          ret, regime=ssr_regime)[0])
                return f * float(black_call(np.array([k_new]),
                                            np.array([sig**2 * T]))[0])
            out.append((price(eps) - price(-eps)) / (2 * eps))
        return np.array(out)

    deltas = {ssr: total_delta(reg) for _, reg, ssr, _ in REGIMES}
    # The gap at a representative OTM put strike (k = -0.15).
    i_put = int(np.argmin(np.abs(k_grid + 0.15)))
    gap = 100 * abs(deltas[2.0][i_put] - deltas[0.0][i_put])
    macro("smddeltagap", "%.1f", gap)

    fig, ax = plt.subplots(figsize=(6.9, 3.9))
    for (name, reg, ssr, col) in REGIMES:
        ax.plot(k_grid, 100 * deltas[ssr], color=col, lw=1.8,
                label=f"{name} ($R={ssr:.0f}$)")
    ax.axvline(k_grid[i_put], color=PALETTE["ink"], lw=0.7, ls=":")
    callout(ax, f"same book, same surface:\n{gap:.1f} delta points apart",
            xy=(float(k_grid[i_put]), 100 * float(deltas[2.0][i_put]) - 2),
            xytext=(-0.28, 38))
    ax.set_xlabel(r"strike log-moneyness $k$")
    ax.set_ylabel("call delta (%, forward units)")
    ax.legend(fontsize=8.5, loc="lower right")
    save(fig, OUT / "fig_smd_delta.pdf")


# ---------------------------------------------------------------------------
# Figure 4: exact sticky-LV (Hagan map) vs the linear transport.
# ---------------------------------------------------------------------------


def figure_exact() -> None:
    k = np.linspace(-0.45, 0.40, 300)
    h = np.log1p(MOVE)
    w_exact = transported_w(w_curve, k, h, Regime.STICKY_LOCAL_VOL)
    w_linear = transported_w(w_curve, k, h, 2.0)  # numeric R => linear path
    iv_exact = 100 * np.sqrt(w_exact / T)
    iv_linear = 100 * np.sqrt(w_linear / T)
    macro("smdwinggapbp", "%.0f",
          1e2 * float(np.max(np.abs(iv_exact - iv_linear))))

    hs = np.linspace(-0.10, 0.10, 41)
    k_probe = -0.20
    gap_h = []
    for hh in hs:
        we = transported_w(w_curve, np.array([k_probe]), float(hh),
                           Regime.STICKY_LOCAL_VOL)[0]
        wl = transported_w(w_curve, np.array([k_probe]), float(hh), 2.0)[0]
        gap_h.append(1e4 * abs(np.sqrt(we / T) - np.sqrt(wl / T)))

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.25, 1.0]})
    ax = axes[0]
    ax.plot(k, 100 * vol_curve(k), color=SLATE, lw=1.4, ls=":",
            label="today")
    ax.plot(k, iv_exact, color=TEAL, lw=2.0,
            label="exact sticky-LV (Hagan map)")
    ax.plot(k, iv_linear, color=RUST, lw=1.7, ls="--",
            label="linear transport, $R=2$")
    ax.set_xlabel(r"new-forward log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(100 * hs, gap_h, color=TEAL, lw=1.9)
    ax.set_xlabel("log-forward move $h$ (%)")
    ax.set_ylabel(r"|exact $-$ linear| at $k=-0.2$ (vol bp)")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.32)
    save(fig, OUT / "fig_smd_exact.pdf")


# ---------------------------------------------------------------------------
# Figure 5: SSR as an output — realized SSR of the frozen-grid reprice.
# ---------------------------------------------------------------------------


def figure_reprice() -> None:
    xi = np.array([0.0, 0.70, 0.85, 1.00, 1.15, 1.40, 2.20])
    tn = np.array([0.0, 0.8, 1.6])
    theta = 0.05 + 0.08 * (1.0 - xi[None, :]) + 0.06 * (1.0 - xi[None, :]) ** 2 \
        + 0.0 * tn[:, None]
    theta = np.maximum(theta, 0.02)
    x_grid = 0.01 * np.arange(221)
    t_grid = 0.005 * np.arange(321)  # to T = 1.6
    exps = [0.05, 0.10, 0.20, 0.40, 0.80, 1.60]
    h = -0.02
    surf0 = AffineVarianceSurface(t_nodes=tn, x_nodes=xi, theta=theta)
    surf1 = AffineVarianceSurface(t_nodes=tn, x_nodes=xi * np.exp(-h),
                                  theta=theta)  # grid frozen in strike
    sol0 = solve_affine_dupire(surf0, x_grid, t_grid, exps)
    sol1 = solve_affine_dupire(surf1, x_grid, t_grid, exps)

    eps = 0.01
    ssr_real = []
    for i, texp in enumerate(exps):
        def iv(sol, kq):
            kq = np.asarray(kq, dtype=float)
            w = implied_total_variance(kq, sol.price_at(i, np.exp(kq)))
            return np.sqrt(w / texp)
        s_t = float((iv(sol0, [eps]) - iv(sol0, [-eps]))[0] / (2 * eps))
        atm0, atm1 = float(iv(sol0, [0.0])[0]), float(iv(sol1, [0.0])[0])
        ssr_real.append((atm1 - atm0) / (s_t * h))
    ssr_real = np.array(ssr_real)
    macro("smdssrshort", "%.2f", ssr_real[0])
    macro("smdssrlong", "%.2f", ssr_real[-1])

    fig, ax = plt.subplots(figsize=(6.9, 3.7))
    ax.axhline(2.0, color=PALETTE["ink"], lw=0.8, ls=":")
    ax.annotate("the short-maturity limit $R=2$", xy=(0.30, 1.995),
                fontsize=8.5, color=SLATE, va="top")
    ax.semilogx(exps, ssr_real, "o-", ms=5, color=TEAL, lw=1.8,
                label="realized SSR of the frozen-grid reprice")
    ax.set_xlabel(r"maturity $T$ (years, log scale)")
    ax.set_ylabel("realized SSR")
    ax.set_ylim(1.90, 2.16)
    ax.legend(fontsize=8.5, loc="upper right")
    save(fig, OUT / "fig_smd_reprice.pdf")


# ---------------------------------------------------------------------------
# Appendix verification: the transport listing against production.
# ---------------------------------------------------------------------------


def listing_shifted_smile(k, curve, atm_skew, spot_return, ssr):
    d = np.log1p(spot_return)
    return curve(k + d) + (ssr - 1.0) * atm_skew * d


def verify_listings() -> None:
    k = np.linspace(-0.4, 0.35, 97)
    d = 0.0
    for ret, ssr in ((-0.05, 0.0), (0.03, 1.0), (-0.02, 2.0), (0.04, 1.5)):
        d = max(d, float(np.max(np.abs(
            listing_shifted_smile(k, vol_curve, SKEW, ret, ssr)
            - shifted_smile(k, vol_curve, SKEW, ret, regime=ssr)))))
    sci_macro("smdrefagree", d)


# ---------------------------------------------------------------------------


def main() -> None:
    figure_fan()
    print("fan done")
    figure_signs()
    print("signs done")
    figure_delta()
    print("delta done")
    figure_exact()
    print("exact done")
    figure_reprice()
    print("reprice done")
    verify_listings()

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("smdgencommit", "%s", commit)
    macro("smdgendate", "%s", date.today().isoformat())

    (OUT / "ssr_derivative_tables.tex").write_text("\n".join(MACROS) + "\n",
                                                   encoding="utf-8")
    (OUT / "ssr_derivative_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
