"""Figures and tables for Note 09 (Wings, Lee bounds, tail control).

Fits LQD, SVI and Multi-Core SIV to the SAME narrow calibration window, then
extrapolates each far into the wings and measures the realized asymptotic
total-variance slope beta = lim w(k)/|k|. Also plots the Lee map beta = psi(p).

  fig_wings_extrap.pdf  total variance + far-wing extrapolation, three models
  fig_wings_psi.pdf     the Lee moment map psi(p)
  wings_tables.tex      \\input-able macros (per-model left/right beta)
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from volfit.models.lqd.basis import lee_psi, lee_slopes
from volfit.models.lqd.calibrate import calibrate_slice
from volfit.models.sigmoid.calibrate import calibrate_sigmoid
from volfit.models.svi_jw.calibrate import calibrate_svi
from volfit.models.svi_jw.svi import RawSVI

OUT = Path(__file__).resolve().parent
plt.rcParams.update(
    {
        "figure.figsize": (7.2, 4.3),
        "font.size": 11,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "lines.linewidth": 1.8,
        "savefig.bbox": "tight",
        "savefig.dpi": 200,
    }
)
TEAL, RUST, AMBER, SLATE = "#0f766e", "#b91c1c", "#b45309", "#334155"


def beta_numeric(implied_w, k_big=2.5):
    """Realized wing slopes (left, right) = w(-K)/K, w(+K)/K at moderate K
    (deep-ITM Black inversion is ill-conditioned, so K=2.5 not 6)."""
    wl = float(implied_w(np.array([-k_big]))[0]) / k_big
    wr = float(implied_w(np.array([k_big]))[0]) / k_big
    return wl, wr


def main():
    t = 0.5
    raw_t = RawSVI(a=0.010625, b=0.0728868987, rho=-0.5, m=0.0583095189, sigma=0.1009950494)
    k = np.linspace(-0.35, 0.30, 23)
    w = raw_t.total_variance(k)

    lqd = calibrate_slice(k, w, t, n_order=6, reg_lambda=1e-6).slice
    svi = calibrate_svi(k, w, t).raw
    siv = calibrate_sigmoid(k, w, t, n_cores=0)

    models = {
        "LQD": (lqd.implied_w, TEAL),
        "SVI": (svi.implied_w, RUST),
        "MC-SIV": (siv.implied_w, AMBER),
    }

    # --- extrapolation plot
    fig, ax = plt.subplots()
    kk = np.linspace(-0.95, 0.80, 400)
    for name, (iw, c) in models.items():
        ax.plot(kk, iw(kk), color=c, label=name)
    ax.axvspan(k.min(), k.max(), color="black", alpha=0.05, label="fit window")
    ax.scatter(k, w, s=10, color=SLATE, zorder=5)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"total variance $w(k)$")
    ax.legend(frameon=False)
    fig.savefig(OUT / "fig_wings_extrap.pdf")
    plt.close(fig)

    # --- Lee map psi(p)
    fig, ax = plt.subplots(figsize=(6.4, 3.8))
    p = np.linspace(0, 4, 300)
    ax.plot(p, lee_psi(p), color=TEAL)
    ax.axhline(2.0, color=RUST, ls="--", lw=1.0, label=r"Lee ceiling $\beta=2$")
    ax.set_xlabel(r"moment critical exponent $p$")
    ax.set_ylabel(r"wing slope $\beta=\psi(p)$")
    ax.legend(frameon=False)
    fig.savefig(OUT / "fig_wings_psi.pdf")
    plt.close(fig)

    # --- analytic asymptotic total-variance slopes beta = lim w(k)/|k|
    bL_lqd, bR_lqd = lee_slopes(lqd.params)          # LQD: via Lee psi(1/A)
    svl, svr = svi.wing_slopes()                      # SVI: b(1 -+ rho), exact
    # SIV: v ~ slope_z * z, w = t v, k = sigma_ref sqrt(t) z  =>
    #      beta = sqrt(t) |slope_z| / sigma_ref
    wl_z, wr_z = siv.wing_slopes()
    scale = np.sqrt(siv.t) / siv.sigma_ref
    bL_siv, bR_siv = abs(wl_z) * scale, abs(wr_z) * scale
    betas = {"LQD": (bL_lqd, bR_lqd), "SVI": (svl, svr), "MC-SIV": (bL_siv, bR_siv)}

    L = ["% Auto-generated by gen_wings.py — do not edit."]
    for name in ["LQD", "SVI", "MC-SIV"]:
        wl, wr = betas[name]
        tag = name.replace("-", "")
        L.append(r"\newcommand{\beta%sL}{%.4f}" % (tag, wl))
        L.append(r"\newcommand{\beta%sR}{%.4f}" % (tag, wr))
    L.append(r"\newcommand{\sviwingLraw}{%.4f}" % svl)
    L.append(r"\newcommand{\sviwingRraw}{%.4f}" % svr)
    (OUT / "wings_tables.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    (OUT / "wings_numbers.json").write_text(
        json.dumps({"betas_analytic": betas}, indent=2), encoding="utf-8")
    print("analytic betas:", {k_: (round(a, 4), round(b, 4)) for k_, (a, b) in betas.items()})


if __name__ == "__main__":
    main()
