"""Figures for Note 11 (event variance clock).

An earnings event at 3 months worth 4 extra variance-days. Shows the dual clock
(variance time tau vs calendar time T) and the implied-vol term-structure kink it
produces when total variance is fixed by price.

  fig_event_clock.pdf   variance time tau(T) vs calendar time
  fig_event_term.pdf    ATM implied-vol term structure with / without the event
  event_tables.tex      \\input-able macros
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from volfit.calib.weighted_time import weighted_variance_years

OUT = Path(__file__).resolve().parent
plt.rcParams.update(
    {
        "figure.figsize": (7.2, 4.3),
        "font.size": 11,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "lines.linewidth": 1.8,
        "savefig.bbox": "tight",
        "savefig.dpi": 200,
    }
)
TEAL, RUST, SLATE = "#0f766e", "#b91c1c", "#334155"


def main():
    te, extra = 0.25, 4.0          # event at 3m, worth 4 extra variance-days
    events = [(te, extra)]
    sigma_base = 0.20              # diffusive vol on the variance clock

    T = np.linspace(0.01, 1.0, 400)
    tau = np.array([weighted_variance_years(float(t), events) for t in T])
    tau_n = np.array([weighted_variance_years(float(t), events, normalize=True) for t in T])

    # --- dual clock
    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    ax.plot(T, T, color=SLATE, ls=":", label=r"calendar $\tau=T$")
    ax.plot(T, tau, color=TEAL, label=r"variance clock $\tau(T)$")
    ax.plot(T, tau_n, color=RUST, ls="--", label=r"$\tau(T)$ normalized")
    ax.axvline(te, color="black", lw=0.8, alpha=0.5)
    ax.annotate("event", (te, 0.05), (te + 0.03, 0.05), fontsize=9)
    ax.set_xlabel(r"calendar time $T$ (years)")
    ax.set_ylabel(r"variance years $\tau$")
    ax.legend(frameon=False, fontsize=9)
    fig.savefig(OUT / "fig_event_clock.pdf")
    plt.close(fig)

    # --- term structure: w = sigma_base^2 * tau, calendar IV = sqrt(w / T)
    w = sigma_base**2 * tau
    iv_event = np.sqrt(w / T)
    iv_flat = sigma_base * np.ones_like(T)   # no event: tau = T
    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    ax.plot(T, 100 * iv_flat, color=SLATE, ls=":", label="no event")
    ax.plot(T, 100 * iv_event, color=TEAL, label="with event")
    ax.axvline(te, color="black", lw=0.8, alpha=0.5)
    ax.set_xlabel(r"calendar time $T$ (years)")
    ax.set_ylabel(r"ATM implied volatility (\%)")
    ax.set_title("The event lifts short-dated vol, then decays (price preserved)",
                 fontsize=10)
    ax.legend(frameon=False)
    fig.savefig(OUT / "fig_event_term.pdf")
    plt.close(fig)

    # the working vol drop at a fixed expiry just past the event (price fixed)
    t_probe = 0.30
    tau_probe = weighted_variance_years(t_probe, events)
    w_probe = sigma_base**2 * t_probe          # if calendar-measured at sigma_base
    iv_cal = sigma_base
    iv_work = np.sqrt((sigma_base**2 * t_probe) / tau_probe)
    drop_bp = 1e4 * (iv_cal - iv_work)

    L = ["% Auto-generated by gen_event.py — do not edit."]
    L.append(r"\newcommand{\evtextra}{%d}" % int(extra))
    L.append(r"\newcommand{\evtte}{%.2f}" % te)
    L.append(r"\newcommand{\evttauprobe}{%.4f}" % tau_probe)
    L.append(r"\newcommand{\evtdropbp}{%.0f}" % drop_bp)
    L.append(r"\newcommand{\evtdays}{365}")
    (OUT / "event_tables.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("tau(0.30) with event = %.4f (cal 0.30); working-vol drop %.0f bp"
          % (tau_probe, drop_bp))


if __name__ == "__main__":
    main()
