"""Figure suite for the inference edition of Note 06 (forwards & dividends).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_fwd_inference.py

Every forward, discount, residual, de-bias and borrow number is produced by
the PRODUCTION resolution code (``volfit.data.forwards``,
``volfit.data.dividends``, ``volfit.data.carry_solve``, with option prices
from ``volfit.core``); local formulae appear only to define synthetic truths,
deterministic noise, and the OLS theory curves the figures audit.  Synthetic
chains are built through the production ``ChainSnapshot``/``OptionQuote``
types so the entry point exercised is the real one.

Outputs, written next to this script:

* ``fig_fwdinf_line.pdf``     -- the parity line, fitted by production, + residuals;
* ``fig_fwdinf_ident.pdf``    -- identifiability Monte Carlo: rate wide, forward tight;
* ``fig_fwdinf_lever.pdf``    -- transmitted forward error ~ the estimator's lever arm;
* ``fig_fwdinf_trim.pdf``     -- two stale quotes vs the robust trim loop;
* ``fig_fwdinf_zerocarry.pdf``-- the vacuous design on the real Massive fixture;
* ``fig_fwdinf_divs.pdf``     -- implied carry under the four dividend modes;
* ``fig_fwdinf_debias.pdf``   -- the American de-bias closing the ATM join;
* ``fig_fwdinf_borrow.pdf``   -- borrow sensitivity and the identifiability floor;
* ``fwd_inference_tables.tex`` / ``fwd_inference_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))

from style import PALETTE, WIDE, label_panel, save, setup  # noqa: E402

from lv_benchmark import load_benchmark  # noqa: E402
from volfit.core.american import binomial_price, deamericanize_batch  # noqa: E402
from volfit.core.black import black_call  # noqa: E402
from volfit.data import forwards as fwd_mod  # noqa: E402
from volfit.data.carry_solve import (  # noqa: E402
    borrow_noise_floor_bp,
    iv_borrow_sensitivity_bp,
)
from volfit.data.dividends import (  # noqa: E402
    Dividend,
    DividendModel,
    equivalent_yield,
    theoretical_forward,
)
from volfit.data.forwards import implied_forward  # noqa: E402
from volfit.data.types import ChainSnapshot, OptionQuote  # noqa: E402

setup()
TEAL, BLUE, RUST, AMBER, SLATE, VIOLET = (
    PALETTE["teal"], PALETTE["blue"], PALETTE["rust"], PALETTE["amber"],
    PALETTE["muted"], PALETTE["violet"],
)

REF = date(2026, 6, 25)
TS = datetime(2026, 6, 25, 16, 0)
FIXTURE = REPO / "backend" / "tests" / "fixtures" / "lv_weekly_massive.json"
RATE_MIN, RATE_MAX = fwd_mod.RATE_MIN, fwd_mod.RATE_MAX

MACROS: list[str] = ["% Auto-generated by gen_fwd_inference.py — do not edit."]
NUMBERS: dict = {}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


# ---------------------------------------------------------------------------
# Chain builders (production types; prices from production Black / CRR).
# ---------------------------------------------------------------------------

SPOT, RATE, DIVY, SIG = 100.0, 0.04, 0.01, 0.22
DAYS = 183
EXPIRY = REF + timedelta(days=DAYS)
T = DAYS / 365.0
F_TRUE = SPOT * float(np.exp((RATE - DIVY) * T))
D_TRUE = float(np.exp(-RATE * T))


def euro_prices(strikes: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    k = np.log(strikes / F_TRUE)
    c = D_TRUE * F_TRUE * black_call(k, SIG * SIG * T * np.ones_like(k))
    p = c - D_TRUE * (F_TRUE - strikes)
    return c, p


def make_chain(strikes, calls, puts, half=0.05, style="european",
               round_cents=True) -> ChainSnapshot:
    qs = []
    for kk, c, p in zip(strikes, calls, puts):
        for cp, m in (("C", c), ("P", p)):
            b, a = m - half, m + half
            if round_cents:
                b, a = round(b, 2), round(a, 2)
            qs.append(OptionQuote("SYN", EXPIRY, float(kk), cp, bid=b, ask=a,
                                  timestamp=TS))
    return ChainSnapshot("SYN", SPOT, TS, qs, exercise_style=style)


STRIKES = np.arange(82.0, 120.5, 2.0)


# ---------------------------------------------------------------------------
# Figure 1: the line itself, fitted by production, with residuals.
# ---------------------------------------------------------------------------


def figure_line() -> None:
    c, p = euro_prices(STRIKES)
    snap = make_chain(STRIKES, c, p)
    res = implied_forward(snap, EXPIRY)
    f_hat, d_hat = res.forward, res.discount
    r_hat = -np.log(d_hat) / T
    mids_c = np.array([q.mid for q in snap.quotes_for(EXPIRY) if q.call_put == "C"])
    mids_p = np.array([q.mid for q in snap.quotes_for(EXPIRY) if q.call_put == "P"])
    y = mids_c - mids_p
    resid = y - d_hat * (f_hat - STRIKES)
    macro("fwdinfFerrbp", "%.2f", 1e4 * abs(f_hat - F_TRUE) / F_TRUE)
    macro("fwdinfraterrbp", "%.1f", 1e4 * abs(r_hat - RATE))
    macro("fwdinfrms", "%.2f", 100 * res.residual_rms)
    macro("fwdinfnpairs", "%d", res.n_strikes)

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.scatter(STRIKES, y, s=22, color=RUST, zorder=5, label="$C-P$ (mids)")
    kk = np.linspace(80, 122, 50)
    ax.plot(kk, d_hat * (f_hat - kk), color=TEAL, label=r"fitted line $\hat D(\hat F-K)$")
    ax.axhline(0, color="black", lw=0.7)
    ax.axvline(f_hat, color=SLATE, ls=":")
    ax.annotate(r"$\hat F$", xy=(f_hat, 0.9), xycoords=("data", "axes fraction"),
                xytext=(4, 0), textcoords="offset points", color=SLATE)
    ax.set_xlabel("strike $K$")
    ax.set_ylabel("$C-P$ (dollars)")
    ax.legend(fontsize=9)
    label_panel(ax, "A")
    ax = axes[1]
    ax.axhline(0, color="black", lw=0.7)
    ax.stem(STRIKES, 100 * resid, linefmt=TEAL, markerfmt="o", basefmt=" ")
    ax.set_xlabel("strike $K$")
    ax.set_ylabel("residual (cents)")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_fwdinf_line.pdf")


# ---------------------------------------------------------------------------
# Figure 2: identifiability Monte Carlo — the slope is the weak parameter.
# ---------------------------------------------------------------------------


def figure_ident() -> None:
    rng = np.random.default_rng(6)
    c0, p0 = euro_prices(STRIKES)
    n_trials, noise = 400, 0.02  # 2-cent quote noise per mid
    rates, fwd_bp = [], []
    for _ in range(n_trials):
        c = c0 + rng.normal(0.0, noise, c0.size)
        p = p0 + rng.normal(0.0, noise, p0.size)
        res = implied_forward(make_chain(STRIKES, c, p, round_cents=False), EXPIRY)
        rates.append(-np.log(res.discount) / T)
        fwd_bp.append(1e4 * (res.forward - F_TRUE) / F_TRUE)
    rates, fwd_bp = np.array(rates), np.array(fwd_bp)

    # OLS theory (audited, not asserted): sd of the slope and of the level.
    s_kk = float(np.sum((STRIKES - STRIKES.mean()) ** 2))
    sd_y = noise * np.sqrt(2.0)  # C and P noise both enter y = C - P
    sd_rate_pred = sd_y / np.sqrt(s_kk) / (D_TRUE * T)
    sd_fwd_pred_bp = 1e4 * (sd_y / np.sqrt(STRIKES.size) / D_TRUE) / F_TRUE
    macro("fwdinfmcratesd", "%.0f", 1e4 * np.std(rates - RATE))
    macro("fwdinfmcratepred", "%.0f", 1e4 * sd_rate_pred)
    macro("fwdinfmcfwdsd", "%.1f", np.std(fwd_bp))
    macro("fwdinfmcfwdpred", "%.1f", sd_fwd_pred_bp)
    macro("fwdinfmcn", "%d", n_trials)

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.hist(100 * rates, bins=31, color=RUST, alpha=0.75)
    ax.axvline(100 * RATE, color=PALETTE["ink"], lw=1.2, ls=":")
    ax.annotate("true rate", xy=(100 * RATE, 0.95), xycoords=("data", "axes fraction"),
                xytext=(5, 0), textcoords="offset points", fontsize=9, color=SLATE)
    ax.set_xlabel("parity-implied rate (%)")
    ax.set_ylabel("trials")
    label_panel(ax, "A")
    ax = axes[1]
    ax.hist(fwd_bp, bins=31, color=TEAL, alpha=0.8)
    ax.axvline(0.0, color=PALETTE["ink"], lw=1.2, ls=":")
    ax.set_xlabel(r"forward error (bp of $F$)")
    ax.set_ylabel("trials")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_fwdinf_ident.pdf")


# ---------------------------------------------------------------------------
# Figure 3: the lever arm — where a discount error can and cannot reach.
# ---------------------------------------------------------------------------


def figure_lever() -> None:
    # Asymmetric board (puts listed deeper than calls), exact prices.
    strikes = np.arange(78.0, 112.5, 2.0)
    c, p = euro_prices(strikes)
    y = c - p
    spread_c = np.full(strikes.size, 0.10)
    spread_p = np.full(strikes.size, 0.10)
    dr = np.linspace(-0.03, 0.03, 41)  # imposed rate error

    err_naive, err_unif, err_kern = [], [], []
    for d in dr:
        d_bad = D_TRUE * float(np.exp(-d * T))
        err_naive.append(D_TRUE * F_TRUE / d_bad - F_TRUE)      # intercept / slope
        err_unif.append(float(np.mean(strikes + y / d_bad)) - F_TRUE)
        err_kern.append(fwd_mod._forward_at_discount(
            strikes, c, p, spread_c, spread_p, SPOT, d_bad) - F_TRUE)
    err_naive, err_unif, err_kern = map(np.array, (err_naive, err_unif, err_kern))
    per1 = lambda e: float(np.polyfit(100 * dr, 1e4 * e / F_TRUE, 1)[0])
    macro("fwdinflevernaive", "%.0f", abs(per1(err_naive)))
    macro("fwdinfleverunif", "%.1f", abs(per1(err_unif)))
    macro("fwdinfleverkern", "%.1f", abs(per1(err_kern)))
    macro("fwdinfleverkbar", "%.1f", float(np.mean(strikes)))

    fig, ax = plt.subplots(figsize=(6.9, 4.0))
    ax.axhline(0, color="black", lw=0.7)
    ax.plot(100 * dr, 1e4 * err_naive / F_TRUE, color=RUST,
            label=r"intercept$/$slope $\hat F=\hat a/D$ (lever $=F$)")
    ax.plot(100 * dr, 1e4 * err_unif / F_TRUE, color=AMBER,
            label=r"uniform level mean (lever $=\bar K-F$)")
    ax.plot(100 * dr, 1e4 * err_kern / F_TRUE, color=TEAL, lw=2.4,
            label="production ATM-kernel level (lever $\\approx S-F$)")
    ax.set_xlabel("imposed rate error (%)")
    ax.set_ylabel(r"transmitted forward error (bp of $F$)")
    ax.legend(fontsize=9, loc="upper right")
    save(fig, OUT / "fig_fwdinf_lever.pdf")


# ---------------------------------------------------------------------------
# Figure 4: robust trim — two stale quotes vs the loop.
# ---------------------------------------------------------------------------


def figure_trim() -> None:
    strikes = np.arange(82.0, 121.0, 3.0)
    c, p = euro_prices(strikes)

    # Experiment 1 (the figure): ONE grossly stale deep put.  The residual
    # trim isolates and drops it; the refit recovers the truth.
    p_bad = p.copy()
    bad = [2]
    p_bad[bad[0]] += 1.20
    snap = make_chain(strikes, c, p_bad, round_cents=False)
    res = implied_forward(snap, EXPIRY)

    y = c - p_bad
    k = strikes
    a_mat = np.column_stack([np.ones_like(k), k])
    (a_raw, b_raw), *_ = np.linalg.lstsq(a_mat, y, rcond=None)
    f_raw, d_raw = a_raw / (-b_raw), -b_raw
    macro("fwdinftrimrawbp", "%.0f", 1e4 * abs(f_raw - F_TRUE) / F_TRUE)
    macro("fwdinftrimrawrate", "%.1f", -100 * np.log(d_raw) / T)
    macro("fwdinftrimbp", "%.1f", 1e4 * abs(res.forward - F_TRUE) / F_TRUE)
    macro("fwdinftrimnout", "%d", res.n_outliers)

    # Experiment 2 (prose): TWO coherent stale puts on the same wing.  They
    # read as carry, the corrupted line fits them well (masking), nothing is
    # trimmed, and the spurious rate stays inside the physical band: the trim
    # and the clamp both pass; only the level's robustness contains the harm.
    p_msk = p.copy()
    p_msk[0] += 1.10
    p_msk[1] += 0.85
    res_m = implied_forward(make_chain(strikes, c, p_msk, round_cents=False),
                            EXPIRY, reference_date=REF)
    macro("fwdinfmaskrate", "%.1f", -100 * np.log(res_m.discount) / T)
    macro("fwdinfmaskbp", "%.0f", 1e4 * abs(res_m.forward - F_TRUE) / F_TRUE)
    macro("fwdinfmasknout", "%d", res_m.n_outliers)

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.scatter(k, y, s=20, color=RUST, zorder=5, label="$C-P$ (one stale put)")
    ax.scatter(k[bad], y[bad], s=110, facecolors="none",
               edgecolors=PALETTE["ink"], zorder=6, label="trimmed by the loop")
    kk = np.linspace(80, 122, 50)
    ax.plot(kk, res.discount * (res.forward - kk), color=TEAL, label="production (trimmed)")
    ax.axhline(0, color="black", lw=0.7)
    ax.set_xlabel("strike $K$")
    ax.set_ylabel("$C-P$ (dollars)")
    ax.legend(fontsize=8.5)
    label_panel(ax, "A")
    ax = axes[1]
    resid = y - res.discount * (res.forward - k)
    sig_rob = 1.4826 * float(np.median(np.abs(resid)))
    ax.axhspan(-100 * 4 * sig_rob, 100 * 4 * sig_rob, color=TEAL, alpha=0.10,
               lw=0)
    ax.annotate(r"keep: $|\mathrm{resid}| \leq 4\hat\sigma$", xy=(0.03, 0.56),
                xycoords="axes fraction", fontsize=8.5, color=SLATE)
    ax.axhline(0, color="black", lw=0.7)
    ax.stem(k, 100 * resid, linefmt=TEAL, markerfmt="o", basefmt=" ")
    ax.plot(k[bad], 100 * resid[bad], "o", ms=7, mfc="none", mec=PALETTE["ink"])
    ax.set_xlabel("strike $K$")
    ax.set_ylabel("residual vs trimmed fit (cents)")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_fwdinf_trim.pdf")


# ---------------------------------------------------------------------------
# Figure 5: the vacuous design — the real synthesized fixture, regressed.
# ---------------------------------------------------------------------------


def figure_zerocarry() -> None:
    data, chains = load_benchmark(FIXTURE)
    as_of = date.fromisoformat(data["as_of"])
    snap = chains["SPY"]
    s = float(snap.spot)
    ts, rates, rms_bp, fdev = [], [], [], []
    for expiry in snap.expiries():
        t = (expiry - as_of).days / 365.0
        if t <= 0 or t > 2.0:
            continue
        res = implied_forward(snap, expiry)  # raw regression, no clamp
        if res is None or res.n_strikes < 6:
            continue
        ts.append(t)
        rates.append(-np.log(res.discount) / t)
        rms_bp.append(1e4 * res.residual_rms / s)
        fdev.append(100 * (res.forward / s - 1.0))
    ts, rates, rms_bp, fdev = map(np.array, (ts, rates, rms_bp, fdev))
    macro("fwdinfzcn", "%d", ts.size)
    macro("fwdinfzcminrate", "%.1f", 100 * rates.min())
    macro("fwdinfzcmaxrate", "%.1f", 100 * rates.max())
    macro("fwdinfzcmedrms", "%.1f", float(np.median(rms_bp)))
    macro("fwdinfzcmaxfdev", "%.1f", float(np.max(np.abs(fdev))))

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.axhspan(100 * RATE_MIN, 100 * RATE_MAX, color=TEAL, alpha=0.07, lw=0)
    ax.axhline(100 * RATE_MIN, color=SLATE, lw=0.8)
    ax.axhline(100 * RATE_MAX, color=SLATE, lw=0.8)
    ax.plot(ts, 100 * rates, "o", ms=5, color=RUST, label="regressed implied rate")
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8, ls=":")
    ax.annotate("construction convention:\n$F=S$, $D=1$ (rate $0$)",
                xy=(0.90, 0.0), xytext=(0.30, -17.5), fontsize=8.5,
                color=PALETTE["ink"],
                arrowprops={"arrowstyle": "->", "color": SLATE, "lw": 1.0})
    ax.annotate("physical band: the clamp bounds\nthe absurd rates, passes the\nplausible ones — all meaningless",
                xy=(0.30, 0.62), xycoords="axes fraction", fontsize=8.5, color=SLATE)
    ax.set_xlabel("time to expiry (years)")
    ax.set_ylabel("parity-implied rate (%)")
    ax.set_ylim(-36, 34)
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(ts, rms_bp, "o", ms=5, color=TEAL)
    ax.set_xlabel("time to expiry (years)")
    ax.set_ylabel("fit residual RMS (bp of spot)")
    ax.set_ylim(0, max(3.0, 1.35 * rms_bp.max()))
    ax.annotate("ordinary-looking residuals: nothing\nin the fit says the design is vacuous",
                xy=(0.22, 0.82), xycoords="axes fraction", fontsize=8.5, color=SLATE)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_fwdinf_zerocarry.pdf")


# ---------------------------------------------------------------------------
# Figure 6: the four dividend modes, as implied carry term structures.
# ---------------------------------------------------------------------------


def figure_divs() -> None:
    r = 0.04
    exs = [REF + timedelta(days=30 + 91 * i) for i in range(8)]
    cash = tuple(Dividend(e, 0.65) for e in exs)
    prop = tuple(Dividend(e, 0.0065) for e in exs)
    models = [
        ("discrete cash (escrowed)", TEAL,
         DividendModel(mode="discrete_absolute", dividends=cash)),
        ("discrete proportional", BLUE,
         DividendModel(mode="discrete_proportional", dividends=prop)),
        ("continuous yield", AMBER,
         DividendModel(mode="continuous", yield_=0.026)),
        ("mixed (cash, then proportional)", VIOLET,
         DividendModel(mode="mixed", dividends=cash, switch_years=1.0)),
    ]
    tt = np.arange(10, 731, 3) / 365.0
    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    for lab, col, model in (models[0], models[2]):
        q_imp = [100 * (r - np.log(theoretical_forward(SPOT, r, float(t), model, REF)
                                   / SPOT) / t) for t in tt]
        ls = "--" if model.mode == "continuous" else "-"
        ax.plot(tt, q_imp, color=col, ls=ls, lw=1.8, label=lab)
    ax.set_xlabel("expiry $t$ (years)")
    ax.set_ylabel(r"implied carry $r-\log(F/S)/t$ (%)")
    ax.legend(fontsize=8.5, loc="upper right")
    label_panel(ax, "A")
    # Panel B: what a STATIC term structure cannot show — the forward's spot
    # elasticity, where the four modes genuinely differ (finite difference of
    # the production forward under a 1% spot bump).
    ax = axes[1]
    bump = 1.01
    for lab, col, model in (models[0], models[1], models[2]):
        el = [np.log(theoretical_forward(SPOT * bump, r, float(t), model, REF)
                     / theoretical_forward(SPOT, r, float(t), model, REF))
              / np.log(bump) for t in tt]
        ls = "--" if model.mode == "continuous" else "-"
        ax.plot(tt, el, color=col, ls=ls, lw=1.8, label=lab)
    ax.set_xlabel("expiry $t$ (years)")
    ax.set_ylabel(r"forward elasticity $\partial\log F/\partial\log S$")
    ax.legend(fontsize=8, loc="upper left")
    label_panel(ax, "B")
    q_eq = equivalent_yield(SPOT, theoretical_forward(
        SPOT, r, 1.0, models[0][2], REF), r, 1.0)
    macro("fwdinfdiveq", "%.2f", 100 * q_eq)
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_fwdinf_divs.pdf")


# ---------------------------------------------------------------------------
# Figure 7: the American de-bias — errors-in-variables, corrected.
# ---------------------------------------------------------------------------


def figure_debias() -> None:
    r, q, sig = 0.05, 0.0, 0.25
    f_true = SPOT * float(np.exp((r - q) * T))
    strikes = np.arange(80.0, 120.5, 2.5)
    c = np.array([binomial_price(True, SPOT, float(kk), T, sig, r, q,
                                 american=True) for kk in strikes])
    p = np.array([binomial_price(False, SPOT, float(kk), T, sig, r, q,
                                 american=True) for kk in strikes])
    snap = make_chain(strikes, c, p, style="american", round_cents=False)
    raw = implied_forward(snap, EXPIRY)
    deb = implied_forward(snap, EXPIRY, reference_date=REF)

    def atm_sides(res) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        rr = -np.log(res.discount) / T
        qq = rr - np.log(res.forward / SPOT) / T
        band = np.abs(np.log(strikes / res.forward)) <= 0.10
        ks = strikes[band]
        sc = deamericanize_batch(np.ones(ks.size, bool), c[band], SPOT, ks, T, rr, qq)
        sp = deamericanize_batch(np.zeros(ks.size, bool), p[band], SPOT, ks, T, rr, qq)
        return ks, sc, sp

    ks_r, sc_r, sp_r = atm_sides(raw)
    ks_d, sc_d, sp_d = atm_sides(deb)
    gap_r = 1e4 * float(np.nanmean(sc_r - sp_r))
    gap_d = 1e4 * float(np.nanmean(sc_d - sp_d))
    macro("fwdinfdebrawbp", "%.0f", 1e4 * abs(raw.forward - f_true) / f_true)
    macro("fwdinfdebbp", "%.1f", 1e4 * abs(deb.forward - f_true) / f_true)
    macro("fwdinfdebrawgap", "%.0f", abs(gap_r))
    macro("fwdinfdebgap", "%.0f", abs(gap_d))
    macro("fwdinfdebrawrate", "%.2f", -100 * np.log(raw.discount) / T)
    macro("fwdinfdebrate", "%.2f", -100 * np.log(deb.discount) / T)

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.plot(ks_r, 100 * sc_r, "o-", ms=3.5, lw=1.3, color=RUST, label="calls, raw carry")
    ax.plot(ks_r, 100 * sp_r, "s--", ms=3.5, lw=1.3, color=AMBER, label="puts, raw carry")
    ax.set_xlabel("strike $K$")
    ax.set_ylabel("de-Americanized vol (%)")
    ax.legend(fontsize=8.5, loc="center right")
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(ks_d, 100 * sc_d, "o-", ms=3.5, lw=1.3, color=TEAL, label="calls, de-biased carry")
    ax.plot(ks_d, 100 * sp_d, "s--", ms=3.5, lw=1.3, color=BLUE, label="puts, de-biased carry")
    ax.set_xlabel("strike $K$")
    ax.set_ylabel("de-Americanized vol (%)")
    ax.legend(fontsize=8.5, loc="lower right")
    label_panel(ax, "B")
    lo = min(ax.get_ylim()[0] for ax in axes)
    hi = max(ax.get_ylim()[1] for ax in axes)
    for ax in axes:
        ax.set_ylim(lo, hi)
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_fwdinf_debias.pdf")


# ---------------------------------------------------------------------------
# Figure 8: the borrow, at the edge of identifiability.
# ---------------------------------------------------------------------------


def figure_borrow() -> None:
    tt = np.linspace(0.05, 2.0, 60)
    sens = np.array([iv_borrow_sensitivity_bp(float(t)) for t in tt])
    floors = {lab: np.array([borrow_noise_floor_bp(rms, float(t), 10) for t in tt])
              for lab, rms in (("10 bp of spot", 1e-3), ("50 bp of spot", 5e-3))}
    i3m = int(np.argmin(np.abs(tt - 0.25)))
    i1y = int(np.argmin(np.abs(tt - 1.0)))
    macro("fwdinfbsensq", "%.0f", sens[i3m])
    macro("fwdinfbsensy", "%.0f", sens[i1y])
    macro("fwdinfbfloory", "%.0f", floors["10 bp of spot"][i1y])
    macro("fwdinfbfloorq", "%.0f", floors["10 bp of spot"][i3m])
    macro("fwdinfbfloorwy", "%.0f", floors["50 bp of spot"][i1y])

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.plot(tt, sens, color=TEAL)
    ax.set_xlabel("expiry $t$ (years)")
    ax.set_ylabel(r"vol bp moved per 100 bp of borrow")
    label_panel(ax, "A")
    ax = axes[1]
    for (lab, fl), col in zip(floors.items(), (TEAL, RUST)):
        ax.semilogy(tt, fl, color=col, label=f"quote noise {lab}")
    ax.axhspan(25, 300, color=SLATE, alpha=0.10, lw=0)
    ax.annotate("typical hard-to-borrow\nlevels 25–300 bp", xy=(1.22, 42),
                fontsize=8.5, color=SLATE)
    ax.set_xlabel("expiry $t$ (years)")
    ax.set_ylabel("borrow noise floor (bp/yr)")
    ax.legend(fontsize=8.5, loc="lower left")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.32)
    save(fig, OUT / "fig_fwdinf_borrow.pdf")


# ---------------------------------------------------------------------------
# Appendix D verification: the two listings against production.
# ---------------------------------------------------------------------------


def listing_implied_forward(K, call_mid, put_mid):
    y = call_mid - put_mid
    b, a = np.polyfit(K, y, 1)
    D = -b
    return a / D, D


def listing_clamp_forward(K, call_mid, put_mid, t, F, D, r_lo=-0.05, r_hi=0.30):
    r = -np.log(D) / t
    if r_lo <= r <= r_hi:
        return F, D
    D = np.exp(-np.clip(r, r_lo, r_hi) * t)
    F = np.mean(K + (call_mid - put_mid) / D)
    return F, D


def verify_listings() -> None:
    c, p = euro_prices(STRIKES)
    snap = make_chain(STRIKES, c, p, round_cents=False)
    res = implied_forward(snap, EXPIRY)
    f_l, d_l = listing_implied_forward(STRIKES, c, p)
    agree = max(abs(f_l - res.forward), abs(d_l - res.discount), 1e-16)
    macro("fwdinfrefagree", "%.0f", np.floor(np.log10(agree)))

    # A tilted board: put mids drift linearly in strike -> the slope (only)
    # is corrupted, hard enough that the implied rate leaves the physical
    # band; production clamps the rate and re-derives the level.
    tilt = 0.055 * (STRIKES - STRIKES.mean())
    snap_bad = make_chain(STRIKES, c, p + tilt, round_cents=False)
    res_bad = implied_forward(snap_bad, EXPIRY, reference_date=REF)
    r_bad = -np.log(res_bad.discount) / T
    f_ref, d_ref = listing_implied_forward(STRIKES, c, p + tilt)
    f_cl, d_cl = listing_clamp_forward(STRIKES, c, p + tilt, T, f_ref, d_ref)
    macro("fwdinfrefclrate", "%.1f", 100 * r_bad)
    macro("fwdinfrefclrateeq", "%.1e", abs(-np.log(d_cl) / T - r_bad))
    macro("fwdinfrefclfbp", "%.0f", 1e4 * abs(f_cl - res_bad.forward) / res_bad.forward)
    macro("fwdinfrefrawrate", "%.1f", -100 * np.log(d_ref) / T)


# ---------------------------------------------------------------------------


def main() -> None:
    figure_line()
    print("line done")
    figure_ident()
    print("ident done")
    figure_lever()
    print("lever done")
    figure_trim()
    print("trim done")
    figure_zerocarry()
    print("zerocarry done")
    figure_divs()
    print("divs done")
    figure_debias()
    print("debias done")
    figure_borrow()
    print("borrow done")
    verify_listings()

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("fwdinfgencommit", "%s", commit)
    macro("fwdinfgendate", "%s", date.today().isoformat())

    (OUT / "fwd_inference_tables.tex").write_text("\n".join(MACROS) + "\n",
                                                  encoding="utf-8")
    (OUT / "fwd_inference_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
