"""Figure suite for the optimal-stopping edition of Note 05 (de-Americanization).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_deam_stopping.py

Every price, premium, root, repair and real-chain number is produced by the
PRODUCTION de-Americanization machinery (``volfit.core.american``,
``volfit.core.black``, ``volfit.data.dividends``, ``volfit.calib.convex_deam``
and the quote-prep premium helper); local formulae appear only to define the
synthetic running example and deterministic perturbations.  The Numba/NumPy
timing macros are NOT regenerated here — the note reuses ``deam_tables.tex``
(the artifact of ``gen_deam.py``'s benchmarked run), so this suite never
re-times a benchmark.

Outputs, written next to this script:

* ``fig_deamst_bias.pdf``    -- the wrong-way demo: naive inversion vs de-Am + EEP;
* ``fig_deamst_vega.pdf``    -- the price->vol dictionary bias ~ EEP/vega, audited;
* ``fig_deamst_map.pdf``     -- thesis figure: EEP and the exercise region in (K,t);
* ``fig_deamst_root.pdf``    -- the monotone root find and its failure lanes;
* ``fig_deamst_cancel.pdf``  -- control-variate cancellation + the depth budget;
* ``fig_deamst_escrow.pdf``  -- discrete cash vs continuous yield in the tree;
* ``fig_deamst_convex.pdf``  -- the wing-only band-constrained convexity repair;
* ``fig_deamst_real.pdf``    -- real SPY stress exhibit (every put, ITM wedge);
* ``fig_deamst_realsel.pdf`` -- real SPY, the production-selected population;
* ``deam_stopping_tables.tex`` / ``deam_stopping_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date, timedelta
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))  # shared figure style (STYLE_GUIDE.md section 6)
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))  # lv_benchmark fixture loader

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from gen_deam_real import EXPIRY, FIXTURE, R, Q, naive_black_iv, two_sided  # noqa: E402
from lv_benchmark import load_benchmark  # noqa: E402
from volfit.calib import convex_deam  # noqa: E402
from volfit.calib.convex_deam import convex_wing_repair, min_norm_butterfly  # noqa: E402
from volfit.core.american import (  # noqa: E402
    DEFAULT_STEPS,
    binomial_price,
    binomial_price_batch,
    deamericanize,
    deamericanize_batch,
)
from volfit.core.black import (  # noqa: E402
    black_vega_sigma,
    implied_total_variance,
)
from volfit.data.dividends import (  # noqa: E402
    Dividend,
    DividendModel,
    equivalent_yield,
    forward_consistent_cash_schedule,
    theoretical_forward,
)

setup()
TEAL, BLUE, RUST, AMBER, SLATE = (
    PALETTE["teal"], PALETTE["blue"], PALETTE["rust"], PALETTE["amber"],
    PALETTE["muted"],
)

# The synthetic running example (identical to the original note's): American
# CALLS on a 6%-dividend-yield stock, true vol 25%, six months.
S0, T0, R0, Q0, SIG0 = 100.0, 0.5, 0.02, 0.06, 0.25

MACROS: list[str] = ["% Auto-generated by gen_deam_stopping.py — do not edit."]
NUMBERS: dict = {}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def naive_iv_calls(strikes: np.ndarray, am: np.ndarray, f: float, d: float,
                   t: float) -> np.ndarray:
    """American CALL dollar prices through the pipeline's analytic European
    inversion (normalize, invert to total variance, annualize)."""
    k = np.log(strikes / f)
    w = implied_total_variance(k, am / (d * f))
    with np.errstate(invalid="ignore"):
        return np.sqrt(w / t)


# ---------------------------------------------------------------------------
# Figures 1+2: the wrong-way demo and the vega dictionary.
# ---------------------------------------------------------------------------


def figure_bias_and_vega() -> None:
    strikes = np.linspace(88, 120, 17)
    f = S0 * float(np.exp((R0 - Q0) * T0))
    d = float(np.exp(-R0 * T0))
    am = np.array([binomial_price(True, S0, float(k), T0, SIG0, R0, Q0,
                                  american=True) for k in strikes])
    eu = np.array([binomial_price(True, S0, float(k), T0, SIG0, R0, Q0,
                                  american=False) for k in strikes])
    eep = am - eu
    naive = naive_iv_calls(strikes, am, f, d, T0)
    deam = np.array([deamericanize(True, float(a), S0, float(k), T0, R0, Q0)
                     for a, k in zip(am, strikes)])
    bias_bp = 1e4 * (naive - deam)
    macro("deamstmaxbias", "%.0f", np.nanmax(bias_bp))

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.axhline(100 * SIG0, color=SLATE, ls=":", lw=1.2)
    ax.plot(strikes, 100 * naive, color=RUST, label="American price, European inversion")
    ax.plot(strikes, 100 * deam, color=TEAL, ls="--", label=r"de-Americanized $\sigma^*$")
    ax.annotate("true vol 25%", xy=(91.0, 100 * SIG0),
                xytext=(6, -14), textcoords="offset points", color=SLATE, fontsize=9)
    ax.set_xlabel("strike $K$")
    ax.set_ylabel("implied volatility (%)")
    ax.set_ylim(24.0, 28.4)
    ax.legend(loc="upper right", fontsize=9)
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(strikes, eep, color=TEAL)
    ax.fill_between(strikes, eep, color=TEAL, alpha=0.12)
    ax.set_xlabel("strike $K$")
    ax.set_ylabel(r"$\pi = A - E$ (dollars)")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_deamst_bias.pdf")

    # The dictionary: a price nuisance pi moves implied vol by ~ pi / vega.
    vega = black_vega_sigma(np.log(strikes / f), deam, T0)  # normalized-call vega
    pred_bp = 1e4 * (eep / (d * f)) / vega
    otm = strikes >= f
    macro("deamstvegaotmerr", "%.1f", np.nanmax(np.abs(bias_bp - pred_bp)[otm]))

    fig, ax = plt.subplots()
    ax.plot(strikes, pred_bp, color=SLATE, lw=1.6,
            label=r"first order: $\pi \,/\, \partial_\sigma B$")
    ax.plot(strikes, bias_bp, "o", ms=5, color=RUST, label="measured naive bias")
    ax.set_xlabel("strike $K$")
    ax.set_ylabel(r"naive $-$ de-Am implied vol (vol bp)")
    ax.legend(loc="upper right", fontsize=9.5)
    callout(ax, "the premium is no longer infinitesimal:\nfirst order under-predicts deep ITM",
            xy=(90.5, float(bias_bp[1])), xytext=(93.5, float(bias_bp[1]) - 24))
    save(fig, OUT / "fig_deamst_vega.pdf")


# ---------------------------------------------------------------------------
# Figure 3: the thesis figure — EEP and the exercise region over (K, t).
# ---------------------------------------------------------------------------


def figure_map() -> None:
    strikes = np.linspace(60.0, 145.0, 52)
    mats = np.linspace(0.04, 1.5, 38)
    KK, TT = np.meshgrid(100.0 * strikes / S0, mats)

    def panel(is_call: bool, r: float, q: float):
        eep = np.empty((mats.size, strikes.size))
        pinned = np.empty_like(eep, dtype=bool)
        flags = np.full(strikes.size, is_call)
        sig = np.full(strikes.size, SIG0)
        intrinsic = np.maximum(S0 - strikes, 0.0) if is_call else np.maximum(strikes - S0, 0.0)
        for i, t in enumerate(mats):
            am = binomial_price_batch(flags, S0, strikes, float(t), sig, r, q,
                                      american=True)
            eu = binomial_price_batch(flags, S0, strikes, float(t), sig, r, q,
                                      american=False)
            eep[i] = am - eu
            # Zero time value where exercise-now is optimal: the price is pinned
            # at a POSITIVE intrinsic (far-OTM prices also vanish; exclude them).
            pinned[i] = (am - intrinsic < 1e-7 * np.maximum(strikes, S0)) & (
                intrinsic > 0.0)
        return eep, pinned

    eep_p, pin_p = panel(False, 0.04, 0.0)
    eep_c, pin_c = panel(True, R0, Q0)

    # Boundary macros at t = 0.5y: first strike (% spot) inside the dead zone.
    row = int(np.argmin(np.abs(mats - 0.5)))
    kp = 100.0 * strikes[pin_p[row]].min() / S0 if pin_p[row].any() else float("nan")
    kc = 100.0 * strikes[pin_c[row]].max() / S0 if pin_c[row].any() else float("nan")
    macro("deamstmapputbdry", "%.0f", kp)
    macro("deamstmapcallbdry", "%.0f", kc)
    macro("deamstmapputeep", "%.1f", eep_p[row].max())

    fig, axes = plt.subplots(1, 2, figsize=(7.6, 3.5), sharey=True)
    vmax = max(eep_p.max(), eep_c.max())
    for ax, eep, pin, title_lab, letter in (
        (axes[0], eep_p, pin_p, "put", "A"),
        (axes[1], eep_c, pin_c, "call", "B"),
    ):
        pc = ax.pcolormesh(KK, TT, eep, cmap="BuGn", vmin=0.0, vmax=vmax,
                           shading="auto", rasterized=True)
        ax.contour(KK, TT, pin.astype(float), levels=[0.5], colors=[RUST],
                   linewidths=1.6)
        ax.set_xlabel("strike (% of spot)")
        label_panel(ax, letter)
        ax.grid(False)
    axes[0].set_ylabel("time to expiry $t$ (years)")
    axes[0].annotate("price $=$ intrinsic:\nexercise now,\nno root exists",
                     xy=(138, 0.75), xytext=(72, 0.95), color=PALETTE["ink"],
                     fontsize=9, ha="left",
                     arrowprops={"arrowstyle": "->", "color": SLATE, "lw": 1.1})
    axes[1].annotate("dividends pull the\nboundary onto\ndeep ITM calls",
                     xy=(66, 0.75), xytext=(94, 0.95), color=PALETTE["ink"],
                     fontsize=9, ha="left",
                     arrowprops={"arrowstyle": "->", "color": SLATE, "lw": 1.1})
    cb = fig.colorbar(pc, ax=axes, pad=0.015, fraction=0.035)
    cb.set_label(r"early-exercise premium $\pi$ (dollars)", fontsize=10)
    save(fig, OUT / "fig_deamst_map.pdf")


# ---------------------------------------------------------------------------
# Figure 4: the root find, well-posed and failing, on American puts.
# ---------------------------------------------------------------------------


def figure_root() -> None:
    r, q, t = 0.04, 0.0, 0.5
    sigmas = np.linspace(0.02, 1.0, 50)
    cases = [(90.0, TEAL, "OTM put, $K=90$"), (105.0, BLUE, "ITM put, $K=105$"),
             (140.0, RUST, "deep ITM put, $K=140$")]
    fig, ax = plt.subplots(figsize=(6.9, 4.1))
    for k, col, lab in cases:
        prices = np.array([binomial_price(False, S0, k, t, float(v), r, q,
                                          american=True) for v in sigmas])
        ax.plot(100 * sigmas, prices, color=col, label=lab)
        quote = binomial_price(False, S0, k, t, SIG0, r, q, american=True)
        if k < 130:
            ax.plot([100 * SIG0], [quote], "o", ms=6, color=col)
            ax.axhline(quote, color=col, ls=":", lw=0.9, alpha=0.55)
    intr = 140.0 - S0
    ax.axhline(intr, color=RUST, ls=":", lw=0.9, alpha=0.55)
    ax.annotate("a quote AT the intrinsic floor:\nno $\\sigma$ reaches it from above"
                "\n$\\Rightarrow$ NaN lane, premium $= 0$",
                xy=(11, intr + 2.2), color=RUST, fontsize=9)
    ax.annotate("roots $\\sigma^*$ at the quotes", xy=(100 * SIG0, 6.4),
                xytext=(42, 10.5), textcoords="data", fontsize=9, color=SLATE,
                arrowprops={"arrowstyle": "->", "color": SLATE, "lw": 1.1})
    ax.set_xlabel(r"volatility $\sigma$ (%)")
    ax.set_ylabel(r"American tree price $A_N(\sigma)$ (dollars)")
    ax.set_ylim(0, 55)
    ax.legend(loc="center right", fontsize=9.5)
    save(fig, OUT / "fig_deamst_root.pdf")


# ---------------------------------------------------------------------------
# Figure 5: control-variate cancellation and the depth budget.
# ---------------------------------------------------------------------------


def pipeline_iv(is_call: bool, a_mkt: float, s: float, k: float, t: float,
                r: float, q: float, n: int) -> tuple[float, float]:
    """The full de-Am arithmetic at depth ``n`` on one quote, exactly as the
    pipeline composes it: root sigma*, model EEP at sigma*, subtract, invert
    the shifted price through the analytic Black formula.  Returns
    (sigma*, reported iv)."""
    f = s * float(np.exp((r - q) * t))
    d = float(np.exp(-r * t))
    sig = deamericanize(is_call, a_mkt, s, k, t, r, q, n_steps=n)
    e_n = binomial_price(is_call, s, k, t, sig, r, q, n_steps=n, american=False)
    eep = max(a_mkt - e_n, 0.0)
    logm = float(np.log(k / f))
    shift = 0.0 if is_call else 1.0 - float(np.exp(logm))
    w = implied_total_variance(np.array([logm]),
                               np.array([(a_mkt - eep) / (d * f) + shift]))[0]
    return sig, float(np.sqrt(w / t))


def figure_cancel() -> None:
    k = 90.0  # the worked-example strike (ITM call, dividend magnet)
    depths = np.array([24, 32, 48, 64, 96, 128, 192, 256, 384, 501, 768, 1024])
    n_ref = 4001
    a_ref = binomial_price(True, S0, k, T0, SIG0, R0, Q0, n_steps=n_ref,
                           american=True)
    root_bp, iv_bp = [], []
    for n in depths:
        sig, iv = pipeline_iv(True, a_ref, S0, k, T0, R0, Q0, int(n))
        root_bp.append(1e4 * abs(sig - SIG0))
        iv_bp.append(1e4 * abs(iv - SIG0))
    root_bp, iv_bp = np.array(root_bp), np.array(iv_bp)
    i192 = int(np.flatnonzero(depths == 192)[0])
    i501 = int(np.flatnonzero(depths == 501)[0])
    macro("deamstdepthbp", "%.1f", iv_bp[i192])
    macro("deamstdepthbpscalar", "%.2f", iv_bp[i501])
    macro("deamstrootbp", "%.1f", root_bp[i192])
    NUMBERS["depth_arrays"] = {"depths": depths.tolist(),
                               "root_bp": root_bp.tolist(), "iv_bp": iv_bp.tolist()}

    # Panel B: the same end-to-end error across the whole strike range,
    # aggregated per depth (batch 192, its rejected cheaper cut 128, scalar).
    strikes = np.linspace(88, 120, 17)
    depth_grid = (96, 128, 192, 256, 384, 501)
    med, mx = [], []
    for n in depth_grid:
        errs = []
        for kk in strikes:
            a_m = binomial_price(True, S0, float(kk), T0, SIG0, R0, Q0,
                                 n_steps=n_ref, american=True)
            _, iv = pipeline_iv(True, a_m, S0, float(kk), T0, R0, Q0, n)
            errs.append(1e4 * abs(iv - SIG0))
        errs = np.array(errs)
        med.append(float(np.median(errs)))
        mx.append(float(errs.max()))
    macro("deamstdepthshift", "%.0f", mx[list(depth_grid).index(128)])
    macro("deamstdepthmax", "%.1f", mx[list(depth_grid).index(192)])

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    guide = iv_bp[0] * depths[0] / depths
    ax.loglog(depths, guide, color=PALETTE["grid"], lw=1.4, zorder=1)
    ax.annotate("$O(1/N)$", xy=(float(depths[-3]), float(guide[-3])),
                xytext=(2, 6), textcoords="offset points", fontsize=8.5,
                color=SLATE)
    ax.loglog(depths, np.maximum(iv_bp, 1e-3), "o", ms=5, color=RUST,
              label="reported quote (carries the European-leg gap)")
    ax.loglog(depths, np.maximum(root_bp, 1e-3), "s", ms=4.2, color=TEAL,
              label=r"root $\sigma^*$ (level error only)")
    for n, tag in ((192, "batch"), (501, "scalar")):
        i = int(np.flatnonzero(depths == n)[0])
        ax.plot([n], [max(iv_bp[i], 1e-3)], "o", ms=9, mfc="none", mec=SLATE)
        ax.annotate(tag, xy=(n, max(iv_bp[i], 1e-3)), xytext=(0, 10),
                    ha="center", textcoords="offset points", fontsize=8.5,
                    color=SLATE)
    ax.set_xlabel("tree depth $N$")
    ax.set_ylabel("error at $K=90$ (vol bp)")
    ax.legend(loc="lower left", fontsize=8.5, handletextpad=0.4)
    ax.set_ylim(6e-4, 60)
    label_panel(ax, "A")
    ax = axes[1]
    xs = np.arange(len(depth_grid))
    ax.bar(xs - 0.2, med, width=0.38, color=TEAL, label="median over strikes")
    ax.bar(xs + 0.2, mx, width=0.38, color=RUST, alpha=0.85, label="worst strike")
    ax.set_xticks(xs, [str(n) for n in depth_grid])
    ax.set_xlabel("tree depth $N$")
    ax.set_ylabel(r"$|$reported $-$ true$|$ (vol bp)")
    ax.legend(loc="upper right", fontsize=9)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_deamst_cancel.pdf")


# ---------------------------------------------------------------------------
# Figure 6: what the tree's carry actually is — cash schedule vs yield.
# ---------------------------------------------------------------------------


def figure_escrow() -> None:
    ref = date(2026, 6, 25)
    r, t = 0.04, 0.75
    model = DividendModel(mode="discrete_absolute",
                          dividends=(Dividend(ref + timedelta(days=128), 3.0),))
    tau_ex = 128 / 365.0
    f_theo = theoretical_forward(S0, r, t, model, ref)
    # A market forward 15 bp of carry under the forecast's: the cash amounts bend.
    f_mkt = f_theo * float(np.exp(-0.0015 * t))
    sched = forward_consistent_cash_schedule(S0, f_mkt, r, t, model, ref)
    assert sched is not None
    div_t, div_a = sched
    macro("deamstalpha", "%.3f", div_a[0] / 3.0)
    q_eq = equivalent_yield(S0, f_mkt, r, t)

    strikes = np.linspace(70.0, 115.0, 24)

    def eep_curve(**kw) -> np.ndarray:
        am = np.array([binomial_price(True, S0, float(k), t, SIG0, r,
                                      american=True, **kw) for k in strikes])
        eu = np.array([binomial_price(True, S0, float(k), t, SIG0, r,
                                      american=False, **kw) for k in strikes])
        return am - eu

    eep_cash = eep_curve(q=0.0, div_times=div_t, div_amounts=div_a)
    eep_yield = eep_curve(q=q_eq)
    deep = eep_yield > 0.05
    macro("deamstescrowratio", "%.1f", float(np.max(eep_cash[deep] / eep_yield[deep])))

    mats = np.linspace(0.08, t, 28)
    k_itm = 90.0
    e_cash, e_yield = [], []
    for tm in mats:
        f_m = theoretical_forward(S0, r, float(tm), model, ref)
        sch = forward_consistent_cash_schedule(S0, f_m, r, float(tm), model, ref)
        kw = ({"q": 0.0, "div_times": sch[0], "div_amounts": sch[1]}
              if sch is not None else {"q": 0.0})
        am = binomial_price(True, S0, k_itm, float(tm), SIG0, r, american=True, **kw)
        eu = binomial_price(True, S0, k_itm, float(tm), SIG0, r, american=False, **kw)
        e_cash.append(am - eu)
        qe = equivalent_yield(S0, f_m, r, float(tm))
        am = binomial_price(True, S0, k_itm, float(tm), SIG0, r, q=qe, american=True)
        eu = binomial_price(True, S0, k_itm, float(tm), SIG0, r, q=qe, american=False)
        e_yield.append(am - eu)

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.plot(strikes, eep_cash, color=TEAL, label="discrete cash schedule ($q=0$)")
    ax.plot(strikes, eep_yield, color=AMBER, ls="--", label="continuous-yield fallback")
    ax.set_xlabel("strike $K$")
    ax.set_ylabel(r"$\pi = A - E$ (dollars)")
    ax.legend(loc="upper right", fontsize=9)
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(mats, e_cash, color=TEAL, label="discrete cash schedule")
    ax.plot(mats, e_yield, color=AMBER, ls="--", label="continuous-yield fallback")
    ax.axvline(tau_ex, color=SLATE, ls=":", lw=1.1)
    ax.annotate("ex-date", xy=(tau_ex, 0.04), xycoords=("data", "axes fraction"),
                xytext=(-42, 0), textcoords="offset points", color=SLATE, fontsize=9)
    ax.set_xlabel("expiry $t$ (years)")
    ax.set_ylabel(r"$\pi$ at $K=90$ (dollars)")
    ax.set_ylim(-0.08, 2.55)
    ax.legend(loc="upper right", fontsize=9)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_deamst_escrow.pdf")


# ---------------------------------------------------------------------------
# Figure 7: the wing-only, band-constrained convexity repair (production).
# ---------------------------------------------------------------------------


def listing_min_butterfly(K: np.ndarray, C: np.ndarray) -> float:
    """The Appendix D listing, verbatim (verified against production below)."""
    a, b = K[1:-1] - K[:-2], K[2:] - K[1:-1]
    fly = C[:-2] * b - C[1:-1] * (a + b) + C[2:] * a
    return (fly / (a + b)).min()


def listing_convex_fit(u: np.ndarray, c: np.ndarray, slope_floor: float) -> np.ndarray:
    """The Appendix D listing, verbatim (verified against production below)."""
    from scipy.optimize import lsq_linear
    cols = [u] + [np.maximum(u - u[j], 0.0) for j in range(1, len(u) - 1)]
    A = np.column_stack(cols)
    lb = np.zeros(A.shape[1]); lb[0] = slope_floor
    x = lsq_linear(A, c - c[0], bounds=(lb, np.inf)).x
    return c[0] + A @ x


def figure_convex() -> None:
    """The wing-only, band-constrained repair on a controlled illiquid wing.

    The real fixture cannot stage this demo: its synthesized delayed-tier
    quotes carry tick-wide spreads (~3e-5 normalized), an order below the
    CONVEX_TOL gate — the liquid no-op regime.  So the mechanism demo is a
    constructed smile with realistic ILLIQUID wing spreads (the -1e-3..-3e-2
    regime the production gate was calibrated on) and a one-sided clamp-scale
    perturbation, repaired by the PRODUCTION projection."""
    from volfit.core.black import black_call

    t = 0.5
    # A smooth skewed smile in normalized units (F = 1); local formula only
    # defines the synthetic truth — pricing and repair are production calls.
    core_k = np.arange(-0.15, 0.121, 0.03)
    wing_k = np.array([-0.55, -0.47, -0.40, -0.34, -0.29, -0.25, -0.215, -0.185])
    k = np.concatenate([wing_k, core_k])
    iv = 0.22 - 0.28 * k + 0.10 * k * k
    c_true = black_call(k, iv * iv * t)
    w_atm = float(0.22**2 * t)
    z = k / np.sqrt(w_atm)
    wing = z < -1.0

    # Illiquid-regime band: tight core, wide sparse wing; then the max(EEP,0)
    # clamp footprint — one-sided UP bumps on alternating wing strikes (an
    # under-estimated premium leaves the shifted price too high).
    half = np.where(wing, 2.2e-3, 2.5e-4)
    c_lo, c_hi = c_true - half, c_true + half
    bump = np.where(wing & (np.arange(k.size) % 2 == 0), 0.85 * half, 0.0)
    c_pert = np.clip(c_true + bump, c_lo, c_hi)

    K = np.exp(k)

    def fly_curve(c: np.ndarray) -> np.ndarray:
        a_, b_ = K[1:-1] - K[:-2], K[2:] - K[1:-1]
        return (c[:-2] * b_ - c[1:-1] * (a_ + b_) + c[2:] * a_) / (a_ + b_)

    before = min_norm_butterfly(K, c_pert)
    repaired = convex_wing_repair(k, c_pert, c_lo, c_hi, w_atm, 1.0)
    if repaired is None:
        raise RuntimeError("repair did not engage (min butterfly %.2e)" % before)
    after = min_norm_butterfly(K, repaired)
    core = ~wing
    core_move = float(np.max(np.abs((repaired - c_pert)[core])))
    in_band = bool(np.all(repaired >= c_lo - 1e-12) and np.all(repaired <= c_hi + 1e-12))

    w_pert = implied_total_variance(k, c_pert)
    w_rep = implied_total_variance(k, repaired)
    iv_pert, iv_rep = np.sqrt(w_pert / t), np.sqrt(w_rep / t)
    iv_lo = np.sqrt(implied_total_variance(k, c_lo) / t)
    iv_hi = np.sqrt(implied_total_variance(k, c_hi) / t)
    macro("deamstcvxbefore", "%.1f", 1e3 * before)
    ex = int(np.floor(np.log10(abs(after)))) if after != 0.0 else 0
    macro("deamstcvxaftermant", "%.1f", after / 10.0**ex)
    macro("deamstcvxafterexp", "%d", ex)
    macro("deamstcvxmove", "%.0f", 1e4 * float(np.nanmax(np.abs(iv_rep - iv_pert))))
    macro("deamstcvxcore", "%.0f", core_move)
    macro("deamstcvxinband", "%s", "yes" if in_band else "NO")

    # Appendix D verification: the two listings against production, same inputs.
    d_fly = abs(listing_min_butterfly(K, c_pert) - before)
    anchor = int(np.flatnonzero(core)[0])
    u = (K[anchor] - K[: anchor + 1])[::-1]
    cw = c_pert[: anchor + 1][::-1]
    sl = convex_deam._core_slope(K, c_pert, anchor, +1)
    d_fit = float(np.max(np.abs(listing_convex_fit(u, cw, -sl)
                                - convex_deam._repair_wing(u, cw, -sl))))
    macro("deamstrefagree", "%.0f", np.floor(np.log10(max(d_fly, d_fit, 1e-16))))

    pctm = 100.0 * K
    show = pctm < 94.0
    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    ax.fill_between(pctm[show], 100 * iv_lo[show], 100 * iv_hi[show], color=SLATE,
                    alpha=0.16, lw=0, label="bid–ask band")
    ax.plot(pctm[show], 100 * iv_pert[show], "o-", ms=3.8, lw=1.2, color=RUST,
            label="de-Am mid, clamp footprint")
    ax.plot(pctm[show], 100 * iv_rep[show], "-", lw=2.0, color=TEAL,
            label="repaired (wing-only projection)")
    zb = 100.0 * float(np.exp(-np.sqrt(w_atm)))
    ax.axvline(zb, color=SLATE, ls=":", lw=1.1)
    ax.annotate("core boundary\n$z=-1$", xy=(zb, 0.42),
                xycoords=("data", "axes fraction"), xytext=(5, 0),
                textcoords="offset points", fontsize=8.5, color=SLATE)
    ax.set_xlabel("strike (% of forward)")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(loc="upper right", fontsize=8.5)
    label_panel(ax, "A")
    ax = axes[1]
    ax.axhspan(-1.0, 0.0, color=RUST, alpha=0.07, lw=0)
    ax.axhline(0.0, color=PALETTE["ink"], lw=0.8)
    ax.axhline(-1.0, color=RUST, lw=0.9, ls="--", alpha=0.7)
    ax.annotate("repair gate $10^{-3}$", xy=(0.02, 0.13), xycoords="axes fraction",
                fontsize=8.5, color=RUST)
    ax.plot(pctm[1:-1], 1e3 * fly_curve(c_pert), "o", ms=4.2, color=RUST,
            label="before")
    ax.plot(pctm[1:-1], 1e3 * fly_curve(repaired), "s", ms=3.8, color=TEAL,
            label="after")
    ax.set_xlabel("strike (% of forward)")
    ax.set_ylabel(r"normalized butterfly ($\times 10^{-3}$)")
    ax.legend(loc="lower right", fontsize=9)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.3)
    save(fig, OUT / "fig_deamst_convex.pdf")


# ---------------------------------------------------------------------------
# Figures 8+9: the real chain, two populations (as gen_deam_real, restyled).
# ---------------------------------------------------------------------------


def figure_real(snap, s, f, d, t) -> None:
    puts = two_sided(snap, EXPIRY, side="P")
    ks = np.array([p.strike for p in puts])
    mids = np.array([p.mid for p in puts])
    keep = (ks >= 0.55 * s) & (ks <= 1.38 * s)
    ks, mids = ks[keep], mids[keep]
    is_call = np.zeros(ks.size, dtype=bool)
    deam = deamericanize_batch(is_call, mids, s, ks, t, R, Q)
    naive = naive_black_iv(is_call, mids, ks, f, d, t)
    ok = np.isfinite(deam) & np.isfinite(naive)
    ks, deam, naive = ks[ok], deam[ok], naive[ok]
    pct = 100.0 * ks / s
    bias_bp = 1e4 * (naive - deam)
    itm = pct > 100.0
    macro("deamstrealmedianitm", "%.0f", np.median(bias_bp[itm]))
    macro("deamstrealmaxbias", "%.0f", bias_bp.max())
    macro("deamstrealnputs", "%d", ks.size)
    macro("deamstrealnitm", "%d", int(itm.sum()))

    fig, ax = plt.subplots(figsize=(6.9, 4.2))
    ax.fill_between(pct, 100 * deam, 100 * naive, where=pct >= 100.0,
                    color=RUST, alpha=0.10, lw=0)
    ax.plot(pct, 100 * naive, color=RUST, lw=1.8,
            label="American mid inverted as European — biased")
    ax.plot(pct, 100 * deam, color=TEAL, ls="--", lw=2.0,
            label=r"de-Americanized $\sigma^*$ — European-equivalent")
    ax.axvline(100.0, color=SLATE, ls=":", lw=1.1, alpha=0.8)
    ax.annotate("ATM", xy=(100.0, 0.02), xycoords=("data", "axes fraction"),
                xytext=(3, 0), textcoords="offset points", color=SLATE, fontsize=9)
    i = int(np.argmin(np.abs(pct - 124.0)))
    ax.annotate(
        "the wedge = model-implied IV effect of $\\pi$\n"
        "on ITM puts production DISCARDS\n(median +%.0f bp, max +%.0f bp)"
        % (float(np.median(bias_bp[itm])), float(bias_bp.max())),
        xy=(pct[i], 50 * (naive[i] + deam[i])), xytext=(-192, 40),
        textcoords="offset points", color=PALETTE["ink"], fontsize=9,
        arrowprops={"arrowstyle": "-", "color": SLATE, "lw": 0.9},
    )
    ax.set_xlabel("put strike (% of spot)")
    ax.set_ylabel("implied volatility (%)")
    lo_y, hi_y = ax.get_ylim()
    ax.set_ylim(lo_y, hi_y + 0.05 * (hi_y - lo_y))
    ax.legend(frameon=False, loc="upper left", fontsize=9)
    fig.tight_layout()
    save(fig, OUT / "fig_deamst_real.pdf")


def figure_real_selected(snap, s, f, d, t) -> None:
    tick_floor = 3.0 * snap.tick_size if getattr(snap, "tick_size", None) else 0.0
    qs = [x for x in two_sided(snap, EXPIRY)
          if x.call_put == ("C" if x.strike >= f else "P") and x.mid > tick_floor]
    ks = np.array([x.strike for x in qs])
    mids = np.array([x.mid for x in qs])
    is_call = np.array([x.call_put == "C" for x in qs])
    # The liquid no-op regime of the convex gate: this fixture's normalized
    # spreads are tick-wide, an order below the 1e-3 repair tolerance.
    spread_norm = float(np.median(
        [(x.ask - x.bid) for x in qs])) / (d * f)
    ex = int(np.floor(np.log10(spread_norm)))
    macro("deamstliqmant", "%.1f", spread_norm / 10.0**ex)
    macro("deamstliqexp", "%d", ex)
    deam = deamericanize_batch(is_call, mids, s, ks, t, R, Q)
    naive = naive_black_iv(is_call, mids, ks, f, d, t)
    ok = np.isfinite(deam) & np.isfinite(naive)
    ks, is_call, deam, naive = ks[ok], is_call[ok], deam[ok], naive[ok]
    k_log = np.log(ks / f)
    w_atm = float(np.interp(0.0, k_log, deam**2 * t))
    wing = np.abs(k_log) <= 4.0 * np.sqrt(w_atm)
    ks, is_call, deam, naive = ks[wing], is_call[wing], deam[wing], naive[wing]
    pct = 100.0 * ks / s
    bias_bp = 1e4 * (naive - deam)
    puts, calls = bias_bp[~is_call], bias_bp[is_call]
    # The depth caution, measured on the fitted population: batch trees at 128
    # steps vs the shipped 192 (same bracketing, same bisections).
    d128 = deamericanize_batch(is_call, mids[ok][wing], s, ks, t, R, Q, n_steps=128)
    d192 = deamericanize_batch(is_call, mids[ok][wing], s, ks, t, R, Q, n_steps=192)
    both = np.isfinite(d128) & np.isfinite(d192)
    shift = 1e4 * np.abs(d128 - d192)[both]
    macro("deamstdepthrealmed", "%.0f", np.median(shift))
    macro("deamstdepthrealmax", "%.0f", shift.max())
    macro("deamstseln", "%d", ks.size)
    macro("deamstselabsmedian", "%.1f", np.median(np.abs(bias_bp)))
    macro("deamstselmax", "%.0f", bias_bp.max())
    macro("deamstselputmedian", "%.0f", np.median(puts))
    macro("deamstselputmax", "%.0f", puts.max())
    macro("deamstselcallmedian", "%.1f", np.median(calls))
    macro("deamstselcallmax", "%.1f", calls.max())

    fig, ax = plt.subplots(figsize=(6.9, 3.9))
    ax.plot(pct[~is_call], puts, "o", ms=4.5, color=TEAL,
            label="selected OTM puts (below $F$)")
    ax.plot(pct[is_call], calls, "s", ms=4.0, color=BLUE,
            label="selected OTM calls (above $F$)")
    ax.axvline(100.0 * f / s, color=SLATE, ls=":", lw=1.1, alpha=0.8)
    ax.annotate("$F$", xy=(100.0 * f / s, 0.9), xycoords=("data", "axes fraction"),
                xytext=(3, 0), textcoords="offset points", color=SLATE, fontsize=9)
    ax.annotate(
        "the fitted population: median $|$effect$|$ %.1f bp, max %.0f bp"
        % (float(np.median(np.abs(bias_bp))), float(bias_bp.max())),
        xy=(0.03, 0.86), xycoords="axes fraction", color=PALETTE["ink"], fontsize=9)
    ax.set_xlabel("strike (% of spot)")
    ax.set_ylabel("naive $-$ de-Am implied vol (vol bp)")
    ax.legend(frameon=False, loc="center left", fontsize=9)
    fig.tight_layout()
    save(fig, OUT / "fig_deamst_realsel.pdf")


# ---------------------------------------------------------------------------


def main() -> None:
    figure_bias_and_vega()
    print("bias/vega done")
    figure_map()
    print("map done")
    figure_root()
    print("root done")
    figure_cancel()
    print("cancel done")
    figure_escrow()
    print("escrow done")
    figure_convex()
    print("convex done")

    data, chains = load_benchmark(FIXTURE)
    ref = date.fromisoformat(data["as_of"])
    snap = chains["SPY"]
    s = float(snap.spot)
    t = (EXPIRY - ref).days / 365.0
    f = s * float(np.exp((R - Q) * t))
    d = float(np.exp(-R * t))
    figure_real(snap, s, f, d, t)
    figure_real_selected(snap, s, f, d, t)
    print("real done")

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("deamstgencommit", "%s", commit)
    macro("deamstgendate", "%s", date.today().isoformat())
    macro("deamstscalarsteps", "%d", DEFAULT_STEPS)

    (OUT / "deam_stopping_tables.tex").write_text("\n".join(MACROS) + "\n",
                                                  encoding="utf-8")
    (OUT / "deam_stopping_numbers.json").write_text(
        json.dumps(NUMBERS, indent=2), encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
