"""Figures for Note 14 (graph smile-extrapolation).

A real run of the production graph solver: a calendar chain of nodes, one lit
node observing an innovation, propagated to the dark nodes via the increment
prior + Gaussian conditioning. Shows the posterior increment decaying along the
graph with a widening credible band, and the effect of the directed-smoothness
weight eta.

  fig_graph_prop.pdf    propagated increment + credible band
  fig_graph_eta.pdf     propagation range vs directed-smoothness eta
  graph_tables.tex      \\input-able macros
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from volfit.graph.build import build_graph
from volfit.graph.posterior import posterior_update
from volfit.graph.prior import build_increment_prior

OUT = Path(__file__).resolve().parent
plt.rcParams.update(
    {
        "figure.figsize": (7.2, 4.3),
        "font.size": 11,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "lines.linewidth": 1.8,
        "savefig.bbox": "tight",
        "savefig.dpi": 200,
    }
)
TEAL, RUST, SLATE, AMBER = "#0f766e", "#b91c1c", "#334155", "#b45309"


def chain_graph(n=7):
    nodes = [f"T{i}" for i in range(n)]
    weights = {}
    for i in range(n - 1):
        weights[(nodes[i], nodes[i + 1])] = 1.0   # T_{i+1} informs T_i
        weights[(nodes[i + 1], nodes[i])] = 1.0   # T_i informs T_{i+1}
    return build_graph(nodes, weights), nodes


def solve(eta, kappa=0.05):
    graph, nodes = chain_graph()
    n = graph.n_nodes
    prior = build_increment_prior(graph, kappa=kappa, eta=eta)
    baseline = np.zeros(n)
    baseline_precision = np.full(n, 0.1)          # weak baseline (dark nodes uncertain)
    observed = np.array([0])                       # one lit node at the front
    observations = np.array([1.0])                 # unit innovation
    observation_precision = np.array([200.0])      # tightly observed
    post = posterior_update(prior, baseline, baseline_precision,
                            observed, observations, observation_precision)
    return post, n


def main():
    post, n = solve(eta=8.0)
    idx = np.arange(n)
    lo, hi = post.credible_band()

    fig, ax = plt.subplots()
    ax.fill_between(idx, lo, hi, color=TEAL, alpha=0.15, label="95\\% credible band")
    ax.plot(idx, post.mean, "-o", color=TEAL, label="posterior increment")
    ax.scatter([0], [post.mean[0]], s=80, color=RUST, zorder=6, label="lit node (observed)")
    ax.axhline(0, color="black", lw=0.7)
    ax.set_xlabel("calendar node (dark $\\to$)")
    ax.set_ylabel("propagated increment $z_i$")
    ax.set_title("A lit innovation flows to dark nodes, decaying with uncertainty",
                 fontsize=10)
    ax.legend(frameon=False, fontsize=9)
    fig.savefig(OUT / "fig_graph_prop.pdf")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7.2, 3.8))
    for eta, c in [(2.0, AMBER), (8.0, TEAL), (20.0, SLATE)]:
        p, _ = solve(eta)
        ax.plot(np.arange(n), p.mean, "-o", color=c, label=fr"$\eta={eta:g}$")
    ax.axhline(0, color="black", lw=0.7)
    ax.set_xlabel("calendar node")
    ax.set_ylabel("propagated increment $z_i$")
    ax.set_title(r"Stronger directed smoothness $\eta$ propagates farther", fontsize=10)
    ax.legend(frameon=False)
    fig.savefig(OUT / "fig_graph_eta.pdf")
    plt.close(fig)

    far = post.mean[-1] / post.mean[0]
    L = ["% Auto-generated by gen_graph.py — do not edit."]
    L.append(r"\newcommand{\graphdecay}{%.0f}" % (100 * far))
    L.append(r"\newcommand{\graphfarprec}{%.2f}" % post.marginal_precision[-1])
    L.append(r"\newcommand{\graphlitprec}{%.2f}" % post.marginal_precision[0])
    (OUT / "graph_tables.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("increment decay lit->far %.0f%%; precision lit %.2f far %.2f"
          % (100 * far, post.marginal_precision[0], post.marginal_precision[-1]))


if __name__ == "__main__":
    main()
