"""Figure suite for the flat-directions edition of Note 13 (prior persistence).

Run from the repository root with the project virtual environment::

    .venv\\Scripts\\python.exe Docs\\notes\\figures\\gen_prior_flat.py

Every fit, gate, support number and reconstruction is produced by PRODUCTION
machinery (``volfit.calib.{precision,operators,factors,prior}`` and the LQD
calibrator); the temporal-backtest panel reads the STORED artifact
``backend/backtest/results/spike_aug2024_temporal_prior.json`` (never re-run).
The running character is the real SPY 2026-12-18 node of the standing export
``tmp/volfit_surfaces_20260718_1324.json`` (quotes embedded).

Outputs, written next to this script:

* ``fig_pfl_flat.pdf``       -- the flat directions: an ensemble of equally
                                good market-only fits + the support profile;
* ``fig_pfl_gate.pdf``       -- the gate and its dead zone vs ridge shrinkage;
* ``fig_pfl_basket.pdf``     -- harmonic support: coverage sweep + dead leg;
* ``fig_pfl_level.pdf``      -- the coordinates demo: operator vs strike
                                anchor across a level jump (case file 1);
* ``fig_pfl_activation.pdf`` -- both gating mechanisms on the SPY node;
* ``fig_pfl_hybrid.pdf``     -- hybrid's division of labour on the smile axis;
* ``fig_pfl_backtest.pdf``   -- the stored temporal adjudication by mode;
* ``fig_pfl_spy.pdf``        -- hero: real-node wing reconstruction;
* ``prior_flat_tables.tex`` / ``prior_flat_numbers.json``.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

OUT = Path(__file__).resolve().parent
sys.path.insert(0, str(OUT))
REPO = OUT.parents[2]
sys.path.insert(0, str(REPO / "backend"))

from style import PALETTE, WIDE, callout, label_panel, save, setup  # noqa: E402

from volfit.calib.factors import build_factor_prior  # noqa: E402
from volfit.calib.operators import (  # noqa: E402
    OPERATOR_DELTAS,
    _operator_obs_info,
    _quote_support,
    build_operator_prior,
    delta_strike,
    hybrid_tail_deltas,
)
from volfit.calib.precision import activation_gap  # noqa: E402
from volfit.calib.prior import DEFAULT_DELTAS, build_prior_anchor  # noqa: E402
from volfit.calib.varswap import VarSwapTarget  # noqa: E402
from volfit.models.lqd.calibrate import calibrate_slice  # noqa: E402
from volfit.models.sigmoid.calibrate import calibrate_sigmoid  # noqa: E402
from volfit.models.svi_jw.calibrate import calibrate_svi  # noqa: E402

setup()
TEAL, RUST, AMBER, SLATE, VIOLET = (PALETTE["teal"], PALETTE["rust"],
                                    PALETTE["amber"], PALETTE["muted"],
                                    PALETTE["violet"])

MACROS: list[str] = ["% Auto-generated by gen_prior_flat.py — do not edit."]
NUMBERS: dict = {}


def macro(name: str, fmt: str, value) -> None:
    MACROS.append((r"\newcommand{\%s}{" + fmt + "}") % (name, value))
    NUMBERS[name] = float(value) if isinstance(value, (int, float, np.floating)) else value


def sci_macro(name: str, value: float) -> None:
    v = max(abs(value), 1e-17)
    e = int(np.floor(np.log10(v)))
    m = v / 10.0**e
    MACROS.append(r"\newcommand{\%s}{\ensuremath{%.1f\times10^{%d}}}" % (name, m, e))
    NUMBERS[name] = float(value)


# ---------------------------------------------------------------------------
# The running character: the real SPY 2026-12-18 node (quotes embedded).
# ---------------------------------------------------------------------------

FIXTURE = REPO / "tmp" / "volfit_surfaces_20260718_1324.json"
_DOC = json.loads(FIXTURE.read_text(encoding="utf-8"))
_SPY = next(tk for tk in _DOC["tickers"] if tk["ticker"] == "SPY")
_NODE = next(n for n in _SPY["nodes"] if n["expiry"] == "2026-12-18")
T = float(_NODE["t"])
CURVE_K = np.array([c["k"] for c in _NODE["curve"]])
CURVE_W = np.array([c["w"] for c in _NODE["curve"]])
_COLS = _NODE["inputs"]["preparedColumns"]
_PREP = np.array(_NODE["inputs"]["prepared"], dtype=float)
Q_K = _PREP[:, _COLS.index("k")]
Q_W = _PREP[:, _COLS.index("wMid")]
BAND = 0.10  # the "quoted this morning" band |k| <= BAND
IN = np.abs(Q_K) <= BAND
K_THIN, W_THIN = Q_K[IN], Q_W[IN]
K_OUT, W_OUT = Q_K[~IN], Q_W[~IN]


def prior_w(k):
    """The stored production fit of the node — the edition's prior object."""
    return np.interp(np.asarray(k, dtype=float), CURVE_K, CURVE_W)


def vol(w, t=T):
    return 100.0 * np.sqrt(np.maximum(np.asarray(w, dtype=float), 1e-12) / t)


OP_SET = ["ATM", "RR25", "BF25", "VarSwap"]  # shipped default operator set


# ---------------------------------------------------------------------------
# Figure 1: the flat directions (ensemble of market-only fits + support).
# ---------------------------------------------------------------------------


def figure_flat() -> None:
    kk = np.linspace(-0.42, 0.30, 320)
    fits = []
    for n_order in (4, 6, 8):  # one model family, degrees of freedom varied
        for reg in (0.0, 1e-6):
            f = calibrate_slice(K_THIN, W_THIN, T, n_order=n_order, reg_lambda=reg)
            fits.append(vol(f.slice.implied_w(kk)))
    fits.append(vol(calibrate_svi(K_THIN, W_THIN, T).raw.total_variance(kk)))
    fits.append(vol(calibrate_sigmoid(K_THIN, W_THIN, T, n_cores=2).implied_w(kk)))
    fits = np.array(fits)
    spread = fits.max(axis=0) - fits.min(axis=0)
    i_atm = int(np.argmin(np.abs(kk)))
    i_wing = int(np.argmin(np.abs(kk + 0.30)))
    macro("pflnfits", "%d", fits.shape[0])
    macro("pflspreadatmbp", "%.0f", 100 * spread[i_atm])
    macro("pflspreadwing", "%.1f", spread[i_wing])
    macro("pflnthin", "%d", K_THIN.size)
    macro("pflnout", "%d", K_OUT.size)

    support = _quote_support(K_THIN, None, kk, 0.06)

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.3, 1.0]})
    ax = axes[0]
    ax.axvspan(-BAND, BAND, color="black", alpha=0.05)
    for row in fits:
        ax.plot(kk, row, color=TEAL, lw=0.9, alpha=0.45)
    ax.scatter(K_THIN, vol(W_THIN), s=15, color="black", zorder=6,
               label="this morning's quotes")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.set_ylim(bottom=float(fits.min()) - 1.0)
    ytop = float(fits[:, : i_wing + 1].max()) + 2.5
    ax.set_ylim(top=ytop)
    ax.legend(loc="upper right")
    ybot = float(fits.min()) - 1.0
    callout(ax, "eight fits, one likelihood:\nindistinguishable where quoted",
            xy=(-0.02, float(fits[:, i_atm].mean()) + 0.4),
            xytext=(-0.41, ybot + 0.13 * (ytop - ybot)))
    label_panel(ax, "A")
    ax = axes[1]
    ax.plot(kk, support, color=SLATE, lw=1.8, label="quote support $s(k)$")
    ax.set_ylim(top=1.22 * float(support.max()))
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("effective quote count", color=SLATE)
    ax2 = ax.twinx()
    ax2.plot(kk, spread, color=RUST, lw=1.8)
    ax2.set_ylabel("ensemble spread (vol pts)", color=RUST)
    ax2.grid(False)
    ax2.spines["top"].set_visible(False)
    ax.legend(loc="upper center")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.46)
    save(fig, OUT / "fig_pfl_flat.pdf")


# ---------------------------------------------------------------------------
# Figure 2: the gate (production) and its dead zone vs ridge shrinkage.
# ---------------------------------------------------------------------------


def figure_gate() -> None:
    x = np.linspace(0.0, 2.0, 400)  # observation precision / required
    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    for gamma, c in ((0.5, AMBER), (1.0, TEAL), (2.0, VIOLET)):
        ax.plot(x, activation_gap(x, 1.0, gamma), color=c,
                label=fr"$\gamma={gamma}$")
    ax.axvline(1.0, color=SLATE, ls=":", lw=1.2)
    ax.annotate(r"$\pi=\pi_{\mathrm{req}}$", xy=(1.06, 0.48), fontsize=9.5,
                color=SLATE)
    ax.set_xlabel(r"observation precision $\pi/\pi_{\mathrm{req}}$")
    ax.set_ylabel(r"gate $g(\pi)$")
    ax.legend(loc="upper right")
    label_panel(ax, "A")

    ax = axes[1]
    lam0 = 0.6  # a visible prior precision
    ridge = lam0 / (lam0 + x)
    gated = lam0 * activation_gap(x, 1.0, 1.0) / (lam0 * activation_gap(x, 1.0, 1.0) + x)
    gated[x <= 0] = 1.0
    ax.plot(x, ridge, color=RUST, ls="--", lw=1.9, label="ridge (fixed prior precision)")
    ax.plot(x, gated, color=TEAL, lw=1.9, label="gated prior")
    ax.axvline(1.0, color=SLATE, ls=":", lw=1.2)
    callout(ax, "the dead zone: bias exactly 0,\nnot merely small",
            xy=(1.45, 0.012), xytext=(0.98, 0.42))
    callout(ax, "ridge still biases a\nwell-observed coordinate",
            xy=(1.6, float(lam0 / (lam0 + 1.6)) + 0.01), xytext=(0.62, 0.68))
    ax.set_xlabel(r"observation precision $\pi/\pi_{\mathrm{req}}$")
    ax.set_ylabel("share of posterior owned by the prior")
    ax.legend(loc="upper right")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_pfl_gate.pdf")


# ---------------------------------------------------------------------------
# Figure 3: harmonic support — coverage sweep and the dead leg.
# ---------------------------------------------------------------------------


def figure_basket() -> None:
    # Coverage sweep on the jump-market smile (tau = 0.5), the case-file
    # configuration: 13 quotes spread over a widening band, kernel b = 0.03.
    tau = SYN_TAU
    halfwidths = np.linspace(0.01, 0.30, 40)
    ops = ["ATM", "RR25", "BF25"]
    obs = {o: [] for o in ops}
    for hw in halfwidths:
        kq = np.linspace(-hw, hw, 13)
        tgt, _ = build_operator_prior(syn_prior_w, tau, tau, kq, None, 1.0,
                                      op_set=ops, required_precision=1e9,
                                      bandwidth=SYN_BW)
        got = {d["operator"]: d["obsPrecision"] for d in tgt.diagnostics}
        for o in ops:
            obs[o].append(got.get(o, np.nan))
    k_p = delta_strike(syn_prior_w, tau, 1.0 - OPERATOR_DELTAS["RR25"])
    macro("pflkptwofive", "%.2f", k_p)
    macro("pflkctwofivereal", "%.2f", delta_strike(prior_w, T, 0.25))
    macro("pflkptwofivereal", "%.2f", delta_strike(prior_w, T, 0.75))

    fig, axes = plt.subplots(1, 2, figsize=WIDE)
    ax = axes[0]
    for o, c in zip(ops, (SLATE, TEAL, AMBER)):
        ax.plot(halfwidths, obs[o], color=c, lw=1.9, label=o)
    ax.axhline(1.0, color=PALETTE["ink"], lw=0.7, ls=":")
    ax.annotate(r"$\pi_{\mathrm{req}}=1$", xy=(0.012, 1.35),
                fontsize=8.5, color=SLATE)
    ax.axvline(abs(k_p), color=AMBER, lw=0.8, ls=":")
    callout(ax, "coverage reaches the\n25$\\Delta$ put leg at $|k_p|$",
            xy=(abs(k_p), 0.3), xytext=(0.17, 0.012))
    ax.set_xlabel("quote coverage half-width (log-moneyness)")
    ax.set_ylabel(r"basket precision $\pi(O)$")
    ax.set_yscale("log")
    ax.set_ylim(1e-4, 3e2)
    ax.legend(loc="upper left")
    label_panel(ax, "A")

    ax = axes[1]
    s_put = np.linspace(0.0, 4.0, 200)
    rr = np.array([_operator_obs_info(np.array([1.0, -1.0]),
                                      np.array([4.0, sp])) for sp in s_put])
    bf = np.array([_operator_obs_info(np.array([0.5, 0.5, -1.0]),
                                      np.array([4.0, sp, 8.0])) for sp in s_put])
    ax.plot(s_put, rr, color=TEAL, lw=1.9, label="RR (call leg support 4)")
    ax.plot(s_put, bf, color=AMBER, lw=1.9, label="BF (call 4, ATM 8)")
    callout(ax, "one dead leg unidentifies\nthe whole basket",
            xy=(0.06, 0.06), xytext=(1.1, 1.25))
    ax.set_xlabel("put-leg quote support $s_p$")
    ax.set_ylabel(r"basket precision $\pi(O)$")
    ax.legend(loc="lower right")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_pfl_basket.pdf")


# ---------------------------------------------------------------------------
# Figure 4: the coordinates demo — a level jump, quoted only at the money
# (the runnable form of case file 1, production calibrator throughout).
# ---------------------------------------------------------------------------


def base_sigma(k):
    k = np.asarray(k, dtype=float)
    return 0.20 - 0.4 * k + 0.5 * k * k


# The controlled overnight-jump market (the runnable form of case file 1):
# yesterday's shape at yesterday's level; today the level jumps 4 vol points
# and only |k| <= 0.05 is quoted.
SYN_TAU, SYN_JUMP = 0.5, 0.04
SYN_K = np.linspace(-0.05, 0.05, 11)
SYN_BUDGET = 5.0 * SYN_K.size
SYN_BW = 0.03


def syn_prior_w(k):
    s = base_sigma(k)
    return s * s * SYN_TAU


SYN_W_TODAY = (base_sigma(SYN_K) + SYN_JUMP) ** 2 * SYN_TAU


def figure_level() -> None:
    tau, d_level, kw = SYN_TAU, SYN_JUMP, -0.10
    K, w_today, budget = SYN_K, SYN_W_TODAY, SYN_BUDGET
    prior_w_syn = syn_prior_w

    op, _ = build_operator_prior(prior_w_syn, tau, tau, K, None, budget,
                                 op_set=["ATM", "RR25", "BF25"], bandwidth=SYN_BW)
    fac, _ = build_factor_prior(prior_w_syn, tau, tau, K, None, budget,
                                factor_set=["skew", "curvature"], step=0.06,
                                bandwidth=SYN_BW)
    sg, _ = build_prior_anchor(prior_w_syn, tau, K, tau, budget,
                               deltas=(0.05, 0.10, 0.25))
    f_data = calibrate_slice(K, w_today, t=tau, n_order=6)
    f_op = calibrate_slice(K, w_today, t=tau, n_order=6, operator_prior=op)
    f_fac = calibrate_slice(K, w_today, t=tau, n_order=6, operator_prior=fac)
    f_sg = calibrate_slice(K, w_today, t=tau, n_order=6, prior_anchor=sg)

    def v(fit, k):
        return 100.0 * float(np.sqrt(max(fit.slice.implied_w(np.array([k]))[0], 1e-12) / tau))

    true_wing, old_wing = 100 * (base_sigma(kw) + d_level), 100 * base_sigma(kw)
    macro("pflopwingerr", "%.1f", abs(v(f_op, kw) - true_wing))
    macro("pflsgwingerr", "%.1f", abs(v(f_sg, kw) - true_wing))
    macro("pflsgoldgap", "%.1f", abs(v(f_sg, kw) - old_wing))
    kd = -0.20  # deeper in the unquoted wing, between the 10 and 5-delta anchors
    macro("pflopwingerrdeep", "%.1f", abs(v(f_op, kd) - 100 * (base_sigma(kd) + d_level)))
    macro("pflsgwingerrdeep", "%.1f", abs(v(f_sg, kd) - 100 * (base_sigma(kd) + d_level)))
    macro("pflatmopgap", "%.2f", abs(v(f_op, 0.0) - v(f_data, 0.0)))
    macro("pflatmfacgap", "%.2f", abs(v(f_fac, 0.0) - v(f_data, 0.0)))
    macro("pfljump", "%.0f", 100 * d_level)

    kk = np.linspace(-0.28, 0.20, 300)
    fig, ax = plt.subplots(figsize=(6.9, 4.1))
    ax.axvspan(K.min(), K.max(), color="black", alpha=0.05)
    ax.plot(kk, 100 * base_sigma(kk), color=SLATE, ls=":", lw=1.6,
            label="yesterday (the prior)")
    ax.plot(kk, 100 * (base_sigma(kk) + d_level), color=PALETTE["ink"], lw=1.1,
            label="today's truth (level lifted)")
    ax.plot(kk, [v(f_op, float(x)) for x in kk], color=TEAL, lw=2.0,
            label="operator prior (shape rows)")
    ax.plot(kk, [v(f_sg, float(x)) for x in kk], color=RUST, ls="--", lw=1.9,
            label="strike anchor (price rows)")
    ax.scatter(K, 100 * np.sqrt(w_today / tau), s=16, color="black", zorder=6)
    callout(ax, "shape rows ride\ntoday's level",
            xy=(-0.235, float(v(f_op, -0.235)) + 0.25), xytext=(-0.14, 38.1))
    callout(ax, "price rows cling to\nyesterday's absolute wing",
            xy=(-0.26, float(v(f_sg, -0.26)) - 0.3), xytext=(-0.298, 26.8))
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(loc="lower left", fontsize=8.7)
    save(fig, OUT / "fig_pfl_level.pdf")


# ---------------------------------------------------------------------------
# Figure 5: both gating mechanisms placing budget on the SPY node.
# ---------------------------------------------------------------------------


def _gate_row(k_quotes: np.ndarray) -> tuple[list, list, list]:
    """Per-operator (name, gap, lambda) under the shipped defaults, incl. the
    gated-off rows and the var-swap rec (production builders)."""
    op, vs = build_operator_prior(prior_w, T, T, k_quotes, None,
                                  0.5 * k_quotes.size, op_set=OP_SET)
    diags = {d["operator"]: d for d in (op.diagnostics if op else [])}
    names = [n for n in OP_SET if n != "VarSwap"] + ["VarSwap"]
    gaps = [diags.get(n, {"gap": 0.0})["gap"] for n in names[:-1]] + [vs.gap]
    lams = [diags.get(n, {"activeLambda": 0.0})["activeLambda"]
            for n in names[:-1]] + [vs.weight]
    return names, gaps, lams


def figure_activation() -> None:
    budget = 0.5 * K_THIN.size  # the shipped 50% budgets
    sg, unmet = build_prior_anchor(prior_w, T, K_THIN, T, budget)
    macro("pflunmet", "%.0f", 100 * unmet)
    K_SPARSE = K_THIN[:: max(K_THIN.size // 4, 1)]
    macro("pflnsparse", "%d", K_SPARSE.size)

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.25, 1.0]})
    ax = axes[0]
    ax.axvspan(-BAND, BAND, color="black", alpha=0.05)
    marker, stems, ba = ax.stem(sg.k, sg.weights)
    plt.setp(stems, color=TEAL, linewidth=2.4)
    plt.setp(marker, color=TEAL, markersize=6)
    plt.setp(ba, color=PALETTE["grid"], linewidth=0.8)
    ax.scatter(K_THIN, np.zeros_like(K_THIN), s=12, color="black", zorder=6,
               label="quotes (ATM band)")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("strike-anchor weight")
    ax.legend(loc="upper right")
    ax.text(0.0, 0.92 * sg.weights.max(),
            "quoted band:\nzero deficit,\nzero anchors", ha="center", va="top",
            fontsize=9.0, color=SLATE)
    label_panel(ax, "A")

    # Macros for the honesty section: on the real dense/sparse mornings the
    # support proxy closes every vol-operator gate (legs sit ~one bandwidth
    # from the quoted band on this node).
    names, gaps_d, _ = _gate_row(K_THIN)
    _, gaps_s, _ = _gate_row(K_SPARSE)
    short = {"ATM": "atm", "RR25": "rr", "BF25": "bf", "VarSwap": "vs"}
    for n, gd, gs in zip(names, gaps_d, gaps_s):
        macro("pflgapdense" + short[n], "%.2f", gd)
        macro("pflgapsparse" + short[n], "%.2f", gs)

    # Panel B: the gate doing its canonical job, on the jump market of case
    # file 1 (dense ATM quotes, dark wings): ATM off, wing operators on.
    ax = axes[1]
    op, vs = build_operator_prior(syn_prior_w, SYN_TAU, SYN_TAU, SYN_K, None,
                                  SYN_BUDGET, op_set=OP_SET, bandwidth=SYN_BW)
    diags = {d["operator"]: d for d in (op.diagnostics if op else [])}
    gaps = [diags.get(n, {"gap": 0.0})["gap"] for n in OP_SET[:-1]] + [vs.gap]
    lams = [diags.get(n, {"activeLambda": 0.0})["activeLambda"]
            for n in OP_SET[:-1]] + [vs.weight]
    cols = [SLATE if g <= 0 else RUST for g in gaps]
    ax.bar(np.arange(len(OP_SET)), gaps, color=cols, alpha=0.9)
    for i, (g, lam) in enumerate(zip(gaps, lams)):
        note = "off" if g <= 0 else fr"$\lambda={lam:.0f}$"
        ax.text(i, g + 0.04, note, ha="center", fontsize=9, color=PALETTE["ink"])
    ax.set_xticks(np.arange(len(OP_SET)))
    ax.set_xticklabels(OP_SET, fontsize=9.5)
    ax.set_ylim(0, 1.3)
    ax.set_ylabel(r"gate $g$ (0 = off, 1 = full pull)")
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.34)
    save(fig, OUT / "fig_pfl_activation.pdf")
    print("  real dense gaps:", dict(zip(names, np.round(gaps_d, 3))),
          "| real sparse gaps:", dict(zip(names, np.round(gaps_s, 3))),
          "| jump-market gaps:", np.round(gaps, 3))


# ---------------------------------------------------------------------------
# Figure 6: hybrid's division of labour on the smile axis.
# ---------------------------------------------------------------------------


def figure_hybrid() -> None:
    tail = hybrid_tail_deltas(OP_SET, DEFAULT_DELTAS)
    macro("pfltaildeltas", "%s", "/".join("%d" % round(100 * d) for d in tail))
    sg, _ = build_prior_anchor(prior_w, T, K_THIN, T, 0.2 * K_THIN.size,
                               deltas=tail)
    k_c = delta_strike(prior_w, T, 0.25)
    k_p = delta_strike(prior_w, T, 0.75)

    kk = np.linspace(-0.55, 0.35, 400)
    v = vol(prior_w(kk))
    vlo, vhi = float(v.min()), float(v.max())
    fig, ax = plt.subplots(figsize=(6.9, 4.0))
    ax.plot(kk, v, color=SLATE, lw=1.8, label="the prior smile")
    ax.axvspan(-BAND, BAND, color="black", alpha=0.06)
    legs = np.array([k_p, 0.0, k_c])
    ax.scatter(legs, vol(prior_w(legs)), s=64, marker="o", color=AMBER,
               zorder=6, label=r"operator legs (ATM, 25$\Delta$)")
    ax.scatter(sg.k, vol(prior_w(sg.k)), s=54, marker="D", color=TEAL,
               zorder=6, label="hybrid tail anchors")
    ax.annotate("quotes own\nthe level",
                xy=(0.0, vlo - 0.055 * (vhi - vlo)),
                ha="center", fontsize=9, color=PALETTE["ink"])
    callout(ax, "operators carry yesterday's\nshape onto today's level",
            xy=(k_p - 0.005, float(vol(prior_w(np.array([k_p])))[0])
                - 0.02 * (vhi - vlo)),
            xytext=(-0.38, vlo + 0.015 * (vhi - vlo)))
    callout(ax, "strike anchors hold the wing\nno operator reaches",
            xy=(float(sg.k.min()) + 0.005,
                float(vol(prior_w(np.array([float(sg.k.min())])))[0])
                + 0.015 * (vhi - vlo)),
            xytext=(-0.54, vlo + 0.52 * (vhi - vlo)))
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.set_ylim(vlo - 0.12 * (vhi - vlo), vhi + 0.10 * (vhi - vlo))
    ax.legend(loc="upper right", fontsize=8.7)
    save(fig, OUT / "fig_pfl_hybrid.pdf")


# ---------------------------------------------------------------------------
# Figure 7: the stored temporal adjudication (never re-run).
# ---------------------------------------------------------------------------


def figure_backtest() -> None:
    art = json.loads((REPO / "backend" / "backtest" / "results" /
                      "spike_aug2024_temporal_prior.json").read_text())
    modes = ["hybrid", "strike_gap", "quote_operator", "smile_factor"]
    colors = {"hybrid": TEAL, "strike_gap": AMBER,
              "quote_operator": VIOLET, "smile_factor": SLATE}
    impr = {m: np.sort([r["improvement_bp"] for r in art["rows"]
                        if r["mode"] == m and r["improvement_bp"] is not None])
            for m in modes}
    summ = {s["mode"]: s for s in art["summary"]}
    macro("pflbtnodes", "%d", summ["hybrid"]["n"])
    macro("pflhybimpr", "%.0f", summ["hybrid"]["median_improvement_bp"])
    macro("pflhybwin", "%.0f", 100 * summ["hybrid"]["win_rate"])
    macro("pflsgimpr", "%.0f", summ["strike_gap"]["median_improvement_bp"])
    macro("pflsgwin", "%.0f", 100 * summ["strike_gap"]["win_rate"])
    macro("pflopwin", "%.0f", 100 * summ["quote_operator"]["win_rate"])
    macro("pflfacwin", "%.0f", 100 * summ["smile_factor"]["win_rate"])

    fig, axes = plt.subplots(1, 2, figsize=WIDE,
                             gridspec_kw={"width_ratios": [1.3, 1.0]})
    ax = axes[0]
    for m in modes:
        x = np.clip(impr[m], -200, 400)
        ax.plot(x, np.linspace(0, 1, x.size), color=colors[m], lw=1.8,
                label=m.replace("_", " "))
    ax.axvline(0.0, color=PALETTE["ink"], lw=0.8, ls=":")
    ax.set_xlabel("held-out wing improvement over no prior (vol bp)")
    ax.set_ylabel("fraction of nodes")
    ax.legend(loc="lower right", fontsize=8.7)
    label_panel(ax, "A")
    ax = axes[1]
    med = [summ[m]["median_improvement_bp"] for m in modes]
    win = [summ[m]["win_rate"] for m in modes]
    xpos = np.arange(len(modes))
    ax.bar(xpos, med, color=[colors[m] for m in modes], alpha=0.9)
    for i, (v, w) in enumerate(zip(med, win)):
        lbl = ("win %.0f%%" if i == 0 else "%.0f%%") % (100 * w)
        ax.text(i, v + 1.2, lbl, ha="center", fontsize=8.3,
                color=PALETTE["ink"])
    ax.set_xticks(xpos)
    ax.set_xticklabels([m.replace("_", "\n") for m in modes], fontsize=8.5)
    ax.set_ylabel("median improvement (vol bp)")
    ax.set_ylim(-4, 44)
    label_panel(ax, "B")
    fig.subplots_adjust(wspace=0.32)
    save(fig, OUT / "fig_pfl_backtest.pdf")


# ---------------------------------------------------------------------------
# Figure 8 (hero): real-node wing reconstruction, mechanism isolated.
# ---------------------------------------------------------------------------


def figure_spy() -> None:
    n = K_THIN.size
    op, vs = build_operator_prior(prior_w, T, T, K_THIN, None, 0.5 * n,
                                  op_set=OP_SET)
    tail, _ = build_prior_anchor(prior_w, T, K_THIN, T, 0.2 * n,
                                 deltas=hybrid_tail_deltas(OP_SET, DEFAULT_DELTAS))
    pvs = (VarSwapTarget(total_var=vs.prior_total_var, weight=vs.weight, t=T)
           if vs.active else None)
    f_mo = calibrate_slice(K_THIN, W_THIN, T, n_order=6, reg_lambda=1e-6)
    f_hy = calibrate_slice(K_THIN, W_THIN, T, n_order=6, reg_lambda=1e-6,
                           operator_prior=op, prior_anchor=tail,
                           prior_var_swap=pvs)

    def rms_bp(fit, k, w):
        dv = vol(fit.slice.implied_w(k)) - vol(w)
        return 100.0 * float(np.sqrt(np.mean(dv * dv)))

    macro("pflspybandrms", "%.0f", rms_bp(f_hy, K_THIN, W_THIN))
    macro("pflspywingmo", "%.0f", rms_bp(f_mo, K_OUT, W_OUT))
    macro("pflspywinghy", "%.0f", rms_bp(f_hy, K_OUT, W_OUT))

    kk = np.linspace(float(Q_K.min()), float(Q_K.max()), 400)
    fig, ax = plt.subplots(figsize=(6.9, 4.2))
    ax.axvspan(-BAND, BAND, color="black", alpha=0.05)
    ax.plot(kk, vol(prior_w(kk)), color=SLATE, ls=":", lw=1.6,
            label="the prior (stored full-chain fit)")
    ax.plot(kk, vol(f_mo.slice.implied_w(kk)), color=RUST, ls="--", lw=1.9,
            label="market-only refit (wings flap)")
    ax.plot(kk, vol(f_hy.slice.implied_w(kk)), color=TEAL, lw=2.0,
            label="hybrid persisted refit")
    ax.scatter(K_THIN, vol(W_THIN), s=14, color="black", zorder=6,
               label="retained quotes")
    ax.scatter(K_OUT, vol(W_OUT), s=22, facecolors="none", edgecolors=RUST,
               linewidths=1.2, zorder=6, label="withheld quotes")
    ax.text(0.02, 26.5,
            "withheld-wing rms error:\nmarket-only %.0f bp, hybrid %.0f bp"
            % (rms_bp(f_mo, K_OUT, W_OUT), rms_bp(f_hy, K_OUT, W_OUT)),
            fontsize=9.2, color=PALETTE["ink"], ha="left")
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel("implied volatility (%)")
    ax.legend(loc="upper right", fontsize=8.7)
    save(fig, OUT / "fig_pfl_spy.pdf")


# ---------------------------------------------------------------------------
# Appendix verification: the reference listing against production.
# ---------------------------------------------------------------------------


def listing_gate(obs, req, gamma=1.0):
    return np.clip(1.0 - obs / np.maximum(req, 1e-12), 0.0, 1.0) ** gamma


def listing_support(k_quotes, k_legs, b):
    z = (np.asarray(k_legs)[:, None] - np.asarray(k_quotes)[None, :]) / b
    return np.exp(-0.5 * z * z).sum(axis=1)


def listing_basket_precision(coeff, support, eps=1e-9):
    return 1.0 / np.sum(coeff[coeff != 0.0] ** 2 / (support[coeff != 0.0] + eps))


def verify_listings() -> None:
    d = 0.0
    grid = np.linspace(0.0, 3.0, 301)
    for gamma in (0.5, 1.0, 2.0):
        d = max(d, float(np.max(np.abs(listing_gate(grid, 1.0, gamma)
                                       - activation_gap(grid, 1.0, gamma)))))
    # The full pipeline (support -> basket precision -> gate -> budget split)
    # against production, on the jump market where operators are live.
    op, _ = build_operator_prior(syn_prior_w, SYN_TAU, SYN_TAU, SYN_K, None,
                                 SYN_BUDGET, op_set=["ATM", "RR25", "BF25"],
                                 bandwidth=SYN_BW)
    support = listing_support(SYN_K, op.legs_k, SYN_BW)
    gaps = np.array([listing_gate(listing_basket_precision(op.coeff[r], support), 1.0)
                     for r in range(len(op.names))])
    lam = SYN_BUDGET * gaps / gaps.sum()
    prod = {di["operator"]: di for di in op.diagnostics}
    for r, name in enumerate(op.names):
        d = max(d, abs(float(lam[r]) - prod[name]["activeLambda"]))
        pi = listing_basket_precision(op.coeff[r], support)
        d = max(d, abs(pi - prod[name]["obsPrecision"]))
    sci_macro("pflrefagree", d)


# ---------------------------------------------------------------------------


def main() -> None:
    figure_flat(); print("flat done")
    figure_gate(); print("gate done")
    figure_basket(); print("basket done")
    figure_level(); print("level done")
    figure_activation(); print("activation done")
    figure_hybrid(); print("hybrid done")
    figure_backtest(); print("backtest done")
    figure_spy(); print("spy done")
    verify_listings()

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, cwd=REPO,
                                check=True).stdout.strip()
    except Exception:
        commit = "unknown"
    macro("pflgencommit", "%s", commit)
    macro("pflgendate", "%s", date.today().isoformat())

    (OUT / "prior_flat_tables.tex").write_text("\n".join(MACROS) + "\n",
                                               encoding="utf-8")
    (OUT / "prior_flat_numbers.json").write_text(json.dumps(NUMBERS, indent=2),
                                                 encoding="utf-8")
    print("\n".join(MACROS[1:]))


if __name__ == "__main__":
    main()
