"""Figures for Note 10 (calendar-arbitrage prevention).

An inverted-wing term structure (a high-vol short expiry over a calmer long
expiry) creates a calendar violation: w_near(k) > w_far(k) in the wings. The
calendar floor cures it by pushing the long slice up to dominate the short one.

  fig_cal_cross.pdf   total variance: near, far-unconstrained (crosses), far-cured
  fig_cal_G.pdf       integrated upper-quantile curves G(alpha), ordered after cure
  cal_tables.tex      \\input-able macros
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.special import expit

from volfit.calib.calendar import calendar_floor_targets, calendar_violation
from volfit.models.lqd.calibrate import calibrate_slice

OUT = Path(__file__).resolve().parent
plt.rcParams.update(
    {
        "figure.figsize": (7.2, 4.3),
        "font.size": 11,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "lines.linewidth": 1.8,
        "savefig.bbox": "tight",
        "savefig.dpi": 200,
    }
)
TEAL, RUST, SLATE, AMBER = "#0f766e", "#b91c1c", "#334155", "#b45309"


def smile_w(k, atm_vol, wing, t):
    """A simple skewed vol smile -> total variance."""
    vol = atm_vol + wing * (np.sqrt(k * k + 0.01) - 0.1) - 0.10 * k
    return (vol**2) * t


def main():
    t_near, t_far = 0.25, 0.50
    k = np.linspace(-0.32, 0.28, 21)
    # Inverted wings: the short expiry is much more volatile than the long one.
    w_near = smile_w(k, 0.30, 0.60, t_near)
    w_far = smile_w(k, 0.20, 0.25, t_far)

    near = calibrate_slice(k, w_near, t_near, n_order=6, reg_lambda=1e-6)
    far_free = calibrate_slice(k, w_far, t_far, n_order=6, reg_lambda=1e-6)

    cz, cfloor = calendar_floor_targets(near.slice)
    far_cured = calibrate_slice(k, w_far, t_far, n_order=6, reg_lambda=1e-6,
                                calendar_z=cz, calendar_floor=cfloor, calendar_weight=1e6)

    v_free = calendar_violation(near.slice, far_free.slice)
    v_cured = calendar_violation(near.slice, far_cured.slice)

    kk = np.linspace(-0.40, 0.34, 300)
    wn = near.slice.implied_w(kk)
    wf_free = far_free.slice.implied_w(kk)
    wf_cured = far_cured.slice.implied_w(kk)

    fig, ax = plt.subplots()
    ax.plot(kk, wn, color=SLATE, label=fr"near $T={t_near}$")
    ax.plot(kk, wf_free, color=RUST, ls="--", label="far, unconstrained (crosses)")
    ax.plot(kk, wf_cured, color=TEAL, label="far, calendar-cured")
    cross = wf_free < wn
    ax.fill_between(kk, wn, wf_free, where=cross, color=RUST, alpha=0.12)
    ax.set_xlabel(r"log-moneyness $k$")
    ax.set_ylabel(r"total variance $w(k)$")
    ax.set_title("Inverted wings: the cured far slice dominates the near one", fontsize=10)
    ax.legend(frameon=False, fontsize=9)
    fig.savefig(OUT / "fig_cal_cross.pdf")
    plt.close(fig)

    # integrated upper-quantile curves (asset share a_z) for the cured pair
    alpha = expit(near.slice.z)
    fig, ax = plt.subplots(figsize=(7.2, 3.6))
    sel = (alpha > 0.02) & (alpha < 0.98)
    ax.plot(alpha[sel], near.slice.a_z[sel], color=SLATE, label=r"$G_{\rm near}(\alpha)$")
    ax.plot(alpha[sel], far_cured.slice.a_z[sel], color=TEAL,
            label=r"$G_{\rm far}(\alpha)$ (cured)")
    ax.set_xlabel(r"quantile level $\alpha$")
    ax.set_ylabel(r"$G(\alpha)=\int_\alpha^1 e^{Q(u)}\,du$")
    ax.set_title(r"$G_{\rm far}\geq G_{\rm near}$: convex order, no calendar arb", fontsize=10)
    ax.legend(frameon=False)
    fig.savefig(OUT / "fig_cal_G.pdf")
    plt.close(fig)

    L = ["% Auto-generated by gen_calendar.py — do not edit."]
    L.append(r"\newcommand{\calviolfree}{%.4f}" % v_free)
    L.append(r"\newcommand{\calviolcured}{%.2e}" % v_cured)
    L.append(r"\newcommand{\calstride}{25}")
    (OUT / "cal_tables.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("calendar violation: unconstrained %.4f -> cured %.2e" % (v_free, v_cured))


if __name__ == "__main__":
    main()
